import '../../../../features/weather/domain/entities/temperature_tier.dart';

const blizzardExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She's fucking apocalyptic. Stay inside immediately babe.",
    'Having a full fucking breakdown in single digits. Burying cars girl.',
    'Shutting down highways like she owns them. Bundle the hell up and stay in.',
    'Storm from X-Men energy. Freezing everything but honestly hot af.',
    "She really said nobody's going anywhere and she fucking meant it babe.",
    'Holy shit. She went nuclear in single digits babe. This is not the day. Stay inside girl.',
    'Not snowing. Declaring fucking war. Single digits zero visibility.',
    "She's fucking channeling Carrie right now. Terrifying. Do not go outside babe.",
    "Peak villain arc at the worst temp. She's unwell. Stay inside babe.",
    'This is not a snow day this is a survival situation. Stay in girl.',
    "She's not playing she's not cute she's dangerous. Stay inside babe.",
    "She's blizzarding so hard she buried the sidewalk. Do not go outside. I mean it girl.",
  ],
  TemperatureTier.freezing: [
    "She's snowing sideways. She's not fucking around babe.",
    'Terrifying as shit at her ideal temp girl.',
    "Burying everything in sight. Doesn't give a single fuck honestly.",
    "Ruining every fucking plan you had. She doesn't negotiate babe.",
    'Closing schools canceling flights. Having the time of her fucking life babe.',
    'Cold as fuck snowing sideways. Committed harder than any ex honestly.',
    "She's performing for nobody because nobody can fucking see. Stay home babe.",
    "She's not just blizzarding she's making a point. Stay the fuck in babe.",
    'Katniss in the arena energy. Survival mode. Stay inside babe.',
    'She watched The Day After Tomorrow and took notes. Freezing blizzard full disaster babe.',
    "She's erasing the entire neighborhood one street at a time babe. Do not leave.",
    'Going absolutely feral. Schools closed. So are your damn plans girl.',
  ],
  TemperatureTier.jacketWeather: [
    'Mild temps and she said full blizzard anyway. Unhinged as fuck girl.',
    "Going nuclear at a temp that doesn't deserve it. Extra as shit girl.",
    'Overkill af. War at a mild disagreement.',
    "Burying the city and it's not even cold. The drama. Incredible as hell babe.",
    "Showed up uninvited. She's staying. Bold as shit.",
    'Siouxsie and the Banshees energy. Cold chaotic af. Stay inside girl.',
    "Alanis wrote You Oughta Know for this weather. Fucking dramatic won't stop. Stay in babe.",
    'The Revenant vibes. Survival mode honestly af girl.',
    'Kate Beckinsale in Whiteout energy. Relentless at this temp. Stay inside babe.',
    'Villain energy. Does not belong here babe.',
    'Did not need to go this damn hard babe.',
    'Overreacting and knows it. Stay inside damn it girl.',
  ],
  TemperatureTier.flannelWeather: [
    'She brought a blizzard to mild weather. Like showing up in a ball gown to a barbecue babe.',
    'Mild weather and she went full blizzard. Nobody asked for this shit girl.',
    'Like she belongs here. Unhinged as shit girl.',
    'Holy shit. At a temp that makes zero sense. Next level honestly.',
    'Sword to a fucking pillow fight.',
    'Confused and furious. Dangerous fucking combo girl.',
    'Florence and the Machine vibes. Epic as fuck girl.',
    'Holy shit. Mild weather is a damn suggestion to her.',
    'Nicole Kidman in The Others energy. Trapped everyone inside. Not sorry babe.',
    "Adele wrote Rolling in the Deep for this. She's breaking everything. Stay safe girl.",
    'Frances McDormand in Fargo energy. Iconic honestly babe.',
    'Villain in the wrong damn movie. Stay inside babe.',
  ],
  TemperatureTier.shortsWeather: [
    "Burying the city in snow and it's warm. What the actual hell babe.",
    'Chose to fucking terrify every meteorologist alive.',
    "She thinks she's Stevie Nicks right now. Mystical as hell babe.",
    "Portishead Glory Box energy. Moody surreal af. I'm not okay girl.",
    "She's channeling Promising Young Woman. She broke every rule and she's proud of it babe.",
    "She won't stop. Relentless. The snow is melting on contact and she does not care girl.",
    'Not pretending to make damn sense. Get inside babe.',
    "A blizzard at shorts weather. She's performing open heart surgery on reality right now babe.",
    "She's blizzarding at eighty degrees like someone dared her. Nobody dared her. She dared herself girl.",
    'Warm blizzard. The snowflakes are confused. My weather app is crying. Everyone is yelling babe.',
    "She's burying cars in snow while people are in tank tops. This is performance art girl.",
    "Blizzard at shorts weather. My neighbor is shoveling in flip flops. She caused this. She's proud babe.",
  ],
  TemperatureTier.scorcher: [
    'Nature filed a restraining order. She violated it. Terrifying as shit honestly.',
    'Dumping snow in extreme heat out of pure spite. Science left the chat girl.',
    'The audacity. The fucking commitment babe.',
    'M.I.A. Paper Planes vibes. Chaotic as fuck. Stay in girl.',
    'Mad Max energy. End of the world. Stay inside af babe.',
    'Rules were boring. She wrote new ones babe.',
    'Miley Cyrus wrote Wrecking Ball for this. Plus scorching. Nothing makes sense girl.',
    'End times. She is the damn main event babe.',
    "She's dumping snow at a hundred degrees like a villain who lost the plot. And the thermometer girl.",
    'Blizzard on a scorcher. The weatherman quit on air. She broke a professional babe.',
    "She's burying the city in snow while the pavement is hot enough to fry an egg. Choose a lane girl.",
    "Hot blizzard. My ice cream and my sanity melted at the same time. She's efficient babe.",
  ],
};

const blizzardExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She's screaming so loud the windows are shaking. Do not open that fucking door girl.",
    'If you go outside right now you are simply choosing fucking death girl.',
    'She turned the air into a solid fucking wall of white. The outside ceased to exist babe.',
    "She's fucking unhinged. The streetlights are just suggestions at this point babe.",
    "Visibility is absolutely fucked. Don't even fucking think about it babe.",
    "She's howling so hard the house is vibrating. This shit is fucking terrifying babe.",
    'The snow is going sideways. She said fuck gravity I do what I want girl.',
    "She's throwing snow in every direction at once. No aim just rage babe.",
    "The wind is so loud I can't hear myself panic. Which is a feature not a bug girl.",
    'She turned the world into TV static. Nothing exists outside your door babe.',
    "The snow is literally horizontal. She's not falling she's attacking girl.",
    'She hit ctrl+A delete on the entire damn city babe.',
    'She buried the mailbox in forty minutes. Mailbox is in witness protection now babe.',
  ],
  TemperatureTier.freezing: [
    'Road gone. Sidewalk gone. Will to live? Also gone girl.',
    "Streetlights surrendered. She's going that hard babe.",
    'Car buried. Driveway gone. She done yet? No babe.',
    'Piling snow against the door. Is this a hostage situation? girl.',
    'Snow to war crimes real quick. Classic her babe.',
    'Volume max visibility zero. Why is she like this girl.',
    "Created a drift taller than me. I'm five seven. She won babe.",
    "She's howling. Got something to prove? She does girl.",
    "Stay the fuck inside. She's burying everything below freezing. Do not open that door babe.",
    'Do not go out there. She went full blizzard below freezing. Stay in your warmest shit girl.',
    "Bundle up and stay the fuck put. She's howling and she's not done babe.",
  ],
  TemperatureTier.jacketWeather: [
    'She brought the fucking apocalypse to a Tuesday. Overachiever girl.',
    'She brought a blizzard to jacket weather. Nobody asked for this much commitment babe.',
    "She's doing this shit for sport girl.",
    "She said I don't need freezing temps to ruin your shit girl.",
    "She's so fucking extra. Zero visibility for what babe.",
    'The drama is unnecessary and iconic as fuck babe.',
    "She didn't need it to be freezing to go absolutely feral babe.",
    'She brought a nuclear weapon to a pillow fight babe.',
    "She's overperforming and making it everyone's problem girl.",
    "Stay the fuck inside. She's blizzarding at jacket weather for no goddamn reason babe.",
    'Do not go out there. She escalated to whiteout at a manageable temp. Let her spiral alone girl.',
    "Jacket on but stay the fuck in. She's doing the most and none of it is necessary babe.",
  ],
  TemperatureTier.flannelWeather: [
    "Make it make fucking sense. You can't girl.",
    "She didn't read the assignment and she doesn't give a shit girl.",
    'The weather app is having a fucking aneurysm girl.',
    'She woke up and chose absolute fucking chaos girl.',
    "She's blizzarding at flannel weather temps. She didn't get the memo and she'd burn it if she did babe.",
    "She broke every damn rule of meteorology and she's proud of it bitch.",
    "Physics is crying. Science is on the floor. She's thriving girl.",
    "She's gaslighting us into thinking this is normal babe.",
    "She showed up to the wrong damn party and won't leave babe.",
    "Stay the fuck inside. She's blizzarding at flannel temps and nothing about this is okay babe.",
    'Do not open that door. She brought a blizzard to a mild night. Stay the fuck put girl.',
    "Cozy up and stay in. She's doing whiteout conditions at hoodie temps. Let her have her tantrum babe.",
  ],
  TemperatureTier.shortsWeather: [
    'The forecast said fuck it and walked off the job girl.',
    "She's doing a fucking blizzard in a tank top babe.",
    "Nature had a full mental breakdown and we're all just fucking watching babe.",
    'The weather just had a fucking psychotic break babe.',
    "She's whiteout conditions in shorts weather. My brain filed a missing persons report babe.",
    'She showed up to summer in a fur coat. Icon bitch.',
    'Holy shit. Every meteorologist just quit their job babe.',
    "She's blizzarding in warm weather. My weather app just sent a resignation letter girl.",
    "Somebody check on the atmosphere she's lost her damn mind babe.",
    "She said seasons are a construct and I'm the damn proof girl.",
    "Stay the fuck inside. She's blizzarding in shorts weather and nothing makes sense babe.",
    'Do not open that door. Warm blizzard. She invented a new kind of hell girl.',
    "Stay put. She's doing whiteout conditions in tank top weather. Nobody go anywhere babe.",
  ],
  TemperatureTier.scorcher: [
    "The world is ending and it's confusing as fuck babe.",
    'Hot blizzard. Those two words should never be together. She invented a war crime girl.',
    'She said fuck your physics fuck your logic fuck your forecast babe.',
    "She can't pick a vibe and she's punishing the shit out of us for it babe.",
    'She looked at the rulebook and set it on fire girl.',
    "She's blizzarding and it's hot. I'm sweating and snowblind. Both at once bitch.",
    "She broke reality and she's not even sorry about it babe. What the hell.",
    "She's doing whiteout conditions in a scorcher. The snow is melting before it blinds us girl.",
    "My sweat is freezing mid-drip. I'm experiencing two seasons per second girl.",
    "She's doing a hot blizzard and my brain just blue screened. I'm rebooting girl.",
    'Stay the fuck inside. Hot blizzard. She broke every rule and your sanity is next babe.',
    "Lightest PJs and do not move. She's doing a scorching whiteout. Stay put girl.",
  ],
};
