import '../../../../features/weather/domain/entities/temperature_tier.dart';

const drizzleExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Drizzling in single digits. Fuck no. Arrested. Straight to jail.',
    'Freezing drizzle like just be snow already. The fuck?',
    'Freezing drizzle. Absolutely the fuck not. Stay home babe.',
    'Drizzling in single digits. What the actual fuck is this. No seriously what is this.',
    "Single digit drizzle. She's pissing on us from the sky. In the cold. Classy girl.",
    "Drizzle at this temp. It's not rain it's not snow it's just fucking rude babe.",
    "She's misting in single digits. Like girl either rain or don't. This half ass shit is embarrassing girl.",
    "Drizzling in single digits. Go to hell. Oh wait we're already here. Forgot babe.",
    "Can't even commit to snow in these temps? Seek help girl like actually.",
    "Single digit drizzle. She can't even be bothered to snow properly. Lazy and cold. The fucking worst.",
    'Drizzle at this temp is a hate crime. I said what I said.',
  ],
  TemperatureTier.freezing: [
    "It's giving A Quiet Place. Cold barely making a sound and honestly fucking terrifying babe.",
    'Below freezing and she chose drizzle. The most annoying option on the menu. Every fucking time.',
    "It's giving Titanic. Fucking cold wet and not helping anyone right now babe. Stay in.",
    'Below freezing with mist. Minimal effort maximum annoyance. Respect af honestly.',
    'Freezing drizzle. Somehow worse than rain and snow combined. She found the loophole. What the hell.',
    'Light drizzle freezing temps. Too lazy to rain too petty to quit.',
    "Freezing and misting. She's out here doing the bare minimum to ruin your day. And succeeding.",
    "Freezing drizzle. She's spitting on us from above like a llama. A cold wet llama girl.",
    'Below freezing and drizzling. She showed up with the energy of a passive aggressive sticky note. Bundle up babe.',
    'Freezing drizzle. She picked the most annoying weapon in her arsenal. Surgical strike energy girl.',
    "She's misting below freezing like a spray bottle aimed at a cat. We're the cat babe.",
    'Drizzle below freezing. Not enough to stay home not enough to enjoy. She lives in the gray area girl.',
  ],
  TemperatureTier.jacketWeather: [
    "It's giving film noir. No crime. Just fucking vibes. Jacket on babe.",
    "She's barely raining and I'm fully in love. Embarrassing honestly girl.",
    "I'm damp and cold as fuck. It's fine we're fine we got this babe.",
    "Misting us like houseplants. We're the damn ferns. Standing here taking it girl.",
    'Low effort. High atmosphere. Iconic ratio honestly.',
    "It's giving fog machine. But make it fashion babe.",
    "Cool drizzle. She got us like the perfume testers at Sephora. We smell like rain now. Didn't ask girl.",
    "She's misting us like a fragrance counter ambush. Like girl chill.",
    "It's giving Stevie Nicks energy. Pretty and iconic as fuck. Go spin somewhere babe.",
    'Cool and misting. Jacket slowly getting heavier. Attitude slowly getting worse. Connected events honestly.',
    "It's giving lo-fi music video. We're all starring in it. No audition needed babe.",
    "Cool drizzle. Ma'am we are not produce. Stop misting us girl.",
    'Bare minimum rain. Standing ovation from me. My standards are in hell girl.',
    "She turned the whole city into a produce aisle. We're the leafy greens. Damp and on display babe.",
    'Wet pavement is serving runway. The puddles have more style than me. She did that babe.',
    "Cool drizzle. She made a puddle look profound. It's just water. I'm fucking delusional girl.",
    'Drizzle at this temp is honestly hot as fuck. Filing a complaint. With who. Unclear babe.',
    "Cool drizzle. She's got us on the produce mister schedule. We're the broccoli now babe.",
  ],
  TemperatureTier.flannelWeather: [
    "Mild and drizzly. She's in her soft girl era. Zero fucking notes babe.",
    "She's misting at the fucking perfect temp and I am emotional. Go play babe.",
    "It's giving manic pixie vibes. Drizzly mild whimsical. Rain boots and romp babe.",
    "She's drizzling at the perfect temp like she read a fucking manual for once. Proud of her honestly.",
    'Mild drizzle. No drama no bullshit just vibes. Who is this bitch and what did she do with the weather.',
    'Tracy Chapman Fast Car vibes. Mild drizzle taking you somewhere. Flannel and go bitch.',
    "Drizzle at this temp. She's being romantic without asking. Fuck. Catching feelings again babe.",
    'Mild drizzle. Flannel and rain boots. Get the fuck outside she deserves a witness babe.',
    "Drizzly and mild. She's being cute as fuck and I hate that I love it. Get outside girl.",
    'Drizzle at this temp is a whole damn mood. Hoodie on get your ass out there babe.',
    'Mild mist. She showed up gentle and perfect. Throw on a flannel and go enjoy her bitch.',
  ],
  TemperatureTier.shortsWeather: [
    "Warm drizzle. Can't commit to rain. At this temp who gives a shit babe.",
    "She's channeling Kiki's Delivery Service. Warm whimsical magical. Go play.",
    'Light warm rain. Doing the bare minimum and somehow fucking nailing it. Good for her.',
    'Drizzly and warm af. Gently misting you like fancy produce. Thanks girl.',
    "Light drizzle warm air. She's being romantic and nobody asked her to be. Go play girl.",
    "She thinks she's Gwen Stefani right now. Warm drizzle unbothered as fuck. Love that for her.",
    "Warm and drizzly. She's out here seducing us with mist and it's fucking working girl.",
    "Warm and drizzly. She's giving tropical rain in a romcom. Main character shit babe.",
    "Showed up warm and soft and drizzly. She's catching feelings and they're contagious as fuck girl.",
    "Warm drizzle. She's being flirty and I refuse to be this easy. But here we are bitch.",
    "Drizzly and nice as fuck. She's setting a mood and I'm fully in it. Go play babe.",
    "Warm mist. She's giving main character in the rain moment. Go have yours babe.",
    'Natasha Bedingfield wrote Unwritten for this exact moment. Go feel the rain on your skin babe.',
    'Warm drizzle. The air tastes like summer and bad decisions. Shorts on go make some girl.',
    'Warm drizzle. She misted you like a houseplant. Get the fuck outside babe.',
    'Drizzly shorts weather. No umbrella needed. Shorts on go get a little wet bitch.',
  ],
  TemperatureTier.scorcher: [
    'Scorching and drizzly. Trying to cool us down barely fucking helping girl.',
    "Drizzle on a scorcher. Like here's some warm rain you ungrateful bitch. She's so sweet.",
    'Hot as fuck and drizzling. Minimal effort maximum humidity. Tank top and go girl.',
    'Scorching with light rain. Bare minimum and somehow still appreciated babe.',
    'Hot as shit and misting. Sky sent her intern to handle a crisis girl.',
    'Hot as fuck and misting. She brought a squirt gun to a wildfire. A for effort babe.',
    "She thinks she's Lizzo right now. So fucking hot she's steaming. Feeling herself honestly.",
    "Hot drizzle. She's trying to put out a fire with a Dasani. Bless her heart.",
    "Scorching and drizzly. The rain is hot. The air is hot. Everything is hot. She's unwell babe.",
    "Drizzle on a scorcher. It's not helping. Congrats girl you made steam.",
    'Scorching and drizzly. She sent one ice cube to a house fire. Noted. Hydrate babe.',
  ],
};

const drizzleExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Dark wet cold. She's speedrunning depression. Fuck this girl.",
    "She's sprinkling suffering on us like fucking seasoning girl.",
    "She's barely raining and it's barely above death. Minimum fucking effort maximum suffering girl.",
    "Cold drizzle in the dark. She's giving us the silent treatment but wet. Fuck off babe.",
    'Wet cold dark. The trifecta of fuck this babe.',
    "She's barely raining and it's single digits. She's doing the least and it's still fucking miserable girl.",
    "She's spitting on us from the sky. Rude as fuck girl.",
    "She's whispering rain at us in single digits. Like girl just fucking scream already babe.",
    'She said rain? No. Fucking inconvenience? Absolutely babe.',
    "She's crying but like barely. Performative bullshit tears babe.",
    "She's not even trying hard and it still fucking sucks. Talent honestly babe.",
    "Stay the fuck inside. She's misting misery in single digits. Do not engage girl.",
  ],
  TemperatureTier.freezing: [
    'Sprinkling misery like fucking seasoning. Strategic bitch.',
    'Not even raining hard. Just enough to piss you the fuck off girl.',
    "Her weakest soldier and it's still kicking our ass. Fuck this babe.",
    "Cold AND wet. What if I don't want fucking either girl.",
    'Pretty and miserable. Her whole damn brand honestly babe.',
    'Misting us in the cold like a psychotic fucking plant mom girl.',
    'Rain barely there. Suffering fully fucking present. Cool cool babe.',
    "She's crying and making it everyone's fucking problem. Classic girl.",
    'Adding insult to fucking injury. The injury is frostbite babe.',
    "Drizzle freezing on contact. She's crafting an ice sculpture out of our will to fucking live girl.",
    "Bundle the fuck up. She's sprinkling misery on us below freezing. Stay inside babe.",
  ],
  TemperatureTier.jacketWeather: [
    "She's barely even fucking raining. Like if rain had a quiet voice this is it babe.",
    "The sky is passive aggressively moisturizing us. We didn't ask for fucking skincare babe.",
    "She's not raining she's just making everything slightly worse. On fucking brand girl.",
    "She's putting in the same effort I put into my last fucking relationship girl.",
    "She's dripping on us so gently it's almost passive aggressive. Jacket on girl.",
    "She's teasing us with rain. Just fucking commit already girl.",
    "She's committing to nothing and achieving mild fucking discomfort girl.",
    "She's on her bullshit but it's small-scale bullshit. Fucking manageable babe.",
    'She turned on the mist setting and walked the fuck away. Autopilot weather babe.',
    "This isn't weather this is a cry for attention babe.",
    "She's fucking microdosing rain. Bold strategy girl.",
    "She's sending one drop at a time like a passive fucking aggressive faucet babe.",
    'Cool night and the drizzle is just enough to fog up your glasses. Helpful. Thanks girl.',
    "The drizzle is so fine it's almost a concept. Barely wet barely committed. Cool night though babe.",
    'If this rain were a text it would just say k.',
    "She's dripping on us one drop at a time like a leaky faucet. Fix yourself girl.",
    'Cool drizzle and the sidewalks are shiny. She made the pavement pretty at least babe.',
    "The drizzle just touched my face uninvited. She's doing the bare minimum and catching feelings. Jacket on babe.",
    "She turned the night into a light mist and the temp into jacket weather. Bare minimum queen but we'll fucking take it girl.",
    "Drizzle so light I can't tell if it's raining or the sky is just breathing on me. Either way she's in my personal space babe.",
  ],
  TemperatureTier.flannelWeather: [
    "She's being soft and we don't trust it but we're into it. Suspicious as hell girl.",
    "Rain on the windows. She's setting a mood and it's actually fucking working girl.",
    'Mild drizzle and the world sounds different. Every surface has a voice tonight girl.',
    "She's on her best behavior tonight. Suspicious as fuck but cute babe.",
    "She's being gentle and it's weirding me the fuck out girl.",
    "Rain tapping on everything like it's got something to say. Speak the fuck up girl.",
    "This is her apology tour and honestly she's fucking nailing it.",
    "She's fucking being atmospheric and she doesn't even know it babe.",
    "She's being fucking gentle for once and honestly it's making us emotional girl.",
    "The streets are shiny and she's feeling herself girl.",
    "The drizzle is tapping on my window like it has gossip. I'm listening babe.",
    "Mild and drizzly and I'm outside with no umbrella on purpose. She made me feral girl.",
    "She's not trying hard but she's trying fucking pretty. That's enough. Damn girl.",
    "She's tapping on the windows like she wants to come in bitch.",
    "Light rain perfect temp. She's being the version of herself I keep telling people about babe.",
    "The drizzle is so gentle it's suspicious as fuck. Free therapy no copay. She's up to something girl.",
    'She finally figured out how to be cute about it. Took long enough girl.',
    "Mild drizzle and the streets look glazed. She's making everything shiny and I'm outside staring girl.",
    "She's doing the bare minimum and making it romantic somehow babe.",
    "She's barely raining and it's the prettiest weather we've had all week. Flannel on go babe.",
  ],
  TemperatureTier.shortsWeather: [
    'She choreographed this for you. Wet streets glowing lights warm air. Go fucking live babe.',
    "She's putting in effort and it shows. We see you girl. We fucking see you.",
    "She's being fucking perfect and it's making us nervous. What's the catch girl.",
    'Warm drizzle and the air smells incredible. She turned the night into a whole experience girl.',
    "She's being so gentle tonight it's suspicious as fuck girl.",
    'She touched our face with rain and we blushed. Down bad as hell babe.',
    "Go walk through it. Be mysterious. She's fucking setting the scene girl.",
    "She's misting us like an expensive facial. Free skincare girl.",
    'This is foreplay weather and I said what I said bitch.',
    'Go stand in it. Like shit. Be that girl.',
    "Warm light rain and I'm outside getting gently wet and having feelings. She did this to me babe.",
    "She's being fucking romantic and we didn't sign up for these damn feelings babe.",
    "Go outside. Get your hair wet. Look mysterious. Fall in fucking love. She's demanding it girl.",
    "The drizzle is so warm it's like standing in someone's breath. Weird? Yes. Into it? Also yes babe.",
    "She's drizzling on us in shorts weather and somehow it's the best night this week. She's a genius girl.",
    "She learned our love language and it's gentle rain apparently. Noted babe.",
    "She brought wine and rain and soft lighting. We're not saying no girl.",
    'Warm drizzle and the whole neighborhood is glistening. She polished the damn city babe.',
    "She's drizzling on us in shorts weather like she's earned our trust. She hasn't. But tonight we're pretending babe.",
    "She's serenading us with tiny rain and perfect temps. Down bad girl.",
  ],
  TemperatureTier.scorcher: [
    "Rain's not helping it's just adding humidity. Thanks for fucking nothing girl.",
    "She's doing the least and somehow making it worse. One talented bitch.",
    "She's fucking not cooling anything down she's marinating us. Medium rare by morning girl.",
    "Hot drizzle. She's adding moisture to the already unbearable. Chef's kiss of suffering babe.",
    "She added water to fucking hot oil. She's trying to start a fire girl.",
    "She's crying in the shower and dragging us in with her bitch.",
    "Scorching drizzle. The rain evaporates before it hits the ground. She's not even cooling us off girl.",
    "Rain evaporating before it hits the ground. She's fucking not even trying girl.",
    "She's misting us in a sauna. Nobody asked for this babe.",
    "She added drizzle to the heat like she's seasoning our suffering. Needed more wet I guess babe.",
    "Hot drizzle. The air is so thick and wet I'm basically drinking it. Hydrate by breathing I guess girl.",
    "The air is wet the ground is wet we're wet. Nobody consented girl.",
  ],
};
