import '../../../../features/weather/domain/entities/temperature_tier.dart';

const drizzleExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She's drizzling in single digits. Tiny soft girl energy in the freezing cold. Bundle the fuck up babe.",
    "Single digit drizzle. She's being so gentle it's almost sweet. The cold is the real bitch here girl.",
    "Drizzling in single digits. She's doing her soft thing while the cold tries to kill us. Layers on babe.",
    "She chose drizzle in the cold. Cute as fuck honestly. The temp is what's rude. Coat on girl.",
    "Single digits and she's barely misting. She's being delicate. The freezing air is the villain here babe.",
    "Drizzle at this temp. She's whispering rain while the cold fucking screams. Bundle up girl.",
    "She's misting us in single digits. Sweet little thing. The cold can fuck right off though babe.",
    "Single digit drizzle. She's trying to be soft and the cold is ruining it. Stay warm girl.",
    "Drizzling in the cold. She's giving us her gentlest moment. Coat on and appreciate her babe.",
    "She's sprinkling tiny raindrops in single digits. Endearing as hell. The temp though? Brutal. Layer up girl.",
    "Single digit mist. She's being so fucking cute about it. The cold is NOT. Bundle up babe.",
  ],
  TemperatureTier.freezing: [
    "Below freezing and she's drizzling so gently. She's trying to be sweet about it babe. The cold is what's mean.",
    "Freezing drizzle. She's being soft and delicate while the temp does all the damage. Bundle up girl.",
    "She's misting below freezing. Gentle little thing. The cold is the one being rude here babe.",
    "Freezing and she chose the softest rain possible. Endearing honestly. The temp can fuck off though girl.",
    "Below freezing with a light mist. She's whispering to us. The cold is the one yelling. Coat on babe.",
    "Freezing drizzle. She showed up tender and quiet. The air is what's being aggressive. Layer up girl.",
    "She's barely raining below freezing. Trying her best to be gentle. The temp is the asshole here babe.",
    "Drizzle below freezing. She's giving us her softest moment in the harshest cold. Bundle up girl.",
    "Freezing and misting. She's out here being cute as hell. The cold can eat shit. Stay warm babe.",
    "Below freezing drizzle. She's doing something delicate and the cold doesn't deserve her. Coat on girl.",
    "She's misting us below freezing like a tiny kiss in the cold. Precious. Bundle the fuck up babe.",
    "Freezing drizzle. She's being so gentle it hurts. Mostly because it's freezing. Layer up girl.",
  ],
  TemperatureTier.jacketWeather: [
    "It's giving film noir. No crime. Just fucking vibes. Jacket on babe.",
    "She's barely raining and I'm fully in love. Embarrassing honestly girl.",
    "I'm damp and cold as fuck. It's fine we're fine we got this babe.",
    "Misting us like houseplants. We're the damn ferns. Standing here taking it girl.",
    'Low effort. High atmosphere. Iconic ratio honestly babe.',
    "It's giving fog machine. But make it fashion babe.",
    "Cool drizzle. She got us like the perfume testers at Sephora. We smell like rain now. Didn't ask girl.",
    "She's misting us like a fragrance counter ambush. Like girl chill.",
    "It's giving Stevie Nicks energy. Pretty and iconic as fuck. Go spin somewhere babe.",
    'Cool and misting. Jacket slowly getting heavier. Attitude slowly getting worse. Connected events honestly.',
    "It's giving lo-fi music video. We're all starring in it. No audition needed babe.",
    "Cool drizzle. Ma'am we are not produce. Stop misting us girl.",
    'Bare minimum rain. Standing ovation from me. My standards are in hell girl.',
    'She turned every surface into a damp handshake. Cool drizzle and the city is just moist. Jacket on babe.',
    'Wet pavement is serving runway. The puddles have more style than me. She did that babe.',
    "Cool drizzle. She made a puddle look profound. It's just water. I'm fucking delusional girl.",
    'Drizzle at this temp is honestly hot as fuck. Filing a complaint. With who. Unclear babe.',
    "Cool drizzle. She's doing that thing where she barely commits but still ruins your hair. Jacket on babe.",
  ],
  TemperatureTier.flannelWeather: [
    "Mild and drizzly. She's in her soft girl era. Zero fucking notes babe.",
    "She's misting at the fucking perfect temp and I am emotional. Go play babe.",
    "It's giving manic pixie vibes. Drizzly mild whimsical. Rain boots and romp babe.",
    "She's drizzling at the perfect temp like she read a fucking manual for once. Proud of her honestly.",
    'Mild drizzle. No drama no bullshit just vibes. Who is this bitch and what did she do with the weather.',
    'Tracy Chapman Fast Car vibes. Mild drizzle taking you somewhere. Flannel and go bitch.',
    "Drizzle at this temp. She's being romantic without asking. Fuck. Catching feelings again babe.",
    'Mild drizzle. Flannel and rain boots. Get the fuck outside she deserves a witness babe.',
    "Drizzly and mild. She's being cute as fuck and I hate that I love it. Get outside girl.",
    'Drizzle at this temp is a whole damn mood. Hoodie on get your ass out there babe.',
    'Mild mist. She showed up gentle and perfect. Throw on a flannel and go enjoy her bitch.',
  ],
  TemperatureTier.shortsWeather: [
    "Warm drizzle. Can't commit to rain. At this temp who gives a shit babe.",
    "She's channeling Kiki's Delivery Service. Warm whimsical magical. Go play.",
    'Light warm rain. Doing the bare minimum and somehow fucking nailing it. Go play babe.',
    'Drizzly and warm af. Gently misting you like fancy produce. Thanks girl.',
    "Light drizzle warm air. She's being romantic and nobody asked her to be. Go play girl.",
    "She thinks she's Gwen Stefani right now. Warm drizzle unbothered as fuck. Love that for her.",
    "Warm and drizzly. She's out here seducing us with mist and it's fucking working girl.",
    "Warm and drizzly. She's giving tropical rain in a romcom. Main character shit babe.",
    "Showed up warm and soft and drizzly. She's catching feelings and they're contagious as fuck girl.",
    "Warm drizzle. She's being flirty and I refuse to be this easy. But here we are bitch.",
    "Drizzly and nice as fuck. She's setting a mood and I'm fully in it. Go play babe.",
    "Warm mist. She's giving main character in the rain moment. Go have yours babe.",
    'Warm drizzle and I just stood in it with my arms out like a goddamn lunatic. Zero shame. Go feel it babe.',
    'Warm drizzle. The air tastes like summer and bad decisions. Shorts on go make some girl.',
    'Warm drizzle. She misted you like a houseplant. Get the fuck outside babe.',
    'Drizzly shorts weather. No umbrella needed. Shorts on go get a little wet bitch.',
  ],
  TemperatureTier.scorcher: [
    'Scorching and drizzly. Trying to cool us down barely fucking helping girl.',
    "Drizzle on a scorcher. Like here's some warm rain you ungrateful bitch. She's so sweet.",
    'Hot as fuck and drizzling. Minimal effort maximum humidity. Tank top and go girl.',
    'Scorching with light rain. Bare minimum and somehow still appreciated babe.',
    'Hot as shit and misting. Sky sent her intern to handle a crisis girl.',
    'Hot as fuck and misting. She brought a squirt gun to a wildfire. A for effort babe.',
    "She thinks she's Lizzo right now. So fucking hot she's steaming. Feeling herself honestly.",
    "Hot drizzle. She's trying to put out a fire with a Dasani. Bless her heart.",
    "Scorching and drizzly. The rain is hot. The air is hot. Everything is hot. She's unwell babe.",
    "Drizzle on a scorcher. It's not helping. Congrats girl you made steam.",
    'Scorching and drizzly. She sent one ice cube to a house fire. Noted. Hydrate babe.',
  ],
};

const drizzleExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She's misting us in the dark in single digits. Soft little thing. The cold is doing all the damage babe.",
    "Single digit drizzle at night. She's being so quiet and gentle. The freezing air is the real enemy girl.",
    "Dark and drizzling in single digits. She's barely there. The cold is fucking loud though. Bundle up babe.",
    "She's whispering rain in the cold dark. Cute as hell honestly. The temp is what's mean girl.",
    "Night drizzle in single digits. She's being delicate. The cold can absolutely fuck off. Stay warm babe.",
    "Single digits and she's misting so softly in the dark. Sweet girl. The cold is the bitch here honestly.",
    "Drizzling at night in single digits. She's doing her gentle thing. The freeze is doing its mean thing. Layers babe.",
    "She's barely raining in the cold dark. Tender energy. The single digits are what's ruthless girl.",
    "Night mist in single digits. She's being precious about it. The temp is not. Bundle the fuck up babe.",
    "Dark and cold and she's drizzling so softly. She's trying. The cold is not cooperating. Stay cozy girl.",
    "She's giving us the gentlest mist in the freezing dark. Angel energy. The temp is demonic though babe.",
    "Single digit drizzle at night. She's being sweet and the cold is being cruel. Coat on and stay warm girl.",
  ],
  TemperatureTier.freezing: [
    "Freezing drizzle at night. She's being so soft in the dark. The cold is what's harsh babe.",
    "She's misting below freezing at night. Gentle little queen. The temp is the villain girl.",
    "Below freezing and she's drizzling so tenderly in the dark. She's trying her best. Bundle up babe.",
    "Night drizzle below freezing. She's giving whisper-soft rain. The cold is giving war. Layer up girl.",
    "She's barely raining in the freezing dark. Delicate as hell. The temp can fuck right off babe.",
    "Freezing and misting at night. She's out here being sweet while the air tries to murder us. Coat on girl.",
    "Below freezing night drizzle. She's doing something soft and pretty. The cold doesn't deserve her babe.",
    "She's drizzling in the freezing dark like a tiny lullaby. The cold is the nightmare though. Stay warm girl.",
    "Freezing drizzle at night. She's being adorable about it honestly. The temp is being a whole bitch. Bundle up babe.",
    "Night mist below freezing. She's gentle. The cold is not. That's the whole story. Layer up girl.",
    "She's sprinkling the softest rain below freezing at night. Precious. The cold can eat shit. Stay cozy babe.",
  ],
  TemperatureTier.jacketWeather: [
    "She's barely even fucking raining. Like if rain had a quiet voice this is it babe.",
    "Cool night drizzle. She's misting us like we're in a fucking music video. Jacket on girl.",
    "She's giving soft atmospheric mist tonight. Low effort high aesthetic. Jacket on babe.",
    "Cool drizzle at night. She's setting a mood and honestly not asking permission. Into it girl.",
    "She's dripping on us so gently it's kind of beautiful. Jacket on girl.",
    "She's teasing us with rain. Just barely there and somehow perfect. Jacket weather babe.",
    "Cool night mist. She's microdosing rain and it's working for her honestly girl.",
    "She's doing her quiet rain thing tonight. The vibe is immaculate. Jacket on babe.",
    "She turned on the mist setting and made everything shiny. Gorgeous honestly girl.",
    "Cool drizzle and the night looks glazed. She's making everything pretty. Jacket on babe.",
    "She's fucking microdosing rain. Bold strategy and honestly it's landing girl.",
    "Night drizzle at jacket temp. She's being gentle and atmospheric as fuck babe.",
    'Cool night and the drizzle is just enough to fog up your glasses. Moody as hell. Jacket on girl.',
    "The drizzle is so fine it's almost a concept. Barely wet barely there. Cool night though babe.",
    "She's giving us the lightest rain at the perfect jacket temp. Atmospheric queen girl.",
    "Cool night mist. Everything is damp and shiny and she did that. Jacket on babe.",
    'Cool drizzle and the sidewalks are shiny. She made the pavement pretty. Jacket on girl.',
    "The drizzle just touched my face and honestly it's kind of romantic. Jacket weather babe.",
    "She turned the night into a light mist and the temp into jacket weather. Whole vibe honestly girl.",
    "Drizzle so light it's barely there. She's being subtle tonight. Jacket on and enjoy it babe.",
  ],
  TemperatureTier.flannelWeather: [
    "She's being soft and we don't trust it but we're into it. Suspicious as hell girl.",
    "Rain on the windows. She's setting a mood and it's actually fucking working girl.",
    'Mild drizzle and the world sounds different. Every surface has a voice tonight girl.',
    "She's on her best behavior tonight. Suspicious as fuck but cute babe.",
    "She's being gentle and it's weirding me the fuck out girl.",
    "Rain tapping on everything like it's got something to say. Speak the fuck up girl.",
    "This is her apology tour and honestly she's fucking nailing it.",
    "She's fucking being atmospheric and she doesn't even know it babe.",
    "She's being fucking gentle for once and honestly it's making us emotional girl.",
    "The streets are shiny and she's feeling herself girl.",
    "The drizzle is tapping on my window like it has gossip. I'm listening babe.",
    "Mild and drizzly and I'm outside with no umbrella on purpose. She made me feral girl.",
    "She's not trying hard but she's trying fucking pretty. That's enough. Damn girl.",
    "She's tapping on the windows like she wants to come in bitch.",
    "Light rain perfect temp. She's being the version of herself I keep telling people about babe.",
    "The drizzle is so gentle it's suspicious as fuck. Free therapy no copay. She's up to something girl.",
    'She finally figured out how to be cute about it. Took long enough girl.',
    "Mild drizzle and the streets look glazed. She's making everything shiny and I'm outside staring girl.",
    "She's doing the bare minimum and making it romantic somehow babe.",
    "She's barely raining and it's the prettiest weather we've had all week. Flannel on go babe.",
  ],
  TemperatureTier.shortsWeather: [
    'She choreographed this for you. Wet streets glowing lights warm air. Go fucking live babe.',
    "She's putting in effort and it shows. We see you girl. We fucking see you.",
    "She's being fucking perfect and it's making us nervous. What's the catch girl.",
    'Warm drizzle and the air smells incredible. She turned the night into a whole experience girl.',
    "She's being so gentle tonight it's suspicious as fuck girl.",
    'She touched our face with rain and we blushed. Down bad as hell babe.',
    "Go walk through it. Be mysterious. She's fucking setting the scene girl.",
    "She's misting us like an expensive facial. Free skincare girl.",
    'This is foreplay weather and I said what I said bitch.',
    'Go stand in it. Like shit. Be that girl.',
    "Warm light rain and I'm outside getting gently wet and having feelings. She did this to me babe.",
    "She's being fucking romantic and we didn't sign up for these damn feelings babe.",
    "Go outside. Get your hair wet. Look mysterious. Fall in fucking love. She's demanding it girl.",
    "The drizzle is so warm it's like standing in someone's breath. Weird? Yes. Into it? Also yes babe.",
    "She's drizzling on us in shorts weather and somehow it's the best night this week. She's a genius girl.",
    "She learned our love language and it's gentle rain apparently. Noted babe.",
    "She brought wine and rain and soft lighting. We're not saying no girl.",
    'Warm drizzle and the whole neighborhood is glistening. She polished the damn city babe.',
    "She's drizzling on us in shorts weather like she's earned our trust. She hasn't. But tonight we're pretending babe.",
    "She's serenading us with tiny rain and perfect temps. Down bad girl.",
  ],
  TemperatureTier.scorcher: [
    "Rain's not helping it's just adding humidity. Thanks for fucking nothing girl.",
    "She's doing the least and somehow making it worse. One talented bitch.",
    "She's fucking not cooling anything down she's marinating us. Medium rare by morning girl.",
    "Hot drizzle. She's adding moisture to the already unbearable. Chef's kiss of suffering babe.",
    "She added water to fucking hot oil. She's trying to start a fire girl.",
    "She's crying in the shower and dragging us in with her bitch.",
    "Scorching drizzle. The rain evaporates before it hits the ground. She's not even cooling us off girl.",
    "Rain evaporating before it hits the ground. She's fucking not even trying girl.",
    "She's misting us in a sauna. Nobody asked for this babe.",
    "She added drizzle to the heat like she's seasoning our suffering. Needed more wet I guess babe.",
    "Hot drizzle. The air is so thick and wet I'm basically drinking it. Hydrate by breathing I guess girl.",
    "The air is wet the ground is wet we're wet. Nobody consented girl.",
  ],
};
