import '../../../../features/weather/domain/entities/temperature_tier.dart';

const foggyExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Foggy single digits. Can't see shit can't feel your face. Love that. Puffer on babe.",
    "It's giving Silent Hill. Creepy af cold af. Every layer and watch out babe.",
    "Foggy and cold as fuck. Mysterious AND mean. Biggest coat babe. Or just don't.",
    "Fog and single digits. Can't see shit can't feel shit. Bundle up babe.",
    'Foggy and cold as fuck. She rolled up like a true villain. No announcement just fog babe.',
    'She rolled in fucking mysterious and freezing. Zero visibility. Zero fucks. Bundle up girl.',
    "Cold fog. Fucking dramatic and dangerous. Love the aesthetic but she's trying to kill us. Puffer on girl.",
    'Foggy and freezing. She deleted the sun and the warmth. Ctrl alt delete af babe.',
    "It's giving Suspiria. Cold foggy and she's not letting you leave girl.",
    'Single digits and fog. She said let me take your vision AND your warmth. How generous.',
  ],
  TemperatureTier.freezing: [
    'Foggy and cold as fuck. Mysterious but so not the vibe. Blanket burrito status babe.',
    "It's giving Last House on the Left. Cold and eerie as fuck. Don't get got babe. Watch it.",
    'Foggy and cold af. Vibes are immaculate. Temp is disrespectful. Layers babe.',
    'Fog below freezing. See nothing and freeze. Bold choice. Layer the fuck up babe.',
    'Foggy and cold as fuck. She looks good though. At least she has that going for her.',
    "Fog below freezing. She's gorgeous she's cold she's not sorry. Trifecta from hell.",
    "Fog below freezing. She's the fucking hot villain you root for even though she's ruining your life girl.",
    'Below freezing and foggy. She erased the world and turned down the thermostat. Double homicide. What the hell.',
    "It's giving Kate Bush energy. Foggy cold dramatic. Coat on babe.",
    'Freezing fog. Two words that should never meet. Like no. Warmest coat girl.',
    'Below freezing and she erased the whole view. Classic her. Heavy coat babe.',
    "Foggy and freezing. She showed up gorgeous and cold and won't explain herself. Never does.",
  ],
  TemperatureTier.jacketWeather: [
    "Cool and foggy. I can't see shit but I feel like I'm in a perfume commercial. Jacket on babe.",
    'Cool fog. She hid the road. She hid the trees. She hid the fucking sidewalk. Helpful.',
    'Foggy and cool. Google Maps just said good luck bitch. Even the GPS gave up babe.',
    "Fog at this temp. She's whispering and I'm leaning in. This is how people go missing babe.",
    "Foggy and cool. She showed up soft and moody and I'm following her into the mist. No questions.",
    "Foggy jacket weather. She showed up soft and spooky and I'm weirdly into it. Ignoring red flags is my fav honestly.",
    "Final Destination vibes out here. Foggy cool and she's plotting something. Jacket on eyes open babe.",
    'Foggy and cool. She rolled in like she owns the place. She does right now honestly.',
    'Cool and foggy. She erased the horizon and replaced it with vibes. Jacket on go get lost babe.',
    "Fog at this temp. Just discovered a street I've lived near for three years. She's a tour guide from hell babe.",
    'She rolled in so thick my dog stopped walking and looked at me like are we dead. No baby. Jacket on girl.',
    "Foggy and cool. I can hear footsteps but can't see the person. She invented a new anxiety. Jacket on girl.",
    'Cool fog. She put the whole city on airplane mode. No signal no visibility. Jacket on girl.',
    "Foggy and cold. Girl go back to design school this isn't working for you.",
  ],
  TemperatureTier.flannelWeather: [
    'Foggy dreamy mild af. Mazzy Star on the headphones. Go fade into her babe.',
    'Portishead vibes out there. Moody as fuck fog out in full force. Get outside babe.',
    'Foggy flannel weather. She erased the world and left us the vibes. Fair trade honestly babe.',
    "Mild fog. She dimmed the lights and set the mood. Didn't ask. Didn't need to bitch.",
    "Foggy and mild. I'm outside and I can't see shit and I've never been more at peace. She healed me girl.",
    'She tucked the whole city into bed and left the nightlight on. Mild foggy fucking perfect babe.',
    'Foggy flannel weather. Hoodie on. Vibes high. Get the fuck out there girl.',
    "Can't see the sky. Don't need to. She feels fucking perfect. Flannel on babe.",
    "Fog rolled in mild and moody. She's a whole damn aesthetic. Go be in it girl.",
    'She erased the horizon and left us the perfect fucking temp. Go get lost babe.',
  ],
  TemperatureTier.shortsWeather: [
    'Foggy and warm as fuck. Romcom or horror movie? Shorts on either way babe.',
    'Foggy shorts weather is underrated. Spa energy. Go play girl.',
    "Warm fog. Can't see shit but it feels incredible. Shorts on go girl.",
    "Fog at this temp. She's warm as fuck and I just walked into a tree. Worth it babe.",
    "Foggy and warm. Lost and moisturized. She's multitasking. Queen shit.",
    'Warm and foggy. She just hot boxed the entire neighborhood. Shorts on girl.',
    "Warm fog. Can't see can't care. Shorts on get your ass out there babe.",
    "She's warm and foggy and you don't need to see. You need to feel. Shorts on bitch.",
  ],
  TemperatureTier.scorcher: [
    "Foggy scorcher. Can't see shit and I'm melting. She really covered all the bases. Love that.",
    'Scorching fog. She said let me make it worse and then hide. Strategic bitch.',
    "Hot fog. She's fucking waterboarding us with humidity. Gently. Lovingly. Still waterboarding.",
    'Scorching and foggy. Air so fucking thick you could chew it. Hydrate girl.',
    'Hot and foggy. The humidity has hands today. Stay cool if you can babe.',
    "Foggy scorcher. I can't see and I'm dissolving. She's erasing evidence girl.",
    'She served a scorcher in fog like a villain monologuing behind a curtain. We can feel you girl.',
    "Hot fog. She turned the outside into the inside of a dishwasher mid cycle. We're the dishes babe.",
    'Foggy and scorching. Even my sweat is sweating. She broke the system girl.',
  ],
};

const foggyExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She's cosplaying as a haunted house and honestly she's fucking nailing it girl.",
    "Fog rolled in and deleted the whole world. It's freezing. She's dramatic as fuck girl.",
    "She erased the world and left us in the freezer. Can't see can't feel can't cope babe.",
    "She's not hiding the sky she's burying it. Cold-blooded af.",
    'Streetlights floating in the void. Creepy as fuck. Stay in babe.',
    "Can't see the sky can't feel your fucking face. Stay inside girl.",
    'The fog ate every landmark. I could be in my yard or in hell. Same energy in single digits girl.',
    'She really put the whole night on mute and turned the fucking cold up. Psychopath vibes honestly.',
    'She really hit us with the smoke machine and the freezer. Broadway villain energy girl.',
    'She dissolved the neighborhood and kept the cold. Nothing to see but suffering babe.',
    "She swallowed everything and it's single digits. She said ambiance? Try survival babe.",
    'She wrapped the world in cotton and set the thermostat to death girl.',
  ],
  TemperatureTier.freezing: [
    'Streetlights look like ghosts. Aesthetic but freezing. Thanks? babe.',
    'Visibility temp vibes. All fucked. Trifecta of bullshit girl.',
    'She took the sky AND the warmth? Greedy babe.',
    'Fog so thick it has texture. Touched the air. Disgusting girl.',
    'Haunted vibes and personal temps. Petty af babe.',
    "Director's cut nobody wanted. Foggy and freezing bitch.",
    "Can't see the sky but can see your breath. Priorities girl.",
    "She swallowed the stars and it's freezing. Beautiful and mean. Classic babe.",
    "World's two feet wide. Everything else is fog and suffering girl.",
    'Fog pressing against the windows like it wants in? It can stay out babe.',
    'She gift-wrapped the block in cold mist. Who asked for this girl.',
  ],
  TemperatureTier.jacketWeather: [
    "Every streetlight's got a halo. She's being cinematic as fuck girl.",
    "Can't see shit but the vibes are immaculate. Jacket on babe.",
    'Foggy and cool. Every sound is muffled. I sneezed and it just disappeared. The fog ate it babe.',
    'Holy shit. She deleted the background but kept the aesthetic. Graphic design queen.',
    'The fog turned every light into a lantern. Cool night and the whole block looks like a painting girl.',
    'She dimmed the world and added mystery. Bold edit babe.',
    "Everything's muffled and soft. She turned the volume down on reality bitch.",
    "Visibility's gone but the vibes showed up. She's fucking prioritizing correctly for once.",
    "She turned the world into a music video. Like shit. Nobody asked but we're watching girl.",
    'Holy shit. She put the world on airplane mode. No visibility no fucks given babe.',
    "Cool foggy night and I can't see the end of my street. She erased the horizon babe.",
    'She put the whole neighborhood in soft focus. Cool and blurry and honestly gorgeous girl.',
    "She made everything blurry and called it art. A bit pretentious but it's working babe.",
    'Fog rolled in and now every walk is a mystery walk. Jacket on go get lost babe.',
    'She put a diffuser on the whole neighborhood. Skincare for the sky girl.',
    'She rolled in like she owns the place. She kind of does babe.',
  ],
  TemperatureTier.flannelWeather: [
    'She put the whole neighborhood in a dream sequence. Main character shit girl.',
    "She dimmed the whole world and it's gorgeous as fuck. Go outside babe.",
    "The world looks drunk and gorgeous. She's fucking that friend again girl.",
    'Streetlights got halos. Even the lamp posts are holier than thou tonight bitch.',
    'She blurred everything and made it fucking gorgeous. Gaslighting us into going outside girl.',
    "Mild and foggy and I'm walking down the street like I own it. Can't see anyone to judge me babe.",
    "She put a filter on reality. No one consented. No one's complaining babe.",
    "She's being pretty and mysterious and not explaining a damn thing. Classic her.",
    'Flannel on get out there. She fogged the whole block and made it fucking gorgeous girl.',
    'Go walk in it. She turned the world blurry and warm. Flannel on go be mysterious babe.',
    'Get outside. The fog made everything look like a damn painting. Flannel weather masterpiece girl.',
  ],
  TemperatureTier.shortsWeather: [
    "Streetlights glowing like they're high af. Like girl wait up I'm coming.",
    "Visibility's fucked but the vibes are elite. She knows what she's doing babe.",
    'She turned the world into a sauna with mood lighting. Bougie as fuck girl.',
    'She steamed up the whole fucking block. Free facial I guess girl.',
    "She can't see us we can't see her. Mutual ghosting. Vibes are fucking great though girl.",
    'Holy shit. She put a humidifier on the whole block. Skincare queen energy.',
    'She turned the night into a steam room. No towel no visibility no complaints babe.',
    "She hit the vape and now we're all living in it. Thanks girl.",
    'The fog is so warm it feels tropical. She turned my street into a rainforest minus the rain girl.',
    "Shorts on. The fog's warm as fuck. Go walk through it like you own the damn place babe.",
    "Get outside. The fog made everything a movie set and you're the fucking lead girl.",
    'She wrapped the block in warm fog. Shorts on go get lost in it babe.',
  ],
  TemperatureTier.scorcher: [
    "Can't see shit can't breathe shit. She's trying to kill us girl.",
    'Hot fog. The air is a wet towel somebody microwaved. Nobody ordered this service babe.',
    "She can't see us sweating and honestly that's for the best girl.",
    'She turned the neighborhood into a steam room with no exit sign. Scorching and blind girl.',
    'She turned the whole block into a fucking hot yoga class nobody signed up for girl.',
    "She's running a sweatshop and we're all clocked in. Drink water girl.",
    'She put a hot towel over the whole city. Nobody booked this treatment bitch.',
    'The air is so thick I could write my name in it. Foggy scorching and impossible girl.',
    "She vaporized the air and called it ambiance. Ma'am this is assault.",
    "She turned the night into a pressure cooker. We're the beans girl.",
    "The fog is holding the heat in like it's personal. Every breath is soup babe.",
    'She really wrapped us in a hot wet blanket. Thanks I hate it.',
  ],
};
