import '../../../../features/weather/domain/entities/temperature_tier.dart';

const freezingRainExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Freezing rain in single digits. Girl why. Who even does this. Stay inside babe.",
    "She's doing freezing rain in single digits. Like girl what is this. Stay safe girl.",
    "Freezing rain at this temp. Girl WHY. Stay the fuck inside babe.",
    "She chose freezing rain in single digits. Like girl who asked for this. Be careful babe.",
    "Freezing rain. In single digits. Girl what are you doing. Stay inside girl.",
    "She's icing everything in single digits. Girl why though. Stay home babe.",
    "Freezing rain at this temp. Like of all the options girl why THIS one. Stay safe girl.",
    "She went with freezing rain in single digits. Girl what. Why. Stay inside babe.",
    "Freezing rain in the cold. Girl who even does that. Who. Stay safe girl.",
    "She chose freezing rain. In single digits. Girl the fuck. Be so careful out there babe.",
    "Freezing rain at this temp. Girl why are you like this. Stay inside girl.",
    "She's doing freezing rain in single digits and I'm just confused. Girl why. Stay safe babe.",
  ],
  TemperatureTier.freezing: [
    "Freezing rain below freezing. Girl why. Why would you do this. Stay inside babe.",
    "She's doing freezing rain below freezing. Like girl what is the point of this. Be careful girl.",
    "Freezing rain at this temp. Girl who even. What are you doing. Stay safe babe.",
    "She chose freezing rain below freezing. Girl WHY though. Stay inside girl.",
    "Freezing rain. Below freezing. Girl what. Who asked for this. Be careful babe.",
    "She's icing everything below freezing. Like girl why this option. Of all options. Stay safe girl.",
    "Freezing rain at freezing temps. Girl what is this. Why. Stay inside babe.",
    "She went with freezing rain below freezing. Like girl make it make sense. Be careful girl.",
    "Freezing rain at this temp. Who does this. Girl why. Stay safe inside babe.",
    "She's doing freezing rain and I'm just bewildered. Girl what. Stay inside girl.",
    "Below freezing and she chose freezing rain. Girl the fuck. Why this. Be careful babe.",
    "Freezing rain. Girl why are you like this. Just be snow. Stay safe girl.",
    "She's icing the city below freezing. Like girl who hurt you. Stay inside babe.",
  ],
  TemperatureTier.jacketWeather: [
    "Freezing rain at jacket temp. Girl why. It's not even that cold. Be careful babe.",
    "She's doing freezing rain at jacket weather. Like girl what. Why. Watch your step girl.",
    "Freezing rain at this temp. Girl who does this. Why though. Be careful babe.",
    "She chose freezing rain at jacket weather. Girl WHAT. Make it make sense. Stay safe girl.",
    "Freezing rain at jacket temp. Like girl why are you like this. Watch your step babe.",
    "She's icing things at jacket weather. Girl the fuck. Who asked. Be careful girl.",
    "Freezing rain at this temp. Girl why though. It doesn't even make sense. Stay safe babe.",
    "She left ice at a perfectly fine temp. Girl why would you do that. Watch your step girl.",
    "Freezing rain at jacket weather. Girl what is this energy. Be so careful out there babe.",
    "She's doing freezing rain when it's barely cold. Girl why. Just why. Watch it girl.",
    "Freezing rain at jacket temp. Like girl this is so confusing. Be careful babe.",
    "She chose freezing rain at this temp. Girl who even does this. Watch your step babe.",
  ],
  TemperatureTier.flannelWeather: [
    "Freezing rain at flannel weather. Girl what. How. Why. Be careful babe.",
    "She's doing freezing rain at mild temps. Girl this makes no sense. Watch your step girl.",
    "Freezing rain at this temp. The most confusing shit. Be careful out there babe.",
    "She chose freezing rain at flannel weather. Girl why would you do that. Stay safe girl.",
    "Freezing rain at mild temps. Girl who even does this. What. Watch your step babe.",
    "She's icing things at flannel weather. Girl the FUCK. Why. Be careful girl.",
    "Freezing rain at this temp. Girl how is this even possible. Watch it babe.",
    "She brought freezing rain to flannel weather. Girl what are you doing. Be careful girl.",
    "Freezing rain at mild temps. Girl why though. Watch your fucking step babe.",
  ],
};

const freezingRainExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Freezing rain in single digits at night. Girl why. Why this. Stay inside babe.",
    "She's doing freezing rain at night in the cold. Like girl what. Stay safe girl.",
    "Night freezing rain in single digits. Girl who does this. Be so careful babe.",
    "Freezing rain at night in single digits. Girl the fuck. Why though. Stay inside girl.",
    "She chose freezing rain at night in the cold. Girl what are you doing. Stay safe babe.",
    "Night freezing rain at this temp. Girl why would you. Stay inside girl.",
    "Freezing rain in single digits at night. Girl what is this. Be careful babe.",
    "She's icing everything at night in single digits. Girl why. Stay the fuck inside girl.",
    "Night freezing rain in the cold. Like girl what even is this. Stay safe babe.",
    "Freezing rain at night in single digits. Girl I am confused. Stay inside girl.",
    "She's doing freezing rain at night in the cold. Girl who even. Be careful babe.",
    "Night freezing rain in single digits. Girl WHY though. Stay safe inside girl.",
  ],
  TemperatureTier.freezing: [
    "Freezing rain below freezing at night. Girl why. Who does this at night. Stay safe babe.",
    "Night freezing rain below freezing. Girl what even is this. Be careful girl.",
    "She's doing freezing rain below freezing at night. Girl why though. Stay inside babe.",
    "Freezing rain at night below freezing. Like girl what. Be so careful girl.",
    "Night freezing rain at this temp. Girl the fuck. Why this option. Stay safe babe.",
    "She chose freezing rain below freezing at night. Girl I'm confused. Be careful girl.",
    "Freezing rain at night in the cold. Girl who even does this. Stay inside babe.",
    "Night freezing rain below freezing. Like girl what are you doing. Stay safe girl.",
    "She's icing everything below freezing at night. Girl why. Just be snow. Be careful babe.",
  ],
  TemperatureTier.jacketWeather: [
    "Freezing rain at jacket temp at night. Girl why. It's not even cold. Be careful babe.",
    "Night freezing rain at jacket weather. Girl what is this. Why though. Watch your step girl.",
    "She's doing freezing rain at jacket temp at night. Girl who asked for this. Be careful babe.",
    "Freezing rain at night at jacket temp. Like girl make it make sense. Stay safe girl.",
    "Night freezing rain at this temp. Girl why are you like this tonight. Watch your step babe.",
    "She chose freezing rain at jacket weather at night. Girl the FUCK. Be careful girl.",
    "Freezing rain at night at jacket temp. Girl who does this. Watch it babe.",
    "Night freezing rain at this temp. Girl what are you doing. Be careful girl.",
    "She's icing things at jacket temp at night. Girl why though. Stay safe babe.",
    "Freezing rain at jacket weather at night. Like girl this is so confusing. Watch your step girl.",
    "Night freezing rain at this temp. Girl why would you do this. Be careful babe.",
    "She's doing freezing rain at jacket temp at night. Girl I don't understand. Watch it girl.",
  ],
  TemperatureTier.flannelWeather: [
    "Freezing rain at flannel weather at night. Girl what. How. Be careful babe.",
    "Night freezing rain at mild temps. Girl why. This makes no sense. Watch your step girl.",
    "She's doing freezing rain at flannel weather at night. Girl who does this. Be careful babe.",
    "Freezing rain at night at mild temps. Girl HOW is this possible. Stay safe girl.",
    "Night freezing rain at flannel temp. Girl the fuck. Why though. Watch it babe.",
    "She chose freezing rain at mild temps at night. Girl what even. Be careful girl.",
    "Freezing rain at flannel weather at night. Girl I am bewildered. Watch your step babe.",
    "Night freezing rain at this temp. Girl make it make sense. Be careful girl.",
    "She's icing things at flannel temps at night. Girl WHY. Stay safe babe.",
    "Freezing rain at night at flannel weather. Girl who asked for this. Watch it girl.",
    "Night freezing rain at mild temps. Girl what is happening. Be so careful babe.",
  ],
  TemperatureTier.shortsWeather: [
    "Freezing rain in shorts weather at night. Girl WHAT. How is this real. Be careful babe.",
    "Night freezing rain at warm temps. Girl why. This is not supposed to happen. Watch it girl.",
    "She's doing freezing rain in shorts weather at night. Girl who even. Be careful babe.",
    "Freezing rain at night in warm weather. Girl make it make sense. Stay safe girl.",
    "Night freezing rain at shorts temp. Girl HOW. Why. What. Be careful babe.",
    "She's icing things in shorts weather at night. Girl the fuck. Why. Watch your step girl.",
    "Freezing rain in warm weather at night. Girl I am so confused. Be careful babe.",
    "Night freezing rain at this temp. Girl what is happening right now. Stay safe girl.",
    "She chose freezing rain in shorts weather at night. Girl who does this. Be careful babe.",
    "Freezing rain at night at warm temps. Girl what are you doing. Watch it girl.",
    "Night freezing rain in shorts weather. Girl WHY though. Be so careful babe.",
    "She's doing freezing rain at warm temps at night. Girl I don't understand. Stay safe girl.",
    "Freezing rain in shorts weather at night. Girl how is this even possible. Be careful babe.",
  ],
  TemperatureTier.scorcher: [
    "Freezing rain in a scorcher at night. Girl WHAT. What is happening. Be careful babe.",
    "Night freezing rain in extreme heat. Girl why. How. I am so confused. Stay safe girl.",
    "She's doing freezing rain in a scorcher at night. Girl who even does this. Be careful babe.",
    "Freezing rain at night in scorching heat. Girl make it make sense. Stay safe girl.",
    "Night freezing rain in the heat. Girl the FUCK. How is this real. Be careful babe.",
    "She chose freezing rain in a scorcher. Girl what are you doing. Stay inside girl.",
    "Freezing rain at night in extreme heat. Girl I don't even know. Be careful babe.",
    "Night freezing rain in a scorcher. Girl my brain can't process this. Stay safe girl.",
    "She's icing things in the scorching heat at night. Girl WHY. Be so careful babe.",
    "Freezing rain in a scorcher at night. Girl who is responsible for this. Stay safe girl.",
    "Night freezing rain in the heat. Girl how is this possible. Be careful babe.",
    "She's doing freezing rain in extreme heat at night. Girl what is this. Stay inside babe.",
  ],
};
