import '../../../../features/weather/domain/entities/temperature_tier.dart';

const freezingRainExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Coating everything in ice. Villain shit babe.',
    'Madonna Frozen but literal. Everything is ice. The fuck. Stay in girl.',
    'She weaponized the fucking ground. Every step is a death wish.',
    'She turned the whole city into a slip and slide to hell. Fucking diabolical.',
    'She really said fuck your ankles fuck your car fuck your plans.',
    'Jesus. Roads are death traps. She coated the city in ice. Stay home babe.',
    "She's not just fucking dangerous she's actively trying to kill us. Respect honestly.",
    'Glazed every damn surface in ice. Villain mode. Do not get the fuck out there.',
    'Final Destination vibes. Every surface is a trap. Stay in babe.',
    "She thinks she's Megan Fox in Jennifer's Body. Ice cold dangerous gorgeous. Stay inside honestly.",
    "She glazed the city like a donut and now we're all gonna die on the sidewalk.",
    'Her deadliest era. Zero fucks given.',
  ],
  TemperatureTier.freezing: [
    'She froze the rain before it landed. Genuinely dangerous as fuck. Do not go out there.',
    "Below freezing and ruthless as fuck. She iced every surface like she's collecting our ankles. Stay inside girl.",
    "She's out here turning the city into a fucking hockey rink. Nobody asked for this girl.",
    "She really said fuck everyone's ankles specifically. Targeted violence.",
    "She really woke up and said today I will personally fuck up everyone's commute.",
    "She's out here collecting broken ankles like fucking Pokemon. Gotta catch em all.",
    "Icing everything in sight like she's decorating the world's worst cake. Nobody ordered this shit.",
    "Jennifer Lawrence in Winter's Bone energy. Everything is frozen and fucking deadly. Stay inside girl.",
    "Oh fuck. She said I'm going to make the ground personally betray every single one of you.",
    'Coating the world in ice. Zero remorse babe.',
    'Full villain mode. Batshit and beautiful girl.',
    'She iced the whole city and went back to bed. Unbothered. Unhinged. Iconic honestly.',
    "She turned the sidewalk into a slip n slide except it's not fun and everyone's crying.",
  ],
  TemperatureTier.jacketWeather: [
    'Left ice everywhere like a rude houseguest. Still dangerous as shit babe.',
    "It's not even that cold and she still iced the roads. She does this shit for fun.",
    "She's a sneaky fucking psycho. The warm air is a lie. The ground wants you dead.",
    "Temp says fine. Ground says fuck you. She's playing both sides.",
    'Nicole Kidman in Cold Mountain energy. Ice at this temp is sneaky girl.',
    "Like a passive aggressive sticky note. Girl we can't walk.",
    'Ice is thinning but she left traps everywhere. Watch your damn step.',
    "Not even cold and the ground is a crime scene. She's framing the temperature babe.",
    "She left invisible ice at a perfectly fine temp. She's a saboteur. Watch every step girl.",
    "The air says jacket weather. The sidewalk says lawsuit. She's sending mixed signals babe.",
    'She iced the roads when nobody was looking. Security camera footage pending. Watch it girl.',
    'Freezing rain at jacket weather. She brought a knife to a pillow fight. Watch your step babe.',
  ],
  TemperatureTier.flannelWeather: [
    'Should not be possible. Unhinged as fuck babe.',
    'Goddamn. Mild out but she left ice everywhere. Still slippery. Watch it babe.',
    'The most confusing shit. Dangerous though babe.',
    "Don't trust that shit. She left traps all over.",
    'She brought freezing rain to flannel weather. Like bringing a sword to a pillow fight. What the hell girl.',
    'Who the fuck does that. Unhinged honestly.',
    'Stormy Weather took a fucking weird damn turn. Watch yourself girl.',
    "Donnie Darko energy. Ice at mild temps. Something's wrong with the timeline. Watch it babe.",
    'Mild outside but the ground says otherwise. She glazed everything. Watch your fucking step girl.',
  ],
};

const freezingRainExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She's not angry she's strategic. Every surface is a fucking crime scene babe.",
    'She looked at regular winter and said let me make it lethal as fuck girl.',
    "Step outside and eat shit immediately. That's a promise not a threat babe.",
    "She lacquered the world and now everything's a mirror. Beautiful and deadly as fuck girl.",
    "She's coating everything in ice like she's preserving evidence. Sick as hell babe.",
    "She's not trying to inconvenience you she's trying to fucking hospitalize you babe.",
    "She said fuck snow that's too obvious. Ice is classier babe.",
    "She's gift wrapping the neighborhood in black ice. Stay the fuck inside girl.",
    'Every step is a fucking audition for a fall compilation video girl.',
    "She's playing chess while the rest of us are just trying to stand up babe.",
    'Your driveway is an ice luge now. Congrats on the Olympic venue girl.',
    'She turned the whole damn city into a skating rink nobody asked for girl.',
  ],
  TemperatureTier.freezing: [
    'Varnishing every surface with a coat of fuck you. Nice babe.',
    'Trust fall on the sidewalk? Nobody signed up girl.',
    'Froze the rain mid-air to prove she could. Psycho shit babe.',
    'Every step is a gamble. House always wins girl.',
    'Regular cold is amateur hour apparently. Watch this babe.',
    'Gorgeous ice on the streetlights. Your ankles though? In danger girl.',
    "Trees stunning. Ground death trap. She's multitasking babe.",
    'She laminated the whole neighborhood. Thorough girl.',
    'Shellacked the city and went to bed. Zero remorse babe.',
  ],
  TemperatureTier.jacketWeather: [
    "She's glazing everything and it's not even that cold. Fucking drama queen.",
    "She didn't need to do this but she chose violence anyway. Petty as fuck girl.",
    "It's not even freezing out and she's still icing shit. Overachiever babe.",
    'She iced the roads at jacket weather. She woke up and chose pettiness girl.',
    "She said I know it's not that cold but I'm still gonna ice your shit babe.",
    "Unnecessary aggressive and inconvenient. She's that bitch.",
    "She escalated for no damn reason. Couldn't just be fucking cold and chill about it girl.",
    "She's doing the most for mediocre fucking cold. Relatable honestly girl.",
    'My car has a full body ice mask on. Spa day but for sedans babe.',
    "She's being dramatic for no reason. She gets off on this honestly.",
    "She's overperforming and nobody asked her to girl.",
    'She brought black ice to a jacket weather party. Read the room babe.',
  ],
  TemperatureTier.flannelWeather: [
    'Make it make fucking sense. It literally cannot babe.',
    "She's not even cold enough for this shit but here we are girl.",
    "She's icing the roads at flannel weather and the audacity alone could kill you girl.",
    "She glitched. This isn't supposed to fucking happen girl.",
    "She's committing crimes against fucking meteorology babe.",
    "The math isn't mathing. The science isn't sciencing babe.",
    'She brought a winter weapon to a spring night. Read the room girl.',
    "She's not making a damn bit of sense and she doesn't care girl.",
    "Stay the fuck inside. She's icing roads at flannel temps and the sidewalk is a lawsuit babe.",
    'Do not go out there. The ground is a trap and the weather is a liar girl.',
    "Flannel on feet up stay the fuck put. She's doing ice where ice has no business being babe.",
  ],
  TemperatureTier.shortsWeather: [
    "She's icing shit in shorts weather. Somebody file a complaint with the sky babe.",
    "She's not even supposed to be here right now. What the fuck girl.",
    "She put ice on the ground in warm weather. She's freelancing at this point babe.",
    "She's gaslighting the shit out of us. Seasons aren't real babe.",
    "She showed up to the wrong damn season and doesn't care girl.",
    "She's fucking committing weather fraud babe.",
    "She didn't read the assignment bitch.",
    'The weather app is having a stroke babe.',
    'Physics left the chat. Science is crying girl.',
    "She's got ice on the ground and sweat on my forehead. Make it make sense girl.",
    "Stay the fuck inside. She's icing shit in shorts weather and the sidewalk is a crime scene babe.",
    'Do not go out there. She turned the warm sidewalk into a skating rink nobody asked for girl.',
    'Feet up shorts on stay the fuck put. The ground is her ice sculpture tonight babe.',
  ],
  TemperatureTier.scorcher: [
    'The weather is having a full fucking psychotic break babe.',
    "Ma'am this is a fucking Wendy's babe.",
    'Holy shit. The atmosphere is drunk. Somebody take her keys babe.',
    "She's speedrunning every fucking season at once girl.",
    "She's cycling through personalities tonight and none of them are fucking stable babe.",
    "She's simultaneously broken and iconic as fuck girl.",
    "She's dropping ice in a scorcher. She's running two weather systems at once girl.",
    'Hot freezing rain at night. My brain blue screened. Restarting girl.',
    "The forecast didn't study for the damn exam girl.",
    "Stay the fuck inside. She's doing hot ice and the ground is a death trap babe.",
    'Do not go out there. She broke physics and your ankles are next girl.',
    "Lightest PJs and stay the fuck put. She's icing shit in a scorcher. Nothing is safe babe.",
  ],
};
