import '../../../../features/weather/domain/entities/temperature_tier.dart';

const hailExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Hailing in single digits. Oh shit be careful babe. She's not playing right now.",
    "She's hailing in single digits. Stay the fuck inside girl. She's intense right now.",
    "Hail at this temp. Girl watch out. She's going hard. Stay inside babe.",
    "Single digit hail. Be careful out there babe. She's really going for it.",
    "She's dropping ice in single digits. Stay safe girl. She's not messing around.",
    "Hailing in the cold. Please stay inside babe. She's being a LOT right now.",
    "Single digit hail. Girl do not go out there. She's intense as fuck right now babe.",
    "She's hailing in single digits. Be so careful girl. The cold plus ice is no joke.",
    "Hail at this temp. Stay in babe. She's really not holding back tonight.",
    "She brought hail to single digits. Watch out girl. She's being serious right now babe.",
  ],
  TemperatureTier.freezing: [
    "Hailing below freezing. Oh girl be careful. She's really going for it right now babe.",
    "She's hailing below freezing. Stay inside girl. She's not playing tonight.",
    "Below freezing and hailing. Be so careful babe. She's intense as fuck right now.",
    "Hail below freezing. Girl stay in. She's being really serious tonight babe.",
    "She's dropping ice below freezing. Watch out girl. She's not holding back.",
    "Holy shit. Hailing below freezing. Stay safe babe. She's going hard right now.",
    "Freezing hail. Please be careful girl. She's really not messing around tonight.",
    "Below freezing and she's hailing. Stay inside babe. She's being intense.",
    "She's hailing in the cold. Girl be careful. She's not slowing down babe.",
    "Hail below freezing. Stay the fuck inside girl. She's going off right now babe.",
  ],
  TemperatureTier.jacketWeather: [
    "Hailing at jacket temp. Girl stay inside. She's being intense right now babe.",
    "She's hailing at jacket weather. Be careful out there girl. She's not playing.",
    "Holy shit. Hail at this temp. Stay safe babe. She's really going for it.",
    "Sky dropped hail at jacket weather. Watch out girl. She's not messing around babe.",
    "Hailing at jacket temp. Be so careful if you go out there babe. She's going hard.",
    "Hail at jacket weather. Stay inside girl. She showed up intense today babe.",
    "She's dropping hail at jacket temp. Watch out babe. She's being serious right now.",
    "Hailing at this temp. Be careful girl. She's really not holding back today babe.",
    "She decided to hail at jacket weather. Stay safe babe. She's intense right now girl.",
    "Hail at jacket temp. Oh shit. Be careful girl. She's not being gentle about it babe.",
  ],
  TemperatureTier.flannelWeather: [
    "Hailing at flannel weather. Be careful out there babe. She's going hard right now.",
    "She's hailing at mild temps. Girl watch out. She's intense today babe.",
    "Hail at flannel weather. Oh shit. Stay safe girl. She's not playing around.",
    "She decided to hail at mild temps. Be careful babe. She's being a lot right now.",
    "Holy shit. Hailing at flannel weather. Stay inside girl. She's really going for it babe.",
    "She's dropping hail at mild temps. Watch out babe. She's serious today girl.",
    "Hail at flannel weather. Stay safe girl. She's going off right now babe.",
    "She brought hail to a mild day. Be careful out there babe. She's intense.",
    "Hailing at this temp. Watch out girl. She's really not holding back today babe.",
    "She's hailing at flannel weather. Girl be careful. She's not messing around babe.",
  ],
  TemperatureTier.shortsWeather: [
    "Hailing in shorts weather. Oh shit be careful girl. She's being wild right now babe.",
    "She's dropping hail in warm weather. Watch out babe. She's intense today.",
    "Hail at shorts weather. Stay safe girl. She's going hard and it's warm. Be careful babe.",
    "She's hailing in the warmth. Girl watch out. She's really going for it babe.",
    "Hail in shorts weather. Get inside girl. She's not playing around right now babe.",
    "She sent hail in shorts weather. Be careful babe. She's being serious out there.",
    "Hail at this temp. Oh shit girl. Stay safe. She's intense in the warm air babe.",
    "She's hailing in warm weather. Be so careful girl. She's not holding back babe.",
    "Hailing in warm weather. Stay inside girl. She's going off right now babe.",
    "She brought hail to shorts weather. Watch out babe. She's not messing around girl.",
  ],
  TemperatureTier.scorcher: [
    "Hailing in a scorcher. Oh shit be careful girl. She's intense in this heat babe.",
    "Hail in a scorcher. Girl stay safe. She's going hard in the heat. Be careful babe.",
    "She's dropping hail in extreme heat. Watch out babe. She's not playing around.",
    "Hailing at scorcher temps. Stay safe girl. She's really going for it out there babe.",
    "She's hailing in a heat wave. Be careful girl. She's serious right now babe.",
    "Hail in this heat. Girl be careful. She's not holding back. Stay inside babe.",
    "She's hailing in the scorching heat. Stay safe babe. She's going hard right now girl.",
    "Hail at scorcher temp. Oh shit. Watch out girl. She's intense as fuck right now babe.",
  ],
};

const hailExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She's hailing in single digits at night. Be so careful babe. She's intense right now.",
    "Night hail in the cold. Oh shit girl. Stay inside. She's really going for it babe.",
    "Hailing in single digits at night. Stay safe girl. She's not holding back tonight.",
    "She's dropping ice in the cold dark. Watch out babe. She's being serious.",
    "Single digit hail at night. Girl stay inside. She's going hard right now babe.",
    "She's hailing in the freezing dark. Be careful babe. She's intense tonight.",
    "Night hail in single digits. Oh girl. Stay safe. She's really not playing right now babe.",
    "Hailing in the cold dark. Stay inside girl. She's going off tonight babe.",
    "She's hailing at night in single digits. Be so careful girl. She's serious right now.",
    "Single digit night hail. Stay safe babe. She's being really intense out there girl.",
    "Night hail in the cold. Girl be careful. She's not messing around tonight babe.",
    "She's dropping ice in the freezing dark. Stay inside babe. She's going hard girl.",
  ],
  TemperatureTier.freezing: [
    "Hailing below freezing at night. Girl stay safe. She's really going hard right now babe.",
    "Night hail below freezing. Be careful out there girl. She's intense tonight babe.",
    "She's dropping ice below freezing in the dark. Watch out babe. She's serious.",
    "Freezing night hail. Oh shit. Stay inside girl. She's not holding back tonight babe.",
    "She's hailing below freezing at night. Be so careful babe. She's going off right now.",
    "Night hail below freezing. Stay safe girl. She's being intense as fuck right now babe.",
    "Below freezing and hailing at night. Girl be careful. She's really not playing tonight babe.",
    "She's going hard with the hail below freezing. Stay safe inside girl. She's serious babe.",
    "Freezing night hail. Watch out babe. She's being a lot right now girl.",
    "She's hailing in the freezing dark. Oh girl be careful. Stay inside babe.",
  ],
  TemperatureTier.jacketWeather: [
    "Hailing at jacket temp at night. Be careful girl. She's going hard right now babe.",
    "Night hail at jacket weather. Stay safe babe. She's intense out there girl.",
    "She's dropping hail at jacket temp tonight. Watch out girl. She's not playing babe.",
    "Hailing at night at jacket temp. Oh shit. Be careful babe. She's going off girl.",
    "She's hailing at jacket weather at night. Stay safe girl. She's being serious babe.",
    "Night hail at this temp. Be so careful babe. She's really going for it girl.",
    "She's dropping ice at jacket temp tonight. Girl watch out. She's intense right now babe.",
    "Hailing at night at this temp. Stay inside babe. She's not messing around girl.",
    "Night hail at jacket weather. Oh girl be careful. She's going hard right now babe.",
    "She's hailing at jacket temp in the dark. Watch out girl. She's serious tonight babe.",
    "Hailing at night at jacket temp. Stay safe inside girl. She's really not holding back babe.",
    "Night hail at this temp. Be careful out there babe. She's intense tonight girl.",
  ],
  TemperatureTier.flannelWeather: [
    "Hailing at flannel weather at night. Be careful girl. She's going hard right now babe.",
    "Night hail at mild temps. Oh shit. Stay safe babe. She's intense out there girl.",
    "She's hailing at flannel temps tonight. Watch out girl. She's not playing around babe.",
    "Hailing on a mild night. Be so careful babe. She's being serious right now girl.",
    "Holy shit. Hail at flannel temp at night. Stay safe girl. She's going off babe.",
    "Night hail at mild temps. Be careful out there babe. She's really going for it girl.",
    "She's dropping hail at flannel weather tonight. Watch out girl. She's intense babe.",
    "Hailing at mild temps at night. Girl be careful. She's not holding back tonight babe.",
    "Night hail at flannel temp. Stay safe babe. She's being a lot right now girl.",
    "She's hailing at nice temps tonight. Be careful girl. She's serious out there babe.",
    "Hailing on a mild night. Oh girl watch out. She's going hard right now babe.",
    "Night hail at this temp. Stay safe inside girl. She's really not messing around babe.",
  ],
  TemperatureTier.shortsWeather: [
    "Hailing in warm weather at night. Girl be careful. She's going hard right now babe.",
    "Night hail in shorts weather. Oh shit. Stay safe girl. She's intense babe.",
    "She's dropping hail in warm weather tonight. Watch out babe. She's not playing girl.",
    "Hailing at shorts temp at night. Be careful babe. She's really going for it girl.",
    "Night hail in the warmth. Stay safe girl. She's being serious right now babe.",
    "She's hailing in shorts weather at night. Be so careful girl. She's going off babe.",
    "Holy shit. Hail at warm temps at night. Stay inside babe. She's intense right now girl.",
    "Night hail in shorts weather. Girl watch out. She's not holding back tonight babe.",
    "She's dropping ice in warm weather at night. Be careful babe. She's serious girl.",
    "Hailing at night in shorts weather. Stay safe girl. She's going hard out there babe.",
    "Night hail in the warmth. Oh girl. Stay inside. She's really not messing around babe.",
    "She's hailing in shorts weather at night. Watch out girl. She's intense tonight babe.",
  ],
  TemperatureTier.scorcher: [
    "Hailing in a scorcher at night. Girl be careful. She's going hard in this heat babe.",
    "Night hail in extreme heat. Oh shit. Stay safe girl. She's intense right now babe.",
    "She's dropping hail in scorching heat tonight. Watch out babe. She's serious girl.",
    "Hailing at night in a scorcher. Be so careful girl. She's not playing around babe.",
    "Night hail in the heat. Stay safe babe. She's really going for it out there girl.",
    "She's hailing in a scorcher at night. Be careful girl. She's going off right now babe.",
    "Hailing in extreme heat at night. Girl watch out. She's intense tonight babe.",
    "Night hail in the scorching heat. Stay inside girl. She's being serious right now babe.",
    "She's dropping ice in a heat wave tonight. Oh shit be careful babe. She's not holding back girl.",
    "Hailing at night in scorching temps. Stay safe babe. She's really going hard girl.",
    "Night hail in a scorcher. Be careful girl. She's intense as fuck right now babe.",
    "She's hailing in extreme heat at night. Watch out girl. Stay safe inside babe.",
  ],
};
