import '../../../../features/weather/domain/entities/temperature_tier.dart';

const hailExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Pelting your car like it owes her money. Hood is fucked. Stay in girl.',
    'Not the sky doing property damage in single digit cold. Stay the hell inside girl.',
    'Uma Thurman in Kill Bill vibes. Cold violent as fuck. Stay in girl.',
    "Denting hoods like it's her damn job. Employee of the month energy af girl.",
    'Sidney Prescott in Scream energy. Destroying everything. Stay inside babe.',
    'Not doing weather. Doing assault. Stay inside honestly.',
    "Hail in single digits. She's filing insurance claims from the sky. Proactive queen babe.",
    'She just dented my car and my spirit in the same minute. Efficient girl.',
    "Hail at this temp. She's so angry the anger is frozen. Literally. Stay inside girl.",
    "She brought ice rocks to single digits. Like girl the cold was already winning. You're overkill babe.",
  ],
  TemperatureTier.freezing: [
    "Throwing ice below freezing because the cold wasn't violent enough. Stay the hell in babe.",
    'Not her adding projectiles to freezing temps. Zero fucking chill literally.',
    'Pelting everything below freezing like she gets paid per dent. Fucking relentless.',
    'Hereditary vibes. Violent as fuck. She snapped. Stay the hell inside girl.',
    'She upgraded her attack to include projectiles. Patch notes from hell girl.',
    'Holy shit. Sky launching golf balls at freezing temps. Your car did nothing wrong babe.',
    'Ice chunks from the sky. Your windshield sends its damn regards af girl.',
    'She watched I Tonya and took notes. Ice and violence. She planned the whole thing babe.',
    "She said the cold wasn't enough let me add ammunition. Stay inside babe.",
    "Chucking ice at your car like she's keying an ex's damn truck. Stay inside girl.",
  ],
  TemperatureTier.jacketWeather: [
    "She's the friend who starts drama at brunch. Now with ice. Stay the fuck in girl.",
    'Everything Everywhere All at Once energy. Ice in every timeline. Stay inside af babe.',
    'Holy shit. Your car was minding its damn business. She chose violence.',
    'Sky decided jacket weather needed a plot twist. Ice everywhere babe.',
    'She brought weapons to a casual hangout. Read the room girl.',
    'Hail at jacket weather. She interrupted a normal day to commit property damage. On brand babe.',
    "She just bounced ice off my windshield like she's playing percussion. I did not buy tickets girl.",
    'Hailing at this temp. My car looks like a golf ball now. Aerodynamic. Thanks I guess babe.',
    'She looked at a fine day and said let me add some violence. Interior decorator from hell girl.',
    'Hail at jacket weather. The ice is melting on my hood and leaving dents as souvenirs. Thoughtful babe.',
  ],
  TemperatureTier.flannelWeather: [
    'Crashed a nice day to destroy your car. Stay the hell inside babe.',
    'Pelting everything at a temp that did not deserve this. Rude as shit girl.',
    "Sky is throwing ice in nice weather because she's petty as hell babe.",
    'Looked at mild temps and said you know what this needs? Ice. Bold as shit.',
    'Holy shit. Your car is getting dented in mild weather. The audacity. Stay inside babe.',
    'She sabotaged her own best day with frozen projectiles. Self destructive icon af girl.',
    'Alanis Morissette wrote Ironic for this. Figures honestly bitch.',
    'Single White Female energy. Everything was fine then she snapped. Stay inside babe.',
    'Amy Dunne in Gone Girl vibes. Mild day ruined. Ice everywhere. Stay inside babe.',
    'Hole wrote Celebrity Skin for this. Loud aggressive. Wrecked the whole damn place girl.',
  ],
  TemperatureTier.shortsWeather: [
    'Launching ice at people in shorts. The visual alone is wild as hell. Get inside girl.',
    'Not the sky pelting frozen shit at 80 degrees. Most chaotic option girl.',
    'Speedrunning property destruction in warm weather. Stay the hell inside babe.',
    "She really fucking said you thought you were safe. You're not girl.",
    'Bikini Kill wrote Rebel Girl for this energy. Chose ice chose violence. Stay in girl.',
    'She sent hail in shorts weather. The sky is throwing ice at people in tank tops babe.',
    "Hail at shorts weather. She's denting cars while people are in flip flops. The range girl.",
    "She just bounced ice off someone's sunglasses. In summer. The disrespect is immaculate babe.",
    "Hailing in warm weather. My iced coffee just got more ice. Didn't order that. Stay inside girl.",
    "She sent frozen projectiles to a barbecue. Nobody RSVP'd for this. Stay inside babe.",
  ],
  TemperatureTier.scorcher: [
    'Pelting your car with ice in extreme heat. Fucking terrifying range girl.',
    'Hail in a scorcher. The sky is throwing ice cubes at people who are already on fire. Pick a lane girl.',
    'Charlize Theron in Atomic Blonde vibes. Brutal as fuck. Stay inside babe.',
    'Throwing ice at 90 degrees. Answers to no fucking one babe.',
    'Sky is fighting itself. Property is collateral damage af babe.',
    "She's throwing ice in a heat wave like a goddamn paradox. Stay inside girl. She's not fucking around.",
    'Missy Elliott wrote Get Ur Freak On for this. Hot violent. She runs this babe.',
    'She combined every extreme at once. Chaotic final boss energy babe.',
  ],
};

const hailExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She's pelting everything in sight. This is fucking assault girl.",
    "She's the sleepover from hell. Here to egg your house with rocks babe. Go home.",
    "Your car's insurance premium just went up. Thanks bitch.",
    'The roof sounds like a popcorn machine from hell girl.',
    "Every piece sounds like a tiny skull hitting the roof. She's keeping score girl.",
    "She put the blindfold on us and said bitch you're a piñata. Ma'am we are not.",
    "She's fucking pelting the neighborhood like she's got a list and every damn person's on it girl.",
    "She's fucking throwing ice at your car like it slept with her boyfriend girl.",
    'She turned off the lights skipped snowballs and went straight to rocks babe.',
    "She said snowflakes are for pussies. Here's some rocks babe.",
    'Your car just filed a restraining order against the sky babe.',
    'She brought a bag of ice and a damn grudge girl.',
  ],
  TemperatureTier.freezing: [
    'Fuck your paint job. Fuck your windshield. She said what she said babe.',
    'Tap dancing in cleats on the roof. Sit down girl.',
    'Beating up your car. Can you do anything about it? No babe.',
    'Looked at snow and said nah. Threw hands instead girl.',
    'Accuracy of a pitcher. Temper of a toddler. Both at once babe.',
    'Committing felonies with frozen water. Iconic honestly girl.',
    'Frozen tantrums bouncing twice. Double damage girl.',
    "That sound? That's every life choice being questioned babe.",
    "She's not sharing the ice she's throwing it. Noted girl.",
    'Vandalizing the neighborhood. No fingerprints. Smart babe.',
  ],
  TemperatureTier.jacketWeather: [
    "She didn't need it to be freezing to start throwing shit babe.",
    'She escalated from rain to assault for absolutely no fucking reason babe.',
    'She waited until no one could see her to start some shit babe.',
    'She waited until everyone was asleep to start vandalizing. Sneaky bitch.',
    "The windshield is praying. The roof is crying. She doesn't give a shit girl.",
    "She's lobbing ice at jacket weather temps. The cold wasn't enough she needed weapons girl.",
    "She's fucking pelting the car like it forgot their anniversary girl.",
    'She pulled up with no headlights and started swinging babe.',
    "Lights off hoods up throwing ice. She's a whole criminal enterprise babe.",
    'She aimed for the windshield first. Then the hood. Then my will to live girl.',
    "She's out there doing batting practice on every car on the street babe.",
    "She's throwing ice at every car on the block like she's working down a list girl.",
  ],
  TemperatureTier.flannelWeather: [
    "The temp didn't deserve this. The cars didn't deserve this. She doesn't give a fuck girl.",
    "It's mild out and she's still launching shit from the sky. Spiteful girl.",
    "She ruined a perfect night with frozen violence. Could've been beautiful but fucking no babe.",
    'She saw a calm mild night and said absolutely the fuck not babe.',
    'Holy shit. She brought hail to a hoodie night. Read the room babe.',
    "The roof sounds like a drum solo nobody requested. She's going off girl.",
    "She's out here denting hoods at flannel temps. The fucking audacity is unmatched girl.",
    'She looked at a perfectly mild night and said you know what this needs? Projectiles bitch.',
    "The temp is fine and she's still throwing ice. She does this for sport babe.",
    "She's hailing at nice temps because she doesn't believe in proportional responses babe.",
    "She's pelting us with ice on a mild night. The pettiness is award-winning babe.",
    'She sabotaged her own best work with ice chunks. Self-destructive legend girl.',
  ],
  TemperatureTier.shortsWeather: [
    "She's throwing frozen shit in warm air. The math isn't mathing girl.",
    "She's throwing frozen shit at us in tank top weather. Psychopath behavior.",
    'She said fuck your plans. Stay in babe.',
    "She's pelting the shit out of everything for absolutely no fucking reason.",
    "She's chucking ice in tank top weather. My skin doesn't know what to do babe.",
    'Wrong fucking season girl.',
    'Holy shit. The ice is melting on contact but she keeps throwing it anyway babe.',
    'She brought winter ammo to a summer night. Girl what?. What the hell.',
    'She really showed up to a pool party with a bag of rocks.',
    "She's the drunk friend throwing ice cubes at the party. Babe cut her off.",
    "She's so confused and so damn violent about it babe.",
    "She's throwing hands and ice at the same damn time babe.",
  ],
  TemperatureTier.scorcher: [
    "She's throwing ice in a sauna. Make it make fucking sense babe.",
    'She said fuck your car fuck your roof fuck physics babe.',
    "She's the most confused and most violent version of herself tonight. Unhinged as fuck girl.",
    'Hot hail. The ice is sweating on the way down. It arrives lukewarm and aggressive babe.',
    "She's throwing frozen shit in hell. That takes talent babe.",
    "She's fucking rage quitting reality and taking your damn paint job with her babe.",
    "She's fucking assaulting us with ice that has no right to exist right now girl.",
    "She's pelting us with ice that evaporates on contact. Commitment to chaos girl.",
    'She brought winter weapons to a heat wave. Unhinged babe.',
    "She's hailing in a scorcher. The ice is sizzling on the pavement like a griddle girl.",
    "She's pelting us with ice that has no business existing in this heat babe.",
    'Your car is getting dented by impossible ice. File that damn claim girl.',
  ],
};
