import '../../../../features/weather/domain/entities/temperature_tier.dart';

const heavyRainExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She's going OFF in single digits. Pouring like she's performing for a sold-out crowd. Incredible from inside babe.",
    "Single digit downpour. She's giving everything she's got and it's honestly breathtaking. Stay warm inside girl.",
    "Pouring in single digits. She's putting on a whole show out there. Watch from the window babe.",
    "She's dumping in the cold and the sound alone is cinematic as fuck. Blanket and listen girl.",
    "Heavy rain in single digits. She's fully committed to this performance. Stay inside and witness her babe.",
    "Single digits and she's POURING. The intensity is stunning honestly. Coat stays on inside too girl.",
    "Torrential in the cold. She's going so hard it's actually impressive. Stay warm and watch babe.",
    "She's absolutely dumping in single digits. The volume is incredible. Stay inside and enjoy the show girl.",
    "Cold heavy rain. She's delivering a full goddamn symphony out there. Bundle up and listen babe.",
    "Single digit downpour. She decided to go full cinematic and honestly she ate. Stay cozy inside girl.",
    "Pouring in single digits. She's giving main stage headliner energy. Watch from somewhere warm babe.",
    "She's dumping cold rain like she rehearsed this. The commitment is stunning. Stay inside girl.",
  ],
  TemperatureTier.freezing: [
    "Freezing and POURING. She's putting on a goddamn show. The sound is unreal. Stay warm inside babe.",
    "Below freezing and she opened the sky. The volume is incredible. Watch from inside girl.",
    "Cold and dumping. She's giving full theatrical performance out there. Impressive as fuck honestly babe.",
    "Freezing downpour. She's going so hard it's actually beautiful to watch from in here girl.",
    "She's pouring below freezing. The intensity is breathtaking. Blanket on and listen babe.",
    "Cold and torrential. She really said I'm going to give you a SHOW tonight. She delivered girl.",
    "Freezing and dumping. The rain sounds like applause. She earned it honestly babe.",
    "Below freezing heavy rain. She's performing like nobody's watching but we absolutely are. Stay inside girl.",
    "Cold and she's absolutely dumping. The commitment to this level of intensity? Respect. Stay warm babe.",
    "Freezing downpour. She cranked it all the way up and it sounds incredible from inside girl.",
    "She's going full downpour below freezing. Cinematic as hell. Bundle up and enjoy the sound babe.",
    "Cold heavy rain. She's not holding back even a little. The energy is immense. Stay cozy girl.",
  ],
  TemperatureTier.jacketWeather: [
    "Cool and POURING. She's giving main event energy. Loud dramatic committed. Jacket on and watch babe.",
    "She's dumping at jacket temp. The volume is unreal. She really said full performance today girl.",
    "Cold and pouring. She's going so hard it's honestly cinematic. Umbrella is useless babe.",
    "Cool and she chose maximum drama today. Pouring with full commitment. Respect honestly girl.",
    "Chilly and she skipped gentle entirely. Full downpour. The intensity is incredible babe.",
    "Cold and fucking dumping. She went from nothing to everything in ten minutes. What a performer girl.",
    "Cold and pouring. The sound on the roof alone is worth staying inside for. She's going OFF babe.",
    "Cool and she's delivering a full torrential performance. Every drop is giving effort girl.",
    "Cool and dumping. She turned the whole day cinematic. Jacket on if you go out babe.",
    "Cool and she escalated straight to monsoon. The commitment is honestly impressive girl.",
    "Cold and pouring. She brought the entire sky and she's not apologizing for the volume babe.",
    "Heavy cold rain. Loud as fuck and committed. She's got something to say and she's saying it LOUD girl.",
    "Cool and pouring. She said subtlety is dead and she's the one who killed it babe.",
    "Cold and pouring. She's excessive and dramatic and honestly kind of beautiful girl.",
    "Cold and fucking dumping. She decided today was the day for a full production. No intermission babe.",
    "Cold and dumping. The streets are rivers already. She works fast girl.",
    "She's giving full dramatic downpour in the cold. Drenched cinematic energy. Jacket on if you dare babe.",
    "Chilly and she went straight to torrential. She doesn't do half measures girl.",
    "Cool and she chose the most dramatic option on the menu. Pouring with her whole chest babe.",
  ],
  TemperatureTier.flannelWeather: [
    'Mild and absolutely drenched and somehow in a good fucking mood. The math isn\'t mathing girl.',
    'Mild and pouring. She ruined my whole damn outfit and perfected the vibe simultaneously. Partial credit bitch.',
    "Soaked head to toe but the temp is mild as fuck. Feels like a hug? I'm so confused honestly.",
    'The rain said fuck you and the temp said I love you. Mixed signals babe.',
    "Mild and torrential. This is objectively terrible and subjectively fucking great. I hate her and I don't babe.",
    "Mild and dumping. Every piece of clothing is fucked but she's honestly still perfect. We forgive you girl.",
    'She wrecked the day with a downpour but kept the temp perfect. Like keying your shit then leaving flowers girl.',
  ],
  TemperatureTier.shortsWeather: [
    "Warm rain absolutely dumping on us and honestly? Main character energy. We're the extras girl.",
    "It's warm and dumping sideways and this is hot girl shit. Go dance in it babe. I'm serious.",
    "It's warm as hell and pouring buckets. Get your ass outside and stand in it like the unhinged person you are babe.",
    "She's dumping warm rain like she's got something to prove and honestly? Best decision she's ever made girl.",
    'Warm and pouring. She said fuck your hair fuck your plans fuck your shoes. Go stand in her girl.',
    "She said I'm going to dump warm rain on you and you're going to like it. She was right babe.",
    "She snapped. Warm rain just dumping everywhere. Get outside and get soaked babe it's everything.",
    "She's absolutely dumping rain and losing her mind and I've never loved her more honestly.",
    "I'm standing in warm pouring rain screaming and my neighbors are watching. She made me feral girl.",
    'Warm rain pouring so hard my shoes are aquariums. Little fish could live in there honestly. Go play babe.',
    "She dumped the whole sky on us and I'm soaked head to toe grinning like an idiot babe.",
  ],
  TemperatureTier.scorcher: [
    "She saw the scorching heat and said I'll fucking handle this. And she did. Go girl.",
    'Hot as fuck and dumping. She combined hell and a waterpark and somehow it works. Chaos queen.',
    'Hot and pouring. Sky had a complete psychotic break and honestly thank fuck she did.',
    "Hot as fuck and absolutely dumping rain. She really said I'm going to fix this with maximum violence.",
    'Hot and pouring. She really chose the most unhinged solution possible and fucking committed. Good for her honestly.',
    "Hot rain dumping on the pavement. Like girl the ground didn't do anything to you relax.",
    "Hot and dumping. Humidity is criminal but she's doing us a solid babe.",
    'Hot rain out here absolutely annihilating the sun. Aggressive but honestly she had it coming girl.',
    'The sun started it and the rain is finishing it. Messy break up energy vibes girl.',
    "She's performing an exorcism on the heat with torrential rain. Violent. Effective. Unhinged babe.",
  ],
};

const heavyRainExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She's DUMPING in single digits at night. The sound is unbelievable. Stay warm and listen babe.",
    "Single digit downpour in the dark. She's delivering a full performance. Breathtaking from inside girl.",
    "She's pouring so hard in the cold dark. The intensity is stunning. Blanket and window open babe.",
    "Night downpour in single digits. The volume alone is cinematic. Stay cozy and witness this girl.",
    "She's going full torrential in the freezing dark. Incredible honestly. Stay inside and enjoy babe.",
    "Cold night heavy rain. She's performing like her life depends on it. The sound is everything girl.",
    "The rain sounds like a standing ovation in the cold dark. She earned it. Bundle up inside babe.",
    "She's absolutely pouring in single digits at night. The commitment is breathtaking. Stay warm girl.",
    "Single digit night rain. She's giving everything. The roof sounds alive. Stay cozy babe.",
    "She's dumping in the cold dark like this is her magnum opus. It might be honestly girl.",
    "Night downpour in single digits. She's going so hard it's actually beautiful to hear. Stay inside babe.",
    "Cold dark heavy rain. She said tonight is the night for a full show. She was right girl.",
  ],
  TemperatureTier.freezing: [
    "Freezing and pouring at night. She's giving a full cinematic performance in the dark babe.",
    "Streets are rivers. She turned the whole block into a scene from a film. Stay warm girl.",
    "She's dumping below freezing at night. The sound on the roof is incredible. Stay cozy babe.",
    "Can't hear yourself think? She's that loud. Honestly impressive. Bundle up inside girl.",
    "Freezing night downpour. She's performing with her whole chest. Watch from the window babe.",
    "Hammering the roof below freezing. The intensity is unreal tonight. Stay warm and listen girl.",
    "She's pouring her heart out in the freezing dark. The volume is beautiful honestly babe.",
    "Below freezing and torrential at night. She escalated to full show mode. Stunning from inside girl.",
    "Windows vibrating from the rain below freezing. She's got something to say and she's saying it LOUD babe.",
  ],
  TemperatureTier.jacketWeather: [
    "She's going absolutely feral out there. The sound is unreal. Jacket on and watch girl.",
    "She went from nothing to full downpour in minutes. The commitment is incredible babe.",
    "She's performing at full volume tonight. The rain on the roof is cinematic as fuck girl.",
    "She said subtle? Doesn't know her. Full torrential tonight babe.",
    "She's not holding back even slightly. The intensity is stunning. Stay dry girl.",
    "She's fucking monsooning at jacket temp. The sound alone is a whole experience babe.",
    "She's giving full dramatic downpour tonight. Every drop sounds intentional. Committed queen girl.",
    "She's performing for an audience of nobody and going this fucking hard. Dedication honestly babe.",
    "She's pouring with her whole chest tonight. The volume is impressive as hell girl.",
    "She decided tonight was for maximum drama. Cold rain dumping. She's delivering babe.",
    "She's going full torrential on the streets. The gutters can barely keep up girl.",
    "She's hammering the roof so hard it's almost musical. Full percussion section out there babe.",
    "She's rinsing the whole city and honestly it sounds amazing from inside girl.",
    "The gutters are overflowing. She's pouring that hard. Impressive honestly babe.",
    "She's dumping so hard the umbrella concept is irrelevant. Full commitment girl.",
    "She's raining so hard my umbrella would be decorative at best. Stay inside babe.",
    "She's pouring like she's been saving up all week. Tonight she goes OFF girl.",
    "She came for the streets the roofs and our evening plans. Worth watching though babe.",
    "She said I have feelings and they're LOUD. The volume is honestly beautiful girl.",
    "She's so loud the whole neighborhood is just listening. Collective audience moment babe.",
  ],
  TemperatureTier.flannelWeather: [
    'Best fucking sleep of your life if you can get past the noise girl.',
    "She's pressure washing the shit out of the streets. Free car wash I guess?",
    "Crack the window. Let her scream. It's actually soothing af babe.",
    "She's having a breakdown at the perfect temperature. Relatable as fuck girl.",
    "She's throwing a tantrum and somehow it's the coziest shit ever girl.",
    "She's absolutely losing her shit at the most comfortable temp possible babe.",
    'She brought the fucking noise. Stay dry and listen babe.',
    'She went nuclear but the temp stayed chill. One of them has fucking manners babe.',
    "You will be soaked in four seconds flat. That's not a warning that's a promise girl.",
    "She's going so hard the windows are vibrating. Free massage from the house girl.",
    "She's the drama outside the window. We're the audience in bed girl.",
    'She built a river in the street in twenty minutes. No permits no planning. Just chaos bitch.',
    "If you get your ass out there you're coming back looking like a wet dog. A cute wet dog but still babe.",
    "She's fucking doing too damn much and somehow it's exactly enough girl.",
    "She's dumping biblical amounts of water at the coziest temp possible. Pick a lane babe.",
    'If you have to go outside bring a kayak and a prayer babe.',
    "She's feral but the temp said I got you. Stay in bed babe.",
    "If you're going out there you better have gills or a death wish babe.",
    "Crack the window and let the chaos in. It's kind of beautiful girl.",
    'The roof is earning its rent tonight. Every shingle is clocking overtime babe.',
  ],
  TemperatureTier.shortsWeather: [
    'Run through it. Be that fucking girl.',
    "She said let me ruin your hair and your plans and your shoes. You're fucking welcome.",
    "You'll look like a drowned rat in seconds but a hot one. Fucking worth it.",
    "She's dumping warm water on us like we're in a car wash without the car babe.",
    'She said fuck your blowout fuck your outfit fuck your plans. Have a nice night girl.',
    "She's absolutely losing her shit but it's warm enough to enjoy the show babe.",
    "She's pouring so hard you can't tell what's rain and what's just the sky giving up babe.",
    "She turned the streets into rivers and honestly it's hot as fuck girl.",
    "She's messy beautiful and not fucking stopping. Queen shit babe.",
    'Holy shit. The puddles are waiting. Embrace your inner child babe.',
    "She's fucking throwing hands and bathwater at the same damn time babe.",
    "She's so heavy the streetlights look like they're underwater. City aquarium girl.",
    'Go stand in it like the feral human she knows you are bitch.',
    "She's baptizing the whole neighborhood. Nobody signed up girl. What the hell.",
    "She's feral but it's warm enough that getting soaked is kind of a vibe babe.",
    'She soaked me in three steps. Three. I counted while drowning girl.',
    "She's out here trauma dumping on us but you know what we got you babe.",
    "If you go out there looking cute you're coming back looking feral. That's a guarantee girl.",
    "She's chaotic but the kind you'd actually follow outside. In rain boots obviously.",
    "She said gentle? I don't know her. Full send babe.",
  ],
  TemperatureTier.scorcher: [
    "She's boiling us alive and drowning us at the same time. Pick a fucking lane babe.",
    'You thought the rain would cool it down. She said absolutely the fuck not girl.',
    "Walking outside is like stepping into someone's mouth. Hard fucking pass babe.",
    'The rain is warm. The air is warm. Everything is warm and wet and wrong girl.',
    'She really fucking said why pick one way to make you miserable when I can do both girl.',
    'You will sweat AND drown simultaneously. Multitasking queen.',
    'The humidity just bred with the rain and made a third thing. Wet air had a baby bitch.',
    "The steam is rising off the pavement like she's summoning demons babe. What the hell.",
    "She's raining hot on us like she's trying to cook a city. Slow roast via sky babe.",
    "You're not getting wet you're getting marinated girl.",
    "She's power washing us with warm spit at this point girl.",
    "Outside smells like a wet dog's fever dream. She created a biome in here girl.",
  ],
};
