import '../../../../features/weather/domain/entities/temperature_tier.dart';

const mostlySunnyExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'She brought the vibes and left the warmth in the fucking car. Classic her honestly. Heaviest coat babe.',
    "Cold as fuck and she's still out here fighting clouds. Girl the cold is the problem not them.",
    "Mostly sunny and cold as fuck. She's just up there smiling while we suffer. Girl read the room.",
    "She pushed through clouds and said ta da. Ta da what bitch. It's seven degrees.",
    "It's giving White Lotus. Gorgeous setting everything's wrong. Heaviest coat girl.",
    "Sun shoved clouds out the way like I got this. Girl you do not got this. It's single digits.",
    'Sun peeked past clouds like surprise. Girl the surprise is hypothermia. Bundle the fuck up babe.',
  ],
  TemperatureTier.freezing: [
    'Mostly sunny below freezing. She fought through clouds in the cold FOR US. The effort alone. Coat on babe.',
    'Cold as fuck but she shoved those clouds aside like a goddamn hero. Appreciate her. Bundle up girl.',
    "Below freezing but mostly sunny. She battled clouds in this cold and won. That's dedication bitch.",
    "Mostly sunny and freezing. She could've stayed behind the clouds but she didn't. She came through. Coat on girl.",
    'Cold as shit but she cleared the sky anyway. Above and beyond honestly. Layer up babe.',
    'Mostly sunny below freezing. At least she tried to make it pretty. And she fucking succeeded. Coat on bitch.',
    "Mostly sunny cold as fuck. She pushed through the clouds in freezing temps. That's harder than it looks. Bundle up girl.",
    'Below freezing but she cleared the sky for us. Free light therapy in the cold. Take what you can get babe.',
    'Mostly sunny and freezing. The fact that she showed up at ALL in this cold is iconic. Coat on girl.',
    'Cold as fuck but she fought for that sunshine. Nobody asked her to. She just did. Respect. Bundle up babe.',
    "Mostly sunny below freezing. She didn't let the cold stop her. Neither should you. Heaviest coat and go girl.",
    'Below freezing and she still elbowed clouds out the way for us. Warrior shit honestly. Coat on girl.',
    'Mostly sunny and cold as fuck. At least the sky is open and gorgeous. Beats gray every damn time babe.',
  ],
  TemperatureTier.jacketWeather: [
    "Mostly sunny and cool. Clouds are actually cute as fuck. She's accessorizing girl.",
    "Nippy but she's fucking stunning. Layer up and go stare at her babe. With sunnies obv.",
    "Mostly sunny and cool and I'm already outside. Didn't think about it. Just went bitch.",
    'Mostly sunny and a little chilly. She finally learned the word moderation. Somebody get this bitch a trophy.',
    "Not her serving a normal nice day like it's a flex. It is though. It absolutely fucking is.",
    "She's mostly sunny and cool and I just curtsied at the fucking sky. In jeans. In public girl.",
    'Mostly sunny and cool. Jacket on sunnies on get the fuck out there babe.',
    "Cool and mostly sunny. She's not perfect but she's trying and I fucking respect that. Go girl.",
    'Mostly sunny and chilly. She finally did something right. Jacket on go enjoy it before she fucks it up babe.',
    "Cool and mostly sunny. Get outside now. She won't be this chill for long bitch.",
  ],
  TemperatureTier.flannelWeather: [
    'She showed up mild and mostly sunny and my jaw hit the floor. Like where have you been babe.',
    'She really said hold my drink and delivered the best fucking day this month. Get out there babe.',
    "She didn't just clear the clouds she put them in a little pile in the corner. Tidy queen. Go your ass outside girl.",
    'Mostly sunny perfection. Shut the fuck up and go outside. Talking to myself babe.',
    "Mostly sunny and mild. She's fucking peaking and she wants witnesses. Go be one girl.",
    "She's showing off and she deserves it today. Get the fuck outside girl.",
    "It's giving hoodie and sunnies and zero responsibilities. She planned this babe.",
    "She cooked today and didn't burn a single fucking thing. Proud of you girl.",
    'She showed up mild and mostly sunny and I have zero fucking notes. Hate that for me honestly.',
    "Mostly sunny and mild. Get outside. Don't bring your phone. Be feral. Be free babe.",
    "She cleared the clouds served the vibes and didn't ask for applause. Standing ovation anyway bitch.",
    'Mostly sunny flannel weather. Hoodie on sunnies on get the fuck out there babe.',
    'Mild and mostly sunny. Flannel. Coffee. Outside. The whole damn plan babe.',
  ],
  TemperatureTier.shortsWeather: [
    'Clouds trying to gatekeep shorts weather. Sun said absolutely tf not. Sunnies on babe.',
    "Mostly sunny and warm and oh my fucking god. That's the whole forecast babe.",
    "She's so nice right now it should be illegal. Arrest her. After I go outside girl.",
    "It's so fucking nice out I forgot my name. Shorts on babe.",
    "She's so warm and sunny my seasonal depression packed a bag. Buh bye bitch.",
    'Nice as fuck out. Just threw my jacket in the trash. Shorts on babe.',
    'Mostly sunny shorts weather. She planned it bitch.',
    'Mostly sunny shorts weather. She made the clouds her hype girls. Get out there girl.',
    'Mostly sunny and warm. Tongue out. No thoughts. All joy. Shorts on babe.',
    'Mostly sunny and warm as fuck. Shorts on. Brain off. Outside now girl.',
    'Mostly sunny and warm as fuck. Sunscreen on. Shorts on. Phone off. Bye babe.',
    'She cleared the clouds just for your ass. Shorts on go thank her girl.',
    'Mostly sunny and gorgeous. Shorts. Sunnies. SPF. Go babe.',
    "She's warm and mostly sunny and you have zero excuse. Get the fuck out there girl.",
  ],
  TemperatureTier.scorcher: [
    'Mostly sunny scorcher. She cleared the clouds for a better angle to cook us from. Strategic. Psychotic. SPF babe.',
    'Mostly sunny hot af. She pushed past clouds to personally victimize us. Like okay Regina.',
    "Hot as fuck and mostly sunny. She's up there with a magnifying glass and we're the ants. SPF or perish babe.",
    'Clouds just standing there while she scorches us. Bystanders. Complicit. Useless bitches.',
    "Mostly sunny and scorching. Clouds watching from the side like they're not involved. You are. You're all guilty girl.",
    "She's so hot the clouds left and honestly same. I would also leave. Can't though. Pool now babe.",
    'Hot as fuck and mostly sunny. Nearest pool. Now. This is not a suggestion babe.',
    'Mostly sunny scorcher. I need a pool a drink and for her to calm the fuck down. In that order.',
    'Mostly sunny hot as shit. Googling nearest pool like my life depends on it. It does babe.',
    'Mostly sunny scorcher. She heard calm down and took it as a fucking dare. Hydrate babe.',
    "Girl relax. We get it. Everyone knows you're hot as fuck.",
    "Hot as shit mostly sunny. My deodorant just texted me saying I'm on my own today. Shade immediately girl.",
    "Mostly sunny hot as fuck. Even my shadow's looking for shade babe. Seek shelter.",
    "She's so fucking hot I'm googling pools near me with my last brain cell girl.",
    'She cleared the clouds and cranked the fucking heat. Double homicide babe.',
    "She's so fucking hot the asphalt is soft. I'm leaving footprints. In the road girl.",
    "She's scorching us through a mostly clear sky and she's not even at full power. That's the scary part babe.",
    'Mostly sunny and hot enough to cook an egg on my dashboard. Tried it. It worked. Send help girl. SOS.',
    "She pushed past clouds in this heat like she's trying to prove a point. Point taken. We're fucking dying babe.",
    "Mostly sunny scorcher. I'm so fucking hot I forgot how to be a person babe.",
    'Holy shit. She fought clouds to bring this heat. Girl we were rooting for the clouds.',
    "She's out here scorching us and the clouds are filming it. Worldstar energy. Find a pool immediately babe.",
    'Mostly sunny scorcher. I just saw a bird panting. A bird. Panting. She broke nature girl.',
    "Hot as fuck and mostly sunny. My sunscreen is sweating off faster than I can apply it. She's winning babe.",
    "Mostly sunny and scorching. She really said I'll leave a few clouds so you can watch me cook you. Front row seats bitch.",
    "She's so hot the ice cream truck played Taps instead of its normal song. Moment of silence. Pool now babe.",
    "Nearest pool. Nearest lake. Nearest garden hose. I'm not picky girl.",
    "She's so hot I'd swim in a puddle right now babe.",
    "Mostly sunny scorcher. I'm so hot I just thanked a cloud for existing. Brief shade. Life saved. For now babe.",
    "She's mostly sunny and scorching and I swear my eyeballs are sweating. Didn't know they could do that girl.",
    "She's so hot my flip flops are melting into the sidewalk. We're one now girl.",
  ],
};

const mostlySunnyExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Clouds keep blocking the stars and it's freezing af. Whole night's a mess girl.",
    'Half the stars showed up and the other half saw the temp and said absolutely not. Smart bitches.',
    "Few stars out looking innocent while it's cold as shit. You're not fooling anyone ladies.",
    "She's trying but it's fucking freezing. Every layer girl.",
    "Some stars some clouds all cold. Can't get her shit together but she's trying babe.",
    "Ma'am this is not a magic show it is single digits.",
    'Stars fighting clouds AND fucking cold tonight. Pick a struggle babe.',
    'She gave us a sky with missing teeth. Cold knocked the rest out I guess girl.',
    "Clouds and stars out having a party, cold decided to crash. You weren't invited girl go home.",
    "She brought some stars like that makes up for single digits. Ma'am that is not enough.",
    'Clouds blocking every good star like a bouncer with a grudge. Single digits and no VIP access babe.',
    "She couldn't even commit to a full sky in single digits. Lazy AND cold. Pick a lane girl.",
  ],
  TemperatureTier.freezing: [
    "Stars that showed up? Brave. Stars that didn't? Smart. Both valid babe.",
    'Half-assed sky. Whole-assed cold. Priorities girl.',
    'She tried tonight. Not hard but she tried babe.',
    'Dollar store sky and below freezing? Come on girl.',
    "She's phoning it in and it's below freezing. Cool cool cool babe.",
    'Most of the stars and all of the suffering. Why is she like this girl.',
    "Sky's buffering. It's freezing. Girl finish loading please babe.",
    "Clouds hogging the sky like they pay rent. They don't. Freeloading bitches.",
    "She's being mid and she knows it. Bundle up girl.",
    "Below freezing and she couldn't even give us a full sky? The audacity babe.",
    'Stars doing community service in freezing temps. Somebody thank them girl.',
    'Almost committed to a full sky. Almost. Story of her life babe.',
  ],
  TemperatureTier.jacketWeather: [
    'Few clouds crashed the star party. Rude but the vibes survived. Jacket on babe.',
    "The clouds aren't ruining shit they're garnish. She plated this night like a damn chef girl.",
    'She showed up and actually delivered tonight. Who is this woman. Jacket on bitch.',
    "Two clouds trying to be relevant on an otherwise perfect night. Nobody's buying it girl.",
    "Clouds trying to hog the stars. Ma'am those aren't yours give them back.",
    "She passed the vibe check tonight. Like shit. Don't let it go to your head girl.",
    'She gave us most of the stars and a cool breeze and honestly I have zero complaints for once babe.',
    "Stars and clouds playing nice tonight. Cool temps. Therapy's working girl.",
    'Clean sky cool air zero complaints. She said less is more and proved it babe.',
    'She rolled out of bed with two clouds in her hair and still looks better than most nights babe.',
    'Cool clear-ish night. The clouds are scenery not a statement. Jacket on go girl.',
    "Jacket on get outside. She gave us most of the sky and perfect temps. Don't fuck this up girl.",
    "Get your ass out there. She's behaving for once and it's gorgeous babe.",
    "Jacket on go. She's almost perfect tonight and that's the best she's ever been babe.",
  ],
  TemperatureTier.flannelWeather: [
    "She's pretty as fuck tonight and being nice about it. What's the catch babe.",
    'Most of the stars and perfect temps. Five stars. No notes.',
    'She gave us this night for free. No strings. Suspicious af but go enjoy it babe.',
    'She set the whole night up and all you have to do is show up. Go outside babe.',
    'Two clouds up there looking embarrassed to exist tonight. As they should babe.',
    'Mild mostly clear. She said watch this. And then she did that. Get the fuck outside girl.',
    "She's peaking tonight babe. Everyone shush. Watch her go.",
    "This temp with this sky. She's flirting with us and it's working girl.",
    "She's so pretty it's honestly annoying. Like girl we get it.",
    "She's not even trying that hard and still outperforming every night this week babe.",
    "She doesn't have to try. She just shows up and the bar moves. Sickening babe.",
    "She said oh this? I just threw it together. Ma'am this took planning we all know it.",
    "Flannel on get outside. She gave us most of the sky and perfect temps. Don't waste this shit girl.",
    "Get your ass out there. She's peaking and she needs an audience babe.",
    "Flannel on go. She's being generous and we're not gonna disrespect that by staying inside girl.",
  ],
  TemperatureTier.shortsWeather: [
    "She's a fucking ten tonight. Okay two clouds. But still a ten babe.",
    'Warm night and most of the stars are out and I just did a full lap around the block in shorts. She made me mobile girl.',
    'Stars out warm as fuck. She just looks like this. No filter no effort. Disgusting girl.',
    'The few clouds up there are window dressing on the best shop in town. Warm night queen babe.',
    "Zero fucking notes. She said perfection isn't hard when you're me. Like okay girl.",
    'Warm night most of the stars. Two clouds up there third-wheeling. Nobody fucking invited you babe.',
    "She's so warm and so pretty I forgot I was looking at my phone. Screen who. Sky won girl.",
    "She just walked in and every other night left. Can't fucking compete babe.",
    "Warm and nice as fuck. Competition's over. She won tonight babe.",
    "She's the hot girl who says she's not even that hot. Fucking stop it girl.",
    "Two clouds trying to start drama tonight. Nobody's fucking listening babe.",
    "Every cloud in the sky just got demoted to scenery. She's running this shit babe.",
    'Stars out clouds quiet temp perfect. She fucking did that girl.',
    'Warm mostly clear night and I just looked up and said oh fuck out loud. In public. No regrets girl.',
    "She gave us this warm gorgeous night and kept two clouds for herself. She's earned them babe.",
    "I don't trust anything this nice but I'm going outside anyway girl.",
    "She's peaking and she wants witnesses. Go be one girl.",
    "If she asked me to hide a body tonight I wouldn't even ask questions girl.",
    "Warm night mostly clear and I'm outside making decisions I'll regret approving in daylight. She's a con artist with good lighting girl.",
    'The stars are putting on a show and the clouds are in the nosebleed seats. Warm as fuck. Get out there babe.',
  ],
  TemperatureTier.scorcher: [
    "Hot as fuck and she couldn't even cover the sky properly. Sweating under a broken parasol energy babe.",
    "Scorching mostly clear. She's punishing us and looking hot as fuck doing it babe.",
    "Hot as shit stars out. She's throwing a party and the dress code is barely anything babe.",
    'Scorching mostly clear. The two clouds up there are doing fuck all to help. Decorative at best girl.',
    "Stars putting on a show but it's hot as fuck. She said no refunds babe.",
    "She's beautiful and burning us alive. The duality of this bitch girl.",
    "She's sweating through her own sky tonight. Chug something cold as hell babe.",
    "Hot as shit and mostly clear. She's cooking us with the lid off tonight babe.",
    "Even the stars look sweaty tonight. Nobody's okay out here girl.",
    "Two clouds up there and they're sweating too bitch.",
    "She forgot it's nighttime and honestly at this temp so fucking did we. Hydrate girl.",
    "She's so hot the stars are trembling. Or that's the heat haze. Either way she's unhinged girl.",
    "She's too hot tonight and she knows it. Chug something cold girl.",
    'Most of the stars are out watching us sweat. Front row seats to our suffering. Hydrate babe.',
    "She's on one tonight but she looks damn good doing it. Silver linings babe.",
  ],
};
