import '../../../../features/weather/domain/entities/temperature_tier.dart';

const mostlySunnyExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'She brought the vibes and left the warmth in the fucking car. Classic her honestly. Heaviest coat babe.',
    "Cold as fuck and she's still out here fighting clouds. Girl the cold is the problem not them.",
    "Mostly sunny and cold as fuck. She's just up there smiling while we suffer. Girl read the room.",
    "She pushed through clouds and said ta da. Ta da what bitch. It's seven degrees.",
    "It's giving White Lotus. Gorgeous setting everything's wrong. Heaviest coat girl.",
    "Sun shoved clouds out the way like I got this. Girl you do not got this. It's single digits.",
    'Sun peeked past clouds like surprise. Girl the surprise is hypothermia. Bundle the fuck up babe.',
  ],
  TemperatureTier.freezing: [
    'Mostly sunny below freezing. She fought through clouds in the cold for US. The effort alone. Coat on babe.',
    'Cold as fuck but she shoved those clouds aside like a goddamn hero. Appreciate her. Bundle up girl.',
    "Below freezing but mostly sunny. She battled clouds in this cold and won. That's dedication bitch.",
    "Mostly sunny and freezing. She could've stayed behind the clouds but she didn't. She came through. Coat on girl.",
    'Cold as shit but she cleared the sky anyway. Above and beyond honestly. Layer up babe.',
    'Mostly sunny below freezing. At least she tried to make it pretty. And she fucking succeeded. Coat on bitch.',
    "Mostly sunny cold as fuck. She pushed through the clouds in freezing temps. That's harder than it looks. Bundle up girl.",
    'Below freezing but she cleared the sky for us. Free light therapy in the cold. Take what you can get babe.',
    'Mostly sunny and freezing. The fact that she showed up at ALL in this cold is iconic. Coat on girl.',
    'Cold as fuck but she fought for that sunshine. Nobody asked her to. She just did. Respect. Bundle up babe.',
    'Mostly sunny below freezing. She shoved past the cold like it owes her money. Same energy. Heaviest coat and go girl.',
    'Below freezing and she still elbowed clouds out the way for us. Warrior shit honestly. Coat on girl.',
    'Mostly sunny and cold as fuck. At least the sky is open and gorgeous. Beats gray every damn time babe.',
  ],
  TemperatureTier.jacketWeather: [
    "Mostly sunny and cool. Clouds are actually cute as fuck. Jacket on go babe.",
    "Nippy but she's fucking stunning. Layer up and go stare at her babe. With sunnies obv.",
    "Mostly sunny and cool and I'm already outside. Didn't think about it. Just went girl.",
    'Mostly sunny and a little chilly. She finally learned the word moderation. Somebody get this bitch a trophy.',
    "Not her serving a normal nice day like it's a flex. It is though. Jacket on babe.",
    "She's mostly sunny and cool and I just curtsied at the fucking sky. In jeans. In public girl.",
    'Mostly sunny and cool. Jacket on sunnies on get the fuck out there babe.',
    "Cool and mostly sunny. She's not perfect but she's trying and I fucking respect that. Go girl.",
    'Mostly sunny and chilly. She finally did something right. Jacket on go enjoy it before she fucks it up babe.',
    "Cool and mostly sunny. Get outside now. She won't be this chill for long babe.",
  ],
  TemperatureTier.flannelWeather: [
    'She showed up mild and mostly sunny and my jaw hit the floor. Like where have you been babe.',
    'She really said hold my drink and delivered the best fucking day this month. Get out there babe.',
    "She didn't just clear the clouds she Marie Kondo'd them. Get your ass outside girl.",
    'Mostly sunny and mild. She served a perfect day and walked off like it was nothing. Get out there girl.',
    "Mostly sunny and mild. She's fucking peaking and she wants witnesses. Go be one girl.",
    "She's showing off and she deserves it today. Get the fuck outside girl.",
    "It's giving hoodie and sunnies and zero responsibilities. She planned this babe.",
    "She cooked today and didn't burn a single fucking thing. Proud of you girl.",
    'She showed up mild and mostly sunny and I have zero fucking notes. Hate that for me honestly.',
    "Mostly sunny and mild. Get outside. Don't bring your phone. Be feral. Be free babe.",
    "She cleared the clouds served the vibes and didn't ask for applause. Standing ovation anyway babe.",
    'Hoodie on sunnies on stop asking questions get the fuck out there babe.',
    "Mild and mostly sunny. Shacket. Coffee. Outside. That's it. That's the whole plan babe.",
  ],
  TemperatureTier.shortsWeather: [
    'Clouds trying to gatekeep shorts weather. Sun said absolutely the fuck not. Sunnies on babe.',
    "Mostly sunny and warm and oh my fucking god. That's the whole forecast babe.",
    "It's so nice out right now it should be illegal. Somebody arrest her. After I go outside girl.",
    "Mostly sunny and warm and I just skipped to my car. No shame. Shorts on babe.",
    "She's so warm and sunny my seasonal depression packed a bag. Buh bye bitch.",
    'Nice as fuck out. Just threw my jacket in the trash. Shorts time babe.',
    'Mostly sunny shorts weather. She left two clouds for decoration and said go play. Get out there babe.',
    'Mostly sunny shorts weather. She showed up ready and so should you. Get out there girl.',
    'Mostly sunny and warm. Tongue out. No thoughts. All joy. Shorts on babe.',
    "Mostly sunny and warm as fuck. This one's ours. We fucking earned it. Shorts on girl.",
    'Mostly sunny and warm. My legs walked outside without consulting my brain. Smart legs. Shorts on babe.',
    'She cleared the clouds just for us. How sweet. Shorts on go thank her girl.',
    'Mostly sunny and warm. Two clouds up there just vibing. They earned it too. Get out there babe.',
    "She's warm and mostly sunny and you have zero excuse. Get the fuck out there girl.",
  ],
  TemperatureTier.scorcher: [
    'Mostly sunny scorcher. She cleared the clouds for a better angle to cook us from. Strategic. Psychotic. SPF babe.',
    "Hot as fuck and mostly sunny. She's up there with a magnifying glass and we're the ants. SPF or perish babe.",
    "She's so hot the clouds left and honestly same. I would also leave. Can't though. Pool now babe.",
    'Mostly sunny scorcher. She heard calm down and took it as a fucking dare. Hydrate babe.',
    "Girl relax. We get it. Everyone knows you're hot as fuck. Hydrate babe.",
    "Hot as shit mostly sunny. My deodorant just texted me saying I'm on my own today. Shade immediately girl.",
    "Mostly sunny hot as fuck. Even my shadow's looking for shade babe. Seek shelter.",
    "She's so fucking hot I'm googling pools near me with my last brain cell girl.",
    'She cleared the clouds and cranked the fucking heat. Double homicide babe.',
    "She's so fucking hot the asphalt is soft. I'm leaving footprints. In the road girl.",
    "She's scorching us through a mostly clear sky and she's not even at full power. That's the scary part babe.",
    'Holy shit. She fought clouds to bring this heat. Girl we were rooting for the clouds.',
    "She's out here scorching us and the clouds are filming it. Worldstar energy. Find a pool immediately babe.",
    'Mostly sunny scorcher. I just saw a bird panting. A bird. Panting. She broke nature girl.',
    "Mostly sunny and scorching. She really said I'll leave a few clouds so you can watch me cook you. Front row seats bitch.",
    "She's so hot the ice cream truck played Taps instead of its normal song. Moment of silence. Pool now babe.",
    "Nearest pool. Nearest lake. Nearest garden hose. I'm not picky girl.",
    "She's so hot I'd swim in a puddle right now babe.",
    "Mostly sunny scorcher. I'm so hot I just thanked a cloud for existing. Brief shade. Life saved. For now babe.",
    "She's so hot my flip flops are melting into the sidewalk. We're one now girl.",
  ],
};

const mostlySunnyExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Clouds keep blocking the stars and it's freezing af. Whole night's a mess girl. Bundle up.",
    'Half the stars showed up and the other half saw the temp and said absolutely not. Smart girls.',
    "Few stars out looking innocent while it's cold as shit. You're not fooling anyone ladies.",
    "She's trying but it's fucking freezing. Every layer girl.",
    "Some stars some clouds all cold. Can't get her shit together but she's trying babe.",
    "She pulled out like four stars in single digits and wants a standing ovation. Sit down girl.",
    "Stars trying to break through clouds in this cold. Girl give it up. Nobody's watching.",
    'She gave us like six stars and single digit temps. Girl that ratio is criminal.',
    "Clouds and stars out having a party, cold decided to crash. You weren't invited girl go home.",
    "She brought some stars like that makes up for single digits. Ma'am that is not enough.",
    "She's gatekeeping every good star tonight. Single digits and zero access. Rude as fuck.",
    "She couldn't commit to a full sky and it's single digits. Half-assing everything tonight babe.",
  ],
  TemperatureTier.freezing: [
    "Stars that showed up? Brave. Stars that didn't? Smart. Both valid.",
    "She gave us half a sky and all the cold. At least she's trying. Bundle up babe.",
    'She showed up with like three stars and called it effort. Below freezing too. The bar is underground babe.',
    "She gave us this beautiful sky and then made it freezing. Like why bother girl.",
    "Pretty sky freezing air. She said look don't touch. What a tease.",
    'Most of the stars and all of the suffering. Why is she like this girl.',
    "She's taking forever to figure out if she's cloudy or clear. It's freezing. Make up your mind girl.",
    "Clouds hogging the sky like they pay rent. They don't. Bundle up girl.",
    "Pretty night shit temp. She's sending mixed signals again babe.",
    "Below freezing and she couldn't even give us a full sky? The audacity.",
    'Stars doing community service in freezing temps. Somebody thank them. Bundle up babe.',
    'Almost committed to a full sky. Almost. Fully committed to this temp. Wrong choice girl.',
  ],
  TemperatureTier.jacketWeather: [
    'Few clouds crashed the star party. Rude but the vibes survived. Jacket on babe.',
    "The clouds aren't ruining shit they're garnish. She plated this night like a damn chef girl.",
    'She showed up and actually delivered tonight. Who is this woman. Jacket on get out there babe.',
    "Two clouds trying to be relevant on an otherwise perfect night. Nobody's buying it girl.",
    "Beautiful night. Clouds trying to hog the stars. Ma'am those aren't yours give them back.",
    "She passed the vibe check tonight. Like shit. Don't let it go to your head girl.",
    'She gave us most of the stars and a cool breeze and honestly I have zero complaints for once.',
    "Stars and clouds playing nice tonight. Cool temps. Therapy's working girl.",
    'Clean sky cool air zero complaints. She said less is more and proved it babe.',
    'She rolled out of bed with two clouds in her hair and still looks better than most nights. Go look babe.',
    'Cool clear-ish night. The clouds are scenery not a statement. Jacket on go girl.',
    "Jacket on get outside. She gave us most of the sky and perfect temps. Don't fuck this up girl.",
    "Get your ass out there. She's behaving for once. Go play.",
  ],
  TemperatureTier.flannelWeather: [
    "She's pretty as fuck tonight and being nice about it. What's the catch babe.",
    'Most of the stars and perfect temps. Five stars. No notes.',
    'She really gave us this night for free. No strings. Suspicious. Go enjoy it babe.',
    'She set the whole night up and all you have to do is show up. Get out there babe.',
    "Mild night and two little clouds up there just vibing. They're adding character honestly.",
    'Mild mostly clear. She said watch this. And then she did that. Get the fuck outside girl.',
    "She's peaking tonight babe. Everyone shush. Watch her go.",
    "This temp with this sky. She's flirting with us and it's working girl.",
    "She's so pretty it's honestly annoying. Like we get it girl.",
    "Mild perfect sky and she's over there acting casual about it. Nobody's buying the humble thing girl.",
    "She doesn't have to try. She just shows up and the bar moves. Sickening honestly.",
    "She said oh this? I just threw it together. Ma'am this took planning we all know it.",
    "Shacket on get outside. She gave us most of the sky and perfect temps. Don't waste this shit girl.",
    "Get your ass out there. She's peaking and she needs an audience babe.",
    "Hoodie on go. She's being generous and we're not gonna disrespect that by staying inside girl.",
  ],
  TemperatureTier.shortsWeather: [
    "She's a fucking ten tonight. Okay two clouds. But still a ten babe.",
    "Warm and mostly clear and now I'm outside having a moment. Blame her girl.",
    'Stars out warm as fuck. She just looks like this. No filter no effort. Disgusting honestly.',
    'Two clouds out there on a warm gorgeous night doing absolutely nothing. Love that for them.',
    "Zero fucking notes. She said perfection isn't hard when you're me. Like okay girl.",
    'Warm night most of the stars. Two clouds up there third-wheeling. Nobody fucking invited you babe.',
    "She's warm and beautiful and my phone's been face down for twenty minutes. Didn't even notice babe.",
    "She just walked in and every other night left. Can't fucking compete babe.",
    "Warm and nice as fuck. Competition's over. She won. Get out there babe.",
    "She's the hot girl who says she's not even that hot. Fucking stop it girl.",
    'Two clouds crashed a warm gorgeous night and everyone just kept vibing around them. Love the energy.',
    "Every cloud in the sky just got demoted to scenery. She's running this shit babe.",
    'Stars out clouds quiet temp perfect. She fucking did that girl.',
    'Warm mostly clear and I just made a sound at the sky that I can\'t take back. Worth it babe.',
    "She gave us this warm gorgeous night and kept two clouds for herself. She's earned them babe.",
    "I don't trust anything this nice but I'm going outside anyway girl. Come with.",
    "She's peaking and she wants witnesses. Go be one girl.",
    "If she asked me to hide a body tonight I wouldn't even ask questions girl.",
    'Warm gorgeous night and my judgment is compromised. She does this shit on purpose girl.',
    'Stars running the show tonight on a warm gorgeous sky. The clouds are just watching. Same girl.',
  ],
  TemperatureTier.scorcher: [
    "She's cooking us alive but looking incredible doing it. You'll sweat and you'll like it girl.",
    "Scorching mostly clear. She's punishing us and looking hot as fuck doing it babe.",
    "Hot as shit stars out. She's throwing a party and the dress code is barely anything babe. Let's go.",
    'Scorching mostly clear. Two clouds up there doing fuck all to help. Decorative at best girls.',
    "Stars putting on a show but it's hot as fuck. She said no refunds babe. Get out there I guess. No choice.",
    "She's beautiful but cooking us alive. The duality of this bitch.",
    "She's sweating through her own sky tonight. Chug water babe.",
    "The sun clocked out and forgot to take the heat home. Somebody come get her. Drink water babe.",
    "Even the stars look sweaty tonight. Nobody's okay out here girl.",
    "Two clouds up there and they're sweating too. Hydrate babe.",
    "She forgot it's nighttime and honestly at this temp so fucking did we. Stay hydrated girl.",
    "Stars are out but they look like they're melting. Same energy honestly. Hydrate girl.",
    "The stars look drunk in this heat. Honestly same. Drink water girl.",
    'Most of the stars are out just watching us sweat. Front row seats to our suffering. Drink water babe.',
    "She's on one tonight but she looks damn good doing it. Silver linings I guess.",
  ],
};
