import '../../../../features/weather/domain/entities/temperature_tier.dart';

const overcastExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Overcast and single digits. She's in her moody era and the cold is the enemy. Puffer on babe.",
    "Gray and cold as fuck. She's giving full grayscale aesthetic. The cold is what's rude. Bundle up girl.",
    "Overcast single digits. She's in her brooding era. The gray is a mood. The cold can fuck off babe.",
    "Gray sky single digits. She's being dramatic and gorgeous. Hot chocolate and layers girl.",
    "Overcast and cold. She's living in her dark academia moment. Puffer on babe.",
    "Overcast single digits. She's in her groutfit era. Full gray full mood. The cold is the problem girl.",
    "Gray and cold as fuck. She's moody and committed. The aesthetic is there. The temp can eat shit babe.",
    "Gray and frozen. She's serving editorial vibes. The cold is what's mean. Bundle up girl.",
    "Overcast single digits. She dimmed the lights and the cold turned up. Gray is the vibe. Coat on babe.",
    "She's giving full grayscale in single digits. Moody as fuck. The cold is the villain here girl.",
  ],
  TemperatureTier.freezing: [
    "Gray and frozen. She's moody AND cold. The aesthetic is immaculate. The temp can fuck off. Heaviest coat babe.",
    "Gray and frozen. She said I will be moody AND cold. Overachiever energy honestly. Bundle up girl.",
    "Overcast below freezing. She's fully in her gray era. The cold is what's disrespectful. Coat on babe.",
    "Overcast below freezing. No sun no warmth just vibes. Bold as fuck. Layer up girl.",
    "Overcast and cold as fuck. She's committed to the moody aesthetic. The freeze is the enemy. Coat on babe.",
    "Below freezing and overcast. She's in her feelings and the cold makes it hit harder. Bundle up girl.",
    "Gray below freezing. She woke up moody and the cold showed up uninvited. On brand. Warmest coat babe.",
    "Gray and freezing. She dimmed the lights and the temp plummeted. The gray is fine. The cold is not girl.",
    "Overcast freezing. She's living her best moody era. The cold can go to hell. Coat on babe.",
    "Gray and freezing. She put a gray ceiling on the sky. Aesthetic. The cold is the problem though girl.",
  ],
  TemperatureTier.jacketWeather: [
    "Overcast and cool. She hid the sun and won't say where. Sus as fuck honestly.",
    'Overcast jacket weather? She said let me be moody AND cute. Fucking nailed it. Coffee stroll incoming.',
    "Overcast and cool. She's not trying to impress anyone and honestly she doesn't have to. Do you girl. Layer the fuck up babe.",
    "Gray and cool. She took away the sun and I'm not even mad. Trench coat energy babe. Go be mysterious.",
    'Alanis energy tbh. Gray moody and walking with purpose. Jacket on babe.',
    "Gray and cool. She's giving that one indie movie you watched alone and fucking loved. Jacket on babe.",
    'Overcast jacket weather. Coffee weather. Moody walk weather. Main character weather. Go girl.',
    "Overcast and cool. My resting bitch face finally matches the sky. We're twinning babe.",
    "She dressed the whole city in grayscale and it's serving editorial. Jacket on babe.",
    "She turned off the sun and turned up the vibes. Didn't know that was an option. Layers babe.",
    'Gray jacket weather. Throw on a coat grab a coffee and get the fuck out there babe.',
    "Overcast and cool as fuck. She's not apologizing and honestly she doesn't need to. Go girl.",
  ],
  TemperatureTier.flannelWeather: [
    "Sky? Trash. Temp? Immaculate. She's a damn con artist and I'm the mark babe.",
    "She's giving bad first impression great personality. Flannel on girl.",
    "It's giving ugly apartment incredible location. Can't fucking leave honestly.",
    'My flannel just looked at the sky and said I got this. And it fucking does girl.',
    'She showed up looking like a DMV ceiling but the temp is nice so fuck it. Boots on babe.',
    'She dressed like shit and still pulled. Get outside babe.',
    "It's giving catfish. Ugly from orbit. Perfect at street level girl.",
    "Overcast and mild. I want to complain but the air won't fucking let me. Hostage vibes babe.",
    'Hot mess energy. Disaster up top. Flawless down here. She gets away with everything girl.',
    "It's giving tinted windows. Can't see shit but the ride is smooth babe.",
    "The sky is boring as fuck and I've been outside for two hours. Do the math girl.",
    'She put a ceiling on the city and the air underneath is perfect. Chaos architect babe.',
    "Zero visual appeal. Maximum comfort. Shouldn't fucking work. Does girl.",
    "She's giving ugly car great engine. Don't look up. Just drive babe.",
    "Overcast flannel weather. She's ugly as fuck up there but the air is perfect. Get outside babe.",
    "It's giving beige flag. Not mad. Not thrilled. Just outside girl. Boring as shit but she feels good.",
    "It's giving substitute teacher who's cooler than the real one. Flannel on babe.",
    'Gray flannel weather. Failing upward energy. A disaster who keeps getting away with it girl.',
    "Gray and mild. Sky is mid. Temp is elite. She's getting away with it again babe.",
    'Gray flannel weather. Throw on a hoodie and get the fuck outside. She earned this girl.',
  ],
  TemperatureTier.shortsWeather: [
    'Gray and warm. She removed the sun and kept the heat. This is a fucking heist babe.',
    "She's giving I woke up hot and sad. Relatable as shit girl.",
    "Overcast and warm. She's emo in a bikini. Shouldn't work. Does babe.",
    'Warm and gray. No sunburn. No squinting. No fucking complaints.',
    'She kept the heat and fired the sun. HR approved. Shorts on babe.',
    "It's giving cheat code. All the warmth none of the fucking UV. She hacked summer girl.",
    'Overcast shorts weather. Brightness down. Heat up. She adjusted the settings again babe.',
    "She's giving sundress no sunscreen. The whole damn operation simplified girl.",
    'She gave us summer without the homework. No SPF no shade math no drama babe.',
    "She made the sun redundant and the temp didn't fucking flinch. Hostile takeover vibes babe.",
    "It's giving the cool side of the pillow but everywhere. Shorts on babe.",
    "Gray and warm. She's the weather equivalent of dark mode. Same heat less glare girl.",
    "Warm and gray. Haven't thought about sunscreen once. That's the whole damn review honestly.",
    'Overcast shorts weather. She subtracted the sun and it got fucking better. Less is more babe.',
    'Gray and warm as fuck. This is what summer would be if summer had manners girl.',
    'She hid the sun and nobody filed a missing persons report. Good riddance babe.',
    'Warm and overcast. The sun is unnecessary and she had the guts to say it. Pioneer bitch.',
    'Gray shorts weather. Shoulders fine. Eyes open. Skin intact. She patched every bug babe.',
    'Gray and warm and you need zero sunscreen. Shorts on get out there babe.',
    'Overcast shorts weather. She simplified the whole damn operation. Get outside girl.',
    'Warm and gray. She removed the glare and kept the heat. Shorts on go babe.',
  ],
  TemperatureTier.scorcher: [
    "Overcast scorcher. She turned the sky into a damn greenhouse. Girl we're not plants.",
    "Gray and hot as fuck. She's steaming us like vegetables. We didn't consent to this girl.",
    "Hot as fuck and gray. She trapped us under a heat blanket nobody asked for. We're steaming girl.",
    'Hot as fuck and gray. Humidity just entered the chat with a baseball bat girl.',
    "Overcast and scorching. She put a lid on us and turned up the heat. We're not soup girl.",
    'Erin Brockovich vibes. Overcast scorcher. Minimal clothing maximum attitude. Stay hydrated girl.',
    'Overcast scorcher. She sealed us in and cranked the temp. Sous vide energy babe.',
    "Gray and hot as fuck. I'm sweating in places I didn't know I had. She found new real estate babe.",
    'Gray and scorching. She sealed us under clouds like leftovers nobody wanted. Drink water babe.',
    "Hot as fuck and gray. The air is thick enough to leave a handprint in. She's absurd girl.",
    'Overcast scorcher. Every breath feels like inhaling a wet towel. Creative. Hateful. Hydrate girl.',
    'Gray and scorching. She invented a new kind of suffering. Not sunny not breezy just damp hell girl.',
    'Gray and hot as shit. I just sweated through my shirt like blotter paper. Modern art babe.',
    'Overcast and blazing. She cranked the humidity to eleven and hid the dial. Good luck girl.',
    "Hot as fuck and she won't even let us see the sun we're suffering for. Hostage energy babe.",
    'Gray scorcher. My ice cream melted before I left the store. The cone wept. I wept. Hydrate girl.',
    "Gray and scorching. Even the birds look confused. They're just standing there panting. Same babe.",
    "She served us a scorcher under full gray like a covered dish from hell. Surprise it's suffering girl.",
    "Overcast scorcher. The clouds aren't blocking anything they're insulation. We didn't ask for this girl.",
  ],
};

const overcastExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She turned the whole sky to dark mode in single digits. Full grayscale era. Bundle up babe.",
    "Overcast and cold at night. She's being moody and the dark amplifies everything. Layer up girl.",
    "Gray dark cold. She's fully in her aesthetic tonight. The cold is the enemy. Stay warm babe.",
    "Overcast night in single digits. She went full dark mode. Moody as fuck. Every layer girl.",
    "No stars just gray. She's in her feelings tonight. The cold is what's cruel. Bundle up babe.",
    "The sky is solid gray and cold as fuck. She's living her moodiest moment. Stay cozy girl.",
    "Overcast single digits at night. She dimmed everything. The gray is a vibe. The cold is not babe.",
    "Gray and cold at night. She's in her dark aesthetic era. The temp can fuck off. Stay warm girl.",
    "No stars just clouds and cold. She's being atmospheric. The cold is the real problem babe.",
    "She went full grayscale at night in single digits. Moody queen. The cold is the bitch here girl.",
    "Overcast night in single digits. She turned it all gray and the cold showed up uninvited. Bundle up babe.",
    "Dark gray cold. She's committed to this mood. The freeze is what's harsh. Stay warm girl.",
  ],
  TemperatureTier.freezing: [
    "Gray ceiling below freezing at night. She's in her moody era. The cold is what's harsh. Coat on babe.",
    "Overcast and freezing at night. Full dark mode activated. She's living her best gray life girl.",
    "Below freezing and overcast at night. She's committed to the grayscale aesthetic. Bundle up babe.",
    "She covered the sky in gray below freezing. Moody and atmospheric. The cold is the enemy girl.",
    "Overcast freezing night. She's giving full noir vibes. The cold can fuck off. Stay warm babe.",
    "No stars below freezing. She's in her dark aesthetic era. The freeze is what's mean girl.",
    "Gray and freezing at night. She's being cinematic and moody. The cold is the real problem babe.",
    "She put a gray lid on the sky below freezing. The vibe is there. The temp is not. Coat on girl.",
    "Overcast freezing night. She's fully in her mood. Grayscale everything. The cold is the villain babe.",
    "Below freezing and gray at night. She's serving dark mode energy. The cold is what sucks girl.",
    "She dimmed the whole sky below freezing. Moody as fuck. The cold is the enemy not the gray babe.",
    "Overcast freezing night. She's in her feelings. The gray is aesthetic. The cold can eat shit girl.",
  ],
  TemperatureTier.jacketWeather: [
    'She really threw a blanket over the sky and said fucking deal with it babe.',
    "She's in her fucking minimalist era. No stars no clouds just void babe.",
    'No stars just vibes. Dark shitty vibes but vibes babe.',
    'She covered the stars and left us with a cool gray ceiling. Moody but livable girl.',
    'Every star ghosted. All of them. At once. Coordinated betrayal girl.',
    "She blacked out the sky like it's a redacted document. Like shit. What are you hiding girl.",
    'The sky is hiding something behind all those clouds. Probably stars. Probably resentment babe.',
    'Overcast and cool. She threw a fitted sheet over the whole sky and tucked in the corners girl.',
    'She gave us a ceiling instead of a sky. Thanks girl I hate it.',
    'She deleted the stars and blocked our number. Moving on bitch.',
    "No stars just clouds and a cool breeze. She's doing the minimum and we're accepting it babe.",
    "Sky dipped but the temp's holding it down. Somebody has to girl.",
    "She said ma'am this is a private event. Exclusive access only.",
    'The sky is just off tonight. Not scary just unsettling. Like a voicemail from your ex.',
    "She sealed the sky shut and handed us a jacket temp. Mixed review but we'll take it girl.",
    'She said stars? In this economy? Jacket on babe.',
    'The clouds are so thick they look solid tonight. I could walk on that sky girl.',
    'She shut the sky down and left the temp on autopilot girl.',
    'She turned the sky into a ceiling and the night into a room. Cozy if you squint babe.',
  ],
  TemperatureTier.flannelWeather: [
    'No stars just clouds and perfect fucking temps. She failed the sky and aced the weather girl.',
    "No stars but the temp is perfect so honestly who cares. Not me. I'm outside babe.",
    'She showed up with zero sky and perfect vibes. Make it make fucking sense girl.',
    "Sky's on mute. Temp's on one. The duality of this bitch.",
    'She served the temp and ghosted the sky. Half-ass excellence babe.',
    "She's the minimalist who threw out everything except the vibes bitch.",
    'No stars just clouds just fucking perfect temps just vibes babe.',
    'Holy shit. She turned the sky off and expects a thank you for the temp. The nerve girl.',
    'She took every star hostage but left the temp as ransom babe.',
    'The sky is taking a personal day. Temp is covering her shift babe.',
    'Flannel on get outside. No stars but who gives a shit. The temp is perfect girl.',
    'Get out there. She killed the sky and nailed the weather. Take the fucking win babe.',
    "Flannel on go. She's serving nothing but perfect temps and honestly that's enough babe.",
  ],
  TemperatureTier.shortsWeather: [
    "Can't see shit up there. Don't care. It's nice as fuck out girl.",
    "She blacked out every star and it's still fucking gorgeous out. Witchcraft honestly babe.",
    'She said stars are optional. Fucking warm air is not. Priorities girl.',
    'She gave us a ceiling and a sauna. Interesting choice girl.',
    'She really murdered the sky and left fucking perfect temps as an alibi babe.',
    'She unplugged the sky and plugged in the heat. Priorities bitch.',
    'Overcast and warm. She tucked the stars in and let the heat roam free babe.',
    "She sealed the sky and the warmth is trapped in here with us. I'm not complaining girl.",
    "Sky's on her bullshit but the temp's on her best behavior girl.",
    "Sky's fully off. Temp's fully on. She's got range I'll give her that.",
    "She said you don't need stars when it's this nice out. She's not wrong girl.",
    "Get your ass outside. No stars but it's warm as fuck and that's all you need girl.",
    'Shorts on. The sky is off duty but the air is doing overtime. Go enjoy it babe.',
  ],
  TemperatureTier.scorcher: [
    "She said cool down? That's not on the fucking menu babe.",
    "Clouds won't let the heat go. Attachment issues honestly babe.",
    "Overcast and scorching. She sealed the heat under clouds like a dutch oven. We're the bread girl.",
    "She sealed the heat under clouds and went to bed. We're marinating. She's sleeping girl.",
    "She took the stars and added heat. She's collecting problems like Pokémon girl.",
    'The clouds are trapping every degree like a savings account for suffering babe.',
    'She really just gave us a fucking hot ceiling. Like a car with the windows up babe.',
    'Holy shit. No stars just suffering. She said ambiance? No. Heatstroke? Maybe.',
    "She put clouds over the sky and heat under them. We're the filling in this sandwich babe.",
    'Hot and overcast. She sealed us in and turned up the heat. Pressure cooker energy girl.',
    "No stars no chill. Literally and figuratively. She's unhinged as hell girl.",
    "The clouds are holding the heat hostage and we're the ransom. Nobody's paying girl.",
    'No stars no breeze no apology. She meant every degree of this babe.',
    'Scorching overcast. The air is so thick and hot I could chew it babe.',
    'She trapped us under clouds and turned up the heat. Rotisserie vibes girl.',
  ],
};
