import '../../../../features/weather/domain/entities/temperature_tier.dart';

const partlyCloudyExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Partly cloudy in single digits. She's giving us glimpses of blue like that changes anything. Still freezing bitch.",
    "Sun popping in and out like she's got somewhere better to be. Probably does at this temp. Bundle up babe.",
    "Single digits partly cloudy. She put effort into the sky and none into the thermostat. Priorities are fucked babe.",
    "Clouds and sun flirting up there while we freeze to death watching. Get a room. And give us heat. Coat on girl.",
    "Partly cloudy and cold as fuck. She keeps flashing a little sun like that's gonna warm us up. Girl that's not how thermodynamics works.",
    "She gave us sun AND clouds like she's generous. Girl we can't deposit a pretty sky into our heating bill. Coat on girl.",
    "Single digits but she put together a whole sky look. Curated. Editorial. Still can't feel my fucking ears though. Coat on babe.",
    'Partly cloudy single digits. The sky? Cute. The temp? Homicidal. Heaviest coat girl.',
    "Cold as fuck but she's doing something interesting up there. Sun and clouds taking turns and honestly it's pretty. Layer up babe.",
    'She dressed the sky up nice and forgot the temp entirely. Very her. Bundle up girl.',
    'Partly cloudy single digits. Sky has a whole vibe going. We have hypothermia. Not a fair trade babe.',
    "Sun and clouds sharing the sky and it's kinda cute honestly. Temp's trying to kill us but at least she looks good doing it.",
    "Partly cloudy and frozen solid. Sky's got this moody little thing going though. Love the look hate the cold. Layers babe.",
  ],
  TemperatureTier.freezing: [
    "Cold as fuck but at least we're getting some sun through the clouds. Not fully gray. Take the win babe.",
    "It's giving Black Swan. Dramatic sky but at least there's light peeking through. Coat on girl.",
    'Partly cloudy below freezing. She brought options and none of them include warmth. A sampler platter of useless. Bundle up babe.',
    "She's giving confused but make it fashion. Threw on clouds and sun and somehow it works. Bundle up babe.",
    "Partly cloudy and freezing but hey. Every time the sun peeks out it's a whole damn gift. Coat on girl.",
    "Below freezing partly cloudy. At least she's not giving us the full concrete ceiling. Low bar but she cleared it. Bundle up girl.",
    "Cold as fuck but sun keeps poking through the clouds like hey I'm still here. Love that energy. Coat on babe.",
    "Partly cloudy and freezing. The sun shows up just long enough to remind you what warmth looks like. Then leaves. Emotional damage. Layer up girl.",
    "Below freezing but at least the clouds aren't hogging the whole sky. We see you sun. Coat on babe.",
    'Partly cloudy cold as shit. But those little patches of blue sky are doing everything for my mood. Bundle up girl.',
    "Freezing and partly cloudy. Oh she left some blue sky. Want a medal? Still can't feel my toes. Bundle up babe.",
    "Cold as fuck but the sun keeps dodging clouds like she's got an agenda. Whatever it is it doesn't include warmth. Coat on girl.",
    "Partly cloudy below freezing. Getting sunshine in intervals like she's charging by the minute. Bundle up babe.",
    "Below freezing partly cloudy. Cool sky babe. Still freezing my ass off down here but yeah cute clouds.",
    "Partly cloudy and freezing. The sun keeps popping out like she forgot something. Girl what did you forget. Warmth? Bring that next time.",
    "Cold as fuck partly cloudy. The sun keeps punching through for a second like remember me? Yes bitch. Come back.",
    "She's mixing sun and clouds below freezing. The sky has range. The temp has one setting and it's fuck you. Coat on babe.",
    "Partly cloudy and freezing. Sun keeps elbowing through clouds like excuse me I'm working here. Girl are you? Try harder.",
    'Below freezing partly cloudy. Sun keeps poking through like a nosy neighbor. Girl mind your business or bring heat. Bundle up babe.',
    "Partly cloudy cold as fuck. But at least there's some blue up there. Coat on girl.",
    "Freezing but partly cloudy. She could've gone full gray but she left the light on for us. How sweet.",
    "Below freezing partly cloudy. The sun breaks through and honestly it hits different when it's this cold. Magical shit girl.",
    'Partly cloudy and freezing. She put some effort into the sky at least. The temp got no such attention. Coat on babe.',
    "She's giving us peekaboo sun at freezing temps. Every time she shows her face I'm like oh now you wanna be cute. Coat on babe.",
  ],
  TemperatureTier.jacketWeather: [
    'Partly cloudy cool temps. She cleaned up fucking nice. Sunnies on babe get out there.',
    "Sun and clouds at jacket temp. She found the sweet spot between too much and not enough. Grab a layer and go babe.",
    "Clouds and sun splitting the sky fifty-fifty. Healthiest relationship I've seen all year. Jacket on girl.",
    "It's giving errand weather. She built today for a Target run. Grab a layer and go babe.",
    "She's giving sun and clouds but the air still has bite. Pretty sky cool temp. Layers not optional babe.",
    "Sun and clouds taking turns but the air is giving jacket. She decorated but didn't adjust the thermostat. Typical.",
    "Partly cloudy and a little chilly. She's being fucking indecisive in the cutest way possible. Layer up and go girl.",
    'Partly cloudy and chilly. Textbook pretty day. She read the fucking assignment for once babe.',
    'Partly cloudy and cool like she planned a whole outfit for the sky but forgot pants. Throw a layer on babe.',
    "She's acting all partly cloudy and breezy like she wasn't just a nightmare three days ago. Love the rebrand. Jacket on girl.",
    'Partly cloudy jacket weather. She finally got her shit together. Bundle up and get out there girl.',
  ],
  TemperatureTier.flannelWeather: [
    'Partly cloudy nice as fuck. Clouds are a whole aesthetic. Get outside girl.',
    'Partly cloudy and perfect. Zero notes zero complaints. Not one. Just go babe.',
    "Partly cloudy and mild and she made it look easy. It wasn't. She's been planning this all week babe.",
    "Partly cloudy at this temp. She's not overachieving she's not underperforming. She's hitting the fucking sweet spot babe.",
    "Partly cloudy and mild and I think I just fell in fucking love. It's mutual girl.",
    "Partly cloudy cool temps and I'm gone. Deceased. She killed me with perfection girl.",
    "Partly cloudy perfect temps. I'm obsessed and no I won't shut up about it. Get your ass outside babe.",
    "Partly cloudy perfect temps. She said too much sun is basic. She's fucking right babe. Let's play.",
    "Partly cloudy mild temps. Put your phone down and go be in her. I'm serious. Get out here bitch.",
    "Clouds rolling through a mild day like opening credits. She's setting a mood and I'm fucking here for it babe.",
    "Partly cloudy and mild. She's on her redemption arc and honestly she's nailing it. Get outside babe.",
    'Partly cloudy at this temp is objectively the best fucking weather on earth. Fight me.',
    'Partly cloudy at this temp hits different. She knows it. I know it. We all know it. Go play.',
    'Sun and clouds and perfect temps. This weather fucks. Get out there babe.',
    'Partly cloudy perfect temp. Hoodie on boots on get the fuck out there babe.',
    'Shacket and sunnies. She served clouds for character and warmth for free. Get outside bitch.',
  ],
  TemperatureTier.shortsWeather: [
    "Partly cloudy nice as fuck. Clouds giving free shade. She's so thoughtful. Shorts time babe.",
    'Partly cloudy shorts weather. Fuck your plans. New plans. Outside. Now. Go.',
    "Partly cloudy shorts weather. If this day were a person I'd ask it out. I'd be nervous too babe.",
    "Partly cloudy and warm. She gave us sun with a dimmer switch. Innovation at its finest. Shorts on babe.",
    "Partly cloudy and warm. This is the day other days wish they were. She set the standard and it's high girl.",
    "Partly cloudy warm day. She brought her own umbrella so we wouldn't have to. Thoughtful queen. Shorts on babe.",
    "Sun and clouds at shorts weather. She's running a buy one get one on vibes today. Get out there bitch.",
    'Partly cloudy and gorgeous. Sky is delivering. Go accept her gift babe.',
    "Sun when you want it shade when you need it. She's fucking psychic girl.",
    'The kind of day you call in sick for. Do it. No regrets babe.',
    'Partly cloudy shorts weather. Shade built in. Get the fuck outside babe.',
    'She gave you sun and shade with perfect temps. The fuck more do you want babe. Go play.',
    'Partly cloudy warm as hell. Shorts on sunnies on bullshit off. Go babe.',
    "She's warm and partly cloudy and you're still inside? Go. Like right now. I'm not asking I'm telling.",
    "Partly cloudy and warm. She handed us the perfect day and said don't waste it. She's right. Go babe.",
    "Partly cloudy and warm. If you stay inside today I'm calling the cops. That's a crime against vibes babe.",
    'Sun and clouds taking shifts at perfect temps. They coordinated outfits too. Get out there girl.',
  ],
  TemperatureTier.scorcher: [
    'Partly cloudy and scorching. Thank fuck for those clouds. SPF 50 babe.',
    'Every time a cloud shows up I whisper thank you. Every time it leaves I whisper you bitch. SPF on babe.',
    'Every cloud gets a thank you and every gap gets a fuck you. Emotional day out here girl.',
    'Hot as fuck. Clouds giving shade breaks like little apologies. Not enough but noted girl.',
    'Hot as shit partly cloudy. Clouds keep dipping like they have somewhere better to be. Rude as fuck honestly.',
    "Hot as fuck with intermittent mercy. She's doling out shade like treats. We'll be good girl I promise.",
    "Partly cloudy scorcher. Sun peeking around clouds like yeah bitch we know you're there. We're boiling.",
    "Scorching partly cloudy. She's playing peekaboo with the sun and we lose every round babe. Drink water.",
    'She showed up confused and hot. Not hot temp hot. Well also hot temp. Both kinds of hot bitch.',
    "Hot as shit. I'm following cloud shadows around like a lost puppy. No shame babe.",
    'Scorching partly cloudy. Cloud shadows are three second vacations from hell. Hydrate babe.',
    'Partly cloudy scorcher. She keeps giving us hope then taking it away. Toxic as fuck. Drink water babe.',
    "Scorching with cloud breaks. She's torturing us on a schedule. It's giving organized sadist. Stay hydrated babe.",
    'Hot as fuck. Found a cloud shadow. I live here now. Come hang. Bring water babe.',
  ],
};

const partlyCloudyExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Single digits partly cloudy night. She bedazzled the sky and left the heat off. On brand. Coat on girl.',
    "Stars keep popping through clouds like she's testing the light show. Girl the audience is freezing. Bundle up babe.",
    "She's swapping clouds and stars around up there like she's trying outfits on. Girl pick one we're freezing. Coat on babe.",
    "Partly cloudy single digits. Sky's out here doing the most and the thermostat's doing the least. Classic her. Coat on girl.",
    "Partly cloudy night in single digits. Sky looks like a lace curtain over a window that's been left open all winter. She looks good though babe.",
    "She's unveiling stars one at a time like a shitty advent calendar. Behind every door is more cold. Bundle up girl.",
    'Stars sneaking through clouds in single digits. The vibes are immaculate up there. The temp is violence down here. Layer up babe.',
    "She keeps sliding stars between clouds like notes under a door. The note says freeze bitch. Bundle up babe.",
    'She built a whole night sky and set the temp to punishment. Production value is high though. Coat on girl.',
    "Partly cloudy single digits. She's airdropping stars to nobody. We're all too frozen to accept. Bundle up babe.",
    'Single digits partly cloudy. The sky brought a charcuterie board and the temp brought a knife. Layer up girl.',
    "Partly cloudy single digits. The sky is gorgeous and the temp is felony assault. She's multitasking. Coat on girl.",
    "She's handing out stars between clouds like Costco samples. Ma'am we came for warmth. Bundle up girl.",
    "Stars breaking through clouds like they have news. The news is it's still fucking freezing. Layer up babe.",
    "Single digits and she's rotating clouds past stars like a screensaver nobody asked for. Coat on babe.",
  ],
  TemperatureTier.freezing: [
    "Stars playing hide and seek behind clouds. Girl we're too cold to seek. Bundle up babe.",
    "Freezing and she keeps hiding stars behind clouds. Girl we already can't see straight from the cold. Bundle up babe.",
    'Partly cloudy below freezing. She styled the whole sky and forgot the thermostat. On brand. Coat on girl.',
    "Below freezing partly cloudy. The sky's moody and the air's mean. Whole night has an attitude. Stay warm babe.",
    "Cold as fuck but at least she's pretty. Coat on girl.",
    "Every time a star breaks through the clouds I gasp. Beauty or cold. Unclear. Coat on girl.",
    "Stars keep poking through clouds like they're checking if it's safe. Girls it's not. Stay warm babe.",
    "Freezing and partly cloudy. She's putting on a whole show for nobody. We're inside girl. Stay warm babe.",
    "Below freezing partly cloudy. Some stars said nope and hid. Honestly fair. We should too. Bundle up girl.",
    "Stars that showed up tonight are brave. Stupid but brave. So cold. Layer up babe.",
    "Below freezing partly cloudy. Bitch the sky can't even commit. Coat on girl.",
    "Partly cloudy below freezing. She's being stingy with stars and warmth. Pick a struggle babe.",
    'Freezing partly cloudy. Stars keep peeking out like hey girl. Girl no. Too cold. Go away.',
    "Freezing and partly cloudy. She really said let me be pretty AND unbearable. Nailed it. Coat on babe.",
    "Partly cloudy below freezing. The sky's half-assing everything tonight. Stars warmth all of it. Coat on girl.",
    "Freezing partly cloudy. She keeps flashing one star like that's enough. Bitch it's not. Bundle up babe.",
  ],
  TemperatureTier.jacketWeather: [
    "Half the stars showed up. Other half said fuck this too cold. Can't blame them honestly. Bundle up babe.",
    'She threw random clouds at the sky like a drunk girl throwing darts. Some hit. Jacket on babe.',
    'She punched holes in the clouds like a three-ring binder. Stars filed neatly. Cool night. Jacket on girl.',
    'Half the stars called in sick tonight and the rest are picking up the slack. Jacket temp though so who cares girl.',
    'She organized the sky like a junk drawer. Somehow everything you need is in there. Jacket on go look babe.',
    "She keeps shuffling clouds around like she's redecorating mid-party. Cool night though. Let her cook babe.",
    'Half clouds half stars and she arranged them like a chessboard mid-game. Cool night. Your move. Jacket on girl.',
    "Clouds crossing the stars like subtitles on a foreign film. Plot unclear but the cinematography's perfect. Jacket on girl.",
    'She gave us a connect-the-dots sky with half the dots missing. Cool night. Figure it out bitch.',
    "She's half clouds half stars and fully not sorry about it. Layer up and get outside babe.",
    "She's flashing stars then hiding them like a dealer at a poker table. Cool night girl.",
    "The sky is rearranging itself every five minutes. She can't sit still. Neither can I. Jacket on babe.",
    "Jacket on get outside. She's messy but she's pretty and the temp is right girl.",
    "Jacket on go. Half the sky showed up and that's more than enough. Get your ass out there babe.",
    "Get outside. She threw the sky together like a résumé she didn't proofread. Still got the job. Jacket on babe.",
  ],
  TemperatureTier.flannelWeather: [
    "She's half-assing the sky and fucking nailing the temp. We'll take it babe.",
    "Sky can't decide but the temp said I got this. Thank fuck girl.",
    "Half the sky's missing. Don't care. It's nice as fuck out babe.",
    "She's a jigsaw puzzle missing half the pieces at the perfect temp. Nobody's filing a complaint babe.",
    'Half the stars and perfect vibes. Math checks the fuck out girl.',
    "She mixed clouds and stars like a bartender who doesn't measure. It's strong and it works babe.",
    "She added clouds on purpose at this temp. It's called atmosphere. Look it up bitch.",
    "She's the friend who cancels half the plans but makes the other half fucking incredible girl.",
    'She threw this night together in five minutes. Perfect temp cute sky. Somehow it works. Fucking annoying honestly babe.',
    "She pressed random on the sky and honestly some of it slaps. We'll allow it bitch.",
    'She really brought half a sky and all of the audacity at the perfect temp babe.',
    "She didn't edit she didn't proofread she just hit send. Mild night cute sky. Flawless. Sick babe.",
    'Flannel on. Get outside. She assembled the sky like IKEA furniture with leftover screws. Somehow it holds babe.',
    "Get your ass out there. The sky's a mess and the temp's perfect. Her best work honestly girl.",
    "Flannel on go. She's being imperfect and it's the hottest shit she's done all week babe.",
  ],
  TemperatureTier.shortsWeather: [
    "Warm partly cloudy and I'm outside in shorts losing my mind. She doesn't need a full sky to end me babe.",
    "Half the sky showed up and it's warm as shit. The half that showed up? Eating girl.",
    "Stars popping in and out. Warm as fuck. She's a slot machine hitting cherries every ten seconds girl.",
    'Warm partly cloudy. She brought half a deck and is still winning every hand. Fuck your full sky babe.',
    "She's a crossword with half the answers filled in and it's warm enough to sit outside and solve the rest girl.",
    'Half the stars half the clouds all the warm. She did the math wrong and it came out perfect girl.',
    "She's fucking not even at full capacity and still bodying every other night this week babe.",
    "Clouds tried to ruin a warm gorgeous night. Failed miserably. She's fucking unstoppable babe.",
    'The clouds are accents tonight not obstacles. Warm as fuck. Get your ass out there babe.',
    "Warm night partly cloudy. She served half a sky and it's still better than most nights' full effort girl.",
    "Warm night partly cloudy. She didn't study didn't practice didn't plan. Still aced it. Get out there bitch.",
    'Warm partly cloudy. She arranged the sky like someone parallel parking by feel. Nailed it anyway. Go outside babe.',
    'Warm night and the sky keeps revealing stars like a slow strip tease. Patience rewarded girl.',
    'She left gaps in the clouds like windows and every window has a view. Warm as fuck. Go look babe.',
    "Stars popping through the clouds in shorts weather. She's a sparkler at a barbecue girl.",
    "Sky's a ten temp's a ten clouds are a four. Averages out to iconic girl.",
    "Stars winking through the clouds on a warm night like she's flirting. She is. Flirt back babe.",
    "Warm partly cloudy night. The clouds are backup dancers and the stars are the main act. Choreography's tight girl.",
    'Warm partly cloudy and the stars between those clouds hit like finding cash in old jeans. Every time. Get out there babe.',
    "She scattered stars through the clouds like confetti at her own party. Warm night. You're invited babe.",
  ],
  TemperatureTier.scorcher: [
    "Sun left hours ago and it's still hell out here. Blame the clouds girl.",
    "Nighttime said I'll handle it. Nighttime fucking lied babe.",
    'Hot as fuck and the clouds are trapping every degree like a savings account for suffering babe.',
    "She can't decide on the sky but she sure decided on the heat babe.",
    "Ma'am it's the damn night shift. Clock out already girl.",
    'Darkness did nothing for the temp. Fucking useless. Drink water girl.',
    "Scorching and partly cloudy. She put a lid on the sky like a pot nobody's watching. Everything's boiling over girl.",
    'She brought the heat AND the clouds. A BOGO nobody wanted bitch.',
    'Holy shit. She said bedtime? No. Heatstroke? Maybe. Hydrate babe.',
    "She's running hot tonight and the clouds are sealing it in like Tupperware. Ice water immediately babe.",
    "The clouds are insulation tonight. Stars can't get out. Heat can't get out. We can't get out girl.",
    'Clouds showed up to hold heat not provide shade. Snakes honestly babe.',
    "She's got commitment issues with the sky but not with the heat girl.",
    'She laid clouds over the sky like cling wrap on leftovers. Sealing in every degree. Go find a hose babe.',
    "She's running the sky like a toll booth tonight. Stars cost sweat. Heat is free. Hydrate girl.",
    "Hot partly cloudy and every star that peeks through looks like it's struggling too. Solidarity girl.",
    'The sky is half clouds half hell and fully committed to our suffering babe.',
    'She wrapped the clouds around us like a hot car with the windows up. Stars tinted out. Hydrate girl.',
    'Hot as fuck and the clouds are just sitting there hoarding heat. Freeloading bitches babe.',
    'Scorching partly cloudy night. The sky looks like a pizza box lid. Greasy warm and holding everything in. Drink water girl.',
  ],
};
