import '../../../../features/weather/domain/entities/temperature_tier.dart';

const partlyCloudyExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Partly cloudy single digits. Can't commit and it's cold as fuck babe. Stay warm.",
    "Sun peeking through like she's helping. Bitch you are a lamp.",
    'Single digits partly cloudy. She packed half a suitcase and left for Antarctica. Girl commit to something.',
    'Clouds and sun sharing the sky, neither doing shit for warmth. Step up girls.',
    "Fucking freezing. Sky's indecisive and the temp chose violence. Great. Love that.",
    'Partly cloudy and cold as fuck. She gave us clouds AND cold AND sun AND nothing. The full useless buffet babe.',
    'Partly cloudy single digits. She brought clouds and sun and forgot the fucking warmth. Classic her.',
    'Partly cloudy cold as fuck. She showed up half-dressed to a funeral. The funeral is us. Layers on girl.',
    "Partly cloudy single digits. She can't pick an outfit or a temperature. Failing at both simultaneously babe.",
    "Half sun half clouds full freeze. Sky's confused. We're confused. Everyone's confused babe.",
    'Single digits partly cloudy. She brought a PowerPoint with two slides and neither one has warmth on it girl.',
    'Single digits and the sky is being petty about it. Clouds and sun taking turns doing nothing girl.',
    'Partly cloudy single digits. The sky is going through it and so the fuck are we babe.',
  ],
  TemperatureTier.freezing: [
    "Cold as fuck but at least we're getting some sun through the clouds. Not fully gray. Take the win babe.",
    "It's giving Black Swan. Dramatic sky but at least there's light peeking through. Coat on girl.",
    "Partly cloudy below freezing. Some sun some clouds. At least she's giving us variety. Bundle up babe.",
    "She's giving Clueless. A little confused but still cute as shit. Cher would layer babe.",
    "Partly cloudy and freezing but hey. Every time the sun peeks out it's a whole damn gift. Coat on girl.",
    'Below freezing partly cloudy. At least the sky has some personality. Full gray would be worse. Bundle up girl.',
    "Cold as fuck but sun keeps poking through the clouds like hey I'm still here. Love that energy. Coat on babe.",
    "Partly cloudy and freezing. She's giving us a light show between the clouds. Free entertainment honestly. Layer up girl.",
    "Below freezing but at least the clouds aren't hogging the whole sky. We see you sun. Coat on babe.",
    'Partly cloudy cold as shit. But those little patches of blue sky are doing everything for my mood. Bundle up girl.',
    "Freezing and partly cloudy. She could be full overcast but she's letting light through. Small mercies babe.",
    "Cold as fuck but the sun keeps sneaking past the clouds for us. She's fighting for it. Respect. Coat on girl.",
    "Partly cloudy below freezing. At least we get moments of sunshine. That's more than January deserved honestly babe.",
    "Below freezing but the sky's got texture. Sun and clouds doing a little dance. Beats flat gray every time girl.",
    'Partly cloudy and freezing. Every sunbreak is a goddamn blessing right now. Appreciate the moments. Coat on babe.',
    "Cold as fuck partly cloudy. But when that sun hits between the clouds it's honestly beautiful. Layer up girl.",
    "She's mixing sun and clouds below freezing. At least she's trying to give us something. Coat on babe.",
    'Partly cloudy and freezing. Not perfect but not hopeless. The sun is in there fighting. Coat on girl.',
    "Below freezing partly cloudy. Sun peeking through like she hasn't given up on us. Neither should you. Bundle up babe.",
    "Partly cloudy cold as fuck. But at least the sky isn't a concrete ceiling. There's blue up there. Coat on girl.",
    "Freezing but partly cloudy. She could've gone full gray but she left the light on. Appreciate that shit babe.",
    "Below freezing partly cloudy. The sun breaks through and honestly it hits different when it's this cold. Magical shit girl.",
    "Partly cloudy and freezing. At least it's not bleak. There's dimension up there. Coat on and go babe.",
    "She's giving us sun between the clouds at freezing temps. Every ray is earned and beautiful honestly babe.",
  ],
  TemperatureTier.jacketWeather: [
    'Partly cloudy and fine. She cleaned up fucking nice. Sunnies on babe.',
    "Sun and clouds doing a little dance. Cool as fuck. She's in her choreography era babe.",
    'Clouds and sun coexisting at a nice temp. If only people could figure this shit out girl.',
    "She's partly cloudy and cool and I just want to walk somewhere with a coffee. She planned this shit babe.",
    "She's mixing sun and clouds like a DJ who actually reads the fucking room babe.",
    'Clouds and sun taking turns at a nice fucking temp. Like a relay race but both teams are winners girl.',
    "Partly cloudy and a little chilly. She's being fucking indecisive in the cutest way possible. Jacket on go girl.",
    'Partly cloudy and chilly. Textbook pretty day. She read the fucking assignment for once babe.',
    'She handed me sun and shade like a waiter with two fucking plates. Both for me. Both perfect babe.',
    "She's being so chill I forgot she tried to kill us last week. Partly cloudy and cool babe.",
    'Partly cloudy jacket weather. Get outside. Jacket on. She finally got her shit together girl.',
  ],
  TemperatureTier.flannelWeather: [
    'Partly cloudy nice as fuck. Clouds are a whole aesthetic. Get outside girl.',
    'Partly cloudy and perfect. Zero notes zero complaints. Not one. Just go babe.',
    "Clouds are giving texture to a perfect day. She's an artist and today is the fucking canvas babe.",
    "Partly cloudy at this temp. She's not overachieving she's not underperforming. She's hitting the fucking sweet spot babe.",
    "Partly cloudy and mild and I think I just fell in fucking love. It's mutual girl.",
    "Partly cloudy cool temps and I'm gone. Deceased. She killed me with perfection girl.",
    "Partly cloudy perfect temps. I'm obsessed and I'm loud about it. Get your ass outside babe.",
    "Partly cloudy perfect temps. She said too much sun is basic. She's fucking right babe.",
    "Partly cloudy mild temps. Put your phone down and go be in her. I'm serious girl.",
    "Clouds drifting through a mild day like she's directing a movie. I'd watch it bitch.",
    "Partly cloudy nice as fuck. This is her apology for last week and it's accepted. Fully babe.",
    'Partly cloudy at this temp is objectively the best fucking weather on earth. Fight me girl.',
    'Partly cloudy at this temp hits different. She knows it. I know it. We all know it girl.',
    'Sun and clouds and perfect temps. This weather fucks. I said what I said.',
    'Partly cloudy flannel weather. Hoodie on boots on get the fuck out there babe.',
    'Flannel and sunnies. She served clouds for character and warmth for free. Get outside bitch.',
  ],
  TemperatureTier.shortsWeather: [
    'Partly cloudy nice as fuck. Clouds giving free shade. So thoughtful. Shorts time babe.',
    'Partly cloudy shorts weather. Fuck your plans. New plans. Outside. Now. Go.',
    "It's nice as fuck outside. Like offensively nice. Shorts on babe.",
    "She's warm with built-in shade. She invented a feature. Shorts on immediately girl.",
    'Partly cloudy and gorgeous. Sky is delivering. Go accept her gift babe.',
    "Sun when you want it shade when you need it. She's fucking psychic girl.",
    'The kind of day you call in sick for. Do it. No regrets babe.',
    'Partly cloudy shorts weather. Shade built in. Sunscreen optional. Get the fuck outside babe.',
    'She gave you sun and shade at shorts weather. The fuck more do you want girl.',
    'Partly cloudy warm as hell. Shorts on sunnies on bullshit off. Go babe.',
    "She's warm and partly cloudy and you're still inside? Go. Like right now girl.",
    'Partly cloudy and perfect. Not asking. Telling. Shorts on. Outside. Now bitch.',
    'Built-in shade at perfect temps. She did the math for you. Shorts on go girl.',
  ],
  TemperatureTier.scorcher: [
    'Partly cloudy and scorching. Thank fuck for those clouds. SPF babe.',
    'Every time a cloud shows up I whisper thank you and every time it leaves I whisper you bitch. Emotional roller coaster girl.',
    'Hot as fuck. Clouds giving shade breaks like little apologies. Not enough but noted babe.',
    'Hot as shit partly cloudy. The clouds are the only witnesses to this crime and they keep leaving. Unreliable as fuck babe.',
    'Partly cloudy and hot as shit. The clouds are doing more for us than the sun ever has girl.',
    "Hot as fuck with intermittent mercy. She's doling out shade like treats. We'll be good girl I promise.",
    "Hot as fuck partly cloudy. I'm out here following cloud shadows like a stray cat follows food babe.",
    "Hot as fuck with cloud relief. She's playing good cop bad cop with herself girl.",
    "Partly cloudy scorcher. The sun keeps peeking around clouds like I'm still here. Girl we know. We're boiling.",
    "Hot as fuck out here. Every time a cloud passes it's a religious experience. Hallelujah babe.",
    'Hot as fuck. Cloud passes overhead and I moan. Like audibly. In public. She reduced me to this babe.',
    'Partly cloudy scorcher. The clouds are doing their best but their best is like holding a napkin over a bonfire girl.',
    "Partly cloudy and scorching. She's playing peekaboo with the sun and every peek costs us another degree of sanity babe.",
    "She's so fucking hot the clouds are the only thing keeping us alive. Guardian angel energy babe.",
    'She showed up confused and hot. Not hot temp hot. Well also hot temp. Both kinds of hot bitch.',
    "Hot as shit partly cloudy. Every cloud shadow is a tiny oasis and I'm a fucking desert nomad stumbling between them babe.",
    "Scorching and partly cloudy. She's assaulting us with shade breaks. How generous.",
    'Partly cloudy scorcher. She keeps giving us hope then taking it away. Toxic as fuck. But the shade is nice girl.',
    "Scorching with cloud breaks. She's torturing us on a schedule. Organized sadist girl.",
    "Partly cloudy and scorching. I befriended a cloud. Named it. It left. Heartbroken. Another one came. I'm over it. Moving on babe.",
    'Partly cloudy and melting. The shade hits like a glass of water in hell. Brief but holy babe.',
    'Scorching partly cloudy. The clouds are pulling overtime and they deserve a raise babe.',
    "Hot as fuck partly cloudy. I'm standing in a cloud shadow refusing to move. People are walking around me. I'm a monument now girl.",
    "Partly cloudy and scorching. She's flash-frying us then giving shade breaks. Tempura energy. We're the shrimp babe.",
  ],
};

const partlyCloudyExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She can't make up her mind and it's cold as fuck. Indecisive AND hostile.",
    'Half the sky looks incredible and the other half is having a crisis. In single digits. Great combo girl.',
    'Clouds and stars fighting for custody of the sky tonight. The cold won. We all lost babe.',
    "She can't commit to shit. Not clouds not stars not livable temps. Seek therapy girl.",
    'Fifty fifty on the sky all in on the cold. Fucking brutal babe.',
    "Stars playing now you see me now you don't in single digits. Nobody's entertained girl.",
    "She split the sky like she's dividing assets in a divorce. Cold got everything good girl.",
    'Stars keep popping out then the clouds eat them. Like girl that was my star. I was watching that babe.',
    "Half clouds half stars all cold. She's having an identity crisis in single digits babe.",
    "She can't pick a sky and the cold doesn't care. We're dying under a PowerPoint transition girl.",
    "Sky's going back and forth like a toxic ex. Stars clouds stars clouds. Committed to the cold though babe.",
    'Clouds keep swallowing the stars and spitting them back out. Make up your damn mind girl.',
  ],
  TemperatureTier.freezing: [
    "Sky's arguing with itself. We're all losing babe.",
    'Half a sky and full suffering? Budget ran out girl.',
    "Sky can't commit but the cold sure can. Bundle up babe.",
    'Fifty percent sky. Hundred percent suffering. The ratio? Fucked girl.',
    'Zero effort sky and wants applause? For what babe.',
    "Stars winking through clouds like they're flirting. Ma'am it's below freezing girl.",
    "Stars coming and going like they're checking if it's safe. It's not babe.",
    "She can't commit to shit except making us miserable. Noted girl.",
    'Mid-breakdown sky and mid-frostbite us. Therapy for everyone honestly babe.',
    'Half the stars missing. Cold is the primary suspect girl.',
    'Girl pick a sky and stay. Stars in stars out. Make up your mind babe.',
    'Management material honestly. Two problems zero solutions girl.',
  ],
  TemperatureTier.jacketWeather: [
    "Half the stars showed up. The other half said fuck this too cold. Can't blame them babe.",
    "She can't decide shit tonight. At least the temp isn't trash babe.",
    "She threw some stars up there and said good enough. Honestly we'll fucking take it.",
    "She's a fucking beautiful disaster tonight and we're here for it babe.",
    'She fucking nailed the temp and phoned in the sky. Bare minimum queen.',
    'She started something up there and forgot where she was going with it. Relatable honestly bitch.',
    "She's the fucking group project member who shows up with half the slides girl.",
    'Clouds keep eating the stars I was looking at. Rude as hell. Find your own constellations girl.',
    'She brought sixty percent of the stars and a hundred percent of the vibes bitch.',
    "She's half clouds half stars and fully not sorry about it. Layer up and get outside babe.",
    "She's flashing stars then hiding them like a dealer at a poker table. Cool night girl.",
    "The sky is rearranging itself every five minutes. She can't sit still. Neither can I. Jacket on babe.",
    "Jacket on get outside. She's messy but she's pretty and the temp is right girl.",
    "Jacket on go. Half the sky showed up and that's more than enough. Get your ass out there babe.",
    "Get outside. She's doing her best and honestly it's working. Jacket on babe.",
  ],
  TemperatureTier.flannelWeather: [
    "She's half-assing the sky and fucking nailing the temp. We'll take it babe.",
    "Sky can't decide but the temp said I got this. Thank fuck girl.",
    "Half the sky's missing. Don't care. It's nice as fuck out babe.",
    "She's imperfect and unbothered. That's the whole fucking vibe babe.",
    'Half the stars and perfect vibes. Math checks the fuck out girl.',
    "She mixed clouds and stars like a bartender who doesn't measure. It's strong and it works babe.",
    "She added clouds on purpose. It's called atmosphere. Look it up bitch.",
    "She's the friend who cancels half the plans but makes the other half fucking incredible girl.",
    'She threw this night together in five minutes and somehow it works. Fucking annoying honestly babe.',
    "She pressed random on the sky and honestly some of it slaps. We'll allow it bitch.",
    'She really brought half a sky and all of the audacity babe.',
    "She didn't edit she didn't proofread she just hit send. And it's flawless. Sick babe.",
    "Flannel on. Get outside. She's half-assing the sky and fully nailing the temp babe.",
    "Get your ass out there. The sky's a mess and the temp's perfect. Her best work honestly girl.",
    "Flannel on go. She's being imperfect and it's the hottest shit she's done all week babe.",
  ],
  TemperatureTier.shortsWeather: [
    "Warm partly cloudy and I'm outside in shorts losing my mind. She doesn't need a full sky to end me babe.",
    "Half the sky showed up and it's warm as shit. The half that showed up? Eating.",
    "Stars popping in and out. Warm as fuck. She's putting on a goddamn show and we have front row girl.",
    "She's incomplete and still outperforming. Fuck your full sky babe.",
    "She's the hot friend with a fucking mysterious side. Intriguing girl.",
    'Half the stars half the clouds all the warm. She did the math wrong and it came out perfect girl.',
    "She's fucking not even at full capacity and still bodying every other night this week babe.",
    "Clouds tried to ruin it. Failed miserably. She's fucking unstoppable babe.",
    'The clouds are accents tonight not obstacles. Warm as fuck. Get your ass out there babe.',
    "Stars and clouds having a dialogue tonight. She's writing the script babe.",
    "She didn't study didn't practice didn't plan. Still aced it. Go off bitch.",
    "She's so fucking pretty tonight I forgot what I was doing. Go outside babe.",
    'Warm night and the sky keeps revealing stars like a slow strip tease. Patience rewarded girl.',
    'She left gaps in the clouds like windows and every window has a view. Warm as fuck. Go look babe.',
    "Stars popping through the clouds in shorts weather. She's a sparkler at a barbecue girl.",
    "Sky's a ten temp's a ten clouds are a four. Averages out to iconic girl.",
    "Stars popping in and out like she's doing a reveal babe.",
    "Clouds adding drama stars adding class. She's got range girl.",
    "Warm partly cloudy and every time a star appears I gasp. Every time. She's got me trained babe.",
    "She mixed warm air and scattered stars and somehow it's everything. Less really is more girl.",
  ],
  TemperatureTier.scorcher: [
    "Sun left hours ago and it's still hell out here. Blame the clouds girl.",
    "Nighttime said I'll handle it. Nighttime fucking lied babe.",
    'Hot as fuck and the clouds are trapping every degree like a savings account for suffering babe.',
    "She can't decide on the sky but she sure decided on the heat babe.",
    "Ma'am it's the damn night shift. Clock out already.",
    'Darkness did nothing for the temp. Fucking useless. Drink water girl.',
    "Scorching and partly cloudy. She's hiding the stars and keeping the heat. Priorities girl.",
    'She brought the heat AND the clouds. A BOGO nobody wanted bitch.',
    'Holy shit. She said bedtime? No. Heatstroke? Maybe. Hydrate babe.',
    "She's fucking running hot tonight and the clouds are just trapping it. Ice water immediately babe.",
    "The clouds are insulation tonight. Stars can't get out. Heat can't get out. We can't get out girl.",
    'Holy shit. Clouds showed up to trap heat not provide shade. Snakes honestly babe.',
    "She's got commitment issues with the sky but not with the heat girl.",
    "She's cooking us with half a blanket of clouds. Enough to trap heat. Not enough to block anything useful babe.",
    "She's holding the heat hostage until further notice girl.",
    "Hot partly cloudy and every star that peeks through looks like it's struggling too. Solidarity girl.",
    'The sky is half clouds half hell and fully committed to our suffering babe.',
    "She's trapping the heat under clouds like a greenhouse. We're the tomatoes girl.",
    "At least the heat's consistent babe. Clouds? Do better.",
    'She said aesthetic? Half-assed. Suffering? Full send girl.',
  ],
};
