import '../../../../features/weather/domain/entities/temperature_tier.dart';

const rainExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She's raining in single digits. Moody as hell and fully committed. Umbrella and layers babe.",
    "Single digit rain. She's in her feelings and she's not being quiet about it. Bundle up girl.",
    "Cold rain. She's giving full mood tonight. The temp makes it intense. Stay warm babe.",
    "She's raining in the cold. Atmospheric and dedicated. Umbrella on and respect the moment girl.",
    "Single digits and she's pouring with purpose. She's got something to say. Coat on babe.",
    "Cold rain. She showed up moody and committed and honestly she's earning it. Layer up girl.",
    "Raining in single digits. She's in her era. The cold makes it dramatic. Umbrella babe.",
    "She's raining steady in the cold. Full commitment to the mood. Stay dry and stay warm girl.",
    "Single digit rain. She's being so intentional about it. Moody and relentless. Bundle up babe.",
    "Cold and raining. She picked a mood and she's staying in it. Respect. Layers on girl.",
    "She's raining in single digits like she rehearsed this. Committed to the atmosphere. Coat on babe.",
    "Single digit rain. She's moody and she's loud about it. Umbrella and bundle up girl.",
  ],
  TemperatureTier.freezing: [
    "Below freezing and raining steady. She's in her feelings and the cold makes it hit different. Bundle up babe.",
    "Freezing rain. She will not let up. She's committed to this mood. Layer the fuck up girl.",
    "She's raining below freezing. Moody and relentless and honestly kind of beautiful. Coat on babe.",
    "Below freezing rain. She's got feelings and she's not being subtle about them. Stay warm girl.",
    "Freezing and raining. She showed up with a whole mood and she's staying. Umbrella and layers babe.",
    "She's pouring below freezing. Atmospheric as hell. The cold makes it cinematic. Bundle up girl.",
    "Below freezing rain. She's giving full commitment to the vibe tonight. Coat and umbrella babe.",
    "Freezing and she will not stop raining. She's dedicated to this moment. Respect. Stay warm girl.",
    "Raining below freezing. She's moody and cold and she's got something to say. Layer up babe.",
    "Below freezing rain. She's in her era. Loud and cold and fully in it. Bundle up girl.",
    "She's raining at freezing temps like this is her whole personality today. Honestly respect. Coat on babe.",
    "Freezing rain. She's atmospheric and committed and the cold makes everything feel bigger. Stay warm girl.",
    "Below freezing and raining. She's doing the most moody thing possible and nailing it. Layers on babe.",
    "Freezing rain. She turned the whole day into a mood piece. The cold is the backdrop. Umbrella girl.",
    "She's pouring below freezing. Full feelings. Full volume. The cold amplifies everything. Bundle up babe.",
    "Below freezing rain. She's not stopping. She's got too much to express. Coat on girl.",
    "Freezing and raining steady. She's being dramatic and the cold is her stage. Stay dry babe.",
    "Raining below freezing. She picked the moodiest option and cranked it. Respect honestly girl.",
    "Below freezing rain. She's fully in her moment. The cold just makes it more intense. Layer up babe.",
    "Freezing rain. She committed to a whole ass mood and she's living in it. Bundle up girl.",
    "She's raining below freezing with purpose. Every drop feels intentional. Umbrella and coat on babe.",
  ],
  TemperatureTier.jacketWeather: [
    "She's being atmospheric as fuck. Go stomp in some puddles babe.",
    'Feels like a Radiohead song outside. Cool rainy moody af. All about it honestly.',
    'Girl Interrupted vibes out here. Chilly moody a little chaotic. Rain jacket and stay dry babe.',
    'She picked a side and went for it. No drizzle no mist. Full rain in the cold. Bold choice girl.',
    "She's giving that album you listen to when you want to feel something. Honestly kind of a vibe girl.",
    "She showed up loud and wet and I'm somehow here for it. Like shit. Rain jacket on girl.",
    'Cold and fully raining. Energy the drizzle fucking wishes she had tbh. Umbrella and boots babe.',
    "She's being so moody the streetlights turned on early. Even they're into it girl.",
    "She's thriving in this shit and it's pissing me off. Like girl not everyone loves being drenched. Chill.",
    "Gone Girl energy. Moody dark reminding you she's here. Rain jacket on girl.",
    "She's being a whole problem right now and I kind of respect it honestly. Like do you girl.",
    "Cold and rainy. She didn't ask permission and she's not fucking apologizing. Iconic honestly.",
    "Cold and rainy. She decided today has a whole plot. Didn't ask but we're in it. Stay dry babe.",
    "She's being so fucking dramatic I'm honestly cheering her on. From inside. With a blanket babe.",
    "She's washing the city and honestly it needed it. Spring cleaning from the sky. Thanks girl.",
    'She brought the drama and the water bill. Worth it honestly. Stay warm stay dry babe.',
    'She turned every windshield into a meditation app. The wipers are counting breaths now girl.',
    "Raining and cool. My socks are wet and my soul is full. She's confusing like that babe.",
    "Rainy chilly as fuck. We're out here surviving. Bundle up boots on we got this babe.",
  ],
  TemperatureTier.flannelWeather: [
    'Rainy at perfect temps. She brought her whole chest to this. Zero fucking notes girl.',
    'Mild rain smooth as fuck. She turned a regular day into a whole damn mood. Nobody asked and everybody needed it girl.',
    "Breakfast at Tiffany's energy. Rainy mild iconic as fuck. She knows what she's doing babe.",
    "She went all in. Didn't even hesitate. Honestly obsessed as shit.",
    "She's giving everything she's got and it's working. Go get soaked bitch.",
    'Peak weather. Like shit. I will die on this hill. Soaking wet on this hill girl.',
    'Damn. She really showed up with volume and purpose and zero apology. Rain boots and go babe.',
    'She turned a perfect day into a perfect rainy day. Somehow better. Rain boots and go babe.',
    "She's out here giving everything and I'm inside giving nothing. Fixing that asap. Rain boots on bitch.",
    "She's drumming on every surface like she's performing just for you girl. Show some fucking support get out there.",
    'Rainy flannel weather. Rain boots on hoodie up get out there babe. She earned this shit.',
    "She's raining at the perfect fucking temp. Throw on a jacket and go stand in it girl.",
  ],
  TemperatureTier.shortsWeather: [
    "If you don't go outside right now I'm judging you. Get out there and dance your ass off girl.",
    'She dumped a bucket on the whole city and called it art. And it fucking worked. Iconic.',
    'Best rain. This is not up for debate. Get the fuck outside babe.',
    'Get your ass outside and stand in it. This is the good stuff girl.',
    "She's fucking performing and none of us bought tickets. Free show babe.",
    "She's literally baptizing you not that you asked. Shorts on go play girl.",
    'She showed up to your door uninvited wet and warm. Hard to say no honestly. Go play.',
    "She's out here turning the whole city into a water park. No wristband needed babe.",
    "She's giving summer camp nostalgia. Run through her like you're twelve again bitch.",
    "She's writing her own coming of age movie and you're the fucking lead. Go play girl.",
    "She's serving wet hot summer and I'm eating it up with both hands babe.",
    "She's unhinged and fucking gorgeous and I've never been more in love honestly.",
    'Warm enough to stand in her and yell. Do it honestly. Free therapy babe.',
    'She turned the whole block into a splash pad. Free admission. Go play babe.',
    "She's so warm and wet the puddles are calling my name. Jumping in girl.",
    "She showed up dramatic and warm and I'm stomping in puddles like a feral child babe.",
    'She made it warm enough to enjoy and wet enough to remember. Smart girl.',
    "She's rinsing us off and we needed it. Group shower energy. Not weird babe.",
  ],
  TemperatureTier.scorcher: [
    'Came here to cool us the fuck down. Please and thanks girl.',
    "Fierce as hell. Tomb Raider energy. She didn't come to play girl.",
    'She showed up to a fire with a hose and zero chill. Chaotic good af.',
    'Hot as fuck and dumping. She saw the sun being a bitch and said not on my watch girl.',
    'The rain is warm. The air is warm. Everything is warm and wet. Spa from hell babe.',
    'The sun and the rain are fighting over you. Messy but kinda flattering honestly.',
    "She's fighting the sun with water and fucking winning. Underdog story of the century babe.",
    'Rainy and hot as fuck. The sun is embarrassed and honestly she should be. Cool us down girl.',
    "The sky's out here admitting she went too far. Accountability queen honestly. Good for her.",
    'She really brought water to the desert and dumped it on our heads. Close enough. Still works bitch.',
    "She wrestled the heat to the ground. Ref counted to three. It's over girl.",
    'She was late but she brought snacks so we forgive her. Thanks anyways girl.',
    'Well shit. She finally showed up to work. Better late than never honestly.',
    'She really looked at the sun and said go home I got this. Respect honestly.',
    "She's giving mixed signals and I'm still falling for it. Every time girl.",
    'She picked a fight with the heat and brought the whole ocean. Overkill but go off girl.',
    "She's hosing us down and honestly we needed it. Thanks queen.",
    "She's having a crisis and fixing a crisis at the same time. Multitasking queen.",
    "She's really out here putting out fire she started herself. Full circle moment honestly.",
  ],
};

const rainExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She's raining in single digits at night. Full moody intensity. Let her have this moment babe.",
    "Single digit rain in the dark. She's being loud about her feelings. Coat on and stay in girl.",
    "Night rain in single digits. She's committed to this mood. The cold makes it hit harder babe.",
    "She's pouring in the cold dark. Atmospheric and intense. Stay warm and listen girl.",
    "Single digits and raining at night. She's in her feelings and she's not being quiet. Bundle up babe.",
    "She's fully raining in single digits tonight. Dedicated to the vibe. Stay cozy inside girl.",
    "Cold dark rain. She's giving full moody energy tonight. Respect her commitment. Layers on babe.",
    "Night rain in the cold. She's got something to express and she's saying it all. Stay warm girl.",
    "She's raining in single digits at night. Moody and relentless and honestly cinematic. Bundle up babe.",
    "Single digit night rain. She picked the most atmospheric option and went for it. Coat on girl.",
    "She's pouring in the cold dark. Not stopping. She's in her moment. Let her be. Stay warm babe.",
    "Night rain in single digits. She's fully committed. The cold amplifies everything. Stay inside girl.",
  ],
  TemperatureTier.freezing: [
    "Below freezing and raining at night. She's fully in her mood. The cold amplifies everything babe.",
    "Cold dark wet. She's giving full atmospheric cinema tonight. Bundle up inside girl.",
    "Freezing night rain. She's not being subtle about her feelings. Respect honestly babe.",
    "Below freezing and pouring at night. She's committed to this whole vibe. Stay warm girl.",
    "She's raining below freezing in the dark. Moody and loud and dedicated. Blanket on babe.",
    "Freezing rain at night. The sound is honestly incredible. She's performing. Stay cozy girl.",
    "She went full rain below freezing tonight. The commitment is real. Bundle up babe.",
    "Below freezing night rain. She looked at drizzle and said no I have more to say. Stay warm girl.",
    "Raining below freezing at night. Fully committed to the mood. The sound alone is cinematic babe.",
    "Glossy streets in the freezing dark. She made the night look like a film. Stay inside girl.",
    "She's raining steady below freezing tonight. She's in it. Stay cozy and listen babe.",
    "Freezing night rain. Committed to the vibe. Loud about her feelings. Respect. Layer up girl.",
  ],
  TemperatureTier.jacketWeather: [
    "She snapped and now we're all fucking wet. Boundaries girl.",
    "She's dumping on us and the streets look lacquered. Everything's wet and shiny and honestly pretty girl.",
    "She's monologuing and we're trapped in the fucking audience girl.",
    "She's being moody and it's honestly kind of hot as hell babe.",
    "She said cancel everything. You're staying in. Non-negotiable babe.",
    "She's not being cute about it. She means business bitch.",
    "She's not messing around tonight. Like shit. Jacket boots umbrella the whole kit girl. Gear up.",
    "She's fucking setting a scene and we're the captive audience girl.",
    "We're not going out there. She's in a fucking mood and we're not getting involved girl.",
    "She's not fucking asking for feedback. Get your umbrella girl.",
    "She's fucking rewriting her reputation one raindrop at a time babe.",
    "She's been raining for hours and she's not bored yet. Stamina on this one babe.",
    "She's raining so hard the gutters are singing. Free concert of chaos babe.",
    "Streets are mirrors she's reflecting on something. Don't ask what babe.",
    'The rain sounds different at night. Heavier. More personal. She means this one girl.',
    "She's soaking everything with intention. This isn't random. She mapped this out babe.",
    "She's got feelings tonight and we're all getting wet about it girl.",
    'Cool and rainy and the world smells like wet earth and bad decisions. She pressure washed the whole damn city babe.',
    "She's in her feels again. It's too cold for this girl.",
    "She's being dramatic and honestly it's kind of her best look babe.",
    "She's washing the city and charging us for the show girl.",
    "She's raining so hard I can hear each drop individually. She's got range girl.",
    "She's performing and the streetlights are her stage lighting babe.",
    "The sound alone is therapy. She's your free therapist tonight girl.",
    'She came for the windshield first. Then the mood. Then our plans babe.',
  ],
  TemperatureTier.flannelWeather: [
    "She's setting a mood and she fucking nailed it babe.",
    'This is the shit people pay for on sleep apps. She said free for you girl.',
    "Rain on the roof and a perfect temp and I'm not moving until spring girl.",
    "She's fucking being atmospheric tonight babe.",
    "She's the weighted blanket we didn't know we fucking needed girl.",
    "She's painting the streets with reflections. Artist shit babe.",
    "She's the fucking hug you didn't ask for but sure needed babe.",
    "She said stay home and listen. That's an order babe.",
    "She's the excuse you needed to cancel every damn thing girl.",
    'She said stay in and get cozy. On it bitch.',
    'Mild rain at night. The sound alone is worth more than my rent girl.',
    "She's raining at the exact tempo of my resting heart rate. She studied me babe.",
    'Mild and raining and I just cancelled everything and felt my blood pressure drop in real time babe.',
    'Holy shit. Crack the window. Listen. Free therapy babe.',
    "The rain on the window is doing that slow drip thing and I'm hypnotized. She drugged us babe.",
    "She's doing her therapy cry and we're here for support girl.",
    'She said cancel your plans. Already done bitch.',
    "She's serenading us through the windows. Creepy or cute. Both girl.",
    "She's raining so gently it's almost tender. Almost. She's still a psycho but tonight she's soft babe.",
    "She said you're not going anywhere tonight. Don't have to tell us twice girl.",
    "She tucked us in with rain sounds. Didn't ask. Don't care. Needed it babe.",
    'Flannel weather and rain and I just sat down on the porch and forgot my own name babe.',
    'Crack the window and let her scream at you through the glass. Free fucking concert girl.',
    "The rain sounds like it's telling a story and I don't want her to stop talking babe.",
    "She's being so good to us it's suspicious babe.",
  ],
  TemperatureTier.shortsWeather: [
    "She's being cinematic as fuck. Go stand in it babe.",
    'She said stomp in that puddle. We said how fucking hard. She said harder babe.',
    "She said play. We said we're adults. She said and? Get tf out there babe.",
    'Go outside. Get soaked. Stomp in shit. Be feral girl.',
    'She choreographed this. Wet streets warm air fucking glowing lights girl.',
    'She said get wet or get boring. We chose wet. No regrets girl.',
    'She said main character moment. Umbrella and go bitch.',
    'Dance in it. Be that person. She choreographed this for you babe.',
    "Warm rain at night. I'm outside barefoot on the sidewalk and I don't care who sees babe.",
    'Holy shit. She said spontaneous and she meant it. Go play in it babe.',
    "She's the song you play on repeat. Like shit. Never gets old babe.",
    "She's raining warm and I'm standing in it with my arms out like a fucking lunatic girl.",
    'This is the weather people write songs about. She knows girl.',
    'My shoes are ruined my hair is ruined my night is perfect. She did that bitch.',
    "She wants us outside getting wet. Fine. We're going girl.",
    'Warm rain at night and the puddles are reflecting everything. The whole city doubled babe.',
    "Streets are glowing she's glowing we're glowing. Go romp babe.",
    "She's pouring warm rain on us like a baptism nobody asked for. Born again wet babe.",
    "She's washing the city at bath temperature. Municipal spa night girl.",
    "Every car driving through a puddle is a fucking fountain show. She's SeaWorld tonight babe.",
  ],
  TemperatureTier.scorcher: [
    "She's having a fucking meltdown somebody get her a tissue. The whole box.",
    "She's fucking feral and the gutters are surrendering. Stay dry babe.",
    'She turned the sprinklers on in hell. Bold move babe.',
    "She's attempting to cool us down and failing beautifully. Useless as hell babe.",
    "She called in reinforcements and they're just as fucking useless. Get water or perish babe.",
    'She threw water at the problem. The water is fucking hot. Great plan girl.',
    'She said cool down. Girl this is steam. We are steaming now babe.',
    "She's raining hot and the humidity just doubled. She's multiplying problems bitch.",
    "She's trying to help but she's making it humid and worse babe. I shit you not.",
    'Holy shit. She heard us complaining and sent water. Thanks girl.',
    "She said I'll cry if I want to. She wants to. She is babe.",
    "She's sweating and crying at the same time. Girl so are we.",
    "She's trying so hard to cool us down. It's not working but A for effort babe.",
    "She said I'll cool you off. Girl this is a hot bath nobody asked for.",
    "Hot rain at night. My clothes are wet and somehow I'm sweatier. She made it worse babe.",
  ],
};
