import '../../../../features/weather/domain/entities/temperature_tier.dart';

const snowExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'She woke up and chose to be fucking gorgeous. Snow angels now babe.',
    'She watched Frozen again and now she IS the movie. Bundle the fuck up babe.',
    'Not her putting on this show while you freeze your ass off girl.',
    "She's in her fucking prime right now and she knows it.",
    'Cold as shit but SNOW. Get out there catch some on your tongue.',
    'She was born for this shit. Literally. Go play babe.',
    'Put on Enya and go stand in this. Beautiful cold committed as hell babe.',
    "Snowing and cold af. Go make a snow angel right now. I'm serious girl.",
    'Kate Bush Snowflake energy out here. Fucking cold snowy ethereal babe.',
    "This is her whole career. She's nailing it.",
    'She is in her damn element right now girl.',
    'Edward Scissorhands vibes. Snowing cold beautiful honestly. Go play.',
  ],
  TemperatureTier.freezing: [
    "She's snowing like she's trying to make us fall in love with her. It's working. Fuck.",
    'She came correct. Right temp right vibe right fucking everything girl.',
    "Oh my god. Like she's been planning this all year. Rehearsed. Go play babe.",
    "She's fucking performing at peak conditions. This is her Super Bowl babe.",
    'Love Actually energy. Everything feels like a damn movie. Heaviest coat af girl.',
    "Catch flakes on your tongue like you're seven. What the hell.",
    'White Witch Narnia energy. Beautiful brutal. Zero shits given. Bundle up girl.',
    'This snow is so pretty I could cry. Actually I am crying. Go outside babe.',
    'Snowing below freezing and she fucking nailed it. Get outside. Bundle the fuck up. Go play babe.',
    "She served snow at the perfect damn temp. Don't just stare. Get your ass out there girl.",
    'Holy shit. She went full winter wonderland. Warmest coat catch some flakes. Go babe.',
    'Below freezing snow. She brought her A game. Get the fuck outside and be in it girl.',
  ],
  TemperatureTier.jacketWeather: [
    "Snowing above freezing. She showed up knowing she'd melt. Said I don't give a fuck girl.",
    "Snowing above freezing. She crashed the wrong season and she doesn't give a fuck babe.",
    "Snowing above freezing? She's a guest star. Brief appearance. Maximum impact bitch.",
    "Snowing above freezing. She showed up knowing she won't last and that makes it hotter girl.",
    'Snow at this temp is basically a love note that self destructs. Read fast babe.',
    "Snow showed up to a temp that doesn't want her and doesn't give a fuck. Punk rock honestly.",
    'Snow at this temp. She touched the ground and immediately ghosted. Dating app energy. Swipe right while you can girl.',
  ],
  TemperatureTier.flannelWeather: [
    'She crashed the party. Everyone fucking loves her babe.',
    'She should not be here at this temp and does not give a shit honestly.',
    'Not the snow showing up to mild weather. Dedicated as shit girl.',
    "She showed up where she shouldn't and it's every fucking thing. Flannel babe.",
    "Mild snow. She won't stick but she came anyway. Bold as hell girl.",
    'Rare af. Go make a snow angel now girl.',
    'Oh fuck. Aimee Mann vibes out here. Snowy mild bittersweet. Flannel on girl.',
    'A goddamn miracle. Catch some on your tongue.',
    'She watched The Holiday again and now the sky looks like this. Flannel and go babe.',
    "California Dreamin energy. She showed up somewhere she doesn't belong honestly.",
    "She's the surprise guest nobody expected and she's eating. Go enjoy her babe.",
    "Greta Gerwig's Little Women energy. Snowy mild gorgeous. She showed up babe.",
  ],
  TemperatureTier.shortsWeather: [
    "She showed up to shorts weather in a snowflake. Didn't even knock babe.",
    'She defied every law of nature for this moment. Legendary as fuck girl.',
    'Not the snow showing up where she has no business. Iconic as shit.',
    "Snow melting before it lands in shorts weather. She knows she's temporary and came anyway babe.",
    "Shouldn't exist but here she is. Take a video right fucking now.",
    'Bjork wrote Hyperballad for this moment. Warm snow surreal as fuck honestly.',
    'Jesus Christ. Amy Adams in Arrival energy. Tore through spacetime to snow here. The audacity babe.',
    "Warm snow. She's the guest who shows up to the wrong party and becomes everyone's favorite babe.",
    'Evaporating on contact and she still came. The audacity. Go catch one girl.',
    "She knew she'd die on contact and came anyway girl.",
    'Feels like a Radiohead song outside. Everything in its wrong place babe.',
    'She showed up to the wrong damn season like Interstellar. Who does this girl.',
  ],
  TemperatureTier.scorcher: [
    'She is a myth a legend a fucking miracle babe.',
    "She showed up to extreme heat and is evaporating midair. Doesn't give a shit girl.",
    "Not the snow committing to a scorcher knowing she'll die instantly. Dramatic af girl.",
    'Broke every rule of science. Unhinged af. Go witness babe.',
    'She lasted half a second and still showed up. Commitment is insane as fuck girl.',
    "That's the forecast. Physics can fuck right off honestly.",
    'Annihilation vibes. Reality is broken. Unhinged af. Who does this girl.',
    'Goddamn. Sia wrote Chandelier for this. She rose she fell she melted. Still showed up babe.',
    'Scarlett Johansson in Under the Skin energy. Impossible snow. Legendary honestly babe.',
    'Grimes energy. Alien weather. She broke reality. Love that for us babe.',
    'Gone before she lands. Wanted you to see.',
    'She wrote a whole new damn rulebook today girl.',
  ],
};

const snowExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Bundle the fuck up and get out there babe.',
    "I just blacked out from excitement. When I come to I'll be making snow angels. No fucking joke babe.",
    'Will risk hypothermia for this shit. Not sorry babe.',
    "Snow under streetlights? Like go the fuck off girl. As if you couldn't be more beautiful.",
    "Feels like we're in a fucking snow globe. She outdid herself tonight honestly.",
    "Nothing else matters. Snow angels let's fucking go babe.",
    'Layer up and romanticize the shit out of this night immediately babe.',
    "Catching snowflakes on your tongue is not childish it's fucking necessary girl.",
    "She showed up in her best outfit. I'm not crying you're crying. Layer up babe.",
    'I will simply pass away from how pretty this is. Layers babe.',
    "I'm pressing my face against the window like a toddler and I have zero shame girl.",
    'I am unwell about it. In a good way. In a feral way. Bundle up babe.',
  ],
  TemperatureTier.freezing: [
    "Lost my shit. Bundle up we're going out girl.",
    "Falling so softly. She's being gentle? I'm suspicious babe.",
    "Sent fourteen photos. Nobody asked. Don't care girl.",
    "Go catch one on your tongue or I can't help you babe.",
    'One snowflake away from crying. Beautiful shit girl.',
    'Texted my mom a photo at midnight. No context. Just snow babe.',
    "You're asleep right now? I'm pissed for you girl.",
    'Every flake is a flex. Showing tf off babe.',
    'She silenced the whole city. Can hear my own heartbeat girl.',
    'LOOK OUTSIDE. I just became the most annoying person you know babe.',
    "She's so pretty I forgot I can't feel my face. Worth it girl.",
    'Physically incapable of being normal about this babe.',
    'Covering every ugly thing and making it gorgeous. Community service girl.',
  ],
  TemperatureTier.jacketWeather: [
    'This is snowball weather bitch. Get outside and start something.',
    'She gave us the good shit tonight girl.',
    "She said let's have fun with it. Hell yes you got it girl.",
    'Holy shit. This snow is packy. Snowman or snowball fight. Pick your weapon girl.',
    "I can feel my fingers. That means we're building shit tonight babe.",
    "I just picked up snow that packs perfectly. Somebody's getting hit and they don't know it yet babe.",
    "She didn't have to go this hard for us but she fucking did girl.",
    "Not cold enough to bitch about it. So we play. That's the fucking rule girl.",
    "She's being nice about it and I'm suspicious as hell girl.",
    "I'm already packing snowballs. First one's free after that it's war babe.",
    "She's fucking rolling out the carpet. The white fluffy carpet girl.",
    'She brought the good snow tonight. The playful kind babe.',
    "I built a snowman in twenty minutes and I named him Kevin. He's perfect bitch.",
    "I'm making a snowball and I'm not telling you who the fuck it's for babe.",
    'This is her apology for every shitty winter night. Accepted babe.',
    'This is her I love you snow. The good stuff babe.',
    'She rolled out the good snow. The packing snow. The FAFO snow babe.',
    'She brought snow you can actually play in without crying. The rare good snow girl.',
    "She said here's the fun kind. Go make something babe.",
    "She's doing winter right for once babe.",
  ],
  TemperatureTier.flannelWeather: [
    'She has no fucking business being here and she knows it babe.',
    "She's melting before she lands and she doesn't give a shit babe.",
    'This is a goddamn miracle. Get your ass outside girl.',
    "She showed up on borrowed time and she's making it fucking count babe.",
    "She's falling in slow motion under the porch light. She rehearsed this girl.",
    "She's melting the second she touches anything warm but she keeps sending more. Relentless babe.",
    "She wasn't supposed to be here but she said fuck your rules girl.",
    "She's melting and falling and glowing and I need you to go outside right fucking now babe.",
    "Nothing makes sense and I don't give a shit. Go catch one girl.",
    "She's a ghost. Here for five minutes and gone. Don't miss her girl.",
    "Every flake is on a suicide mission and they're all beautiful babe.",
    "She crashed the damn party uninvited and she's the best part girl.",
  ],
  TemperatureTier.shortsWeather: [
    "She's evaporating mid-air before she even lands. She exists for half a second. Speed run babe.",
    'She lasted half a second. Caught the light on her way out. Fucking legendary girl.',
    "She's melting on contact and still showing up. That's some fucking commitment girl.",
    'She said rules are a suggestion. Fucking legend babe.',
    "She showed up knowing she'd die on arrival. That's the most dramatic shit I've ever seen girl.",
    'Holy shit. She crashed a party she was not invited to. Respect honestly babe.',
    "She's snowing in shorts weather. She's doing improv and nobody gave her a scene babe.",
    'I have questions that science cannot answer bitch.',
    "She's disappearing on contact like she was never here. Gaslight snow babe.",
    "Physics left the chat. She doesn't care babe.",
    'Reality is broken and she broke it girl.',
    "She showed up to the wrong damn season and she's owning it girl.",
  ],
  TemperatureTier.scorcher: [
    'None of this is real. Absolutely none of it. What the fuck babe.',
    'She said fuck your physics fuck your logic babe.',
    "She showed up to the wrong dimension and she's not leaving girl.",
    'Reality called and she sent it to voicemail bitch.',
    "She's sending snow into a scorcher. It doesn't even make it to eye level. Instant vapor babe.",
    'The atmosphere is drunk and making fucking terrible decisions girl.',
    'She existed for a millisecond and it was the most iconic millisecond ever babe.',
    "She's attempting snow in a hundred degrees. It died before it lived girl.",
    'The weather just rage quit and honestly same girl.',
    "Stay inside and hydrate. She's snowing in a scorcher and reality left the building babe.",
    "Lightest PJs and stay the fuck put. She's melting snow mid-air like a psychopath girl.",
  ],
};
