import '../../../../features/weather/domain/entities/temperature_tier.dart';

const sunnyExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Sunny and freezing. The duality of this bitch. Clearly a Gemini.',
    "She showed up to a shit situation and said I'm here. Like girl we needed warmth not moral support.",
    "It's giving Titanic. Gorgeous view but cold as shit. Puffer on babe.",
    "Shining like she's helping. Bitch you are a lamp. Layers girl.",
    "Sun rolled up to single digits and said I'm enough. Narrator: she was not even close to enough. Coat on babe.",
    "She's up there shining like she's doing us a favor. Bitch my eyelashes are frozen. Sit the fuck down.",
    'Sun clocked in did nothing and wants credit. Like damn okay girl.',
  ],
  TemperatureTier.freezing: [
    "Cold as fuck but she showed up anyway. She didn't have to but she did it for us. Coat on and go babe.",
    "Below freezing but sunny. At least she's trying and honestly that's more than most. Bundle up girl.",
    "Freezing but the sun is out and she's gorgeous. Could be worse. Could be gray. Coat on babe.",
    "It's giving Miranda Priestly. Cold as shit but stunning. Heaviest coat babe.",
    "She rolled up to freezing temps and said I'm still here. Respect the fuck out of that honestly. Coat on babe.",
    "Sunny and cold as fuck but at least she showed up. That's more than your ex ever did. Layer up babe.",
    'Below freezing but the sun came through. She chose us today. Coat on and show her some love babe.',
    'Cold as fuck but she showed up anyways. The effort alone deserves a standing ovation. Coat on get out there babe.',
    "Freezing but sun's out. At least the sky isn't gray and depressing. Silver linings literally. Bundle up babe.",
    "She's out here shining in below freezing like a goddamn warrior. Didn't quit on us. Coat on girl.",
    "Sunny and freezing. Cold as shit but at least she's making it pretty. Vitamin D is vitamin D. Layers babe.",
    "Below freezing but she lit the whole sky up for us. Free serotonin in the cold. We'll take it. Coat on babe.",
    "She's giving winter postcard energy. Cold as fuck but honestly breathtaking. Coat on babe.",
  ],
  TemperatureTier.jacketWeather: [
    'Sun walked in like she owns the place. You do girl. Jacket on get out there babe.',
    'Sun really said watch me do my fucking job today. And then she did it. Standing ovation girl.',
    'The kind of day you bitch about not having when it sucks. Shut up and go live in it babe.',
    'Oh so now she wants to act right. After everything she put us through. The nerve. Jacket on babe.',
    'She showed up looking like she slept eight hours and drank water. Since fucking when. Jacket on go babe.',
    "Not her gaslighting us into trusting her again with one pretty day. It's working though. Jacket on go play babe.",
    "She's behaving and it's making me emotional. Who are you and what did you do with that psycho bitch. Jacket on girl.",
    'Sunny and cool and she actually fucking delivered. Get out there before she changes her mind babe.',
    "Oh she's in her sane era today. Didn't know she had this setting. Get out there before she changes her mind girl.",
    "Not her acting like she didn't try to kill us last week. Short memory cute face. Jacket on babe.",
    'The weather just handed me a coffee and asked how I slept. Who the fuck is this woman. Jacket on babe.',
    'She showed up cute and chill as fuck today. 5 stars. Get out there babe.',
    'Cold and sunny and we are putting our jacket and boots on and no we are not taking questions thank youuu.',
    "Sunny and cool and she's out here making me wanna do shit. Get the fuck outside babe.",
  ],
  TemperatureTier.flannelWeather: [
    'She woke up and chose to be fucking perfect. No notes. Not one. Get outside immediately babe.',
    "It's so fucking nice out strangers are making eye contact and smiling. She drugged us all babe.",
    "This weather's so good I'm suspicious honestly. Get your ass out there before she changes her mind girl.",
    'She really looked at perfection and said hold my beer. Get outside babe.',
    "Okay it's nice as fuck outside. If you're inside I'm judging you babe. Go.",
    "Sunny and nice as fuck. Stop whatever you're doing. Stop it. Go outside right now.",
    "She's the kind of day that makes you forgive January. The whole fucking month. Just gone. Erased babe.",
    "Holy shit she's pretty today. Like offensively pretty. Get the fuck out there girl.",
    "It's so nice out the squirrels are showing off for her. Little backflips and shit. Get out there babe.",
    "It's giving Ferris Bueller. Like skip everything and go play today babe. You earned it.",
    'Sunny with perfect temps. She built today brick by brick for you bitch.',
    "Nice af out. If you're inside right now you're committing a crime. Like actually. Straight to jail girl.",
    'Weather equivalent of a glow up. Unrecognizable tbh. Light layers and go babe.',
    'Sunny and perfect temps. She really said fuck your plans I am the plan. She was right babe. Go.',
    'Flannel on boots on attitude off. She served a perfect day. Get out there babe.',
    'Sunny flannel weather. Throw on a hoodie and get the fuck outside. You earned this girl.',
  ],
  TemperatureTier.shortsWeather: [
    "Sun showed the fuck up and I'm emotional about it tbh. Shorts on go go go.",
    'Warm and sunny. She heard me talking shit all winter and took it personally. Good. Go play babe.',
    'Cancel everything. She popped tf off. Shorts. Sunnies. Outside. Now.',
    "She's giving '97 Shania. Warm sunny confident as fuck. That don't impress me much? This does babe.",
    'She woke up hot and sunny and I woke up grateful as fuck. Shorts on babe.',
    "She's so warm and sunny the trees are showing off. Leaves all perky and shit. Like okay girls.",
    "Sunny and warm and I'm fucking feral about it. Shorts on go girl.",
    'Sun came correct today. Sundress and go babe.',
    "It's giving serotonin on a silver platter. She's not even charging. Free drugs bitch.",
    'She served the kind of day that ruins every day after it. Shorts on babe.',
    "Sunny and warm and if you're not outside in five minutes what the fuck are you doing girl.",
    'Shorts on. Sunscreen on. Brain off. Get the fuck outside babe.',
    'She cooked today. Like actually fucking cooked. Shortest shorts you own. Go girl.',
    'Hot and sunny as fuck. Your legs have been in jail all winter. Free them bitch.',
    "SPF and shorts. That's the whole plan. Go babe.",
    'Booty shorts weather. Zero complaints. Get out there babe.',
    "It's nice as fuck out. Get out there babe. I'm not asking I'm telling.",
    "Don't even think about staying inside today babe. Get out there go play.",
  ],
  TemperatureTier.scorcher: [
    'Sun took every criticism personally and snapped. Like girl calm the fuck down.',
    "Not her cooking us like a fucking rotisserie chicken. She's unwell. Chug water babe.",
    "Sun said I'm going to make today everyone's problem. And she absolutely fucking did. SPF babe.",
    "She's running this bitch like a tanning bed with no off switch. SPF and hydrate babe.",
    "Hot as shit and sunny and I'm pretty sure my car is a pizza oven. Like girl calm down.",
    "Nearest body of water immediately. A pool a river a fucking sprinkler I don't care girl.",
    "She's literally holding a magnifying glass over us right now. Girl we are not ants.",
    "Sun's having a psychotic break and she's committed to the bit. SPF 50 babe.",
    "It's so fucking hot I'm googling how far is the ocean like I'll actually drive four hours. I will babe.",
    "She's cooking us alive and she's not even sorry. She's never fucking sorry. Hydrate babe.",
    'This bitch turned the planet into a panini press and we are the panini. Hydrate girl.',
    'I need a body of water or a body bag. Those are the options right now girl.',
    "So hot the birds are walking. She's out of her damn mind girl. SPF 50.",
  ],
};

const sunnyExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Every star out in single digits. She really decorated a crime scene. Layers babe.',
    'She rolled out the whole fucking constellation map in single digits. Pretty but damn girl.',
    'Opened the door to stargaze and my nostril hairs froze. Fuck that. Window view babe.',
    "Cassiopeia looking smug as hell for a bitch who's never paid a heating bill. Layers girl.",
    "She put on her whole damn show for an audience of zero. Nobody's that stupid. Layers girl.",
    'Cold as shit and she hung every star like we asked. Bitch we asked for warmth. Layers babe.',
    "The North Star isn't worth single digits. Not even she's that pretty. Fuck this. Stay in babe.",
  ],
  TemperatureTier.freezing: [
    'She served every star on a silver platter and our fingers are too fucking frozen to hold it. Classic girl.',
    "Looked up for three seconds and now I can't blink. Gorgeous and homicidal. That's her brand babe.",
    "The moon is being theatrical for a bitch who can't generate heat. We see you girl.",
    'Venus showed up below freezing looking like a hot ex at your party. The audacity babe.',
    'She strung constellations up like Christmas lights on a house with no furnace. Festive and fatal girl.',
    "Cold as fuck but Orion's staring me down like go inside idiot. Even the stars are judging me girl.",
    "She's glittering her ass off and my face is numb. Cute show from behind the window babe.",
    'Every star is out and not one is helping. Solidarity my ass. Bundle up girl.',
    'She put the whole Milky Way out below freezing. Who the fuck is this for. The penguins? Coat on babe.',
    'I want to stargaze so bad but my body said absolutely the fuck not. Coat scarf hat girl.',
    "She's too damn pretty to ignore below freezing. I hate that shit about her. Coat on go look babe.",
    'Every constellation crystal clear because the cold murdered the humidity. Silver lining girl.',
    'She hung the moon out like a dare. Below freezing and she wants us outside. Psychotic bitch babe.',
    'Cold enough to see my breath and every star. She really wants both or nothing huh girl.',
    'Sky looks like she hired a decorator. Temp feels like she hired a fucking hitman. Bundle up babe.',
  ],
  TemperatureTier.jacketWeather: [
    "Cool and covered in stars and acting like she didn't ruin our lives all winter. Cute sky. Jacket on bitch.",
    "Constellations are sharp as fuck tonight and the air feels good. She's in her redemption arc babe.",
    'Walked outside looked up and said oh shit out loud. She rehearsed this. Jacket on girl.',
    "She's being pretty and reasonable at the same time. Didn't know she had this range. Jacket on babe.",
    'Cool enough for a jacket warm enough to stare at stars like a damn maniac. Sweet spot girl.',
    "I can see Orion's whole belt and I'm not losing extremities. She finally read the fucking room babe.",
    "Every star showed up. She said I'll make it worth going outside. And she fucking did girl.",
    'Moon just cleared the treeline and I gasped out loud. Alone. No shame. Jacket on go look babe.',
    "Cool and starry and I forgave every shitty night she's ever given us. My loyalty is embarrassing girl.",
    "She put every star out like she's interviewing for a promotion. Hired. Get your ass outside babe.",
    "Not her acting like she's always been this gorgeous. Ma'am I have receipts. Jacket on girl.",
    'Sky so clear I can see planets and I am not calm about it. Jacket on go be unhinged babe.',
    'Crisp and sparkling and I just stood on my porch for ten minutes doing nothing. She fucking hypnotized me girl.',
    "Cool air clear sky and my whole body just relaxed. She's a chiropractor now apparently. Jacket on babe.",
    'Saw the Milky Way and now I need to rethink my entire life. Jacket weather existential crisis girl.',
    "She's got the sky looking like a screensaver and the temp finally cooperating. Jacket on go babe.",
    'Cool enough to feel alive and clear enough to see forever. She understood the damn assignment girl.',
    'She turned up the stars like a DJ who finally read the room. Jacket on go babe.',
  ],
  TemperatureTier.flannelWeather: [
    'She dropped every fucking star she owns tonight and the temp is perfect. Calling in sick tomorrow girl.',
    "Stepped outside and the sky hit me in the chest. Emotionally. I'm on the ground. She got me babe.",
    "Mild and starry and I just whispered she's so beautiful to no one. I'm fucking losing it girl.",
    'Put a blanket in the grass and laid down. I live here now. This is my home babe.',
    "Moon is out temp is perfect and I'm one deep breath from crying. She did this shit on purpose girl.",
    "Mild enough to stay outside until my phone dies. Twelve percent. Don't care. She's worth it babe.",
    'Tried to photograph the stars and it looks like shit but I know what I saw. She showed the fuck out girl.',
    "She said here's a perfect night now put your fucking phone down. Yes ma'am. Going dark babe.",
    'Stargazing weather and zero excuses not to be outside. She eliminated every damn argument girl.',
    "Found Cassiopeia without a chart and I've never felt more powerful. I'm a fucking genius babe.",
    "Sky's showing off the temp is behaving and I'm one blanket from sleeping outside. Don't test me girl.",
    'Flannel weather and a sky full of stars and she expects us to just go to bed? Fuck that babe.',
    "Mild and clear and I can smell somebody's fire pit three houses down. She's curating vibes girl.",
    "Went outside for one minute been on the porch for thirty. She's holding me hostage and I consent babe.",
    "Stars so bright I turned off my porch light out of respect. She doesn't need the competition girl.",
    "She made the temp perfect and the sky ridiculous and I'm pissed I have to sleep eventually babe.",
    'Every star every constellation every planet. She dumped the whole damn jewelry box tonight girl.',
    'Mild and starry and I just texted someone about camping with zero follow-through. She got me delusional babe.',
  ],
  TemperatureTier.shortsWeather: [
    'Orion is flexing so hard tonight he might pull something. Same energy. Shorts on go worship him babe.',
    'She made the air warm enough to just exist and then hung every damn star she owns. Showing off girl.',
    'I can see three planets and named them all after myself. This is my sky tonight girl.',
    "She hung every star low and warm for people who lay in grass. That's me bitch. Shorts on babe.",
    'Constellations are insane tonight and the air is so warm the sky is hugging me. Shorts on babe.',
    "That sky is the best ceiling I've ever had. Sleeping outside. Not a suggestion. Shorts on girl.",
    "Told the moon she's beautiful out loud and a neighbor said thanks. Wrong person but valid babe.",
    'She left every light on and made the air feel like cashmere. This bitch knows how to throw a night girl.',
    "Shorts on blanket down face up. She's giving me everything. Stay as long as you fucking want babe.",
    'The kind of night where you text everyone you love and say get outside right now. She made me do it babe.',
    "Night so perfect I called my mom about the stars. She said go to bed. She's wrong. Shorts on girl.",
    "She arranged the whole sky like she's proposing. I accept. Warm air stars yes. Shorts on go babe.",
    'Every star is out and I would fight someone who tries to make me go inside right now. Try me bitch.',
    "Shorts on. Get the fuck outside. The stars are putting on a show and you're not missing it babe.",
    "She did all this for you and you're inside? Shorts on get your ass out there girl.",
  ],
  TemperatureTier.scorcher: [
    "Hot as fuck but the sky is so gorgeous I'm sweating and staring. No regrets. Hydrate babe.",
    'She cranked the heat and hung every star. Chaotic. Committed. Unhinged. Hydrate girl.',
    "Million degrees and the Milky Way is out. I'm melting on the driveway stargazing. Worth it babe.",
    "Stars are stunning and I'm dissolving. She said beauty is pain and meant that shit literally girl.",
    "Hot as shit but the constellations are so sharp I can't go inside. Send water babe.",
    'She turned the heat to psychotic and the stars to eleven. Pick a fucking setting girl.',
    "Sweating through my shirt staring at Orion like he did this. He didn't but I need someone to blame girl.",
    "Hot as hell and starry as fuck. Five star restaurant no AC. Food's incredible though. Hydrate babe.",
    'Wanted to lie in the grass and stargaze but the grass could steam vegetables. Porch it is girl.',
    "She said here's the most beautiful sky ever and also fuck your sheets. Generous and cruel babe.",
    "Sky dripping with stars and I'm dripping with everything else. She doesn't do subtle. Hydrate girl.",
    "So hot the stars are twinkling extra like even they're panting. Gorgeous and miserable babe.",
    "She kept every damn degree from today and added stars. That's not a combo anyone asked for girl.",
    "Hot enough that I'm stargazing from the kiddie pool. Adaptive. She'd respect it babe.",
    "Constellations crystal clear because the heat is cooking the atmosphere. View's worth the heatstroke girl.",
    "She's scorching and sparkling and I'm outside because I'm stubborn and she's beautiful. Both unhinged babe.",
    "So hot the moon looks like she's melting. Or I'm delirious. Either way she's fucking gorgeous. Water now girl.",
  ],
};
