import '../../../../features/weather/domain/entities/temperature_tier.dart';

const sunnyExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Sunny and freezing. The duality of this bitch. Clearly a Gemini.',
    "She showed up to a shit situation and said I'm here. Like girl we needed warmth not moral support.",
    "It's giving Titanic. Gorgeous view but cold as shit. Puffer on babe.",
    "Shining like she's helping. Bitch you are a lamp. Layers girl.",
    "Sun rolled up to single digits and said I'm enough. Narrator: she was not even close to enough. Coat on babe.",
    "She's up there shining like she's doing us a favor. Bitch my eyelashes are frozen. Sit the fuck down.",
    'Sun clocked in did nothing and wants credit. Like damn okay girl.',
  ],
  TemperatureTier.freezing: [
    "Cold as fuck but she showed up anyway. She didn't have to but she did it for us. Coat on and go babe.",
    "Below freezing but sunny. At least she's trying and honestly that's more than most. Bundle up girl.",
    "Freezing but the sun is out and she's gorgeous. Could be worse. Could be gray. Coat on babe.",
    "It's giving Miranda Priestly. Cold as shit but stunning. Heaviest coat babe.",
    "She rolled up to freezing temps and said I'm still here. Respect the fuck out of that honestly. Coat on babe.",
    "Sunny and cold as fuck but at least she showed up. That's more than your ex ever did. Layer up babe.",
    'Below freezing but the sun came through. She chose us today. Coat on and show her some love babe.',
    'Cold as fuck but she showed up anyways. The effort alone deserves a standing ovation. Coat on get out there babe.',
    "Freezing but sun's out. At least the sky isn't gray and depressing. Silver linings literally. Bundle up babe.",
    "She's out here shining in below freezing like a goddamn warrior. Didn't quit on us. Coat on girl.",
    "Sunny and freezing. Cold as shit but at least she's making it pretty. Vitamin D is vitamin D. Layers babe.",
    "Below freezing but she lit the whole sky up for us. Free serotonin in the cold. We'll take it. Coat on babe.",
    "She's giving winter postcard energy. Cold as fuck but honestly breathtaking. Coat on babe.",
  ],
  TemperatureTier.jacketWeather: [
    'Sun walked in like she owns the place. You do girl. Jacket on get out there babe.',
    'Sun really said watch me do my fucking job today. And then she did it. Standing ovation girl.',
    'The kind of day you bitch about not having when it sucks. Shut up and go live in it babe.',
    'Oh so now she wants to act right. After everything she put us through. The nerve. Jacket on babe.',
    'She showed up looking like she slept eight hours and drank water. Since fucking when. Jacket on go babe.',
    "Not her gaslighting us into trusting her again with one pretty day. It's working though. Jacket on go play babe.",
    "She's behaving and it's making me emotional. Who are you and what did you do with that psycho bitch. Jacket on girl.",
    'Sunny and cool and she actually fucking delivered. Get out there before she changes her mind babe.',
    "Oh she's in her sane era today. Didn't know she had this setting. Get out there before she changes her mind girl.",
    "Not her acting like she didn't try to kill us last week. Short memory cute face. Jacket on babe.",
    'The weather just handed me a coffee and asked how I slept. Who the fuck is this woman. Jacket on babe.',
    'She showed up cute and chill as fuck today. 5 stars. Get out there babe.',
    'Cold and sunny and we are putting our jacket and boots on and no we are not taking questions thank youuu.',
    "Sunny and cool and she's out here making me wanna do shit. Get the fuck outside babe.",
  ],
  TemperatureTier.flannelWeather: [
    'She woke up and chose to be fucking perfect. No notes. Not one. Get outside immediately babe.',
    "It's so fucking nice out strangers are making eye contact and smiling. She drugged us all babe.",
    "This weather's so good I'm suspicious honestly. Get your ass out there before she changes her mind girl.",
    'She really looked at perfection and said hold my beer. Get outside babe.',
    "Okay it's nice as fuck outside. If you're inside I'm judging you babe. Go.",
    "Sunny and nice as fuck. Stop whatever you're doing. Stop it. Go outside right now.",
    "She's the kind of day that makes you forgive January. The whole fucking month. Just gone. Erased babe.",
    "Holy shit she's pretty today. Like offensively pretty. Get the fuck out there girl.",
    "It's so nice out the squirrels are showing off for her. Little backflips and shit. Get out there babe.",
    "It's giving Ferris Bueller. Like skip everything and go play today babe. You earned it.",
    'Sunny with perfect temps. She built today brick by brick for you bitch.',
    "Nice af out. If you're inside right now you're committing a crime. Like actually. Straight to jail girl.",
    'Weather equivalent of a glow up. Unrecognizable tbh. Light layers and go babe.',
    'Sunny and perfect temps. She really said fuck your plans I am the plan. She was right babe. Go.',
    'Shacket on boots on attitude off. She served a perfect day. Get out there babe.',
    'Throw on a hoodie and get the fuck outside. You earned this girl.',
  ],
  TemperatureTier.shortsWeather: [
    "Sun showed the fuck up and I'm emotional about it tbh. Shorts on go go go.",
    'Warm and sunny. She heard me talking shit all winter and took it personally. Good. Go play babe.',
    'Cancel everything. She popped tf off. Shorts. Sunnies. Outside. Now.',
    'She woke up hot and sunny and I woke up grateful as fuck. Shorts on babe.',
    "She's so warm and sunny the trees are showing off. Leaves all perky and shit. Like okay girls.",
    "Sunny and warm and I'm fucking feral about it. Shorts on go girl.",
    'Sun came correct today. Sundress and go babe.',
    "It's giving serotonin on a silver platter. She's not even charging. Free drugs bitch.",
    'She served the kind of day that ruins every day after it. Shorts on babe.',
    "Sunny and warm and if you're not outside in five minutes what the fuck are you doing girl.",
    'Shorts on. Sunscreen on. Brain off. Get the fuck outside babe.',
    'She cooked today. Like actually fucking cooked. Shortest shorts you own. Go girl.',
    'Hot and sunny as fuck. Your legs have been in jail all winter. Free them bitch.',
    "SPF and shorts. That's the whole plan. Go babe.",
    'Booty shorts weather. Zero complaints. Get out there babe.',
    "It's nice as fuck out. Get out there babe. I'm not asking I'm telling.",
    "Don't even think about staying inside today babe. Get out there go play.",
  ],
  TemperatureTier.scorcher: [
    'Sun took every criticism personally and snapped. Like girl calm the fuck down.',
    "Not her cooking us like a fucking rotisserie chicken. She's unwell. Chug water babe.",
    "Sun said I'm going to make today everyone's problem. And she absolutely fucking did. SPF babe.",
    "She's running this bitch like a tanning bed with no off switch. SPF and hydrate babe.",
    "Hot as shit and sunny and I'm pretty sure my car is a pizza oven. Like girl calm down.",
    "Nearest body of water immediately. A pool a river a fucking sprinkler I don't care girl.",
    "She's literally holding a magnifying glass over us right now. Girl we are not ants.",
    "Sun's having a psychotic break and she's committed to the bit. SPF 50 babe.",
    "It's so fucking hot I'm googling how far is the ocean like I'll actually drive four hours. I will babe.",
    "She's cooking us alive and she's not even sorry. She's never fucking sorry. Hydrate babe.",
    'This bitch turned the planet into a panini press and we are the panini. Hydrate girl.',
    'I need a body of water or a body bag. Those are the options right now girl.',
    "So hot the birds are walking. She's out of her damn mind girl. SPF 50.",
  ],
};

const sunnyExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Every star out in single digits. She really decorated a crime scene. Layers babe.',
    'She rolled out the whole fucking constellation map in single digits. Pretty but damn girl.',
    'Opened the door to stargaze and my nostril hairs froze. Fuck that. Window view babe.',
    "Cassiopeia looking smug as hell for a bitch who's never paid a heating bill. Every layer you own girl.",
    "She put on a whole show for an audience of zero. Nobody's that stupid. Layers if you have to babe.",
    'Cold as shit and she hung every star like we asked. Bitch we asked for warmth. Heaviest coat babe.',
    "The North Star isn't worth single digits. Not even she's that pretty. Bundle up babe.",
  ],
  TemperatureTier.freezing: [
    'She served every star on a silver platter and our fingers are too fucking frozen to hold it. Classic.',
    "Looked up for three seconds and my face went numb. She's gorgeous but homicidal. Layer up babe.",
    'She hung every star she owns and forgot to turn the heat on. Typical. Coat on babe.',
    'She made the sky gorgeous and the temp unbearable. Mixed signals from hell. Coat on babe.',
    'She went all out on the sky and said warmth is not my department. Noted bitch. Layers babe.',
    'Cold as fuck and she expects us to stand here and admire her work. The entitlement. Layer up girl.',
    "She's sparkling her ass off and my face is numb. Cute show from behind the window babe.",
    'Every star is out and not one is helping. Solidarity my ass. Bundle up girl.',
    'She put the whole Milky Way out below freezing. Who the fuck is this for. The penguins? Coat on babe.',
    'I want to stargaze so bad but my body said absolutely the fuck not. Coat scarf hat every layer babe.',
    "She's too damn pretty to ignore below freezing. I hate that shit about her. Coat on go look babe.",
    'She froze the humidity out of the air so the stars could show off. Priorities. Coat on girl.',
    'Below freezing and she put on a show like we owe her attendance. We do not. Bundle up babe.',
    'Below freezing and she still wants an audience. Diva status. But honestly coat on go look babe.',
    'Cold enough to see my breath and every damn star. She cranked both dials to max. Bundle up girl.',
    "It's giving Cruella. Looks stunning wants you dead. Bundle up babe.",
  ],
  TemperatureTier.jacketWeather: [
    "Cool temps and covered in stars and acting like she didn't ruin our lives all winter. Cute.",
    'Sharp sky cool air and she finally remembered how to act. About fucking time. Jacket on babe.',
    'Walked outside and the sky shut me up immediately. She knew what she was doing. Jacket on get out there babe.',
    "She's being pretty and reasonable at the same time. Didn't know she had this range. Jacket on babe.",
    'Cool enough for a jacket warm enough to stare at stars like the fan girls we are. Get out there babe.',
    "I can see Orion's whole belt and I'm not losing extremities. She finally read the fucking room babe.",
    "Every star showed up. She said I'll make it worth going outside. And she fucking did girl.",
    "It's giving screensaver. She's so pretty she looks fake. Jacket on go check babe.",
    'Okay planeterium baddie. She set the whole thing up and admission is free. Jacket on go look babe.',
    "She put every star out like she's interviewing for a promotion. Hired. Get your ass outside babe.",
    "Not her acting like she's always been this gorgeous. Ma'am I have receipts. Jacket on girl.",
    'Sky so clear I can see planets and I am not calm about it. Jacket on go be unhinged babe.',
    'Crisp and sparkling and she fucking hypnotized me on my own porch. Jacket on girl.',
    "Cool air clear sky and my whole body just relaxed. She's a chiropractor now apparently. Jacket on babe.",
    'Saw the Milky Way and now I need to rethink my entire fucking life. Jacket on girl.',
    "She's got the sky looking like a screensaver and the temp finally cooperating. Jacket on go babe.",
    'She bedazzled the whole fucking sky tonight. At this temp? Iconic. Jacket on girl.',
    'She pulled out the bedazzler and went to fucking town up there. Jacket on go babe.',
  ],
  TemperatureTier.flannelWeather: [
    'She dropped every fucking star she owns tonight and the temp is perfect. Calling in sick tomorrow immediately.',
    'Stepped outside and the sky hit me in the fucking chest. She got me. Get out there babe.',
    "Mild and starry and I just whispered she's so beautiful to no one. I'm fucking losing it girl.",
    'Put a blanket in the grass and laid the fuck down. I live here now. Flannel on babe.',
    'Stars are out temp is perfect and she did this shit on purpose. Get your ass outside girl.',
    "Mild enough to stay outside until my phone dies. Twelve percent. Don't fucking care. Flannel on babe.",
    'Tried to photograph the stars and it looks like shit but I know what I saw. She showed the fuck out girl.',
    "She said here's a perfect night now put your fucking phone down. Yes ma'am. Going dark babe.",
    'Stargazing weather and zero fucking excuses. She eliminated every argument. Get outside girl.',
    'Named a constellation wrong on purpose and nobody stopped me. My sky my rules. Shacket on girl.',
    "Sky's showing off the temp is behaving and I'm one blanket from sleeping outside. Don't test me girl.",
    'Hoodie weather and a sky full of stars and she expects us to just go to bed? Fuck that.',
    "Mild and clear and I can smell somebody's fire pit three houses down. She's fucking curating the night babe.",
    "Went outside for one minute been on the porch for thirty. She's holding me fucking hostage babe.",
    "Stars so bright I turned off my porch light out of respect. She doesn't need the competition.",
    "She made the temp perfect and the sky ridiculous and I'm pissed I have to sleep eventually. Do I?",
    'Every star every constellation every planet. She dumped the whole damn jewelry box out for us babe.',
    "She dropped a perfect night on a weekday like she's trying to get me fired. Fuck it who needs a job.",
  ],
  TemperatureTier.shortsWeather: [
    'Orion is flexing so hard tonight he might pull something. Same energy. Shorts on go look babe.',
    'She made the air warm and hung every damn star she owns. Showing the fuck off. Here for it babe.',
    'She put the whole solar system on display tonight. Overachiever as fuck. Shorts on girl.',
    'Stars out air warm grass soft. She set a trap and I walked right the fuck into it. Blanket time babe.',
    'Constellations are insane tonight and the air is warm as fuck. Go play babe.',
    "My landlord could never. She's giving better ceilings for free. Shorts on girl.",
    "She's got the whole block outside looking up like she's recruiting. Worked on me. Shorts on babe.",
    "She's got the whole block outside staring up. We look insane. She did this. Get out here babe.",
    'She set the temp to perfect and the sky to insane. Girl knows how to host. Great party babe.',
    "Shorts on blanket down face up. She's giving me everything. Stay as long as you fucking want babe.",
    'She put on the best show of the year and half the city is asleep. Their fucking loss. Not us babe.',
    'She threw everything she has at tonight and it landed. Every single bit of it. Get out there girl.',
    'She served the sky the temp and the vibes all at once. Triple threat. Shorts on go babe.',
    'She is showing off so hard right now. Every star on deck. Full fucking send. Get out here girl.',
    "Shorts on. Get the fuck outside. The stars are putting on a show and you're not missing it babe.",
    "She did all this for you and you're inside? Shorts on get your ass out there girl.",
  ],
  TemperatureTier.scorcher: [
    "Okay yes it's hot as shit but like look up for a second. See? Yeah. Stay hydrated babe.",
    'She said heatstroke AND a light show. Dinner and a fucking show. Drink water girl.',
    'Million degrees and the Milky Way is out. Melting on the driveway stargazing. Fuck it. Water. Now babe.',
    "Stars are stunning and I'm dissolving. She said beauty is pain and meant that shit literally girl.",
    "Hot as shit but the constellations are so sharp I can't go inside. Send water babe.",
    'She turned the heat to psychotic and the stars to eleven. Pick a fucking setting girl.',
    "Hot as fuck and I'm still out here staring up like an idiot. She knows what she's doing. Chug water girl.",
    "It's giving hot girl summer but literal. The sky is perfect the temp is assault. Nearest AC immediately babe.",
    'Tried to stargaze from the yard but the ground is hotter than me right now. Inside it is girl.',
    "She said here's the most beautiful sky ever and also fuck your sheets. Sweet but cruel babe.",
    "She's giving sauna with a view. Didn't book this. Can't leave. Ice water immediately girl.",
    'Like yes girl you are stunning can you also not cook us alive at the same time? Stay hydrated babe.',
    "If there's a pool within walking distance I'm trespassing tonight. She gave me no choice girl.",
    "She's hot and she's beautiful and I'm not going inside. Fight me. Water on deck babe.",
    'Hot as fuck but the sky is worth every degree tonight. No complaints. Okay one complaint. Drink water girl.',
    "Hot as hell and the sky is flirting with me. I'm staying. She earned it. Hydrate babe.",
    'Still outside. Still sweating. Still obsessed with her. This is a lifestyle now. Chug something cold girl.',
  ],
};
