import '../../../../features/weather/domain/entities/temperature_tier.dart';

const thunderstormExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Frozen and booming. Did she really just add pyrotechnics to this. Stay the fuck in girl.',
    'Not her adding lightning to frozen hell. The audacity honestly girl.',
    'Frozen cold thunder. She said fuck your plans tonight and she meant it girl.',
    "She's performing in frozen temps for an audience of nobody. Respect that shit honestly babe.",
    'Frozen and storming. Giving Alien. Giving Sigourney. Stay inside babe.',
    "She's putting on a whole fucking light show in frozen air for literally nobody. Who is this for girl?",
    'Frozen and electric. AC/DC wrote Thunderstruck for this and I believe that. Stay inside girl.',
    "The cold wasn't dramatic enough for her so she added fucking explosions. Classic babe.",
    'Did she just watch Twister again? Frozen and storming like it owes her money. Stay inside babe.',
    'Frozen thunder. Nobody bought tickets but she does not care. Stay in girl.',
    'She brought the bass the lights and zero regard for human life in frozen temps. Iconic honestly babe.',
    'Cold and booming. Like who the fuck asked for this. Nobody asked for this girl.',
  ],
  TemperatureTier.freezing: [
    'Freezing thunder. Like a whole ass talent show nobody approved. Stay safe girl.',
    'Going this fucking hard in freezing temps. More commitment than your ex honestly girl.',
    'Headlining a frozen festival nobody fucking wanted. Bold or just unwell? Both honestly babe.',
    "Freezing and thundering. She's channeling Garbage right now. I hear it girl.",
    'She gave the freezing cold a soundtrack. Nobody asked for this. Stay inside babe.',
    'She really said the freezing cold needed a beat drop. It did not girl.',
    'Freezing thunder. Giving Corpse Bride. Dramatic and cutting through the sky. Honestly stunning babe.',
    'Holy shit. The freezing cold was too quiet for her so she added thunder.',
    "Freezing and booming. She wasn't satisfied just being cold she had to be loud as fuck about it too girl.",
    "Freezing storm. She's doing too damn much and she knows it and she does not give a shit babe.",
    'Freezing and thundering. Why is she performing this hard for us right now? Go inside girl.',
    "Freezing cold and booming. Is she okay? She's not okay. Stay inside and let her work through it babe.",
  ],
  TemperatureTier.jacketWeather: [
    "Cold and storming. Girl you're already cold enough why the fuck are you like this. Stay inside babe.",
    "Cold and booming. Like girl chill. Oh wait you can't it's freezing. Stay dry babe.",
    "Cold storm and she's out here performing for us like we fucking asked. We did not ask girl.",
    "She's terrorizing the whole block in the cold and for what. For what girl.",
    "Cold and booming so loud a car alarm joined in. She's got a backup singer now babe.",
    'Cool and stormy. She went from moody to full psychotic break in like ten minutes. Girl relax.',
    "Cold and stormy. She didn't just snap she detonated. Like ma'am this is a neighborhood.",
    "Cold and storming. It's already cold enough and she said you know what let me add drama babe.",
    "Cold as fuck and she's booming like she's got a point to make. What is the point girl. What is it.",
    'Cold and stormy. Nobody asked her to upgrade rain to a full fucking production but here we are girl.',
    "Cold thunder just rattled my windows like she's knocking. Am I answering? Absolutely not girl.",
    'Cold and booming so hard my coffee rippled. Girl leave my coffee out of this.',
    "Cool and stormy. Every boom and I'm like girl we fucking get it you're upset. Stay dry babe.",
    'Cold thunder just flickered every light on my block. Like girl that is not your light switch.',
  ],
  TemperatureTier.flannelWeather: [
    "Mild and booming. Cracked a window. She's therapeutic as fuck girl.",
    "She's having a full menty B but the temp is fucking perfect. Crack a window and enjoy the show babe.",
    "She's throwing a tantrum and the nice temp is holding my hand through it. One out of two ain't bad girl.",
    "She couldn't just give us a nice fucking day? Had to add pyrotechnics. Honestly though? Here for it babe.",
    "She's out there doing the absolute most and I'm in here doing the absolute least. That's called balance babe.",
    "Mild and booming. She just rattled every window like she's knocking. We're not answering. We're cozy girl.",
    "Pull up a chair and let her have her little tantrum. She'll tire herself out eventually babe.",
    'Volume at ten. Consideration at zero. Temp is fucking perfect though. Two out of three girl.',
    "Mild thunder so close the floor vibrated. She's communicating through bass now. Message received girl.",
    "Mild and stormy and I'm watching her fucking lose it from the window like reality TV. Best episode yet honestly.",
    'Rain on the window thunder in the distance perfect temp. Did she finally do something right? Kind of. Almost girl.',
    "Mild and fucking booming. She's here and she's not apologizing. Stay safe stay dry babe.",
    "Perfect temp and she's out there fucking screaming. Unhinged but make it cozy babe.",
    "Mild and booming so hard my walls shook. She's got a point and she's making it loud girl.",
    'Mild thunder at this temp just hits different honestly. Like free therapy babe.',
    "Mild and absolutely losing it out there. My windows are vibrating and I'm vibing girl.",
    "She's booming at the perfect temp and I've got a window cracked like a psycho. No regrets babe.",
    'Stormy and mild. She boomed so loud my dog just looked at me like this is your fault. Is it? Girl.',
    "Perfect temp. Thunder shaking the roof. She's doing too much and I'm doing nothing and it's beautiful babe.",
  ],
  TemperatureTier.shortsWeather: [
    'Summer storm energy. Crack a window and let her serenade you with chaos. Therapeutic as fuck girl.',
    "Warm and stormy. She's so alive out there I can feel it through the walls. Electric as fuck babe.",
    'Warm and fucking booming. Might kill you but vibes are immaculate babe. Stay safe out there.',
    "Warm and stormy. She's out here setting off car alarms like a poltergeist. Stay safe babe.",
    "Summer storm energy. I'm on the porch watching her perform. Best seat in the house bitch.",
    "Storming and warm as fuck. She's louder than my thoughts and I've never been more grateful girl.",
    "Hot n stormy. She's being so fucking theatrical the trees are swaying. Standing ovation from nature girl.",
    "The rain is warm as fuck the thunder is booming she's having the time of her life and honestly same girl.",
    'Warm and fucking booming. My cat just astral projected under the bed. Gone girl.',
    "She's going absolutely apeshit out there and I'm on the porch clapping. Summer storms are such a vibe babe.",
    'She just boomed so hard my drink rippled. Jurassic Park shit in my kitchen babe. Stay safe out there.',
    "Warm and feeling this thunder in my chest. She's not making noise she's making contact girl.",
    'Warm and booming. She really said cancel your plans I am your plan tonight. Stay safe out there girl.',
    'Warm storm just walked in like she fucking owns the place. Honestly she does. We just live here babe.',
    'Warm and storming. She said you thought tonight was yours. Cute babe.',
    "Warm thunder shook my windows like she's checking if anyone's home. We're home. We know girl.",
    'Warm and booming. She really walked in and every plan I had walked out. Stay dry babe.',
    "Warm and storming and I'm on the couch with popcorn watching her meltdown like it's HBO babe.",
    "Warm thunder just said fuck your quiet night. I'm the plans now babe.",
    "Warm thunder. I'm not scared I'm impressed honestly. Okay I'm a little scared babe.",
    "She's warm and electric and unhinged and I would die for her honestly girl.",
  ],
  TemperatureTier.scorcher: [
    'Hot and fucking booming. Is she okay? No. Do we love her? Absolutely. From inside babe.',
    'Scorching thunder. Did she just fight the fucking sun? I think she just fought the sun girl.',
    'Hot as fuck and she just boomed so hard my AC kicked on out of fear. Did she scare my house babe?',
    'Why the fuck is she going this hard in this heat? Like girl who hurt you. Stay inside babe.',
    "Hot thunder. The sun started it and honestly? She's finishing it. Stay dry girl.",
    "Scorching and booming. She's having a whole moment out there. Are we crying? Maybe. From inside babe.",
    "Hot storm and she's putting on the show of her fucking life. Who told her she could do this girl?",
    "She's thundering in scorching heat and honestly? Icon behavior. Stay the fuck inside babe.",
    'Hot and storming. Did the heat deserve this? Yes. Did she have to go that hard? Also yes girl.',
    'Hot and booming. Is it a breakdown or a moment? Either way she looks incredible girl.',
    'Thunder on a scorcher. Did she just tell the heat to eat shit? Because I heard it too babe.',
    "Scorching and storming. She's literally everything right now. Like how is she doing this girl.",
    "She's booming at the sun like girl you're done. Go home. It's over. Stay dry babe.",
    'Hot storm. Is the sun embarrassed? She should be. She got cooked by her own weather girl.',
    'Scorching thunder and she walked in and the heat just left? Like it got up and left babe.',
    'Hot and electric and completely fucking unhinged. Is she perfect? She might be perfect girl.',
  ],
};

const thunderstormExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'She brought fucking lightning to a freezing night. Girl what are you proving?',
    "She's got her own sound system and strobe lights. Absolutely unhinged as fuck babe.",
    "She's cracking lightning in single digits. The cold wasn't enough she needed special effects babe.",
    'She brought pyrotechnics to a Tuesday. Read the fucking room babe.',
    'The audacity to add electricity to this bullshit. Iconic as hell honestly babe.',
    "She said darkness and cold aren't enough? Fine. Have some lightning bitch.",
    "She's so cold and so loud the windows are fogging from the bass girl.",
    "The sky just exploded. She's fucking shaking the whole house like she's got a warrant girl.",
    "She's flickering the power like a goddamn poltergeist girl.",
    "She said snow wasn't dramatic enough so she added special effects girl.",
    "She's flashing the whole neighborhood. Someone call HR girl.",
    'She directed produced and starred in her own horror movie tonight babe.',
  ],
  TemperatureTier.freezing: [
    'Walls vibrating. Can you calm down? girl.',
    'Jump scared the whole neighborhood. Rude as fuck babe.',
    'Let there be light. Then immediately took it back. Tease girl.',
    'Surround sound and a strobe light. This a venue? babe.',
    "Rattled every dish in the cabinet. She's redecorating from the sky girl.",
    'Car alarms joining in. Collaboration nobody needed babe.',
    'Lightning like a camera flash. Full sky lit up. Holy shit girl.',
    "She's big mad and the whole city knows it. What happened? babe.",
    'Taking selfies up there apparently. Flash after flash girl.',
    'Bass treble light show. Full concert. Nobody bought tickets babe.',
  ],
  TemperatureTier.jacketWeather: [
    "She just jump scared the whole city. Bitch we're trying to sleep.",
    "Every boom is her knocking. We're not fucking answering girl.",
    "She's rearranging furniture upstairs at 2am. Worst fucking roommate ever girl.",
    "She's making her presence known. Loudly. Very fucking loudly girl.",
    "She's fucking been going off for a damn hour. Girl take it to therapy.",
    "She's out there doing sound check for nobody girl.",
    "She's out there bowling in the sky and getting strikes every time bitch.",
    "She's fucking playing drums on the roof. She's not good at it. Like at all girl.",
    "She just fucking shook the windows and didn't apologize babe.",
    "She just lit up my whole bedroom through the curtains. I didn't consent to this girl.",
    "She's so loud the dog got under the bed and I'm considering joining him babe.",
    "She's fucking out there doing pyrotechnics on a budget babe.",
    "She's got the bass the treble and zero chill girl.",
    "Every crack of thunder sounds closer. She's walking toward us girl.",
    "She boomed so hard the power flickered. She's editing the electricity now babe.",
    'The lightning flash lasted two seconds and I counted three rooms lit up. She got the whole house babe.',
    "She's out there having a full meltdown with pyrotechnics. Budget is insane babe.",
    "The lightning just lit up my whole bedroom. Girl I'm trying to sleep not rave.",
    "She just thundered three times in a row like she's knocking. We're not home babe.",
    'The power went out for half a second and my whole life flashed before me babe.',
  ],
  TemperatureTier.flannelWeather: [
    "Blanket candle couch. She's losing her fucking mind but we're thriving babe.",
    "She's having a full meltdown outside and I'm under a blanket with tea watching. Dinner and a show girl.",
    'She cracked the sky open and I cracked a window. Free concert. Best acoustics of my fucking life babe.',
    "She's screaming into the void and I lit a candle for her. Supportive from a distance girl.",
    "She just shook the walls so hard a picture frame tilted. She's redecorating from the sky now babe.",
    "She's throwing a tantrum and the temp is holding my hand through it. One out of two ain't bad girl.",
    'She boomed so hard my tea rippled. Jurassic Park but make it cozy. Flannel on blanket up babe.',
    "Window cracked rain smell hitting and she's providing the bass. Didn't ask for a spa night but here we are girl.",
    "She's out there doing the absolute most and I'm in here doing the absolute least. Balance babe.",
    'She lit up my whole bedroom for one second and I saw everything including my poor life choices. Back to dark. Cozy though girl.',
    "She's putting on a whole production and the temp said your ticket includes comfort. Best deal of my life babe.",
    "She just rattled every window in the house like she's knocking. We're not answering. We're cozy girl.",
    "She can't just give us a nice night she has to add pyrotechnics. Extra but honestly iconic babe.",
    "She's the friend who shows up with fireworks to a casual dinner. Nobody asked but nobody's mad girl.",
    "She's being dramatic as fuck outside and the temp is being an angel inside. I know which one I'm with babe.",
    "She boomed so hard the dog got under the blanket with me. She's a matchmaker now girl.",
    "Every crack of thunder is her adding another chapter to tonight. She's writing a whole novel out there babe.",
    'She just flickered every light on the block like a poltergeist with a weather degree. Cozy in here though girl.',
    "She's got the volume at ten and the consideration at zero but the temp at perfect. Two out of three babe.",
    "Pull the blanket up and let her have her little moment. She'll tire herself out eventually girl.",
    "Mild stormy night and I'm watching her lose it from the couch like reality TV. Best episode yet babe.",
    "She's performing to an audience of one and I'm giving her a standing ovation from my bed girl.",
    'She took a perfectly nice night and gave it a soundtrack. Overachiever shit honestly babe.',
    "Thunder so close the floor vibrated. She's communicating through bass now. Message received girl.",
    "She's so dramatic tonight the candle I lit feels like a prop in her movie. I'm an extra and I'm fine with it babe.",
  ],
  TemperatureTier.shortsWeather: [
    "She's hot and she's booming. Hot as fuck tbh. Get on the porch and watch babe.",
    'The air smells like rain and chaos. Fucking love this shit girl.',
    'She just cracked the sky open. Holy shit babe.',
    "She's scary she's sexy she's everything. I'm obsessed girl.",
    'Windows open and the rain smell just hit. I would bottle this shit if I could babe.',
    "She's putting on a fucking show. Get on the porch babe.",
    "She's the fireworks show we didn't know we fucking needed babe.",
    "She's feral fucking gorgeous and loud. The whole package girl.",
    "The air smells insane after that last crack. She's a whole fucking experience babe.",
    "She's got the sky flashing like a VIP section. We're on the list girl.",
    "She's fucking electric. Literally and figuratively girl.",
    'The lightning is so close I can smell it. Ozone and chaos. Her signature scent bitch.',
    'Holy shit. She just cracked the sky open and the rain smells like redemption babe.',
    "She's beautiful and terrifying. If she had a dating profile I'd swipe right so fucking damn fast babe.",
    "She's fucking beautiful and screaming. If she had a wine glass she'd throw it girl.",
    "She's a smoke show. Literally. There's steam rising off the pavement girl.",
    "She's fucking putting on a whole show. Porch. Now. Don't argue babe.",
    'She just turned night into day for one second and took it back. Emotional whiplash babe.',
    "She's warm and violent and the air smells incredible after each crack girl.",
    "She's the hottest mess I've ever seen and I mean that as a compliment babe.",
    "She's scary beautiful. The kind you can't look away from girl.",
    "She's flashing and booming and the air is thick with drama babe.",
    "Lightning just lit up the clouds from inside. She's glowing girl.",
    "The thunder rolls through your chest. She's got bass babe.",
    "She's performing her whole discography tonight. Every hit girl.",
  ],
  TemperatureTier.scorcher: [
    "She's throwing lightning bolts in a sauna. This is hell with a light show babe.",
    "The thunder isn't cooling shit down it's just adding noise to the misery girl.",
    'Hot thunder. The air is thick and every boom vibrates through the humidity babe.',
    "She's so hot and so angry. Relatable as fuck girl.",
    "She said you're hot? Have some lightning too. Generous bitch girl.",
    "She's not just flashing us she's going full fucking nude. Like girl chill.",
    'She added special effects to the sauna. Nobody asked girl.',
    "She's not cooling us off she's cooking us with sound effects bitch.",
    "She's fucking directing an action movie and we're all extras babe.",
    'Holy shit. She turned the whole city into a boiler room. No guest list no exit babe.',
    "The thunder is just the microwave timer. We're done. We're cooked girl.",
    'The heat and the noise are competing for who can kill us first babe.',
    "She's cracking lightning in a sauna. Each bolt is just heating us more babe.",
    "She's so hot and loud the pavement is steaming between each flash girl.",
    "Every thunder boom pushes a wave of hot air through the window. She's breathing on us girl.",
    "The lightning lit up the steam rising off the road. She's making her own fog machine babe.",
    "She's got lightning and humidity and zero mercy girl.",
    "She's so loud and so hot. She's the friend who's too much at parties girl.",
    "Scorching hot thunderstorm at night. I can't tell if I'm sweating or getting rained on babe.",
    "She's the final boss of summer nights. Unbeatable girl.",
  ],
};
