import '../../../../features/weather/domain/entities/temperature_tier.dart';

const thunderstormExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Frozen and booming. She's doing too much in single digits. Stay the fuck inside babe.",
    "Not her adding thunder to the cold. Girl nobody asked for this. Bundle up and stay in girl.",
    "Single digit thunderstorm. She really said I can make this more chaotic. And she did babe.",
    "She's performing in frozen temps for nobody. Like girl who is this for. Stay inside girl.",
    "Frozen and storming. She added a sound system to the cold. So extra. Stay in babe.",
    "She's putting on a whole light show in single digits. Girl this is too much. Stay inside girl.",
    "Frozen and electric. She could have just been cold but no. She had to be loud too babe.",
    "The cold wasn't enough for her so she added fucking thunder. Classic overachiever. Stay inside girl.",
    "Single digit storm. She really decided to be the most out there. Bundle up and stay in babe.",
    "Frozen thunder. Nobody bought tickets. She's performing anyway. Stay in girl.",
    "She brought the full light show to single digits. Girl it's too cold for this. Stay inside babe.",
    "Cold and booming. Like girl this is a lot. We get it. You're extra. Stay warm babe.",
  ],
  TemperatureTier.freezing: [
    "Freezing thunder. She's doing a whole talent show nobody approved. Stay safe girl.",
    "Going this hard in freezing temps. She's too much right now honestly. Bundle up inside babe.",
    "Freezing and thundering. She woke up chaotic and plugged in an amp. We hear you girl.",
    "She gave the freezing cold a soundtrack. Nobody asked for this energy. Stay inside babe.",
    "She really said the cold needed a beat drop. It did not. She's a lot right now girl.",
    "Freezing thunder. Dramatic as hell cutting through the sky. She's doing too much babe.",
    "The freezing cold was too quiet for her so she added thunder. Of course she did girl.",
    "Freezing and booming. Not satisfied just being cold she had to be loud too. So extra babe.",
    "Freezing storm. She's doing too damn much and she knows it. Stay inside girl.",
    "Freezing and thundering. Why is she going this hard right now. Bundle up and stay in babe.",
    "Freezing and booming. She's being chaotic in the cold. Less fun than summer storms honestly girl.",
    "Freezing thunder. She's a lot tonight. Stay inside and let her do her thing babe.",
  ],
  TemperatureTier.jacketWeather: [
    "Cold and storming. Girl it's already cold enough why are you adding drama. Stay inside babe.",
    "Cold and booming. Like girl chill. Oh wait you can't it's freezing. Stay dry babe.",
    "Cold storm and she's out here performing like we asked. We did not ask girl.",
    "She's being so extra in the cold right now. Like girl this is a lot. Stay dry babe.",
    "Cold and booming so loud a car alarm joined in. She's got a backup singer now girl.",
    "Cool and stormy. She went from moody to chaotic in ten minutes. Girl relax babe.",
    "Cold and storming. It's already cold enough and she said let me add drama. Classic her girl.",
    "Cold as fuck and she's booming. She's got something to say and she's being LOUD about it babe.",
    "Cold and stormy. Nobody asked for a full production but here we are. Stay dry girl.",
    "Cold thunder just rattled my windows. She's knocking. We're not answering babe.",
    "Cold and booming so hard my coffee rippled. Girl leave my coffee out of this babe.",
    "Cool and stormy. She's being a lot tonight. We get it. You have feelings. Stay dry girl.",
    "Cold thunder just flickered every light on my block. She's too much right now babe.",
    "She's booming in the cold like she has a point. What is the point girl. Jacket on and stay in babe.",
  ],
  TemperatureTier.flannelWeather: [
    "Mild and booming. Cracked a window. She's therapeutic as fuck girl.",
    "She's having a full menty B but the temp is fucking perfect. Crack a window and enjoy the show babe.",
    "She's throwing a tantrum and the nice temp is holding my hand through it. One out of two ain't bad girl.",
    "She couldn't just give us a nice fucking day? Had to add pyrotechnics. Honestly though? Here for it babe.",
    "She's out there doing the absolute most and I'm in here doing the absolute least. That's called balance babe.",
    "Mild and booming. She just rattled every window like she's knocking. We're not answering. We're cozy girl.",
    "Pull up a chair and let her have her little tantrum. She'll tire herself out eventually babe.",
    'Volume at ten. Consideration at zero. Temp is fucking perfect though. Two out of three girl.',
    "Mild thunder so close the floor vibrated. She's communicating through bass now. Message received girl.",
    "Mild and stormy and I'm watching her fucking lose it from the window like reality TV. Best episode yet honestly.",
    'Rain on the window thunder in the distance perfect temp. Did she finally do something right? Kind of. Almost girl.',
    "Mild and fucking booming. She's here and she's not apologizing. Stay safe stay dry babe.",
    "Perfect temp and she's out there fucking screaming. Unhinged but make it cozy babe.",
    "Mild and booming so hard my walls shook. She's got a point and she's making it loud girl.",
    'Mild thunder at this temp just hits different honestly. Like free therapy babe.',
    "Mild and absolutely losing it out there. My windows are vibrating and I'm vibing girl.",
    "She's booming at the perfect temp and I've got a window cracked like a psycho. No regrets babe.",
    'Stormy and mild. She boomed so loud my dog just looked at me like this is your fault. Is it? Girl.',
    "Perfect temp. Thunder shaking the roof. She's doing too much and I'm doing nothing and it's beautiful babe.",
  ],
  TemperatureTier.shortsWeather: [
    'Summer storm energy. Crack a window and let her serenade you with chaos. Therapeutic as fuck girl.',
    "Warm and stormy. She's so alive out there I can feel it through the walls. Electric as fuck babe.",
    'Warm and fucking booming. Might kill you but vibes are immaculate babe. Stay safe out there.',
    "Warm and stormy. She's out here setting off car alarms. Chaotic queen. Stay safe babe.",
    "Summer storm energy. I'm on the porch watching her perform. Best seat in the house bitch.",
    "Storming and warm as fuck. She's louder than my thoughts and I've never been more grateful girl.",
    "Hot n stormy. She's being so fucking theatrical the trees are swaying. Standing ovation from nature girl.",
    "The rain is warm as fuck the thunder is booming she's having the time of her life and honestly same girl.",
    'Warm and fucking booming. My cat just astral projected under the bed. Gone girl.',
    "She's going absolutely apeshit out there and I'm on the porch clapping. Summer storms are such a vibe babe.",
    'She just boomed so hard my drink rippled. Jurassic Park shit in my kitchen babe. Stay safe out there.',
    "Warm and feeling this thunder in my chest. She's not making noise she's making contact girl.",
    'Warm and booming. She really said cancel your plans I am your plan tonight. Stay safe out there girl.',
    'Warm storm just walked in like she fucking owns the place. Honestly she does. We just live here babe.',
    'Warm and storming. She said you thought tonight was yours. Cute babe.',
    "Warm thunder shook my windows like she's checking if anyone's home. We're home. We know girl.",
    'Warm and booming. She really walked in and every plan I had walked out. Stay dry babe.',
    "Warm and storming and I'm on the couch with popcorn watching her meltdown like it's HBO babe.",
    "Warm thunder just said fuck your quiet night. I'm the plans now babe.",
    "Warm thunder. I'm not scared I'm impressed honestly. Okay I'm a little scared babe.",
    "She's warm and electric and unhinged and I would die for her honestly girl.",
  ],
  TemperatureTier.scorcher: [
    'Hot and fucking booming. Is she okay? No. Do we love her? Absolutely. From inside babe.',
    'Scorching thunder. Did she just fight the fucking sun? I think she just fought the sun girl.',
    'Hot as fuck and she just boomed so hard my AC kicked on out of fear. Did she scare my house babe?',
    'Why the fuck is she going this hard in this heat? Like girl who hurt you. Stay inside babe.',
    "Hot thunder. The sun started it and honestly? She's finishing it. Stay dry girl.",
    "Scorching and booming. She's having a whole moment out there. Are we crying? Maybe. From inside babe.",
    "Hot storm and she's putting on the show of her fucking life. Who told her she could do this girl?",
    "She's thundering in scorching heat and honestly? Icon behavior. Stay the fuck inside babe.",
    'Hot and storming. Did the heat deserve this? Yes. Did she have to go that hard? Also yes girl.',
    'Hot and booming. Is it a breakdown or a moment? Either way she looks incredible girl.',
    'Thunder on a scorcher. Did she just tell the heat to eat shit? Because I heard it too babe.',
    "Scorching and storming. She's literally everything right now. Like how is she doing this girl.",
    "She's booming at the sun like girl you're done. Go home. It's over. Stay dry babe.",
    'Hot storm. Is the sun embarrassed? She should be. She got cooked by her own weather girl.',
    'Scorching thunder and she walked in and the heat just left? Like it got up and left babe.',
    'Hot and electric and completely fucking unhinged. Is she perfect? She might be perfect girl.',
  ],
};

const thunderstormExplicitNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She brought thunder to a freezing night. Girl what are you proving. Stay inside babe.",
    "She's got her own sound system and strobe lights. Too much in this cold honestly girl.",
    "She's cracking lightning in single digits. The cold wasn't enough she needed special effects babe.",
    "She brought pyrotechnics to a Tuesday. Read the room girl. Bundle up and stay in babe.",
    "The audacity to add electricity to this cold. She's so chaotic. Stay inside girl.",
    "Single digits and she added thunder AND lightning. Girl that's a lot. Stay warm babe.",
    "She's so cold and so loud the windows are fogging from the bass. She's too much girl.",
    "The sky just boomed so hard the whole house shook. She's being extra tonight. Stay in babe.",
    "She's flickering the power in the cold dark. Girl this is chaotic. Bundle up inside girl.",
    "She said cold wasn't dramatic enough so she added a whole light show. Classic her babe.",
    "She's flashing and booming in single digits. Girl nobody asked for all this. Stay inside girl.",
    "She's directing producing and starring in her own show tonight. In the cold. Too much babe.",
  ],
  TemperatureTier.freezing: [
    "Walls vibrating below freezing. Girl can you calm the fuck down. Bundle up inside babe.",
    "She just boomed so loud in the freezing dark. She's being a lot tonight. Stay warm girl.",
    "Lightning lit the whole sky below freezing. Then took it back. Such a tease. Stay in babe.",
    "Freezing thunder at night. She set up surround sound and a strobe light. Girl this is too much babe.",
    "She rattled every dish below freezing. She's being chaotic as hell tonight. Stay inside girl.",
    "Car alarms joining in below freezing. She started a collaboration nobody asked for. Stay warm babe.",
    "Lightning flash below freezing. Full sky lit up. She's being so extra tonight. Bundle up girl.",
    "She's going off below freezing and the whole city can hear her. She's a lot right now babe.",
    "Flash after flash below freezing. She's really giving everything tonight. Stay inside girl.",
    "Full concert below freezing at night. Nobody bought tickets but she's performing anyway. Bundle up babe.",
  ],
  TemperatureTier.jacketWeather: [
    "She just boomed so loud the whole city woke up. Girl we're trying to sleep. Jacket weather too babe.",
    "Every boom is her knocking. We're not answering. Stay dry and cozy girl.",
    "She's being so loud at jacket temp. Girl this is a lot for a weeknight babe.",
    "She's making her presence known. Very fucking loudly. Jacket on if you go anywhere girl.",
    "She's been going off for an hour. Girl take it down a notch. Stay inside babe.",
    "She's out there doing sound check for nobody. Chaotic energy tonight girl.",
    "She's out there bowling in the sky and getting strikes every time. Too much babe.",
    "She's playing drums on the roof. She's enthusiastic about it. Jacket weather and chaos girl.",
    "She just shook the windows and didn't apologize. Classic her. Stay dry babe.",
    "She just lit up my whole bedroom through the curtains. Girl I was sleeping. Jacket weather chaos girl.",
    "She's so loud tonight. Like girl we get it you have feelings. Stay cozy inside babe.",
    "She's doing pyrotechnics at jacket temp. The budget on this production is insane girl.",
    "She's got the bass the treble and zero chill tonight. Jacket on and stay in babe.",
    "Every crack of thunder sounds closer. She's being dramatic as hell. Stay inside girl.",
    "She boomed so hard the power flickered. She's editing the electricity now. So extra babe.",
    "The lightning flash lasted two seconds and lit up three rooms. She's a lot tonight girl.",
    "She's going full production outside at jacket temp. Chaotic queen. Stay inside babe.",
    "The lightning just lit up my whole bedroom. Girl it's a cool night calm down babe.",
    "She just thundered three times in a row. She's got something to say. Noted girl.",
    "The power went out for half a second. She's being SO extra tonight. Stay inside babe.",
  ],
  TemperatureTier.flannelWeather: [
    "Blanket candle couch. She's losing her fucking mind but we're thriving babe.",
    "She's having a full meltdown outside and I'm under a blanket with tea watching. Dinner and a show girl.",
    'She cracked the sky open and I cracked a window. Free concert. Best acoustics of my fucking life babe.',
    "She's screaming into the void and I lit a candle for her. Supportive from a distance girl.",
    "She just shook the walls so hard a picture frame tilted. She's redecorating from the sky now babe.",
    "She's screaming into the void and the temp is rubbing our back through it. Cozy chaos. Love that for us girl.",
    "She boomed so hard the candle flickered. She's knocking out the ambiance one thunder at a time babe.",
    "Window cracked rain smell hitting and she's providing the bass. Didn't ask for a spa night but here we are girl.",
    "She's performing a whole concert outside and I'm horizontal with a blanket. She works so I don't have to babe.",
    'She lit up my whole bedroom for one second and I saw everything including my poor life choices. Back to dark. Cozy though girl.',
    "She's putting on a whole production and the temp said your ticket includes comfort. Best deal of my life babe.",
    "She keeps booming like she's trying to get our attention. Girl we see you. We're just not coming out girl.",
    "She can't just give us a nice night she has to add pyrotechnics. Extra but honestly iconic babe.",
    "She's the friend who shows up with fireworks to a casual dinner. Nobody asked but nobody's mad girl.",
    "She's being dramatic as fuck outside and the temp is being an angel inside. I know which one I'm with babe.",
    "She boomed so hard the dog got under the blanket with me. She's a matchmaker now girl.",
    "Every crack of thunder is her adding another chapter to tonight. She's writing a whole novel out there babe.",
    "She just flickered every light on the block. Girl that's chaotic. Cozy in here though babe.",
    "She's at full volume and zero apologies but the temp is carrying the whole damn night. We'll allow it babe.",
    "Pull the blanket up and let her have her little moment. She'll tire herself out eventually girl.",
    "Mild stormy night and I'm watching her lose it from the couch like reality TV. Best episode yet babe.",
    "She's performing to an audience of one and I'm giving her a standing ovation from my bed girl.",
    'She took a perfectly nice night and gave it a soundtrack. Overachiever shit honestly babe.',
    "Thunder so close the floor vibrated. She's communicating through bass now. Message received girl.",
    "She's so dramatic tonight the candle I lit feels like a prop in her movie. I'm an extra and I'm fine with it babe.",
  ],
  TemperatureTier.shortsWeather: [
    "She's hot and she's booming. Hot as fuck tbh. Get on the porch and watch babe.",
    'The air smells like rain and chaos. Fucking love this shit girl.',
    'She just cracked the sky open. Holy shit babe.',
    "She's scary she's sexy she's everything. I'm obsessed girl.",
    'Windows open and the rain smell just hit. I would bottle this shit if I could babe.',
    "She's putting on a fucking show. Get on the porch babe.",
    "She's the fireworks show we didn't know we fucking needed babe.",
    "She's feral fucking gorgeous and loud. The whole package girl.",
    "The air smells insane after that last crack. She's a whole fucking experience babe.",
    "She's got the sky flashing like a VIP section. We're on the list girl.",
    "She's fucking electric. Literally and figuratively girl.",
    'The lightning is so close I can smell it. Ozone and chaos. Her signature scent bitch.',
    'Holy shit. She just cracked the sky open and the rain smells like redemption babe.',
    "She's beautiful and terrifying. If she had a dating profile I'd swipe right so fucking damn fast babe.",
    "She's fucking beautiful and screaming. If she had a wine glass she'd throw it girl.",
    "She's a smoke show. Literally. There's steam rising off the pavement girl.",
    "She's fucking putting on a whole show. Porch. Now. Don't argue babe.",
    'She just turned night into day for one second and took it back. Emotional whiplash babe.',
    "She's warm and violent and the air smells incredible after each crack girl.",
    "She's the hottest mess I've ever seen and I mean that as a compliment babe.",
    "She's scary beautiful. The kind you can't look away from girl.",
    "She's flashing and booming and the air is thick with drama babe.",
    "Lightning just lit up the clouds from inside. She's glowing girl.",
    "The thunder rolls through your chest. She's got bass babe.",
    "She's performing her whole discography tonight. Every hit girl.",
  ],
  TemperatureTier.scorcher: [
    "She's throwing lightning bolts in a sauna. This is hell with a light show babe.",
    "The thunder isn't cooling shit down it's just adding noise to the misery girl.",
    'Hot thunder. The air is thick and every boom vibrates through the humidity babe.',
    "She's so hot and so angry. Relatable as fuck girl.",
    "She said you're hot? Have some lightning too. Generous bitch girl.",
    "She's not just flashing us she's going full fucking nude. Like girl chill.",
    'She added special effects to the sauna. Nobody asked girl.',
    "She's not cooling us off she's cooking us with sound effects bitch.",
    "She's fucking directing an action movie and we're all extras babe.",
    'Holy shit. She turned the whole city into a boiler room. No guest list no exit babe.',
    "The thunder is just the microwave timer. We're done. We're cooked girl.",
    'The heat and the noise are competing for who can kill us first babe.',
    "She's cracking lightning in a sauna. Each bolt is just heating us more babe.",
    "She's so hot and loud the pavement is steaming between each flash girl.",
    "Every thunder boom pushes a wave of hot air through the window. She's breathing on us girl.",
    "The lightning lit up the steam rising off the road. She's making her own fog machine babe.",
    "She's got lightning and humidity and zero mercy girl.",
    "She's so loud and so hot. She's the friend who's too much at parties girl.",
    "Scorching hot thunderstorm at night. I can't tell if I'm sweating or getting rained on babe.",
    "She's the final boss of summer nights. Unbeatable girl.",
  ],
};
