import '../../../features/weather/domain/entities/temperature_tier.dart';

const blizzardQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Blizzard in single digits. She's giving the storm scene in Frozen before the love saves everyone. Stay in girl.",
    'Peak villain weather. She is not playing and she is not cute. Every layer you own and stay inside bestie.',
    'Single digit blizzard. This is a survival movie now. Do not go outside. Blanket burrito babe.',
    "She's burying everything in sight. The snow queen has no chill. Warmest boots and stay in girl.",
  ],
  TemperatureTier.freezing: [
    "Freezing blizzard. She's giving Disney movie ice storm energy. Stay inside in your warmest PJs bestie.",
    "Blizzard below freezing. She's erasing the world one snowflake at a time. Do not leave. Hot cocoa time babe.",
    'She went full ice storm villain arc. Schools closed plans cancelled. Stay safe in every layer girl.',
    'Freezing blizzard. Even Elsa would say this is a bit much. Stay in with fuzzy socks bestie.',
  ],
  TemperatureTier.jacketWeather: [
    "Blizzard at jacket weather. She's being dramatic and she knows it. Stay inside girl.",
    'She went full snow tantrum at a manageable temp. Overreacting queen honestly. Jacket on if you must go out bestie.',
    'Blizzard at cool temps. She did not need to go this hard. Stay in your hoodie babe.',
    "She's blizzarding at jacket weather like a fairy tale villain with something to prove girl.",
  ],
  TemperatureTier.flannelWeather: [
    "Blizzard at mild temps. She's giving animated movie boss battle for no reason. Stay inside bestie.",
    'She picked a perfect temp day to have a full snow meltdown. Iconic honestly. Cozy sweater babe.',
    "Mild blizzard. She's the plot twist nobody asked for. Stay safe in your warmest layers girl.",
    "She's blizzarding at flannel weather. The script is wrong but she is committed bestie.",
  ],
  TemperatureTier.shortsWeather: [
    "Warm blizzard. She's giving fairy tale that went completely off the rails girl.",
    "She's blizzarding in warm temps and none of it makes sense. Stay inside bestie.",
    'Snow melting on contact and she will not stop. Relentless queen. Shorts feel wrong but okay babe.',
    'Warm blizzard. The laws of weather no longer apply. She rewrote everything girl.',
  ],
  TemperatureTier.scorcher: [
    "Blizzard in a scorcher. She broke reality and she's proud of it. Lightest clothes somehow bestie.",
    'Scorching blizzard. Every rule has been violated. She is the final boss. SPF and stay inside babe.',
    'Hot blizzard. She showed up where she has no business being. Absolute chaos girl.',
    'She combined everything impossible and called it a Tuesday. Legend honestly bestie.',
  ],
};

const blizzardExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She's fucking apocalyptic. Stay inside immediately babe.",
    'Having a full fucking breakdown in single digits. Burying cars girl.',
    'Shutting down highways like she owns them. Bundle the hell up and stay in.',
    'Storm from X-Men energy. Freezing everything but honestly hot af.',
    "She really said nobody's going anywhere and she fucking meant it babe.",
    'Holy shit. She went nuclear in single digits babe. This is not the day. Stay inside girl.',
    'Not snowing. Declaring fucking war. Single digits zero visibility.',
    "She's fucking channeling Carrie right now. Terrifying. Do not go outside babe.",
    "Peak villain arc at the worst temp. She's unwell. Stay inside babe.",
    'This is not a snow day this is a survival situation. Stay in girl.',
    "She's not playing she's not cute she's dangerous. Stay inside babe.",
    "She's blizzarding so hard she buried the sidewalk. Do not go outside. I mean it girl.",
  ],
  TemperatureTier.freezing: [
    "She's snowing sideways. She's not fucking around babe.",
    'Terrifying as shit at her ideal temp girl.',
    "Burying everything in sight. Doesn't give a single fuck honestly.",
    "Ruining every fucking plan you had. She doesn't negotiate babe.",
    'Closing schools canceling flights. Having the time of her fucking life babe.',
    'Cold as fuck snowing sideways. Committed harder than any ex honestly.',
    "She's performing for nobody because nobody can fucking see. Stay home babe.",
    "She's not just blizzarding she's making a point. Stay the fuck in babe.",
    'Katniss in the arena energy. Survival mode. Stay inside babe.',
    'She watched The Day After Tomorrow and took notes. Freezing blizzard full disaster babe.',
    "She's erasing the entire neighborhood one street at a time babe. Do not leave.",
    'Going absolutely feral. Schools closed. So are your damn plans girl.',
  ],
  TemperatureTier.jacketWeather: [
    'Mild temps and she said full blizzard anyway. Unhinged as fuck girl.',
    "Going nuclear at a temp that doesn't deserve it. Extra as shit girl.",
    'Overkill af. War at a mild disagreement.',
    "Burying the city and it's not even cold. The drama. Incredible as hell babe.",
    "Showed up uninvited. She's staying. Bold as shit.",
    'Siouxsie and the Banshees energy. Cold chaotic af. Stay inside girl.',
    "Alanis wrote You Oughta Know for this weather. Fucking dramatic won't stop. Stay in babe.",
    'The Revenant vibes. Survival mode honestly af girl.',
    'Kate Beckinsale in Whiteout energy. Relentless at this temp. Stay inside babe.',
    'Villain energy. Does not belong here babe.',
    'Did not need to go this damn hard babe.',
    'Overreacting and knows it. Stay inside damn it girl.',
  ],
  TemperatureTier.flannelWeather: [
    "She brought a blizzard to mild weather. Like showing up in a ball gown to a barbecue babe.",
    'Mild weather and she went full blizzard. Nobody asked for this shit girl.',
    'Like she belongs here. Unhinged as shit girl.',
    'Holy shit. At a temp that makes zero sense. Next level honestly.',
    'Sword to a fucking pillow fight.',
    'Confused and furious. Dangerous fucking combo girl.',
    'Florence and the Machine vibes. Epic as fuck girl.',
    'Holy shit. Mild weather is a damn suggestion to her.',
    'Nicole Kidman in The Others energy. Trapped everyone inside. Not sorry babe.',
    "Adele wrote Rolling in the Deep for this. She's breaking everything. Stay safe girl.",
    'Frances McDormand in Fargo energy. Iconic honestly babe.',
    'Villain in the wrong damn movie. Stay inside babe.',
  ],
  TemperatureTier.shortsWeather: [
    "Burying the city in snow and it's warm. What the actual hell babe.",
    'Chose to fucking terrify every meteorologist alive.',
    "She thinks she's Stevie Nicks right now. Mystical as hell babe.",
    "Portishead Glory Box energy. Moody surreal af. I'm not okay girl.",
    "She's channeling Promising Young Woman. She broke every rule and she's proud of it babe.",
    "She won't stop. Relentless. The snow is melting on contact and she does not care girl.",
    'Not pretending to make damn sense. Get inside babe.',
    "A blizzard at shorts weather. She's performing open heart surgery on reality right now babe.",
    "She's blizzarding at eighty degrees like someone dared her. Nobody dared her. She dared herself girl.",
    'Warm blizzard. The snowflakes are confused. My weather app is crying. Everyone is yelling babe.',
    "She's burying cars in snow while people are in tank tops. This is performance art girl.",
    "Blizzard at shorts weather. My neighbor is shoveling in flip flops. She caused this. She's proud babe.",
  ],
  TemperatureTier.scorcher: [
    'Nature filed a restraining order. She violated it. Terrifying as shit honestly.',
    'Dumping snow in extreme heat out of pure spite. Science left the chat girl.',
    'The audacity. The fucking commitment babe.',
    'M.I.A. Paper Planes vibes. Chaotic as fuck. Stay in girl.',
    'Mad Max energy. End of the world. Stay inside af babe.',
    'Rules were boring. She wrote new ones babe.',
    'Miley Cyrus wrote Wrecking Ball for this. Plus scorching. Nothing makes sense girl.',
    'End times. She is the damn main event babe.',
    "She's dumping snow at a hundred degrees like a villain who lost the plot. And the thermometer girl.",
    'Blizzard on a scorcher. The weatherman quit on air. She broke a professional babe.',
    "She's burying the city in snow while the pavement is hot enough to fry an egg. Choose a lane girl.",
    "Hot blizzard. My ice cream and my sanity melted at the same time. She's efficient babe.",
  ],
};
