import '../../../features/weather/domain/entities/temperature_tier.dart';

const drizzleQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Drizzle in single digits. She can't even commit to snow. Disappointing on every level. Stay inside bestie.",
    'Single digit drizzle. The saddest weather event in Disney history. Puffiest coat and stay in girl.',
    "Misting at single digits. She's giving the sad rain scene but worse because it's lazy. Every layer you own babe.",
    'Drizzle this cold is just disrespectful. Even Inside Out Sadness would complain. Blanket burrito bestie.',
  ],
  TemperatureTier.freezing: [
    "Freezing drizzle. She's giving the before scene in every makeover movie. Heaviest coat on girl.",
    'Below freezing and misting. She chose the most annoying option available. Scarf and gloves babe.',
    'Freezing and drizzly. Too lazy to snow too petty to stop. Warm boots on bestie.',
    "She's misting below freezing like a passive aggressive fairy godmother. Layer up and stay dry girl.",
  ],
  TemperatureTier.jacketWeather: [
    "Cool and drizzly. She's giving the part in Tangled where Rapunzel first feels rain. Jacket on bestie.",
    'Drizzle at jacket weather. Very indie coming of age film energy. Go be contemplative in your hoodie babe.',
    'Light mist and cool air. She turned the day into a fairy tale rain scene. Cute jacket on girl.',
    'Drizzly and cool. Taylor Swift would call this the tortured poets weather. Jacket and rain boots on bestie.',
    "She's giving Rapunzel first rain experience energy. Light jacket and enjoy the magic girl.",
    'Drizzle and jacket weather. Very Olivia Rodrigo walking scene in a music video. Light layers babe.',
    'Cool drizzle. Very Raya exploring a new land in the rain vibes. Jacket and umbrella on bestie.',
  ],
  TemperatureTier.flannelWeather: [
    "Mild drizzle. She's giving the kiss in the rain scene but gentle. Flannel and a cute umbrella on babe.",
    "Drizzly flannel weather. She added mist to perfection because she's directing a fairy tale girl.",
    'Light rain at this temp. Olivia Rodrigo would write a whole album about this moment bestie.',
    "She's misting at the perfect temp. Very fairy tale enchanted garden energy. Cozy sweater babe.",
    "Mild drizzle energy. She's giving Taylor Swift cardigan rainy day writing session vibes girl.",
    'Drizzly and flannel weather. Very Sabrina Carpenter cozy cafe music video. Cute boots on bestie.',
    "Light rain and mild. She's giving the scene where the garden comes alive in the rain. Flannel on babe.",
  ],
  TemperatureTier.shortsWeather: [
    "Warm drizzle. She's giving the summer rain scene in every Disney movie. Sandals on and go dance bestie.",
    "Drizzly and warm. Sabrina Carpenter poolside sprinkle energy. Don't even go inside girl.",
    "Warm mist on bare legs. She's giving tropical princess vibes. Sundress babe.",
    'She added a light spritz to a perfect day. Spa upgrade courtesy of the sky. Shorts on bestie.',
    "She's giving Moana gentle rain on the ocean energy. Warm and refreshing. Sandals on girl.",
    'Warm drizzle. Very Luca running through Italian streets in summer rain vibes. Shorts on babe.',
    "Light rain and warm. She's giving that scene where everyone plays in the sprinklers. Tank top on bestie.",
  ],
  TemperatureTier.scorcher: [
    "Scorching drizzle. She made steam. That's not rain that's a sauna malfunction. Lightest clothes girl.",
    'Hot drizzle. She brought a spray bottle to a wildfire. Cute effort. Hat and SPF bestie.',
    "Drizzle on a scorcher. She's trying to help and making it humid. Water bottle on hand babe.",
    'Scorching and misting. The rain evaporates before it lands. Hydrate yourself and find shade girl.',
  ],
};

const drizzleExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Drizzling in single digits. Fuck no. Arrested. Straight to jail.',
    'Freezing drizzle like just be snow already. The fuck?',
    'Freezing drizzle. Absolutely the fuck not. Stay home babe.',
    'Drizzling in single digits. What the actual fuck is this. No seriously what is this.',
    "Single digit drizzle. She's pissing on us from the sky. In the cold. Classy girl.",
    "Drizzle at this temp. It's not rain it's not snow it's just fucking rude babe.",
    "She's misting in single digits. Like girl either rain or don't. This half ass shit is embarrassing girl.",
    "Drizzling in single digits. Go to hell. Oh wait we're already here. Forgot babe.",
    "Can't even commit to snow in these temps? Seek help girl like actually.",
    "Single digit drizzle. She can't even be bothered to snow properly. Lazy and cold. The fucking worst.",
    'Drizzle at this temp is a hate crime. I said what I said.',
  ],
  TemperatureTier.freezing: [
    "It's giving A Quiet Place. Cold barely making a sound and honestly fucking terrifying babe.",
    'Below freezing and she chose drizzle. The most annoying option on the menu. Every fucking time.',
    "It's giving Titanic. Fucking cold wet and not helping anyone right now babe. Stay in.",
    'Below freezing with mist. Minimal effort maximum annoyance. Respect af honestly.',
    'Freezing drizzle. Somehow worse than rain and snow combined. She found the loophole. What the hell.',
    'Light drizzle freezing temps. Too lazy to rain too petty to quit.',
    "Freezing and misting. She's out here doing the bare minimum to ruin your day. And succeeding.",
    "Freezing drizzle. She's spitting on us from above like a llama. A cold wet llama girl.",
    "Below freezing and drizzling. She showed up with the energy of a passive aggressive sticky note. Bundle up babe.",
    "Freezing drizzle. She picked the most annoying weapon in her arsenal. Surgical strike energy girl.",
    "She's misting below freezing like a spray bottle aimed at a cat. We're the cat babe.",
    "Drizzle below freezing. Not enough to stay home not enough to enjoy. She lives in the gray area girl.",
  ],
  TemperatureTier.jacketWeather: [
    "It's giving film noir. No crime. Just fucking vibes. Jacket on babe.",
    "She's barely raining and I'm fully in love. Embarrassing honestly girl.",
    "I'm damp and cold as fuck. It's fine we're fine we got this babe.",
    "Misting us like houseplants. We're the damn ferns. Standing here taking it girl.",
    'Low effort. High atmosphere. Iconic ratio honestly.',
    "It's giving fog machine. But make it fashion babe.",
    // "My glasses have tiny dots on them and I can't see shit. She's targeting me babe.",
    // "She's doing that thing where she barely rains but your hair knows. Hair always fucking knows girl.",
    // 'Cool drizzle. Too wet to enjoy. Too mild to complain. She boxed me in queen.',
    "Cool drizzle. She got us like the perfume testers at Sephora. We smell like rain now. Didn't ask girl.",
    "She's misting us like a fragrance counter ambush. Like girl chill.",
    "It's giving Stevie Nicks energy. Pretty and iconic as fuck. Go spin somewhere babe.",
    'Cool and misting. Jacket slowly getting heavier. Attitude slowly getting worse. Connected events honestly.',
    "It's giving lo-fi music video. We're all starring in it. No audition needed babe.",
    "Cool drizzle. Ma'am we are not produce. Stop misting us girl.",
    'Bare minimum rain. Standing ovation from me. My standards are in hell girl.',
    "She turned the whole city into a produce aisle. We're the leafy greens. Damp and on display babe.",
    'Wet pavement is serving runway. The puddles have more style than me. She did that babe.',
    "Cool drizzle. She made a puddle look profound. It's just water. I'm fucking delusional girl.",
    'Drizzle at this temp is honestly hot as fuck. Filing a complaint. With who. Unclear babe.',
    "Cool drizzle. She's got us on the produce mister schedule. We're the broccoli now babe.",
  ],
  TemperatureTier.flannelWeather: [
    "Mild and drizzly. She's in her soft girl era. Zero fucking notes babe.",
    "She's misting at the fucking perfect temp and I am emotional. Go play babe.",
    "It's giving manic pixie vibes. Drizzly mild whimsical. Rain boots and romp babe.",
    "She's drizzling at the perfect temp like she read a fucking manual for once. Proud of her honestly.",
    'Mild drizzle. No drama no bullshit just vibes. Who is this bitch and what did she do with the weather.',
    'Tracy Chapman Fast Car vibes. Mild drizzle taking you somewhere. Flannel and go bitch.',
    "Drizzle at this temp. She's being romantic without asking. Fuck. Catching feelings again babe.",
    'Mild drizzle. Flannel and rain boots. Get the fuck outside she deserves a witness babe.',
    "Drizzly and mild. She's being cute as fuck and I hate that I love it. Get outside girl.",
    'Drizzle at this temp is a whole damn mood. Hoodie on get your ass out there babe.',
    "Mild mist. She showed up gentle and perfect. Throw on a flannel and go enjoy her bitch.",
  ],
  TemperatureTier.shortsWeather: [
    "Warm drizzle. Can't commit to rain. At this temp who gives a shit babe.",
    "She's channeling Kiki's Delivery Service. Warm whimsical magical. Go play.",
    'Light warm rain. Doing the bare minimum and somehow fucking nailing it. Good for her.',
    'Drizzly and warm af. Gently misting you like fancy produce. Thanks girl.',
    "Light drizzle warm air. She's being romantic and nobody asked her to be. Go play girl.",
    "She thinks she's Gwen Stefani right now. Warm drizzle unbothered as fuck. Love that for her.",
    "Warm and drizzly. She's out here seducing us with mist and it's fucking working girl.",
    "Warm and drizzly. She's giving tropical rain in a romcom. Main character shit babe.",
    "Showed up warm and soft and drizzly. She's catching feelings and they're contagious as fuck girl.",
    "Warm drizzle. She's being flirty and I refuse to be this easy. But here we are bitch.",
    "Drizzly and nice as fuck. She's setting a mood and I'm fully in it. Go play babe.",
    "Warm mist. She's giving main character in the rain moment. Go have yours babe.",
    'Natasha Bedingfield wrote Unwritten for this exact moment. Go feel the rain on your skin babe.',
    'Warm drizzle. The air tastes like summer and bad decisions. Shorts on go make some girl.',
    'Warm drizzle. She misted you like a houseplant. Get the fuck outside babe.',
    'Drizzly shorts weather. No umbrella needed. Shorts on go get a little wet bitch.',
  ],
  TemperatureTier.scorcher: [
    'Scorching and drizzly. Trying to cool us down barely fucking helping girl.',
    "Drizzle on a scorcher. Like here's some warm rain you ungrateful bitch. She's so sweet.",
    'Hot as fuck and drizzling. Minimal effort maximum humidity. Tank top and go girl.',
    'Scorching with light rain. Bare minimum and somehow still appreciated babe.',
    'Hot as shit and misting. Sky sent her intern to handle a crisis girl.',
    'Hot as fuck and misting. She brought a squirt gun to a wildfire. A for effort babe.',
    "She thinks she's Lizzo right now. So fucking hot she's steaming. Feeling herself honestly.",
    "Hot drizzle. She's trying to put out a fire with a Dasani. Bless her heart.",
    "Scorching and drizzly. The rain is hot. The air is hot. Everything is hot. She's unwell babe.",
    "Drizzle on a scorcher. It's not helping. Congrats girl you made steam.",
    // "Hot drizzle. She's applying a band aid to a bullet wound. Adorable. Hydrate girl.",
    "Scorching and drizzly. She sent one ice cube to a house fire. Noted. Hydrate babe.",
    // "Hot drizzle. The drops are evaporating before they hit the ground. She's fighting gravity and losing. Bless her honestly girl.",
  ],
};
