import '../../../features/weather/domain/entities/temperature_tier.dart';

const foggyQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Fog and single digits. She's giving the dark forest scene in every fairy tale. Stay inside in your warmest PJs bestie.",
    "Foggy and freezing cold. Can't see and can't feel your fingers. Fuzzy socks and stay in girl.",
    'She wrapped the world in fog at single digits. Very enchanted forest entrance energy. Puffiest coat on babe.',
    'Single digit fog. The enchanted forest is not taking visitors today. Blanket burrito time bestie.',
  ],
  TemperatureTier.freezing: [
    "Freezing fog. She's giving the fairy tale curse before the princess breaks it. Heaviest coat on girl.",
    'Below freezing and foggy. Very into the unknown Frozen energy. Scarf and warm boots on bestie.',
    'Fog and freezing temps. She rolled in like a Disney villain with a fog machine. Layer up babe.',
    "Freezing and foggy. She erased the world and froze what's left. Earmuffs and gloves on girl.",
  ],
  TemperatureTier.jacketWeather: [
    "Foggy and cool. She's giving mysterious forest path in a fairy tale. Jacket on go explore bestie.",
    'Cool fog rolling in. Very Disney enchanted morning energy. Layer up and wander babe.',
    'Foggy jacket weather. She turned the neighborhood into a storybook. Hoodie on and go get lost in it girl.',
    'She rolled in all cinematic and cool. Main character in the mist. Cute jacket on bestie.',
    "She's giving Rapunzel first morning outside the tower in the mist energy. Jacket on go explore girl.",
    'Foggy and cool. Very Merida riding through the misty highlands vibes. Light layers on babe.',
    'Cool fog energy. Very mysterious protagonist about to discover a secret garden. Denim jacket on bestie.',
  ],
  TemperatureTier.flannelWeather: [
    "Foggy and mild. She's giving enchanted garden vibes. Flannel on go be whimsical babe.",
    "Mild fog. Very Belle walking through a misty village morning energy. She's gorgeous and mysterious bestie.",
    'Fog at this temp is actually magical. She understood the fairy tale assignment. Cozy sweater on girl.',
    'Foggy flannel weather. She wrapped the world in silk and whispered go explore. Cute boots on babe.',
    "Foggy and mild. She's giving Raya arriving in a new land for the first time vibes girl.",
    'Flannel weather fog. Very enchanted forest before you meet the magical creatures energy bestie.',
    'Mild and misty. The world looks like a fairy tale watercolor and you are in it. Best fall outfit babe.',
  ],
  TemperatureTier.shortsWeather: [
    "Warm fog. She's giving tropical island morning mystery vibes. Shorts on bestie.",
    'Foggy and warm. She turned the whole neighborhood into a spa. Sundress on girl.',
    "Warm and misty. She's giving Moana but make it mysterious. Sandals on and go wander babe.",
    'Fog at this temp is just a free facial. She is looking out for your skin. Tank top on bestie.',
  ],
  TemperatureTier.scorcher: [
    "Hot fog. She's steaming everything like a dumpling. Lightest clothes and drink water immediately girl.",
    "Foggy scorcher. Can't see and can't breathe. She chose violence today. Hat and water bottle bestie.",
    'She combined heat and fog like a villain mixing potions. Lightest outfit and hydrate babe.',
    "Scorching fog. The air is soup and she's serving it whether you ordered it or not. SPF on girl.",
  ],
};

const foggyExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Foggy single digits. Can't see shit can't feel your face. Love that. Puffer on babe.",
    "It's giving Silent Hill. Creepy af cold af. Every layer and watch out babe.",
    "Foggy and cold as fuck. Mysterious AND mean. Biggest coat babe. Or just don't.",
    "Fog and single digits. Can't see shit can't feel shit. She really thought this through.",
    'Foggy and cold as fuck. She rolled up like a true villain. No announcement just fog babe.',
    'She rolled in fucking mysterious and freezing. Zero visibility. Zero fucks. Bundle up girl.',
    "Cold fog. Fucking dramatic and dangerous. Love the aesthetic but she's trying to kill us. Puffer on girl.",
    'Foggy and freezing. She deleted the sun and the warmth. Ctrl alt delete af babe.',
    "It's giving Suspiria. Cold foggy and she's not letting you leave girl.",
    'Single digits and fog. She said let me take your vision AND your warmth. How generous.',
  ],
  TemperatureTier.freezing: [
    'Foggy and cold as fuck. Mysterious but so not the vibe. Blanket burrito status babe.',
    "It's giving Last House on the Left. Cold and eerie as fuck. Don't get got babe. Watch it.",
    'Foggy and cold af. Vibes are immaculate. Temp is disrespectful. Layers babe.',
    'Fog below freezing. See nothing and freeze. Bold choice. Layer the fuck up babe.',
    'Foggy and cold as fuck. She looks good though. At least she has that going for her.',
    "Fog below freezing. She's gorgeous she's cold she's not sorry. Trifecta from hell.",
    "Fog below freezing. She's the fucking hot villain you root for even though she's ruining your life girl.",
    'Below freezing and foggy. She erased the world and turned down the thermostat. Double homicide. What the hell.',
    "It's giving Kate Bush energy. Foggy cold dramatic. Coat on babe.",
    'Freezing fog. Two words that should never meet. Like no. Warmest coat girl.',
    'Below freezing and she erased the whole view. Classic her. Heavy coat babe.',
    "Foggy and freezing. She showed up gorgeous and cold and won't explain herself. Never does.",
  ],
  TemperatureTier.jacketWeather: [
    "Cool and foggy. I can't see shit but I feel like I'm in a perfume commercial. Going with it.",
    'Cool fog. She hid the road. She hid the trees. She hid the fucking sidewalk. Helpful.',
    'Foggy and cool. Google Maps just said good luck bitch. Even the GPS gave up babe.',
    "Fog at this temp. She's whispering and I'm leaning in. This is how people go missing babe.",
    "Foggy and cool. She showed up soft and moody and I'm following her into the mist. No questions.",
    "Foggy jacket weather. She showed up soft and spooky and I'm weirdly into it. Ignoring red flags is my fav honestly.",
    "Final Destination vibes out here. Foggy cool and she's plotting something. Jacket on eyes open babe.",
    'Foggy and cool. She rolled in like she owns the place. She does right now honestly.',
    // 'Cool fog. She wrapped the world in cotton and said figure it out. Jacket on babe.',
    'Cool and foggy. She erased the horizon and replaced it with vibes. Jacket on go get lost babe.',
    // "Foggy and cool. My neighbor walked past me and I didn't recognize them. She's doing witness protection for fun girl.",
    "Fog at this temp. Just discovered a street I've lived near for three years. She's a tour guide from hell babe.",
    // "Cool fog. She turned my commute into an escape room. She really said good luck out there. Jacket on babe.",
    // "Foggy and cool. A car drove by and disappeared like a magic trick. She's performing street magic girl.",
    // "Fog jacket weather. I just waved at a mailbox thinking it was a person. She's gaslighting me babe.",
    "She rolled in so thick my dog stopped walking and looked at me like are we dead. No baby. Jacket on girl.",
    "Foggy and cool. I can hear footsteps but can't see the person. She invented a new anxiety. Love that.",
    "Cool fog. She put the whole city on airplane mode. No signal no visibility. Jacket on girl.",
    // "Foggy and cool. She turned the sidewalk into a runway except nobody can see you. Fashion for ghosts babe.",
    // "She's so thick right now the streetlights look like they're drowning. Jacket on go save them girl.",
    "Foggy and cold. Girl go back to design school this isn't working for you.",
  ],
  TemperatureTier.flannelWeather: [
    'Foggy dreamy mild af. Mazzy Star on the headphones. Go fade into her babe.',
    'Portishead vibes out there. Moody as fuck fog out in full force. Get outside babe.',
    'Foggy flannel weather. She erased the world and left us the vibes. Fair trade honestly babe.',
    "Mild fog. She dimmed the lights and set the mood. Didn't ask. Didn't need to bitch.",
    "Foggy and mild. I'm outside and I can't see shit and I've never been more at peace. She healed me girl.",
    "She tucked the whole city into bed and left the nightlight on. Mild foggy fucking perfect babe.",
    'Foggy flannel weather. Hoodie on. Vibes high. Get the fuck out there girl.',
    "Can't see the sky. Don't need to. She feels fucking perfect. Flannel on babe.",
    "Fog rolled in mild and moody. She's a whole damn aesthetic. Go be in it girl.",
    "She erased the horizon and left us the perfect fucking temp. Go get lost babe.",
  ],
  TemperatureTier.shortsWeather: [
    'Foggy and warm as fuck. Romcom or horror movie? Shorts on either way babe.',
    'Foggy shorts weather is underrated. Spa energy. Go play girl.',
    "Warm fog. Can't see shit but it feels incredible. Shorts on go girl.",
    "Fog at this temp. She's warm as fuck and I just walked into a tree. Worth it babe.",
    "Foggy and warm. Lost and moisturized. She's multitasking. Queen shit.",
    "Warm and foggy. She just hot boxed the entire neighborhood. Shorts on girl.",
    "Warm fog. Can't see can't care. Shorts on get your ass out there babe.",
    "She's warm and foggy and you don't need to see. You need to feel. Shorts on bitch.",
  ],
  TemperatureTier.scorcher: [
    "Foggy scorcher. Can't see shit and I'm melting. She really covered all the bases. Love that.",
    'Scorching fog. She said let me make it worse and then hide. Strategic bitch.',
    "Hot fog. She's fucking waterboarding us with humidity. Gently. Lovingly. Still waterboarding.",
    'Scorching and foggy. Air so fucking thick you could chew it. Hydrate girl.',
    'Hot and foggy. The humidity has hands today. Stay cool if you can babe.',
    // "Hot fog. My glasses fogged up the second I walked outside. She blinded me twice. Once with fog once with sweat babe.",
    "Foggy scorcher. I can't see and I'm dissolving. She's erasing evidence girl.",
    "She served a scorcher in fog like a villain monologuing behind a curtain. We can feel you girl.",
    "Hot fog. She turned the outside into the inside of a dishwasher mid cycle. We're the dishes babe.",
    "Foggy and scorching. Even my sweat is sweating. She broke the system girl.",
    // "She rolled in hot and foggy like opening a car door in August. Except the car is the whole city babe.",
  ],
};
