import '../../../features/weather/domain/entities/temperature_tier.dart';

const freezingRainQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Freezing rain in single digits. She's giving evil ice queen with no redemption arc. Stay inside girl.",
    'Ice rain at single digits. Every surface is a trap. Do not leave your tower. Warmest boots bestie.',
    'She glazed the world like a cursed fairy tale. Single digits and slippery. Every layer and stay in babe.',
    "Freezing rain this cold. She's the villain the Disney princess hasn't defeated yet. Stay safe girl.",
  ],
  TemperatureTier.freezing: [
    'Freezing rain. She iced the whole kingdom like a fairy tale curse. Warmest boots and stay safe bestie.',
    "She's coating everything in ice. Very Frozen but the scary parts energy. Heavy coat babe.",
    "Below freezing ice rain. She's giving Elsa on her worst day. Gloves on and watch your step girl.",
    'Freezing rain. The sidewalk is a slip and slide and nobody signed up for this. Warm boots on bestie.',
  ],
  TemperatureTier.jacketWeather: [
    "Ice at jacket weather. Sneaky and slippery. She's the plot twist nobody wanted. Rain boots girl.",
    "Freezing rain at cool temps. She's glitching like a broken spell. Watch your step in warm boots bestie.",
    "She's glazing everything at jacket weather. Tricky villain energy. Jacket and careful steps babe.",
    'Ice at this temp is unexpected and unwelcome. Watch every step in your warmest boots girl.',
  ],
  TemperatureTier.flannelWeather: [
    'Ice at mild temps. The simulation is broken. Something is very wrong. Warm boots on bestie.',
    "Freezing rain at flannel weather. She's giving cursed fairy tale energy. Be careful in your boots babe.",
    "Mild air but the ground is an ice rink. She's not making sense. Stay inside girl.",
    'The temp says flannel but the ice says stay inside. Trust the ice bestie.',
  ],
};

const freezingRainExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Coating everything in ice. Villain shit babe.',
    'Madonna Frozen but literal. Everything is ice. The fuck. Stay in girl.',
    'She weaponized the fucking ground. Every step is a death wish.',
    'She turned the whole city into a slip and slide to hell. Fucking diabolical.',
    'She really said fuck your ankles fuck your car fuck your plans.',
    'Jesus. Roads are death traps. She coated the city in ice. Stay home babe.',
    "She's not just fucking dangerous she's actively trying to kill us. Respect honestly.",
    'Glazed every damn surface in ice. Villain mode. Do not get the fuck out there.',
    'Final Destination vibes. Every surface is a trap. Stay in babe.',
    "She thinks she's Megan Fox in Jennifer's Body. Ice cold dangerous gorgeous. Stay inside honestly.",
    "She glazed the city like a donut and now we're all gonna die on the sidewalk.",
    'Her deadliest era. Zero fucks given.',
  ],
  TemperatureTier.freezing: [
    'She froze the rain before it landed. Genuinely dangerous as fuck. Do not go out there.',
    'Bjork wrote Army of Me for this. Below freezing icy ruthless af. Stay inside girl.',
    "She's out here turning the city into a fucking hockey rink. Nobody asked for this girl.",
    "She really said fuck everyone's ankles specifically. Targeted violence.",
    "She really woke up and said today I will personally fuck up everyone's commute.",
    "She's out here collecting broken ankles like fucking Pokemon. Gotta catch em all.",
    "Icing everything in sight like she's decorating the world's worst cake. Nobody ordered this shit.",
    "Jennifer Lawrence in Winter's Bone energy. Everything is frozen and fucking deadly. Stay inside girl.",
    "Oh fuck. She said I'm going to make the ground personally betray every single one of you.",
    'Coating the world in ice. Zero remorse babe.',
    'Full villain mode. Batshit and beautiful girl.',
    'She iced the whole city and went back to bed. Unbothered. Unhinged. Iconic honestly.',
    "She turned the sidewalk into a slip n slide except it's not fun and everyone's crying.",
  ],
  TemperatureTier.jacketWeather: [
    'Left ice everywhere like a rude houseguest. Still dangerous as shit babe.',
    "It's not even that cold and she still iced the roads. She does this shit for fun.",
    "She's a sneaky fucking psycho. The warm air is a lie. The ground wants you dead.",
    "Temp says fine. Ground says fuck you. She's playing both sides.",
    'Nicole Kidman in Cold Mountain energy. Ice at this temp is sneaky girl.',
    "Like a passive aggressive sticky note. Girl we can't walk.",
    'Ice is thinning but she left traps everywhere. Watch your damn step.',
    "Not even cold and the ground is a crime scene. She's framing the temperature babe.",
    "She left invisible ice at a perfectly fine temp. She's a saboteur. Watch every step girl.",
    "The air says jacket weather. The sidewalk says lawsuit. She's sending mixed signals babe.",
    "She iced the roads when nobody was looking. Security camera footage pending. Watch it girl.",
    "Freezing rain at jacket weather. She brought a knife to a pillow fight. Watch your step babe.",
  ],
  TemperatureTier.flannelWeather: [
    'Should not be possible. Unhinged as fuck babe.',
    'Goddamn. Mild out but she left ice everywhere. Still slippery. Watch it babe.',
    'The most confusing shit. Dangerous though babe.',
    "Don't trust that shit. She left traps all over.",
    "She brought freezing rain to flannel weather. Like bringing a sword to a pillow fight. What the hell girl.",
    'Who the fuck does that. Unhinged honestly.',
    'Stormy Weather took a fucking weird damn turn. Watch yourself girl.',
    "Donnie Darko energy. Ice at mild temps. Something's wrong with the timeline. Watch it babe.",
    'Mild outside but the ground says otherwise. She glazed everything. Watch your fucking step girl.',
  ],
};
