import '../../../features/weather/domain/entities/temperature_tier.dart';

const hailQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Hail in single digits. She's the final boss of weather. Stay inside immediately girl.",
    "Ice pellets at single digits. She's giving every animated villain at once. Do not go outside bestie.",
    "She's throwing ice at single digits. This is a fairy tale curse. Warmest everything and stay in babe.",
    'Single digit hail. Your car is the main character in a tragedy. Puffiest coat if you must leave girl.',
  ],
  TemperatureTier.freezing: [
    "Freezing hail. She's giving the ice storm scene in every fairy tale. Stay in bestie.",
    'Below freezing and hailing. She chose drama and brought ammunition. Heaviest coat babe.',
    "Hail below freezing. She's giving Elsa on a rampage. Stay safe in your warmest layers girl.",
    "She's chucking ice in the cold. The evil queen energy is off the charts. Warm boots on bestie.",
  ],
  TemperatureTier.jacketWeather: [
    'Hail at jacket weather. She really said this day was too nice. Let me fix that. Jacket and stay inside girl.',
    'She brought ice to a casual day. Overreaction is her brand honestly. Stay in bestie.',
    'Hail at cool temps. She added a plot twist nobody wanted. Rain boots and shelter babe.',
    'She turned a jacket weather day into a dodge ball game. With ice. Stay inside girl.',
  ],
  TemperatureTier.flannelWeather: [
    'Hail at mild temps. She snapped during the best weather. Classic villain move. Stay inside bestie.',
    'She waited for perfect temps to throw ice. Calculated and unhinged. Cozy sweater and stay in babe.',
    "Mild and hailing. She's giving animated villain who strikes during the ball scene. Cute boots and shelter girl.",
    'She ruined a perfect day with ice pellets. Very fairy tale curse energy. Flannel on and stay in bestie.',
  ],
  TemperatureTier.shortsWeather: [
    "Hail at shorts weather. She looked at everyone's bare legs and chose war. Get inside girl.",
    'Warm hail. She does not believe in proportional responses. Shelter immediately bestie.',
    "She's hailing in warm weather like a Pixar villain who makes no sense. Stay inside babe.",
    'Shorts weather hail. She said you thought this was a beach episode. Wrong genre. Get inside girl.',
  ],
  TemperatureTier.scorcher: [
    'Hail on a scorcher. She combined every extreme. Chaotic final boss energy. Get to shelter bestie.',
    'Scorching hail. She broke every rule in the weather handbook. Lightest clothes and stay inside babe.',
    "Hot ice falling from the sky. She's the plot twist that breaks the whole movie. Stay inside girl.",
    'She did the impossible and made a scorcher worse. With ice. Icon honestly. SPF and shelter bestie.',
  ],
};

const hailExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Pelting your car like it owes her money. Hood is fucked. Stay in girl.',
    'Not the sky doing property damage in single digit cold. Stay the hell inside girl.',
    'Uma Thurman in Kill Bill vibes. Cold violent as fuck. Stay in girl.',
    "Denting hoods like it's her damn job. Employee of the month energy af girl.",
    'Sidney Prescott in Scream energy. Destroying everything. Stay inside babe.',
    'Not doing weather. Doing assault. Stay inside honestly.',
    "Hail in single digits. She's filing insurance claims from the sky. Proactive queen babe.",
    "She just dented my car and my spirit in the same minute. Efficient girl.",
    "Hail at this temp. She's so angry the anger is frozen. Literally. Stay inside girl.",
    "She brought ice rocks to single digits. Like girl the cold was already winning. You're overkill babe.",
  ],
  TemperatureTier.freezing: [
    "Throwing ice below freezing because the cold wasn't violent enough. Stay the hell in babe.",
    'Not her adding projectiles to freezing temps. Zero fucking chill literally.',
    'Pelting everything below freezing like she gets paid per dent. Fucking relentless.',
    'Hereditary vibes. Violent as fuck. She snapped. Stay the hell inside girl.',
    'She upgraded her attack to include projectiles. Patch notes from hell girl.',
    'Holy shit. Sky launching golf balls at freezing temps. Your car did nothing wrong babe.',
    'Ice chunks from the sky. Your windshield sends its damn regards af girl.',
    'She watched I Tonya and took notes. Ice and violence. She planned the whole thing babe.',
    "She said the cold wasn't enough let me add ammunition. Stay inside babe.",
    "Chucking ice at your car like she's keying an ex's damn truck. Stay inside girl.",
  ],
  TemperatureTier.jacketWeather: [
    "She's the friend who starts drama at brunch. Now with ice. Stay the fuck in girl.",
    'Everything Everywhere All at Once energy. Ice in every timeline. Stay inside af babe.',
    'Holy shit. Your car was minding its damn business. She chose violence.',
    'Sky decided jacket weather needed a plot twist. Ice everywhere babe.',
    'She brought weapons to a casual hangout. Read the room girl.',
    "Hail at jacket weather. She interrupted a normal day to commit property damage. On brand babe.",
    "She just bounced ice off my windshield like she's playing percussion. I did not buy tickets girl.",
    "Hailing at this temp. My car looks like a golf ball now. Aerodynamic. Thanks I guess babe.",
    "She looked at a fine day and said let me add some violence. Interior decorator from hell girl.",
    "Hail at jacket weather. The ice is melting on my hood and leaving dents as souvenirs. Thoughtful babe.",
  ],
  TemperatureTier.flannelWeather: [
    'Crashed a nice day to destroy your car. Stay the hell inside babe.',
    'Pelting everything at a temp that did not deserve this. Rude as shit girl.',
    "Sky is throwing ice in nice weather because she's petty as hell babe.",
    'Looked at mild temps and said you know what this needs? Ice. Bold as shit.',
    'Holy shit. Your car is getting dented in mild weather. The audacity. Stay inside babe.',
    'She sabotaged her own best day with frozen projectiles. Self destructive icon af girl.',
    'Alanis Morissette wrote Ironic for this. Figures honestly bitch.',
    'Single White Female energy. Everything was fine then she snapped. Stay inside babe.',
    'Amy Dunne in Gone Girl vibes. Mild day ruined. Ice everywhere. Stay inside babe.',
    'Hole wrote Celebrity Skin for this. Loud aggressive. Wrecked the whole damn place girl.',
  ],
  TemperatureTier.shortsWeather: [
    'Launching ice at people in shorts. The visual alone is wild as hell. Get inside girl.',
    'Not the sky pelting frozen shit at 80 degrees. Most chaotic option girl.',
    'Speedrunning property destruction in warm weather. Stay the hell inside babe.',
    "She really fucking said you thought you were safe. You're not girl.",
    'Bikini Kill wrote Rebel Girl for this energy. Chose ice chose violence. Stay in girl.',
    "She sent hail in shorts weather. The sky is throwing ice at people in tank tops babe.",
    "Hail at shorts weather. She's denting cars while people are in flip flops. The range girl.",
    "She just bounced ice off someone's sunglasses. In summer. The disrespect is immaculate babe.",
    "Hailing in warm weather. My iced coffee just got more ice. Didn't order that. Stay inside girl.",
    "She sent frozen projectiles to a barbecue. Nobody RSVP'd for this. Stay inside babe.",
  ],
  TemperatureTier.scorcher: [
    'Pelting your car with ice in extreme heat. Fucking terrifying range girl.',
    "Hail in a scorcher. The sky is throwing ice cubes at people who are already on fire. Pick a lane girl.",
    'Charlize Theron in Atomic Blonde vibes. Brutal as fuck. Stay inside babe.',
    'Throwing ice at 90 degrees. Answers to no fucking one babe.',
    'Sky is fighting itself. Property is collateral damage af babe.',
    "She's throwing ice in a heat wave like a goddamn paradox. Stay inside girl. She's not fucking around.",
    'Missy Elliott wrote Get Ur Freak On for this. Hot violent. She runs this babe.',
    'She combined every extreme at once. Chaotic final boss energy babe.',
  ],
};
