import '../../../features/weather/domain/entities/temperature_tier.dart';

const heavyRainQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Pouring in single digits. She's giving the storm that shipwrecks the Disney princess. Stay inside girl.",
    'Heavy rain at single digits. This is the weather that creates villain backstories. Every layer and stay in bestie.',
    'She went full downpour in single digits. Dramatic even for her. Blanket burrito time babe.',
    'Torrential and freezing cold. She really said let me make it worse. Warmest everything and stay inside girl.',
  ],
  TemperatureTier.freezing: [
    "Below freezing downpour. She's giving the dark forest storm in every fairy tale. Stay in and bundle up bestie.",
    "Heavy rain and freezing. She didn't just choose drama she choreographed it. Heaviest coat on babe.",
    'Pouring below freezing. The weather equivalent of the scary part in every Disney movie. Scarf and warm boots girl.',
    "Freezing downpour. She's having a full breakdown and taking us all with her. Every layer you own bestie.",
  ],
  TemperatureTier.jacketWeather: [
    "Heavy rain at jacket weather. She's giving the dramatic storm scene before the happy ending. Rain boots girl.",
    'Pouring and cool. She skipped drizzle and went straight to monsoon. Classic overachiever. Jacket on bestie.',
    'She could have misted. She could have drizzled. She chose the cinematic option. Umbrella and jacket babe.',
    'Heavy rain jacket weather. Grab an umbrella or just commit to being drenched. Pick a lane girl.',
    "Heavy rain jacket weather. She's giving fairy tale river flooding vibes. Stay dry bestie.",
    'Pouring and cool. The sky is performing a whole dramatic opera. Rain boots and hoodie babe.',
    'Downpour at jacket weather. Very Rapunzel dramatic escape in the rain energy. Umbrella now girl.',
  ],
  TemperatureTier.flannelWeather: [
    'Pouring at this perfect temp. She ruined her own masterpiece. Very tragic princess energy. Cute umbrella bestie.',
    'Heavy rain flannel weather. She had perfection and added a flood. Chaotic queen. Rain boots babe.',
    'The temp was perfect and she still chose a downpour. Self sabotage is her love language. Cozy sweater girl.',
    'She wasted a perfect temp on a monsoon. Very animated movie plot twist energy. Stay dry bestie.',
    "Heavy rain mild temps. She's giving Encanto making the seeds grow in the storm energy. Flannel girl.",
    'Pouring and flannel weather. Very Merida running through the rain in the forest vibes. Rain boots bestie.',
    "Downpour but mild. She's giving acoustic Olivia Rodrigo playing through the storm. Cute umbrella babe.",
  ],
  TemperatureTier.shortsWeather: [
    "Warm downpour. She's giving the fun part of every summer movie. Sandals on and go splash around babe.",
    'Heavy warm rain. Moana running on the waves energy. Go be feral bestie.',
    "She's throwing a pool party from the sky. No invite needed. Shorts girl.",
    'Pouring and warm. The kind of rain you sprint through laughing. Go do that in your sandals babe.',
    "Warm heavy rain. She's giving Luca ocean reveal but make it a waterfall. Shorts on girl.",
    'Pouring at shorts weather. The sky is doing a whole power wash. Stay inside or embrace it bestie.',
    'Heavy warm rain. Very Encanto dramatic storm energy but it feels amazing. Sundress babe.',
  ],
  TemperatureTier.scorcher: [
    "Heavy rain on a scorcher. She's ending the heat wave with maximum drama. Lightest clothes bestie.",
    'Pouring hot rain. She declared war on the sun and brought the whole ocean. Shorts on girl.',
    'Scorching downpour. Relief is loud and wet and dramatic. Just like every Disney climax. Sandals on babe.',
    "She's fighting the heat with a waterfall. Aggressive but effective. Stay hydrated bestie.",
  ],
};

const heavyRainExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Dumping ice cold rain. Absolutely unhinged. Terrified as fuck honestly.',
    'Freezing and she opened up like a fire hydrant. Fuck your plans girl.',
    'Torrential and frozen. Villain origin story shit for real babe.',
    "PJ Harvey energy out here. Torrential cold relentless as hell. I'm not okay.",
    'Not her throwing a monsoon at single digits. The fucking audacity girl.',
    "Pouring cold rain. She's not just unhinged she's off the fucking hinges entirely.",
    'Freezing downpour. She combined every bad idea and executed flawlessly. Evil genius shit.',
    'Cold rain hammering down. Naomi Watts in The Impossible energy. Stay inside girl.',
    "Frozen and dumping. Sky lost her mind. She's unwell.",
    'Cold monsoon out here. She really said what if I make it worse. And then she did.',
    "Pouring and freezing. This isn't weather it's a hostage situation babe.",
    'She chose the damn apocalypse. Pouring and freezing. Stay inside babe.',
  ],
  TemperatureTier.freezing: [
    'She went full Noah. Rain is biblical. Cold as fuck babe.',
    "Cold and pouring. Didn't come to play. Came to fucking destroy girl.",
    'Freezing and she opened the sky like deal with it. Bitch move girl.',
    'Cold and dumping like rent is due. Relentless as fuck.',
    'Cold rain pouring. She snapped. Not fucking stopping girl.',
    "Freezing downpour. Almost impressive. Almost. It's still shit.",
    "She didn't just burn the bridge she flooded it. In the cold. Thorough bitch.",
    'Cold torrential rain. She skipped angry and went straight to unforgivable. Impressive honestly.',
    "Pouring and freezing. She's not processing her emotions she's projecting them. On all of us.",
    'Cold rain hammering. She really combined the two worst things and cranked both to ten.',
    'She went full scorched earth except wet and cold. Same energy though.',
    'Freezing and dumping. She woke up and chose damn war. Stay inside babe.',
  ],
  TemperatureTier.jacketWeather: [
    "Charlie's Angels energy. Heavy cold rain. She's not fucking around babe.",
    'Not her pouring this hard in the cold. Extra as shit girl.',
    "Cold and pouring like she's holding a grudge. Dramatic as fuck. Like why girl.",
    "Cool and dumping on us like we personally wronged her. We didn't. Or did we. Fuck.",
    "Chilly and she really said fuck a drizzle fuck a light rain. Full psycho today girl.",
    'Cold and fucking dumping. She went from zero to biblical in like ten minutes. Zero warning babe.',
    'Cold and pouring. She really has no off switch and no shame. Honestly respect girl.',
    "Cool and she's out here power washing the entire neighborhood. Nobody asked for this babe.",
    "Cool and dumping. She's absolutely unloading right now. Like who hurt you girl.",
    'Cool and she escalated a fine day into a torrential fucking disaster. Impressive honestly.',
    'Cold and pouring. She really brought the entire ocean and no apology babe.',
    // "She could've been normal about it. She chose chaos. Obviously.",
    'Sleater-Kinney wrote this weather. Heavy cold rain. Loud and fucking committed honestly.',
    "Cool and pouring. She really said I'm going to ruin everything and look good doing it.",
    'Cold and pouring. Like girl this is excessive even for you.',
    'Cold and fucking pouring. She went from zero to restraining order real quick girl.',
    'Cold and fucking dumping. Even the rain looks surprised. She went rogue babe.',
    "She's giving villain monologue in the cold rain energy. Drenched and dramatic af girl.",
    'Chilly and she could have drizzled. Could have misted. She chose violence girl.',
    'Cool and she skipped every reasonable option and went straight to monsoon. Zero chill as always girl.',
    // "Heavy rain cold temps. My umbrella just inverted and I'm holding a sad metal tulip. She turned it into modern art girl.",
  ],
  TemperatureTier.flannelWeather: [
    'Mild and absolutely drenched and somehow in a good fucking mood. The math isn\'t mathing girl.',
    'Mild and pouring. She ruined my whole damn outfit and perfected the vibe simultaneously. Partial credit bitch.',
    "Soaked head to toe but the temp is mild as fuck. Feels like a hug? I'm so confused honestly.",
    'The rain said fuck you and the temp said I love you. Mixed signals babe.',
    "Mild and torrential. This is objectively terrible and subjectively fucking great. I hate her and I don't babe.",
    "Mild and dumping. Every piece of clothing is fucked but she's honestly still perfect. We forgive you girl.",
    'She wrecked the day with a downpour but kept the temp perfect. Like keying your shit then leaving flowers girl.',
  ],
  TemperatureTier.shortsWeather: [
    "Warm rain absolutely dumping on us and honestly? Main character energy. We're the extras girl.",
    "It's warm and dumping sideways and this is hot girl shit. Go dance in it babe. I'm serious.",
    "It's warm as hell and pouring buckets. Get your ass outside and stand in it like the unhinged person you are babe.",
    "She's dumping warm rain like she's got something to prove and honestly? Best decision she's ever made girl.",
    "Warm and pouring. She said fuck your hair fuck your plans fuck your shoes. Go stand in her girl.",
    "She said I'm going to dump warm rain on you and you're going to like it. She was right babe.",
    // 'Warm and monsooning. Lauryn Hill wrote Everything is Everything for this. She meant it bitch.',
    // 'Warm and pouring. She lost it in the best way. Go stand in her chaos girl.',
    // "She's dumping the entire warm ocean on us and it's a gift girl.",
    "She snapped. Warm rain just dumping everywhere. Get outside and get soaked babe it's everything.",
    "She's absolutely dumping rain and losing her mind and I've never loved her more honestly.",
    // "She really turned the streets into rivers. I'm not even mad. Go splash around babe.",
    // "Warm rain dumping so hard the drains filed for overtime. Go splash like a feral child girl.",
    // "Soaked to my bones in warm rain and I've never felt more alive. She factory reset me girl.",
    // "Warm rain just power washed the whole block and everyone on it. Aggressive but effective skincare routine babe.",
    "I'm standing in warm pouring rain screaming and my neighbors are watching. She made me feral girl.",
    "Warm rain pouring so hard my shoes are aquariums. Little fish could live in there honestly. Go play babe.",
    // "Came back inside from that warm downpour and wrung out my shirt like a fitness commercial. She directed it girl.",
    "She dumped the whole sky on us and I'm soaked head to toe grinning like an idiot babe.",
    // "I just ran through warm dumping rain in my good shirt because she told me to. She didn't. I just wanted to girl.",
    // "Warm rain dumping so hard my mascara is running and I look like a raccoon in a car wash. She did my makeup girl.",
  ],
  TemperatureTier.scorcher: [
    // "Hot as fuck. Rain fighting the sun and winning. Thanks girl we needed you.",
    "She saw the scorching heat and said I'll fucking handle this. And she did. Go girl.",
    'Hot as fuck and dumping. She combined hell and a waterpark and somehow it works. Chaos queen.',
    // 'Rain said sun you stupid bitch sit down. Sun sat.',
    'Hot and pouring. Sky had a complete psychotic break and honestly thank fuck she did.',
    "Hot as fuck and absolutely dumping rain. She really said I'm going to fix this with maximum violence.",
    'Hot and pouring. She really chose the most unhinged solution possible and fucking committed. Good for her honestly.',
    "Hot rain dumping on the pavement. Like girl the ground didn't do anything to you relax.",
    "Hot and dumping. Humidity is criminal but she's doing us a solid babe.",
    "Hot rain out here absolutely annihilating the sun. Aggressive but honestly she had it coming girl.",
    'The sun started it and the rain is finishing it. Messy break up energy vibes girl.',
    "She's performing an exorcism on the heat with torrential rain. Violent. Effective. Unhinged babe.",
  ],
};
