import '../../../features/weather/domain/entities/temperature_tier.dart';

const mostlySunnyQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'She fought past the clouds for single digits and honestly why. Stay inside in your fuzzy socks girl.',
    'Mostly sunny single digits. Giving Narnia lamppost energy. Beautiful and freezing. Puffiest coat on bestie.',
    'The sun pushed through like a Disney heroine but the cold is the real villain here. Every layer you own babe.',
    "She showed up through the clouds for this. It's single digits. Go back to bed in your warmest PJs girl.",
  ],
  TemperatureTier.freezing: [
    'Mostly sunny and freezing. Very Elsa without the ice palace perks. Heaviest coat and earmuffs bestie.',
    'She battled clouds in the cold like Mulan but nobody asked her to. Scarf and gloves on babe.',
    'The sun showed up below freezing like an animated sidekick. Cute and completely unhelpful. Warm boots on girl.',
    'Mostly sunny below freezing. Very Elsa built an ice castle but left the lights on energy. Heavy coat bestie.',
    'The sun cleared most of the clouds just to show us the cold. Thanks I guess. Hot cocoa time babe.',
    "Freezing with mostly sun. She's giving winter Frozen landscape that's gorgeous from inside. Heaviest coat girl.",
    "Below freezing and mostly sunny. She's giving Anna searching for Elsa energy. Scarf and warmest boots bestie.",
  ],
  TemperatureTier.jacketWeather: [
    'Mostly sunny and cool. Very cottagecore fairy tale afternoon vibes. Jacket on and go wander bestie.',
    "She's giving Enchanted princess discovering the park for the first time. Jacket and sunnies babe.",
    'Sun pushed through a few clouds at jacket weather. She understood the assignment. Hoodie on girl.',
    'Taylor Swift cardigan weather with a side of sunshine. Go write your own love story bestie.',
    'Mostly sunny and jacket weather. Very Tangled kingdom town square vibes. Cute jacket on and go explore girl.',
    "She's giving Barbie stepping outside the dream house on a cool morning. Light layers babe.",
    'A few clouds and jacket weather. The sky is accessorizing. Smart. Denim jacket on bestie.',
    'Joy from Inside Out is running the weather console today. Light jacket and sneakers girl.',
    'She cleared the clouds just enough to serve a look. Light jacket and sunnies on bestie.',
    'Cool with mostly sun. Very Taylor Swift begin again walking through the city energy. Jacket on babe.',
  ],
  TemperatureTier.flannelWeather: [
    'Mostly sunny and mild. This is the weather fairy tales promised us. Flannel on and get outside girl.',
    "She's giving Mirabel exploring the Encanto courtyard energy. Joyful and effortless. Cute boots on babe.",
    'The clouds are just set decoration. This day is a whole Disney masterpiece. Cozy sweater on bestie.',
    'Mostly sunny perfect temps. Olivia Rodrigo would call this her happiness era. Same girl.',
    'Mostly sunny and mild. Raya would sprint through this weather and so should you. Best fall outfit on babe.',
    "She's giving Brave archery in the meadow energy. Mild and mostly sunny and free. Light scarf on bestie.",
    'The clouds are just accent pieces. Mild and gorgeous. Very fairy tale garden afternoon. Flannel on babe.',
    "Mostly sunny flannel weather. She's giving Olivia Rodrigo spinning in a field energy girl.",
    'This weather is the background of every Taylor Swift love story. Cozy sweater and go write yours bestie.',
    'Mild with mostly sun. Very Rapunzel painting in her tower but you should actually go outside babe.',
    'She pushed the clouds aside like curtains on a Pixar morning. Cute boots on and enjoy the show girl.',
    'Mostly sunny and perfect. The kind of day Pixar would animate in stunning detail. Flannel on bestie.',
    'Flannel weather with sun peeking through. Very Sabrina Carpenter autumn music video. Light layers babe.',
  ],
  TemperatureTier.shortsWeather: [
    "Warm and mostly sunny. She's giving Moana sequel energy. Sundress on and the ocean is calling babe.",
    'She fought off the clouds to serve us this warmth. Respect the hustle. Shorts on bestie.',
    'Mostly sunny and warm. Princess Jasmine whole new world energy. Sandals on and go see it girl.',
    'This weather is the montage scene in every feel-good movie. Shorts on and go live it babe.',
    'Warm and mostly sunny. Very Mirabel dancing through the Casita on a perfect day. Tank top girl.',
    'She served us warmth with a few clouds for drama. We love a layered queen. Sunglasses on bestie.',
    'Mostly sunny shorts weather. This is the weather that launches a thousand beach trips. Sundress on babe.',
    "Warm with mostly sun. She's giving Lilo hula dancing on the beach vibes. Ponytail and sandals girl.",
    "The clouds are just cameos in today's sunny warm blockbuster. Shorts on because you're the star bestie.",
    "She's serving Olivia Rodrigo summer tour energy. Warm and mostly radiant. Tank top on babe.",
    "Mostly sunny and warm. Very Rapunzel seeing the lanterns but it's just a really good day. Sundress girl.",
    'Warm with a few clouds adding character. Very tropical Disney island energy. Shorts on bestie.',
    "She's giving Moana setting sail on a perfect day. Sandals on because the outdoors is calling babe.",
  ],
  TemperatureTier.scorcher: [
    'She fought through clouds to scorch us. The dedication is unhinged. SPF and a hat immediately girl.',
    "Mostly sunny scorcher. She's giving Mirabel in the sun but make it dangerous. Water bottle now bestie.",
    'She pushed past clouds to commit heat crimes. SPF and shade and your lightest clothes babe.',
    'The sun cleared the clouds just to cook us. Villain origin story honestly. Hydrate and hat on girl.',
    'Mostly sunny and scorching. She fought through clouds to personally attack us. SPF on bestie.',
    "The clouds couldn't even cool her down. Scorching and relentless. Water bottle and hat now babe.",
    'Mostly sunny scorcher. Very Aladdin rooftop in the desert heat vibes. Shade immediately girl.',
    "She's giving Maui pulled the sun closer through the clouds energy. Hydrate or perish bestie.",
    'Hot with mostly sun. Lightest clothes you own and drink water like your life depends on it babe.',
    'The clouds tried to help but the heat won. Villain energy. SPF hat and cool down immediately girl.',
  ],
};

const mostlySunnyExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "She brought the vibes and left the warmth in the fucking car. Classic her honestly. Heaviest coat babe.",
    "Cold as fuck and she's still out here fighting clouds. Girl the cold is the problem not them.",
    "Mostly sunny and cold as fuck. She's just up there smiling while we suffer. Girl read the room.",
    "She pushed through clouds and said ta da. Ta da what bitch. It's seven degrees.",
    "It's giving White Lotus. Gorgeous setting everything's wrong. Heaviest coat girl.",
    "Sun shoved clouds out the way like I got this. Girl you do not got this. It's single digits.",
    "Sun peeked past clouds like surprise. Girl the surprise is hypothermia. Bundle the fuck up babe.",
  ],
  TemperatureTier.freezing: [
    "Mostly sunny below freezing. She fought through clouds in the cold FOR US. The effort alone. Coat on babe.",
    "Cold as fuck but she shoved those clouds aside like a goddamn hero. Appreciate her. Bundle up girl.",
    "Below freezing but mostly sunny. She battled clouds in this cold and won. That's dedication bitch.",
    "Mostly sunny and freezing. She could've stayed behind the clouds but she didn't. She came through. Coat on girl.",
    "Cold as shit but she cleared the sky anyway. Above and beyond honestly. Layer up babe.",
    // "Below freezing mostly sunny. She brought a bouquet of flowers to a house fire. Read the room girl.",
    "Mostly sunny below freezing. At least she tried to make it pretty. And she fucking succeeded. Coat on bitch.",
    "Mostly sunny cold as fuck. She pushed through the clouds in freezing temps. That's harder than it looks. Bundle up girl.",
    "Below freezing but she cleared the sky for us. Free light therapy in the cold. Take what you can get babe.",
    "Mostly sunny and freezing. The fact that she showed up at ALL in this cold is iconic. Coat on girl.",
    "Cold as fuck but she fought for that sunshine. Nobody asked her to. She just did. Respect. Bundle up babe.",
    "Mostly sunny below freezing. She didn't let the cold stop her. Neither should you. Heaviest coat and go girl.",
    "Below freezing and she still elbowed clouds out the way for us. Warrior shit honestly. Coat on girl.",
    "Mostly sunny and cold as fuck. At least the sky is open and gorgeous. Beats gray every damn time babe.",
    //"Mostly sunny and freezing. She said the ambiance is my department. Ma'am your department is on fire. Bundle up girl.",
    //"She said I'll handle the clouds. Ma'am the clouds were not the issue.",
  ],
  TemperatureTier.jacketWeather: [
    "Mostly sunny and cool. Clouds are actually cute as fuck. She's accessorizing girl.",
    "Nippy but she's fucking stunning. Layer up and go stare at her babe. With sunnies obv.",
    "Mostly sunny and cool and I'm already outside. Didn't think about it. Just went bitch.",
    'Mostly sunny and a little chilly. She finally learned the word moderation. Somebody get this bitch a trophy.',
    "Not her serving a normal nice day like it's a flex. It is though. It absolutely fucking is.",
    "She's mostly sunny and cool and I just curtsied at the fucking sky. In jeans. In public girl.",
    'Mostly sunny and cool. Jacket on sunnies on get the fuck out there babe.',
    "Cool and mostly sunny. She's not perfect but she's trying and I fucking respect that. Go girl.",
    "Mostly sunny and chilly. She finally did something right. Jacket on go enjoy it before she fucks it up babe.",
    "Cool and mostly sunny. Get outside now. She won't be this chill for long bitch.",
  ],
  TemperatureTier.flannelWeather: [
    "She showed up mild and mostly sunny and my jaw hit the floor. Like where have you been babe.",
    'She really said hold my drink and delivered the best fucking day this month. Get out there babe.',
    "She didn't just clear the clouds she put them in a little pile in the corner. Tidy queen. Go your ass outside girl.",
    'Mostly sunny perfection. Shut the fuck up and go outside. Talking to myself babe.',
    "Mostly sunny and mild. She's fucking peaking and she wants witnesses. Go be one girl.",
    "She's showing off and she deserves it today. Get the fuck outside girl.",
    "It's giving hoodie and sunnies and zero responsibilities. She planned this babe.",
    "She cooked today and didn't burn a single fucking thing. Proud of you girl.",
    'She showed up mild and mostly sunny and I have zero fucking notes. Hate that for me honestly.',
    "Mostly sunny and mild. Get outside. Don't bring your phone. Be feral. Be free babe.",
    "She cleared the clouds served the vibes and didn't ask for applause. Standing ovation anyway bitch.",
    'Mostly sunny flannel weather. Hoodie on sunnies on get the fuck out there babe.',
    'Mild and mostly sunny. Flannel. Coffee. Outside. The whole damn plan babe.',
  ],
  TemperatureTier.shortsWeather: [
    'Clouds trying to gatekeep shorts weather. Sun said absolutely tf not. Sunnies on babe.',
    "Mostly sunny and warm and oh my fucking god. That's the whole forecast babe.",
    "She's so nice right now it should be illegal. Arrest her. After I go outside girl.",
    "It's so fucking nice out I forgot my name. Shorts on babe.",
    "She's so warm and sunny my seasonal depression packed a bag. Buh bye bitch.",
    "Nice as fuck out. Just threw my jacket in the trash. Shorts on babe.",
    'Mostly sunny shorts weather. She planned it bitch.',
    'Mostly sunny shorts weather. She made the clouds her hype girls. Get out there girl.',
    'Mostly sunny and warm. Tongue out. No thoughts. All joy. Shorts on babe.',
    'Mostly sunny and warm as fuck. Shorts on. Brain off. Outside now girl.',
    'Mostly sunny and warm as fuck. Sunscreen on. Shorts on. Phone off. Bye babe.',
    "She cleared the clouds just for your ass. Shorts on go thank her girl.",
    'Mostly sunny and gorgeous. Shorts. Sunnies. SPF. Go babe.',
    "She's warm and mostly sunny and you have zero excuse. Get the fuck out there girl.",
  ],
  TemperatureTier.scorcher: [
    "Mostly sunny scorcher. She cleared the clouds for a better angle to cook us from. Strategic. Psychotic. SPF babe.",
    'Mostly sunny hot af. She pushed past clouds to personally victimize us. Like okay Regina.',
    "Hot as fuck and mostly sunny. She's up there with a magnifying glass and we're the ants. SPF or perish babe.",
    'Clouds just standing there while she scorches us. Bystanders. Complicit. Useless bitches.',
    "Mostly sunny and scorching. Clouds watching from the side like they're not involved. You are. You're all guilty girl.",
    "She's so hot the clouds left and honestly same. I would also leave. Can't though. Pool now babe.",
    'Hot as fuck and mostly sunny. Nearest pool. Now. This is not a suggestion babe.',
    'Mostly sunny scorcher. I need a pool a drink and for her to calm the fuck down. In that order.',
    'Mostly sunny hot as shit. Googling nearest pool like my life depends on it. It does babe.',
    "Mostly sunny scorcher. She heard calm down and took it as a fucking dare. Hydrate babe.",
    "Girl relax. We get it. Everyone knows you're hot as fuck.",
    "Hot as shit mostly sunny. My deodorant just texted me saying I'm on my own today. Shade immediately girl.",
    "Mostly sunny hot as fuck. Even my shadow's looking for shade babe. Seek shelter.",
    "She's so fucking hot I'm googling pools near me with my last brain cell girl.",
    'She cleared the clouds and cranked the fucking heat. Double homicide babe.',
    "She's so fucking hot the asphalt is soft. I'm leaving footprints. In the road girl.",
    "She's scorching us through a mostly clear sky and she's not even at full power. That's the scary part babe.",
    "Mostly sunny and hot enough to cook an egg on my dashboard. Tried it. It worked. Send help girl. SOS.",
    "She pushed past clouds in this heat like she's trying to prove a point. Point taken. We're fucking dying babe.",
    "Mostly sunny scorcher. I'm so fucking hot I forgot how to be a person babe.",
    'Holy shit. She fought clouds to bring this heat. Girl we were rooting for the clouds.',
    "She's out here scorching us and the clouds are filming it. Worldstar energy. Find a pool immediately babe.",
    "Mostly sunny scorcher. I just saw a bird panting. A bird. Panting. She broke nature girl.",
    "Hot as fuck and mostly sunny. My sunscreen is sweating off faster than I can apply it. She's winning babe.",
    "Mostly sunny and scorching. She really said I'll leave a few clouds so you can watch me cook you. Front row seats bitch.",
    "She's so hot the ice cream truck played Taps instead of its normal song. Moment of silence. Pool now babe.",
    "Nearest pool. Nearest lake. Nearest garden hose. I'm not picky girl.",
    "She's so hot I'd swim in a puddle right now babe.",
    "Mostly sunny scorcher. I'm so hot I just thanked a cloud for existing. Brief shade. Life saved. For now babe.",
    "She's mostly sunny and scorching and I swear my eyeballs are sweating. Didn't know they could do that girl.",
    "She's so hot my flip flops are melting into the sidewalk. We're one now girl.",
  ],
};
