import '../../../features/weather/domain/entities/temperature_tier.dart';

const overcastQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Gray sky single digits. She's giving the sad montage in an animated movie. Stay inside in your PJs girl.",
    'Overcast and freezing cold. Inside Out Sadness energy but make it fashion. Every layer you own bestie.',
    "Full cloud cover in single digits. She's in her villain era and we're all trapped. Blanket burrito babe.",
    'No sun no warmth no mercy. Every layer you own and stay inside. She chose violence girl.',
  ],
  TemperatureTier.freezing: [
    "Gray and freezing. She's giving the before scene in every fairy tale transformation. Heaviest coat bestie.",
    'Overcast below freezing. The clouds came for the sun and won. Heavy coat and earmuffs babe.',
    'She blocked the sun and froze the air. Very animated villain energy. Scarf and gloves girl.',
    "Below freezing under a gray blanket. She's giving the before part of every transformation story. Warm boots bestie.",
    "Overcast and freezing. She's giving the part of Frozen where everyone is sad. Heaviest coat now girl.",
    'Grey and below freezing. Very ice kingdom on a moody winter day vibes. Hot cocoa and layers babe.',
    'She covered the sky and froze the air. Full supervillain protocol. Every layer you own bestie.',
  ],
  TemperatureTier.jacketWeather: [
    'Overcast and cool. Very bookshop in a fairy tale film vibes. Jacket on and go be cozy girl.',
    "Gray sky jacket weather. She's giving indie movie protagonist energy. Hoodie on and go wander bestie.",
    'The clouds took over but the temp is cute. Coffee shop weather honestly. Cute jacket babe.',
    'Overcast and cool. Belle going to the bookshop in her blue dress energy. Light layers girl.',
    'Grey skies and cool. Very Rapunzel reading by the window but you should go outside energy bestie.',
    'Overcast jacket weather. Very Taylor Swift all too well ten minute version vibes. Jacket on babe.',
    'The clouds took over but the jacket weather keeps it cozy. Moody and cute. Denim jacket girl.',
    'Grey and cool. Very Merida being independent in the highlands type energy bestie.',
    "Overcast and jacket weather. She's giving the part of the movie where the heroine goes on a walk. Sneakers on babe.",
    'The sky went full grey but the temp stayed reasonable. We take our wins. Hoodie on girl.',
  ],
  TemperatureTier.flannelWeather: [
    "Overcast and mild. She's giving Totoro bus stop scene. Cozy moody perfect. Flannel on bestie.",
    "Gray skies at this temp hit different. She's serving cottagecore energy. Cozy sweater on babe.",
    'The clouds are a vibe and the temp is immaculate. Flannel on and go be mysterious girl.',
    "Overcast flannel weather. She didn't need the sun to be perfect and she proved it bestie.",
    'Overcast and mild. Very Belle curled up with a book energy. Cute sweater on babe.',
    "Grey skies flannel weather. She's giving acoustic set in a cozy venue vibes. Light scarf girl.",
    'The clouds are giving soft lighting. Mild temps. Very fairy tale afternoon. Best fall outfit bestie.',
    "Overcast and flannel weather. Giving cozy Encanto kitchen scene vibes. Warm sweater on babe.",
    "Grey but mild. She's giving Olivia Rodrigo writing songs by the window energy. Flannel on girl.",
    'Overcast flannel weather. Very Sabrina Carpenter cozy autumn aesthetic. Cute boots bestie.',
  ],
  TemperatureTier.shortsWeather: [
    'Warm and overcast. No sunburn no squinting just vibes. She figured out the cheat code. Shorts on babe.',
    'Overcast shorts weather. She said sun is optional when the temp goes this hard. Sandals on bestie.',
    "Gray sky warm air. She's giving beach day without the sunscreen. Sundress on and go enjoy it girl.",
    'She blocked the sun but kept the warmth. Strategic queen honestly. Tank top on babe.',
    "Grey but warm. She's giving tropical island before the party vibes. Shorts girl.",
    'Overcast and warm. Very Luca Italian seaside town on a cloudy day energy. Sandals on bestie.',
    'Warm under grey skies. The clouds are just a filter. Still serving. Ponytail and shorts babe.',
    'She blocked the sun but kept the heat. Very strategic. Sundress still works girl.',
    'Overcast shorts weather. Like a warm hug from a grey blanket. Go enjoy it in your favorite shorts bestie.',
    "Grey and warm. She's giving Moana before the adventure vibes. Tank top and sandals babe.",
  ],
  TemperatureTier.scorcher: [
    'Overcast scorcher. She sealed the heat in like a pressure cooker. Lightest clothes and hydrate immediately girl.',
    'Gray and scorching. She trapped us under a hot blanket. Water bottle and hat on bestie.',
    'Overcast and melting. She turned the sky into a sauna ceiling. Stay cool in your lightest outfit babe.',
    'She covered the sky and cranked the heat. Very dramatic villain move. Hydrate immediately girl.',
    "Grey and scorching. She's trapping heat like Jafar trapping the genie. Water bottle now bestie.",
    'Overcast and hot. The clouds are a lid on a boiling pot. Lightest clothes on and hydrate right now babe.',
    'Scorching under grey skies. She invented the outdoor sauna. Cool down and SPF up girl.',
  ],
};

const overcastExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Overcast and single digits. Full gray and cold as fuck. Girl why.',
    'Overcast and cold as fuck. Sky and temp are twinning and they both chose violence.',
    "Gray and cold as fuck. She's not depressed she's brooding. There's a difference apparently.",
    "It's giving seasonal depression starter pack. Hot chocolate is not optional it's medicine babe.",
    "It's giving Girl with the Dragon Tattoo. Dark cold and not sorry. Puffer on babe.",
    "Overcast single digits. She's in her groutfit era. No color no warmth no fucks.",
    'The sky has the personality of a DMV waiting room. Cold and fucking joyless. Puffer on babe.',
    "Gray and frozen and she didn't even accessorize. Lazy villain energy. Bundle up girl.",
    "Overcast single digits. She turned off the lights and left us in the fucking freezer. Helpful.",
    'She put a concrete ceiling over the whole city and dipped. Zero effort. Max suffering girl.',
  ],
  TemperatureTier.freezing: [
    // 'Overcast below freezing. Committed to gray and cold as fuck. Just like your ex. Coat on babe.',
    "It's giving Heathers. Gray strange cold as shit. Heaviest coat babe.",
    'Gray and frozen. She said I will be moody AND cold. Overachiever energy honestly.',
    "It's giving Fargo. Gray flat cold as fuck. Bundle up babe.",
    'Overcast below freezing. She really said no sun no warmth no apology. Bold as fuck girl.',
    "Overcast and cold as fuck. She didn't just block the sun she filed a restraining order girl.",
    'Below freezing and overcast. She combined depression and frostbite. Efficient as fuck honestly.',
    "Gray below freezing. She woke up moody and made it everyone's problem. On brand as fuck babe.",
    // 'Overcast and freezing. My phone brightness is higher than hers. Embarrassing for her honestly.',
    // 'She deleted color and warmth in the same update. Patch notes are bleak girl.',
    // 'Gray and freezing. The sky looks like an unprimed canvas. Blank cold and disappointing babe.',
    'Gray and freezing. She turned off the lights and the heat. Get your warmest coat on babe.',
    "Overcast freezing. It's giving the pilot of a show you're gonna flip off in like 2 seconds. Coat on babe.",
    "Gray and freezing. She put a concrete lid on the sky and turned off the furnace. Landlord from hell energy. Coat on babe.",
  ],
  TemperatureTier.jacketWeather: [
    "Overcast and cool. She hid the sun and won't say where. Sus as fuck honestly.",
    'Overcast jacket weather? She said let me be moody AND cute. Fucking nailed it. Coffee stroll incoming.',
    "Overcast and cool. She's not trying to impress anyone and honestly she doesn't have to. Do you girl. Layer the fuck up babe.",
    "Gray and cool. She took away the sun and I'm not even mad. Trench coat energy babe. Go be mysterious.",
    'Alanis energy tbh. Gray moody and walking with purpose. Jacket on babe.',
    "Gray and cool. She's giving that one indie movie you watched alone and fucking loved. Jacket on babe.",
    'Overcast jacket weather. Coffee weather. Moody walk weather. Main character weather. Go girl.',
    "Overcast and cool. My resting bitch face finally matches the sky. We're twinning babe.",
    "She dressed the whole city in grayscale and it's serving editorial. Jacket on babe.",
    "She turned off the sun and turned up the vibes. Didn't know that was an option. Layers babe.",
    'Gray jacket weather. Throw on a coat grab a coffee and get the fuck out there babe.',
    "Overcast and cool as fuck. She's not apologizing and honestly she doesn't need to. Go girl.",
  ],
  TemperatureTier.flannelWeather: [
    "Sky? Trash. Temp? Immaculate. She's a damn con artist and I'm the mark babe.",
    "She's giving bad first impression great personality. Flannel on girl.",
    "It's giving ugly apartment incredible location. Can't fucking leave honestly.",
    // 'Gray and mild. The sky contributed nothing. The temp did the whole group project babe.',
    'My flannel just looked at the sky and said I got this. And it fucking does girl.',
    'She showed up looking like a DMV ceiling but the temp is nice so fuck it. Boots on babe.',
    'She dressed like shit and still pulled. Respect honestly.',
    "It's giving catfish. Ugly from orbit. Perfect at street level girl.",
    // 'Gray and mild. The sky is a blank page. The temp wrote the whole fucking novel girl.',
    "Overcast and mild. I want to complain but the air won't fucking let me. Hostage vibes babe.",
    // 'Gray flannel weather. Temp is doing all the work. Sky is taking all the credit. Classic babe.',
    'Hot mess energy. Disaster up top. Flawless down here. She gets away with everything girl.',
    // "She's giving C minus effort A plus results. Scam queen.",
    // "My jacket can't commit. On. Off. On again. Gray sure can though babe.",
    "It's giving tinted windows. Can't see shit but the ride is smooth babe.",
    "The sky is boring as fuck and I've been outside for two hours. Do the math girl.",
    'She put a ceiling on the city and the air underneath is perfect. Chaos architect babe.',
    "Zero visual appeal. Maximum comfort. Shouldn't fucking work. Does girl.",
    "She's giving ugly car great engine. Don't look up. Just drive babe.",
    "Overcast flannel weather. She's ugly as fuck up there but the air is perfect. Get outside babe.",
    "It's giving beige flag. Not mad. Not thrilled. Just outside girl. Boring as shit but she feels good.",
    // 'Gray and mild. Built like a strip mall with a Michelin star restaurant inside. Respect babe.',
    "It's giving substitute teacher who's cooler than the real one. Flannel on babe.",
    // "She killed the sun and the temp didn't flinch. Cold blooded.",
    // 'Overcast and mild. The sky gave up. The air never will. Contradictions queen.',
    'Gray flannel weather. Failing upward energy. A disaster who keeps getting away with it girl.',
    "Gray and mild. Sky is mid. Temp is elite. She's getting away with it again babe.",
    'Gray flannel weather. Throw on a hoodie and get the fuck outside. She earned this girl.',
  ],
  TemperatureTier.shortsWeather: [
    'Gray and warm. She removed the sun and kept the heat. This is a fucking heist babe.',
    "She's giving I woke up hot and sad. Relatable as shit girl.",
    "Overcast and warm. She's emo in a bikini. Shouldn't work. Does babe.",
    'Warm and gray. No sunburn. No squinting. No fucking complaints.',
    'She kept the heat and fired the sun. HR approved. Shorts on babe.',
    "It's giving cheat code. All the warmth none of the fucking UV. She hacked summer girl.",
    'Overcast shorts weather. Brightness down. Heat up. She adjusted the settings again babe.',
    "She's giving sundress no sunscreen. The whole damn operation simplified girl.",
    'She gave us summer without the homework. No SPF no shade math no drama babe.',
    "She made the sun redundant and the temp didn't fucking flinch. Hostile takeover vibes.",
    "It's giving the cool side of the pillow but everywhere. Shorts on babe.",
    "Gray and warm. She's the weather equivalent of dark mode. Same heat less glare girl.",
    "Warm and gray. Haven't thought about sunscreen once. That's the whole damn review honestly.",
    'Overcast shorts weather. She subtracted the sun and it got fucking better. Less is more babe.',
    'Gray and warm as fuck. This is what summer would be if summer had manners girl.',
    'She hid the sun and nobody filed a missing persons report. Good riddance babe.',
    'Warm and overcast. The sun is unnecessary and she had the guts to say it. Pioneer bitch.',
    'Gray shorts weather. Shoulders fine. Eyes open. Skin intact. She patched every bug babe.',
    'Gray and warm and you need zero sunscreen. Shorts on get out there babe.',
    "Overcast shorts weather. She simplified the whole damn operation. Get outside girl.",
    'Warm and gray. She removed the glare and kept the heat. Shorts on go babe.',
  ],
  TemperatureTier.scorcher: [
    "Overcast scorcher. She turned the sky into a damn greenhouse. Girl we're not plants.",
    "Gray and hot as fuck. She's steaming us like vegetables. We didn't consent to this girl.",
    "Hot as fuck and gray. She trapped us under a heat blanket nobody asked for. We're steaming girl.",
    'Hot as fuck and gray. Humidity just entered the chat with a baseball bat girl.',
    "Overcast and scorching. She put a lid on us and turned up the heat. We're not soup girl.",
    'Erin Brockovich vibes. Overcast scorcher. Minimal clothing maximum attitude. Stay hydrated girl.',
    'Overcast scorcher. She sealed us in and cranked the temp. Sous vide energy babe.',
    "Gray and hot as fuck. I'm sweating in places I didn't know I had. She found new real estate babe.",
    // 'Overcast scorcher. My deodorant just filed for early retirement. Two hours in girl.',
    "Gray and scorching. She sealed us under clouds like leftovers nobody wanted. Drink water babe.",
    "Hot as fuck and gray. The air is thick enough to leave a handprint in. She's absurd girl.",
    "Overcast scorcher. Every breath feels like inhaling a wet towel. Creative. Hateful. Hydrate girl.",
    "Gray and scorching. She invented a new kind of suffering. Not sunny not breezy just damp hell girl.",
    "Gray and hot as shit. I just sweated through my shirt like blotter paper. Modern art babe.",
    "Overcast and blazing. She cranked the humidity to eleven and hid the dial. Good luck girl.",
    "Hot as fuck and she won't even let us see the sun we're suffering for. Hostage energy babe.",
    "Gray scorcher. My ice cream melted before I left the store. The cone wept. I wept. Hydrate girl.",
    // "Overcast and scorching. She took the sun's heat and kept it in a jar. Opened it on all of us babe.",
    "Gray and scorching. Even the birds look confused. They're just standing there panting. Same babe.",
    "She served us a scorcher under full gray like a covered dish from hell. Surprise it's suffering girl.",
    "Overcast scorcher. The clouds aren't blocking anything they're insulation. We didn't ask for this girl.",
  ],
};
