import '../../../features/weather/domain/entities/temperature_tier.dart';

const partlyCloudyQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Partly cloudy single digits. She's giving Ice Age but the sad parts. Stay inside in your warmest everything bestie.",
    'Clouds and sun fighting for the sky while we freeze. Very animated movie rivalry. Blanket burrito time girl.',
    'Half sun half clouds all cold. Elsa and Anna need to sort this out. Puffiest coat on babe.',
    "The sky can't pick a side and neither can the thermostat. Every layer you own bestie.",
  ],
  TemperatureTier.freezing: [
    "Sun and clouds doing the will-they-won't-they below freezing. Heaviest coat on for the whole season girl.",
    "Partly cloudy and freezing. She's giving winter fairy tale energy. Pretty but shivery. Scarf on babe.",
    'Below freezing with clouds playing peekaboo with the sun. Nobody asked for this game. Warm boots bestie.',
    'The sky is having a whole identity crisis in the cold. Bundle up in your heavy coat and let her figure it out girl.',
    "Partly cloudy and freezing. She's giving Frozen wasteland scene where Anna is looking for Elsa. Earmuffs on babe.",
    'Below freezing with clouds playing tag with the sun. Cute game horrible temperature. Gloves on bestie.',
    "The sky can't decide and neither can the cold. Full winter gear no exceptions girl.",
    'Partly cloudy below freezing. Very ice kingdom establishing shot vibes. Layer like royalty babe.',
    'Clouds and sun trading shifts in the cold. Both unhelpful. Heaviest coat and hot cocoa bestie.',
  ],
  TemperatureTier.jacketWeather: [
    "Partly cloudy jacket weather. Very Merida running through the highlands vibes. Jacket on bestie.",
    'Sun and clouds sharing the sky like Disney princesses sharing screen time. Jacket on and go enjoy babe.',
    "She's giving cottagecore with a light layer. The clouds are just adding dimension. Hoodie on girl.",
    'Cool and partly cloudy. Taylor Swift folklore album cover energy. Cute jacket and go bestie.',
    "She's giving Enchanted Central Park scene vibes. Cool with a few clouds for drama. Sneakers on girl.",
    'Partly cloudy jacket weather. Very Olivia Rodrigo walking and thinking deeply energy. Denim jacket bestie.',
    'The sky is doing a whole sun-cloud duet. Cool enough for a jacket. Go enjoy the show babe.',
    'Cool with clouds and sun. Very Belle walking through town looking dreamy energy girl.',
    "Partly cloudy and jacket weather. She's giving friendship bracelet making weather. Layer up bestie.",
    'A few clouds at jacket weather. Sabrina Carpenter would film something gorgeous in this. Light layers babe.',
  ],
  TemperatureTier.flannelWeather: [
    'Partly cloudy and mild. This is peak fairy tale weather and I will not be taking questions girl.',
    "She's giving the exact vibes of a Pixar movie where everything goes right. Flannel on and get outside babe.",
    'Sun and clouds at this temp. Literally the weather equivalent of a Taylor Swift bridge. Cozy sweater perfection bestie.',
    "Flannel weather with clouds adding aesthetic. She's giving main character autumn montage. Cute boots girl.",
    "She's giving Brave riding through the highlands with clouds rolling by energy. Light scarf on babe.",
    'Partly cloudy and mild. The sky is doing a watercolor tutorial. Flannel on and go be the subject bestie.',
    'Clouds and sun and perfect temps. Very Encanto magical courtyard vibes. Best fall outfit girl.',
    "Mild with artistic clouds. She's giving Olivia Rodrigo album cover shoot energy. Cozy layers babe.",
    'The sky mixed sun and clouds like a DJ mixing a perfect set. Go dance in your cutest sweater bestie.',
    'Partly cloudy flannel weather. Very Rapunzel painting the sky from her window vibes girl.',
    "She's giving that Pixar movie scene where the protagonist discovers something beautiful. Flannel on babe.",
    'Mild with a few clouds. Very Sabrina Carpenter afternoon picnic vibes. Light scarf bestie.',
    'The clouds are just adding texture to a perfect day. Interior designer sky. Cute boots on girl.',
  ],
  TemperatureTier.shortsWeather: [
    "Warm and partly cloudy. Built in shade breaks. She's so thoughtful. Sundress on babe.",
    "She's giving Luca Italian summer with cloud breaks. Silenzio Bruno and go outside in your shorts bestie.",
    'Partly cloudy shorts weather. The clouds are just keeping it interesting. Sandals on girl.',
    'Warm with some clouds. Sabrina Carpenter would film a music video in this. Shorts and sunglasses babe.',
    "She's giving Encanto courtyard in the afternoon with everyone dancing vibes. Tank top girl.",
    'Warm with clouds for character development. Very coming of age summer movie. Ponytail and shorts bestie.',
    'Partly cloudy and warm. The clouds are just providing free shade breaks. Sundress babe.',
    'Warm with a side of clouds. Very Lilo surfing while Stitch causes problems energy. Sandals girl.',
    "She mixed warm weather with a few clouds and honestly it's giving range. Shorts on bestie.",
    'Partly cloudy shorts weather. Olivia Rodrigo would film the music video today. Sunglasses on babe.',
    'The sky is half sun half clouds and fully serving. Shorts on and go outside girl.',
    'Warm partly cloudy perfection. Very Moana vibes minus the demigod drama. Sundress bestie.',
    "She's giving Sabrina Carpenter beach day with aesthetic cloud coverage. Tank top and sandals babe.",
  ],
  TemperatureTier.scorcher: [
    'Scorching with cloud breaks. The clouds are doing charity work at this point. SPF on bestie.',
    'Partly cloudy and melting. Thank the clouds for every second of shade. Hat on girl.',
    "She's giving Aladdin desert scene but the clouds are Genie trying to help. Hydrate immediately babe.",
    'Scorching partly cloudy. The clouds are the only thing standing between you and sunburn. SPF bestie.',
    'Hot with clouds that showed up to spectate not help. SPF and water bottle anyway girl.',
    'Scorching and partly cloudy. The clouds are just heat accessories at this point. Lightest clothes on babe.',
    "She's giving Moana lava scene but the clouds are just watching. Water now bestie.",
    'Partly cloudy and scorching. The shade is a tease. Commit to the hydration. Hat on girl.',
    "Hot with decorative clouds. She's giving desert oasis mirage energy. Drink water for real babe.",
    "The clouds are cosplaying as shade. Still scorching. Don't fall for it. SPF on bestie.",
  ],
};

const partlyCloudyExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Partly cloudy single digits. Can't commit and it's cold as fuck babe. Stay warm.",
    "Sun peeking through like she's helping. Bitch you are a lamp.",
    "Single digits partly cloudy. She packed half a suitcase and left for Antarctica. Girl commit to something.",
    'Clouds and sun sharing the sky, neither doing shit for warmth. Step up girls.',
    "Fucking freezing. Sky's indecisive and the temp chose violence. Great. Love that.",
    "Partly cloudy and cold as fuck. She gave us clouds AND cold AND sun AND nothing. The full useless buffet babe.",
    'Partly cloudy single digits. She brought clouds and sun and forgot the fucking warmth. Classic her.',
    "Partly cloudy cold as fuck. She showed up half-dressed to a funeral. The funeral is us. Layers on girl.",
    "Partly cloudy single digits. She can't pick an outfit or a temperature. Failing at both simultaneously babe.",
    "Half sun half clouds full freeze. Sky's confused. We're confused. Everyone's confused babe.",
    "Single digits partly cloudy. She brought a PowerPoint with two slides and neither one has warmth on it girl.",
    "Single digits and the sky is being petty about it. Clouds and sun taking turns doing nothing girl.",
    'Partly cloudy single digits. The sky is going through it and so the fuck are we babe.',
  ],
  TemperatureTier.freezing: [
    "Cold as fuck but at least we're getting some sun through the clouds. Not fully gray. Take the win babe.",
    "It's giving Black Swan. Dramatic sky but at least there's light peeking through. Coat on girl.",
    "Partly cloudy below freezing. Some sun some clouds. At least she's giving us variety. Bundle up babe.",
    "She's giving Clueless. A little confused but still cute as shit. Cher would layer babe.",
    "Partly cloudy and freezing but hey. Every time the sun peeks out it's a whole damn gift. Coat on girl.",
    "Below freezing partly cloudy. At least the sky has some personality. Full gray would be worse. Bundle up girl.",
    "Cold as fuck but sun keeps poking through the clouds like hey I'm still here. Love that energy. Coat on babe.",
    "Partly cloudy and freezing. She's giving us a light show between the clouds. Free entertainment honestly. Layer up girl.",
    "Below freezing but at least the clouds aren't hogging the whole sky. We see you sun. Coat on babe.",
    "Partly cloudy cold as shit. But those little patches of blue sky are doing everything for my mood. Bundle up girl.",
    "Freezing and partly cloudy. She could be full overcast but she's letting light through. Small mercies babe.",
    "Cold as fuck but the sun keeps sneaking past the clouds for us. She's fighting for it. Respect. Coat on girl.",
    "Partly cloudy below freezing. At least we get moments of sunshine. That's more than January deserved honestly babe.",
    "Below freezing but the sky's got texture. Sun and clouds doing a little dance. Beats flat gray every time girl.",
    "Partly cloudy and freezing. Every sunbreak is a goddamn blessing right now. Appreciate the moments. Coat on babe.",
    "Cold as fuck partly cloudy. But when that sun hits between the clouds it's honestly beautiful. Layer up girl.",
    "She's mixing sun and clouds below freezing. At least she's trying to give us something. Coat on babe.",
    "Partly cloudy and freezing. Not perfect but not hopeless. The sun is in there fighting. Coat on girl.",
    "Below freezing partly cloudy. Sun peeking through like she hasn't given up on us. Neither should you. Bundle up babe.",
    "Partly cloudy cold as fuck. But at least the sky isn't a concrete ceiling. There's blue up there. Coat on girl.",
    "Freezing but partly cloudy. She could've gone full gray but she left the light on. Appreciate that shit babe.",
    //"Partly cloudy below freezing. She's giving restaurant menu with no food. Great options. Nothing available babe.",
    "Below freezing partly cloudy. The sun breaks through and honestly it hits different when it's this cold. Magical shit girl.",
    "Partly cloudy and freezing. At least it's not bleak. There's dimension up there. Coat on and go babe.",
    "She's giving us sun between the clouds at freezing temps. Every ray is earned and beautiful honestly babe.",
    //'Partly cloudy below freezing. She brought props to a tragedy. The clouds are decorative. The cold is not babe.',
    //"Partly cloudy and freezing. She's redecorating a house fire. Girl the house is on fire.",
  ],
  TemperatureTier.jacketWeather: [
    'Partly cloudy and fine. She cleaned up fucking nice. Sunnies on babe.',
    "Sun and clouds doing a little dance. Cool as fuck. She's in her choreography era babe.",
    'Clouds and sun coexisting at a nice temp. If only people could figure this shit out girl.',
    "She's partly cloudy and cool and I just want to walk somewhere with a coffee. She planned this shit babe.",
    "She's mixing sun and clouds like a DJ who actually reads the fucking room babe.",
    'Clouds and sun taking turns at a nice fucking temp. Like a relay race but both teams are winners girl.',
    "Partly cloudy and a little chilly. She's being fucking indecisive in the cutest way possible. Jacket on go girl.",
    'Partly cloudy and chilly. Textbook pretty day. She read the fucking assignment for once babe.',
    "She handed me sun and shade like a waiter with two fucking plates. Both for me. Both perfect babe.",
    "She's being so chill I forgot she tried to kill us last week. Partly cloudy and cool babe.",
    'Partly cloudy jacket weather. Get outside. Jacket on. She finally got her shit together girl.',
  ],
  TemperatureTier.flannelWeather: [
    'Partly cloudy nice as fuck. Clouds are a whole aesthetic. Get outside girl.',
    'Partly cloudy and perfect. Zero notes zero complaints. Not one. Just go babe.',
    "Clouds are giving texture to a perfect day. She's an artist and today is the fucking canvas babe.",
    "Partly cloudy at this temp. She's not overachieving she's not underperforming. She's hitting the fucking sweet spot babe.",
    "Partly cloudy and mild and I think I just fell in fucking love. It's mutual girl.",
    "Partly cloudy cool temps and I'm gone. Deceased. She killed me with perfection girl.",
    "Partly cloudy perfect temps. I'm obsessed and I'm loud about it. Get your ass outside babe.",
    "Partly cloudy perfect temps. She said too much sun is basic. She's fucking right babe.",
    "Partly cloudy mild temps. Put your phone down and go be in her. I'm serious girl.",
    "Clouds drifting through a mild day like she's directing a movie. I'd watch it bitch.",
    "Partly cloudy nice as fuck. This is her apology for last week and it's accepted. Fully babe.",
    'Partly cloudy at this temp is objectively the best fucking weather on earth. Fight me girl.',
    'Partly cloudy at this temp hits different. She knows it. I know it. We all know it girl.',
    'Sun and clouds and perfect temps. This weather fucks. I said what I said.',
    'Partly cloudy flannel weather. Hoodie on boots on get the fuck out there babe.',
    "Flannel and sunnies. She served clouds for character and warmth for free. Get outside bitch.",
  ],
  TemperatureTier.shortsWeather: [
    'Partly cloudy nice as fuck. Clouds giving free shade. So thoughtful. Shorts time babe.',
    'Partly cloudy shorts weather. Fuck your plans. New plans. Outside. Now. Go.',
    "It's nice as fuck outside. Like offensively nice. Shorts on babe.",
    "She's warm with built-in shade. She invented a feature. Shorts on immediately girl.",
    'Partly cloudy and gorgeous. Sky is delivering. Go accept her gift babe.',
    "Sun when you want it shade when you need it. She's fucking psychic girl.",
    'The kind of day you call in sick for. Do it. No regrets babe.',
    'Partly cloudy shorts weather. Shade built in. Sunscreen optional. Get the fuck outside babe.',
    "She gave you sun and shade at shorts weather. The fuck more do you want girl.",
    'Partly cloudy warm as hell. Shorts on sunnies on bullshit off. Go babe.',
    "She's warm and partly cloudy and you're still inside? Go. Like right now girl.",
    'Partly cloudy and perfect. Not asking. Telling. Shorts on. Outside. Now bitch.',
    'Built-in shade at perfect temps. She did the math for you. Shorts on go girl.',
  ],
  TemperatureTier.scorcher: [
    'Partly cloudy and scorching. Thank fuck for those clouds. SPF babe.',
    "Every time a cloud shows up I whisper thank you and every time it leaves I whisper you bitch. Emotional roller coaster girl.",
    'Hot as fuck. Clouds giving shade breaks like little apologies. Not enough but noted babe.',
    "Hot as shit partly cloudy. The clouds are the only witnesses to this crime and they keep leaving. Unreliable as fuck babe.",
    // "Partly cloudy and scorching. I'm timing my life around cloud shadows like a sundial but with more swearing girl.",
    'Partly cloudy and hot as shit. The clouds are doing more for us than the sun ever has girl.',
    "Hot as fuck with intermittent mercy. She's doling out shade like treats. We'll be good girl I promise.",
    // "Partly cloudy scorcher. I'm timing my walks between cloud shadows. Strategic as fuck girl.",
    "Hot as fuck partly cloudy. I'm out here following cloud shadows like a stray cat follows food babe.",
    // 'Partly cloudy hot as shit. Every cloud is a tiny vacation from her violence babe.',
    "Hot as fuck with cloud relief. She's playing good cop bad cop with herself girl.",
    "Partly cloudy scorcher. The sun keeps peeking around clouds like I'm still here. Girl we know. We're boiling.",
    "Hot as fuck out here. Every time a cloud passes it's a religious experience. Hallelujah babe.",
    "Hot as fuck. Cloud passes overhead and I moan. Like audibly. In public. She reduced me to this babe.",
    "Partly cloudy scorcher. The clouds are doing their best but their best is like holding a napkin over a bonfire girl.",
    "Partly cloudy and scorching. She's playing peekaboo with the sun and every peek costs us another degree of sanity babe.",
    "She's so fucking hot the clouds are the only thing keeping us alive. Guardian angel energy babe.",
    // 'Scorching and partly cloudy. She burned us then covered us then burned us again. Make up your mind girl.',
    // "Scorching partly cloudy. I just chased a cloud shadow across a parking lot. Running. In flip flops. She made me feral girl.",
    "She showed up confused and hot. Not hot temp hot. Well also hot temp. Both kinds of hot bitch.",
    "Hot as shit partly cloudy. Every cloud shadow is a tiny oasis and I'm a fucking desert nomad stumbling between them babe.",
    "Scorching and partly cloudy. She's assaulting us with shade breaks. How generous.",
    "Partly cloudy scorcher. She keeps giving us hope then taking it away. Toxic as fuck. But the shade is nice girl.",
    "Scorching with cloud breaks. She's torturing us on a schedule. Organized sadist girl.",
    "Partly cloudy and scorching. I befriended a cloud. Named it. It left. Heartbroken. Another one came. I'm over it. Moving on babe.",
    // "Scorching partly cloudy. The sun and clouds are taking turns parenting us. Sun grills us. Clouds comfort us. Divorced energy girl.",
    'Partly cloudy and melting. The shade hits like a glass of water in hell. Brief but holy babe.',
    'Scorching partly cloudy. The clouds are pulling overtime and they deserve a raise babe.',
    "Hot as fuck partly cloudy. I'm standing in a cloud shadow refusing to move. People are walking around me. I'm a monument now girl.",
    "Partly cloudy and scorching. She's flash-frying us then giving shade breaks. Tempura energy. We're the shrimp babe.",
  ],
};
