import '../../../features/weather/domain/entities/temperature_tier.dart';

const rainQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Rain in single digits. She chose the cruelest combo in the weather handbook. Stay inside in every layer bestie.',
    'Pouring at single digits. Very villain origin story weather. Do not go outside. Fuzzy socks on girl.',
    "She picked rain and single digits like she's speedrunning misery. Stay in your blanket burrito babe.",
    'Rain this cold is a personal attack. Every fairy tale villain is taking notes. Puffiest coat if you must go out bestie.',
  ],
  TemperatureTier.freezing: [
    "Below freezing rain. She's giving the storm scene before the big rescue in every Disney movie. Heaviest coat girl.",
    'Rain and freezing. She really went for maximum drama today. Warm boots and scarf on bestie.',
    "Freezing rain. She watched the sad part of Bambi and made it everyone's problem. Heavy coat babe.",
    'She combined cold and wet like a villain mixing her worst spells. Heavy coat and gloves girl.',
    'Freezing rain. She woke up and chose maximum drama today. Do not leave without full winter gear bestie.',
    'Below freezing and raining. Very Mulan training montage but make it miserable. Earmuffs on babe.',
    "Cold rain coming down hard. She's giving ice queen villain origin weather. Heaviest coat and scarf girl.",
  ],
  TemperatureTier.jacketWeather: [
    "Rainy and cool. She's giving the contemplative walk scene in every coming of age movie. Rain boots bestie.",
    'Rain at jacket weather. Very Totoro bus stop moment vibes. Grab an umbrella and go enjoy it babe.',
    "She's raining at jacket temp like a fairy tale film in the best way. Cute umbrella on girl.",
    'Cool and rainy. Taylor Swift would call this the perfect song writing weather. Jacket and boots bestie.',
    'Rainy and cool. Very Rapunzel running through puddles vibes. Jacket and rain boots girl.',
    "She's giving Olivia Rodrigo rainy day music video energy. Hoodie and cute umbrella babe.",
    'Rain at jacket weather. Very Raya walking through the rain on her quest vibes. Jacket on bestie.',
    'Cool rain. Rain boots and your cutest umbrella. She is giving main character in a rainy day montage vibes babe.',
    'Rainy and jacket weather. The sky is giving dramatic monologue and honestly she ate. Light layers girl.',
    'Rain and cool. Very Sabrina Carpenter pensive rainy window moment. Jacket and rain boots bestie.',
  ],
  TemperatureTier.flannelWeather: [
    "Rain at this temp. She's giving the cozy scene where the characters finally talk about their feelings. Flannel babe.",
    "Rainy flannel weather. She's serving fairy tale rainstorm realness. Curl up in your coziest sweater girl.",
    "She's raining at the perfect temp. Window seat and hot chocolate energy bestie.",
    'Mild and rainy. She understood the cozy assignment and turned it in early. Cute boots on babe.',
    "Rainy and mild. She's giving Rapunzel watching the rain from the tower but make it cozy energy girl.",
    'Mild rain. Very Encanto growing the garden in the rain scene vibes. Flannel on bestie.',
    "Rain at flannel weather. She's giving Olivia Rodrigo favorite crime rainy day. Cozy sweater on babe.",
    'Rainy and mild. Very Ponyo house by the sea during a gentle storm energy girl.',
    "Mild rain energy. She's giving Taylor Swift writing poetry by a rainy window. Flannel on bestie.",
    'Rain and flannel weather. The kind of day that makes you want to bake something. Warm sweater babe.',
  ],
  TemperatureTier.shortsWeather: [
    "Warm rain. She's giving the summer storm scene in a Pixar movie. Sandals on and go splash around bestie.",
    'Rainy and warm. The kind of rain you dance in. Sabrina Carpenter music video energy girl.',
    'Warm enough to stand in her and smile. Free therapy from the sky. Shorts on babe.',
    "She's raining warm. Every puddle is an invitation. Go jump in one in your sandals bestie.",
    "Warm rain. She's giving Encanto miracle scene but make it refreshing girl.",
    'Rainy and warm. Very Luca ocean transformation reveal vibes. Shorts on babe.',
    "Warm rain energy. She's giving Sabrina Carpenter dancing on the lawn in summer. Sundress on bestie.",
  ],
  TemperatureTier.scorcher: [
    "Rain on a scorcher. She's fighting fire with water. Go off queen. Lightest clothes girl.",
    'Hot rain. Relief is dramatic and wet and we are grateful. Thank you. Shorts on bestie.',
    'Scorching rain. She looked at the heat and said not on my watch. Tank top babe.',
    "She's hosing down the city and honestly everyone needed this. Sandals on girl.",
    "Hot rain. She's giving Moana restoring Te Fiti vibes. Lightest clothes on bestie.",
    'Scorching rain. The sky is sweating and crying at the same time. Honestly relatable. Shorts on babe.',
    'Raining and hot. Very Mirabel running through the rain to save the miracle energy. Stay hydrated girl.',
  ],
};

const rainExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'She chose fucking violence. Stay inside babe.',
    "She fucking committed and I wish she hadn't. Waterproof everything girl.",
    'She watched The Ring again and it shows. Cold dark pouring. Nobody asked for this shit.',
    'Not her going this hard in the cold. Zero chill. Never fucking has.',
    'Adele wrote Set Fire to the Rain for this exact energy. Cold dramatic af babe.',
    "Sinéad O'Connor energy. Cold rain dramatic as fuck. Honestly crying babe.",
    'Oh fuck. She has something to prove and your plans are collateral damage.',
    'Sky fully lost it. She is down bad and taking it out on all of us. What the hell.',
    "She served cold rain like it's a signature dish. Nobody ordered this babe.",
    "She didn't just choose violence she premeditated it.",
    "She's punishing us and we don't even know what we did.",
    "Rain and cold teaming up like they rehearsed this. Coordinated assault babe.",
  ],
  TemperatureTier.freezing: [
    "She's off the deep end and dragging everyone down with her. Stay the fuck inside girl.",
    "The Cranberries Zombie on repeat out here. Below freezing rain won't fucking die.",
    "Like it's personal. She woke up with a vendetta. Bundle the fuck up babe.",
    "She's not angry she's disappointed. Which is so much fucking worse.",
    'She brought the worst of both worlds and served them together. Combo meal from hell babe.',
    'Kathy Bates in Misery energy. Cold fucking relentless. Not letting you leave. Classic her.',
    "She's channeling Shelley Duvall in The Shining. Below freezing rain. She's losing it babe.",
    "She showed up wet and angry and won't leave. Classic her honestly girl.",
    "She's weaponized water and cold at the same time. Dual wielding misery girl.",
    "Below freezing rain. She's writing an autobiography and every chapter is about us suffering babe.",
    "Raining below freezing. She's so cold the rain looks surprised it's not ice yet girl.",
    "She turned the whole city into a cold shower nobody consented to. Class action lawsuit energy babe.",
    "Below freezing and raining like she's trying to fill a swimming pool nobody ordered girl.",
    "Freezing rain. My umbrella just looked at me and said I can only do so much. She broke its spirit babe.",
    "She's pouring at freezing temps like rent is due and she's paying in misery girl.",
    "Below freezing rain. Even my waterproof jacket said this is above my pay grade babe.",
    "She dialed up the cold and the wet simultaneously like a DJ mixing two terrible songs girl.",
    "Freezing rain. She's not just ruining today she's ruining the memory of today. Retroactive misery babe.",
    "Raining below freezing. The puddles are forming grudges. The sidewalks are pressing charges girl.",
    "She brought freezing rain like a hostess gift from hell. Nobody asked. Can't return it babe.",
    "Freezing rain. My windshield wipers are ice skating and losing. She choreographed their funeral babe.",
  ],
  TemperatureTier.jacketWeather: [
    "She's being atmospheric as fuck. Go stomp in some puddles babe.",
    "Feels like a Radiohead song outside. Cool rainy moody af. All about it honestly.",
    'Girl Interrupted vibes out here. Chilly moody a little chaotic. Rain jacket and stay dry babe.',
    // "She's fucking giving I'm not mad I'm just disappointed but actually she's very mad babe.",
    'She picked a side and went for it. No drizzle no mist. Full rain in the cold. Bold choice girl.',
    "She's giving that album you listen to when you want to feel something. Honestly kind of a vibe girl.",
    "She showed up loud and wet and I'm somehow here for it. Like shit. Rain jacket on girl.",
    'Cold and fully raining. Energy the drizzle fucking wishes she had tbh. Umbrella and boots babe.',
    "She's being so moody the streetlights turned on early. Even they're into it girl.",
    'Not her blasting Only Happy When It Rains on repeat. Like girl we get it. Chill.',
    "Gone Girl energy. Moody dark reminding you she's here. Rain jacket on girl.",
    // "She's got that unhinged ex energy. Showing up uninvited making everything wet.",
    // 'She made the sidewalks shine and ruined your hair. Priorities babe.',
    "She's being a whole problem right now and I kind of respect it honestly. Like do you girl.",
    "Cold and rainy. She didn't ask permission and she's not fucking apologizing. Iconic honestly.",
    "Cold and rainy. She decided today has a whole plot. Didn't ask but we're in it. Stay dry babe.",
    "She's being so fucking dramatic I'm honestly cheering her on. From inside. With a blanket babe.",
    "She's washing the city and honestly it needed it. Spring cleaning from the sky. Thanks girl.",
    'She brought the drama and the water bill. Worth it honestly. Stay warm stay dry babe.',
    "She turned every windshield into a meditation app. The wipers are counting breaths now girl.",
    // "Raining at jacket weather. She just made every parking lot look like a Renaissance painting babe.",
    // "She ruined my hair and fixed my mood. Complicated bitch. Rain jacket on girl.",
    // "She's so loud on my roof right now I turned off the TV. She IS the entertainment babe.",
    // "She turned every storm drain into a river and every gutter into a symphony. Gross and gorgeous girl.",
    "Raining and cool. My socks are wet and my soul is full. She's confusing like that babe.",
    // "She's drumming on my car so hard I'm convinced she has a message. I'm listening girl.",
    // "She just turned my umbrella inside out and I laughed. She's funny when she's mean babe.",
    "Rainy chilly as fuck. We're out here surviving. Bundle up boots on we got this babe.",
    // "She made the whole city smell like wet pavement and nostalgia. My childhood just called babe.",
    // "She's raining so hard the squirrels gave up. They're just sitting there accepting it. Same girl.",
    // "Raining at jacket weather. A pigeon just walked under an awning looked at me and we both sighed. She united us in suffering babe.",
  ],
  TemperatureTier.flannelWeather: [
    'Rainy at perfect temps. She brought her whole chest to this. Zero fucking notes girl.',
    'Mild rain smooth as fuck. Mitski wrote Nobody for weather like this. She gets it girl.',
    "Breakfast at Tiffany's energy. Rainy mild iconic as fuck. She knows what she's doing babe.",
    "She went all in. Didn't even hesitate. Honestly obsessed as shit.",
    "She's giving everything she's got and it's working. Go get soaked bitch.",
    'Peak weather. Like shit. I will die on this hill. Soaking wet on this hill girl.',
    'Damn. She really showed up with volume and purpose and zero apology. Rain boots and go babe.',
    'She turned a perfect day into a perfect rainy day. Somehow better. Rain boots and go babe.',
    "She's out here giving everything and I'm inside giving nothing. Fixing that asap. Rain boots on bitch.",
    "She's drumming on every surface like she's performing just for you girl. Show some fucking support get out there.",
    'Rainy flannel weather. Rain boots on hoodie up get out there babe. She earned this shit.',
    "She's raining at the perfect fucking temp. Throw on a jacket and go stand in it girl.",
  ],
  TemperatureTier.shortsWeather: [
    "If you don't go outside right now I'm judging you. Get out there and dance your ass off girl.",
    'Flashdance energy out here. She dumped a bucket on herself called it art and it fucking worked. Iconic.',
    'Best rain. This is not up for debate. Get the fuck outside babe.',
    'Get your ass outside and stand in it. This is the good stuff girl.',
    "She's fucking performing and none of us bought tickets. Free show babe.",
    "She's literally baptizing you not that you asked. Shorts on go play girl.",
    "Waterfalls energy but she said don't go chasing me I'll come to you. Go play honestly.",
    "She's out here turning the whole city into a water park. No wristband needed babe.",
    "She's giving summer camp nostalgia. Run through her like you're twelve again bitch.",
    "She's writing her own coming of age movie and you're the fucking lead. Go play girl.",
    "She's serving wet hot summer and I'm eating it up with both hands babe.",
    // "She said I'm going to make everyone wet and not be weird about it. She lied. It's weird as shit.",
    // "She's the ex you write songs about. Go stand in her bitch.",
    "She's unhinged and fucking gorgeous and I've never been more in love honestly.",
    'Warm enough to stand in her and yell. Do it honestly. Free therapy babe.',
    'She turned the whole block into a splash pad. Free admission. Go play babe.',
    "She's so warm and wet the puddles are calling my name. Jumping in girl.",
    "She showed up dramatic and warm and I'm stomping in puddles like a feral child babe.",
    'She made it warm enough to enjoy and wet enough to remember. Smart girl.',
    "She's rinsing us off and we needed it. Group shower energy. Not weird babe.",
    // "Warm rain. I just splashed through a puddle in sandals and kicked water at a stranger. They kicked back. She started a revolution babe.",
  ],
  TemperatureTier.scorcher: [
    'Came here to cool us the fuck down. Please and thanks girl.',
    "Fierce as hell. Tomb Raider energy. She didn't come to play girl.",
    // "SZA wrote Kill Bill for this energy. Hot rainy dramatic as fuck. She's in her feelings babe.",
    'She showed up to a fire with a hose and zero chill. Chaotic good af.',
    'Hot as fuck and dumping. She saw the sun being a bitch and said not on my watch girl.',
    'The rain is warm. The air is warm. Everything is warm and wet. Spa from hell babe.',
    'The sun and the rain are fighting over you. Messy but kinda flattering honestly.',
    "She's fighting the sun with water and fucking winning. Underdog story of the century babe.",
    'Rainy and hot as fuck. The sun is embarrassed and honestly she should be. Cool us down girl.',
    "The sky's out here admitting she went too far. Accountability queen honestly. Good for her.",
    'She really brought water to the desert and dumped it on our heads. Close enough. Still works bitch.',
    "She wrestled the heat to the ground. Ref counted to three. It's over girl.",
    'She was late but she brought snacks so we forgive her. Thanks anyways girl.',
    'Well shit. She finally showed up to work. Better late than never honestly.',
    'She really looked at the sun and said go home I got this. Respect honestly.',
    "She's giving mixed signals and I'm still falling for it. Every time girl.",
    'She picked a fight with the heat and brought the whole ocean. Overkill but go off girl.',
    "She's hosing us down and honestly we needed it. Thanks queen.",
    "She's having a crisis and fixing a crisis at the same time. Multitasking queen.",
    "She's really out here putting out fire she started herself. Full circle moment honestly.",
    // "Scorching rain. The steam is rising off the pavement like the street is having a hot flash. Menopause energy. Hydrate babe.",
  ],
};
