import '../../../features/weather/domain/entities/temperature_tier.dart';

const snowQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Elsa walked so this snow could run. Bundle up in every layer and watch from inside girl.',
    'Snowing in single digits. She is in her absolute element right now. Warmest boots and stay cozy bestie.',
    "Peak snow energy. She's giving the Frozen opening sequence. Every layer you own babe.",
    'Single digit snow. This is the scene where the Disney princess stays in the castle. Fuzzy socks on girl.',
  ],
  TemperatureTier.freezing: [
    "Snow below freezing. She's giving Narnia through the wardrobe energy. Warmest coat and boots bestie.",
    'Snowing and freezing. Very fairy tale winter episode vibes. Layer up and watch from the window with hot cocoa babe.',
    "She's in her snow era and she is thriving. Below freezing and beautiful. Scarf and gloves girl.",
    "Freezing snow. She's serving winter fairy tale realness. Go play if you can handle it in your heavy coat bestie.",
    'Snowing and freezing. Very Frozen winter train stop energy. Every layer every accessory girl.',
    "Snow below freezing. She's giving Brave but in winter. Warmest boots and earmuffs bestie.",
    "Freezing snow. The sky committed fully. Very Elsa ice palace in the mountains winter scene. Heavy coat babe.",
  ],
  TemperatureTier.jacketWeather: [
    "Snow at jacket weather. She's giving magical and temporary. Go catch snowflakes in your cute jacket babe.",
    'Snowing and cool. The kind of snow that melts on your tongue. Disney princess moment. Hoodie on girl.',
    "She showed up knowing she won't stay long. Fleeting and beautiful. Jacket on and go witness her bestie.",
    "Snow at jacket temp. She's giving the surprise twist in a Pixar short. Boots on and go enjoy it babe.",
    "Snow at jacket weather. She's giving confused spring fairy tale transition energy girl.",
    "Snowing but not that cold. Very Tangled winter festival that wasn't planned vibes. Cute jacket on bestie.",
    "Jacket weather snow. She's giving Olivia Rodrigo music video where seasons don't make sense. Sneakers on babe.",
  ],
  TemperatureTier.flannelWeather: [
    'Snow at this temp. She watched a holiday movie and said hold my hot cocoa bestie.',
    "Snowing and mild. She's the surprise guest nobody expected. Very plot twist energy. Cozy sweater girl.",
    "Mild snow. She showed up where she doesn't belong and she is eating. Legend. Cute boots babe.",
    "Snow at flannel weather. She's giving confused fairy tale energy and it is adorable bestie.",
  ],
  TemperatureTier.shortsWeather: [
    "Snow at warm temps. She's giving glitch in the fairy tale matrix. Go catch one before she melts girl.",
    'Warm snow. She showed up to the wrong season like a lost Pixar character. Shorts still on babe.',
    'Snowing and warm. Evaporating on contact and she does not care. Dramatic queen bestie.',
    "She knew she wouldn't last and came anyway. Main character energy. Sandals on girl.",
  ],
  TemperatureTier.scorcher: [
    'Snow in a scorcher. She broke the rules and wrote new ones. Legendary honestly. Lightest clothes bestie.',
    "Hot snow. She's gone before she lands but she wanted you to see her. Iconic. SPF on babe.",
    'Scorching and snowing. The simulation crashed. Every fairy tale law has been violated girl.',
    'She showed up impossible and unbothered. The main character of weather. Hat and water on bestie.',
  ],
};

const snowExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'She woke up and chose to be fucking gorgeous. Snow angels now babe.',
    'She watched Frozen again and now she IS the movie. Bundle the fuck up babe.',
    'Not her putting on this show while you freeze your ass off girl.',
    "She's in her fucking prime right now and she knows it.",
    'Cold as shit but SNOW. Get out there catch some on your tongue.',
    'She was born for this shit. Literally. Go play babe.',
    'Put on Enya and go stand in this. Beautiful cold committed as hell babe.',
    "Snowing and cold af. Go make a snow angel right now. I'm serious girl.",
    'Kate Bush Snowflake energy out here. Fucking cold snowy ethereal babe.',
    "This is her whole career. She's nailing it.",
    'She is in her damn element right now girl.',
    'Edward Scissorhands vibes. Snowing cold beautiful honestly. Go play.',
  ],
  TemperatureTier.freezing: [
    "She's snowing like she's trying to make us fall in love with her. It's working. Fuck.",
    'She came correct. Right temp right vibe right fucking everything girl.',
    "Oh my god. Like she's been planning this all year. Rehearsed. Go play babe.",
    "She's fucking performing at peak conditions. This is her Super Bowl babe.",
    'Love Actually energy. Everything feels like a damn movie. Heaviest coat af girl.',
    "Catch flakes on your tongue like you're seven. What the hell.",
    'White Witch Narnia energy. Beautiful brutal. Zero shits given. Bundle up girl.',
    'This snow is so pretty I could cry. Actually I am crying. Go outside babe.',
    'Snowing below freezing and she fucking nailed it. Get outside. Bundle the fuck up. Go play babe.',
    "She served snow at the perfect damn temp. Don't just stare. Get your ass out there girl.",
    'Holy shit. She went full winter wonderland. Warmest coat catch some flakes. Go babe.',
    'Below freezing snow. She brought her A game. Get the fuck outside and be in it girl.',
  ],
  TemperatureTier.jacketWeather: [
    "Snowing above freezing. She showed up knowing she'd melt. Said I don't give a fuck girl.",
    // 'Not the snow being a tease at this temp. Catch her while you fucking can.',
    // "Won't stick but she's here and she's fucking perfect and I'm emotional. Go.",
    "Snowing above freezing. She crashed the wrong season and she doesn't give a fuck babe.",
    // 'Tori Amos Winter vibes. Melting and fucking gorgeous. Go play babe.',
    // "I'm outside catching flakes on my tongue like a feral child af babe.",
    // "She's snowing at this temp like a beautiful idiot. Doomed and fucking gorgeous. Go love her while she's here.",
    "Snowing above freezing? She's a guest star. Brief appearance. Maximum impact bitch.",
    // 'Coraline vibes. Magical and a little creepy. Go catch her babe.',
    "Snowing above freezing. She showed up knowing she won't last and that makes it hotter girl.",
    // "She's the friend who shows up for twenty minutes and makes the whole party girl.",
    // 'She knew the assignment was impossible and showed up anyway. Legend girl.',
    // 'Brief and beautiful. Like a first kiss. Go witness her babe.',
    // "Snow at jacket weather. She's dissolving on my hand like a secret she didn't mean to tell babe.",
    // "She's dying on the sidewalk and being gorgeous about it. Dramatic exit energy girl.",
    "Snow at this temp is basically a love note that self destructs. Read fast babe.",
    "Snow showed up to a temp that doesn't want her and doesn't give a fuck. Punk rock honestly.",
    // "Flakes hitting the pavement and vanishing like she was never here. Ghost story energy babe.",
    // "She landed on my jacket and lasted three seconds. Shortest relationship I've ever had. Still emotional girl.",
    // "Snow at jacket weather. She's speedrunning her whole life cycle on my windshield. Inspirational honestly babe.",
    "Snow at this temp. She touched the ground and immediately ghosted. Dating app energy. Swipe right while you can girl.",
  ],
  TemperatureTier.flannelWeather: [
    'She crashed the party. Everyone fucking loves her babe.',
    'She should not be here at this temp and does not give a shit honestly.',
    'Not the snow showing up to mild weather. Dedicated as shit girl.',
    "She showed up where she shouldn't and it's every fucking thing. Flannel babe.",
    "Mild snow. She won't stick but she came anyway. Bold as hell girl.",
    'Rare af. Go make a snow angel now girl.',
    'Oh fuck. Aimee Mann vibes out here. Snowy mild bittersweet. Flannel on girl.',
    'A goddamn miracle. Catch some on your tongue.',
    'She watched The Holiday again and now the sky looks like this. Flannel and go babe.',
    "California Dreamin energy. She showed up somewhere she doesn't belong honestly.",
    "She's the surprise guest nobody expected and she's eating. Go enjoy her babe.",
    "Greta Gerwig's Little Women energy. Snowy mild gorgeous. She showed up babe.",
  ],
  TemperatureTier.shortsWeather: [
    "She showed up to shorts weather in a snowflake. Didn't even knock babe.",
    'She defied every law of nature for this moment. Legendary as fuck girl.',
    'Not the snow showing up where she has no business. Iconic as shit.',
    "Snow melting before it lands in shorts weather. She knows she's temporary and came anyway babe.",
    "Shouldn't exist but here she is. Take a video right fucking now.",
    'Bjork wrote Hyperballad for this moment. Warm snow surreal as fuck honestly.',
    'Jesus Christ. Amy Adams in Arrival energy. Tore through spacetime to snow here. The audacity babe.',
    "Warm snow. She's the guest who shows up to the wrong party and becomes everyone's favorite babe.",
    'Evaporating on contact and she still came. The audacity. Go catch one girl.',
    "She knew she'd die on contact and came anyway girl.",
    'Feels like a Radiohead song outside. Everything in its wrong place babe.',
    'She showed up to the wrong damn season like Interstellar. Who does this girl.',
  ],
  TemperatureTier.scorcher: [
    'She is a myth a legend a fucking miracle babe.',
    "She showed up to extreme heat and is evaporating midair. Doesn't give a shit girl.",
    "Not the snow committing to a scorcher knowing she'll die instantly. Dramatic af girl.",
    'Broke every rule of science. Unhinged af. Go witness babe.',
    'She lasted half a second and still showed up. Commitment is insane as fuck girl.',
    "That's the forecast. Physics can fuck right off honestly.",
    'Annihilation vibes. Reality is broken. Unhinged af. Who does this girl.',
    'Goddamn. Sia wrote Chandelier for this. She rose she fell she melted. Still showed up babe.',
    'Scarlett Johansson in Under the Skin energy. Impossible snow. Legendary honestly babe.',
    'Grimes energy. Alien weather. She broke reality. Love that for us babe.',
    'Gone before she lands. Wanted you to see.',
    'She wrote a whole new damn rulebook today girl.',
  ],
};
