import '../../../features/weather/domain/entities/temperature_tier.dart';

const sunnyQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Elsa really said let it go and let the temps drop to single digits. Stay inside in your coziest PJs bestie.',
    'The sun showed up like a Disney princess but forgot the warm hug. Puffiest coat on girl.',
    "She's giving Tangled tower vibes. Beautiful outside but do not leave your blanket burrito babe.",
    'Sunshine and single digits. Olaf would not survive this and neither will you without every layer you own bestie.',
  ],
  TemperatureTier.freezing: [
    'Rapunzel waited eighteen years for this and honestly she should have waited longer. Heaviest coat girl.',
    "It's giving Frozen soundtrack without the fun parts. Below freezing and the sun is just decoration. Scarf and gloves babe.",
    'Sun came out like a Disney princess opening scene but the cold said plot twist. Heavy coat and earmuffs bestie.',
    "She's giving Taylor Swift music video pretty but you will freeze if you go outside. Layer up girl.",
    'The sun really showed up to a below-zero party with no coat. Iconic but useless. Warm boots on babe.',
    "Sunny and freezing like Elsa's ice palace with the curtains open. Heaviest coat on bestie.",
    "She's giving Jack Frost with a ring light. Gorgeous and absolutely brutal. Scarf gloves everything girl.",
  ],
  TemperatureTier.jacketWeather: [
    'Main character energy and the soundtrack is Taylor Swift. Sunnies on and cute jacket ready babe.',
    "She's giving Mirabel stepping outside the Casita vibes. Cool breezy and magical. Jacket on bestie.",
    'Sunny and cool like a Pixar movie opening. Denim jacket on and go be the main character girl.',
    'Sabrina Carpenter would write a bop about this weather. Light jacket and go live your life bestie.',
    "Cool and sunny like the opening scene of a Pixar road trip movie. Jacket on let's ride girl.",
    "She's giving Rapunzel finally leaving the tower energy. Cute jacket on and go explore babe.",
    'Sunny jacket weather is giving folklore era but make it daytime. Hoodie and sunnies on bestie.',
    "The sun said I'll show up but I won't overheat you. Finally some emotional intelligence. Light layers girl.",
    'Joy from Inside Out planned this weather and she nailed it. Jacket and sneakers babe.',
    'Sabrina Carpenter espresso weather. Cool enough for a denim jacket cute enough for a photo dump bestie.',
  ],
  TemperatureTier.flannelWeather: [
    "She's giving Tangled lantern scene energy. Sun's out temps are perfect. Cutest fall outfit on girl.",
    'Rapunzel finally left the tower for this weather and honestly same. Best flannel on bestie.',
    'This is the weather Taylor Swift wrote golden hour songs about. Cozy sweater and sunnies on babe.',
    "It's giving Disney princess morning with the birds and everything. Cute boots on and get outside immediately girl.",
    'This weather understood the assignment better than most Disney sidekicks. Light scarf on and go bestie.',
    "Sunny and mild like Isabela's flower scene but everywhere you look. Flannel on and go touch grass babe.",
    "She's giving Olivia Rodrigo driving down the coast with the windows down energy. Light layers girl.",
    'The sun and the temp are in their collaboration era. We are blessed. Cute boots on and go frolic bestie.',
    'Sunny and perfect. Very Mirabel dancing through the Casita courtyard vibes. Best fall outfit on babe.',
    'This is the weather Barbie would have in her dream house. Go be cinematic in your cutest sweater girl.',
    "She's serving Inside Out Joy's happiest core memory energy. Flannel on and go make some bestie.",
    'Perfect sunny day. The kind where woodland creatures would help you pick your outfit babe.',
    'Mild and sunny like a fairy tale picnic scene. Cozy sweater on and pack a snack girl.',
  ],
  TemperatureTier.shortsWeather: [
    "She's serving Moana ocean breeze energy. Sundress on and go explore babe.",
    'This weather just said aloha like Lilo and Stitch. Shorts on and go be feral bestie.',
    'Warm sunny and perfect. Olivia Rodrigo would call this her brutal summer era. Sundress and live in it girl.',
    'The sun ate and left no crumbs. Sabrina Carpenter poolside energy. Shorts and tank top on babe.',
    "Warm and sunny. She's giving Ariel discovering legs for the first time energy. Sandals on girl.",
    'The sun is fully locked in. Very Sabrina Carpenter music video on a rooftop. Shorts and sunglasses bestie.',
    "She's serving Coco marigold bridge golden hour energy. Sundress on and go shine babe.",
    "Sunny and warm like Rapunzel's best day ever. Literally go have the best day ever in your cutest shorts girl.",
    'This weather is giving main character montage set to an Olivia Rodrigo summer track. Ponytail and sandals bestie.',
    'Warm sunny perfection. Lilo would ditch hula class for this and honestly valid. Tank top on babe.',
    "She's giving Pixar short film where everything is beautiful and nothing hurts. Sundress girl.",
    'The sun showed up and brought the warmth. Unlike some people she follows through. Sunglasses on bestie.',
    'Sunny and warm. Very Jasmine escaping the palace to explore the market vibes. Sandals on babe.',
  ],
  TemperatureTier.scorcher: [
    'Maui pulled the sun too close again. SPF and a big hat or perish bestie.',
    "She's giving Aladdin desert scene without the magic carpet shade. Lightest clothes and hydrate immediately girl.",
    'The sun really said you wanted hot girl summer and meant it literally. Water bottle now babe.',
    "She's giving Moana lava monster energy but from the sky. SPF 50 and stay in the shade bestie.",
    "The sun took it personally today. Hat on water bottle full and don't you dare skip sunscreen girl.",
    'Scorching sun. She went full villain arc. Shade water and lightest clothes you own babe.',
    "Hot enough to melt Olaf twice. Sunscreen is not optional it's survival bestie.",
    "Sabrina Carpenter said it's hot and she was not being metaphorical. Big hat and hydrate girl.",
    "She's giving Inside Out Anger took over headquarters energy. SPF and stay hydrated bestie.",
    'Taylor Swift would not even tour in this heat. Lightest clothes water bottle and find some shade babe.',
  ],
};

const sunnyExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Sunny and freezing. The duality of this bitch. Clearly a Gemini.',
    "She showed up to a shit situation and said I'm here. Like girl we needed warmth not moral support.",
    "It's giving Titanic. Gorgeous view but cold as shit. Puffer on babe.",
    "Shining like she's helping. Bitch you are a lamp. Layers girl.",
    "Sun rolled up to single digits and said I'm enough. Narrator: she was not fucking enough. Coat on babe.",
    "She's up there shining like she's doing us a favor. Bitch my eyelashes are frozen. Sit the fuck down.",
    'Sun clocked in did nothing and wants credit. Like damn okay girl.',
  ],
  TemperatureTier.freezing: [
    "Cold as fuck but she showed up anyway. She didn't have to but she did it for us babe. Coat on and go.",
    "Below freezing but sunny. At least she's trying and honestly that's more than most. Bundle up girl.",
    "Freezing but the sun is out and she's gorgeous. Could be worse. Could be gray. Coat on babe.",
    "It's giving Miranda Priestly. Cold as shit but stunning. Heaviest coat girl.",
    "She rolled up to freezing temps and said I'm still here. Respect the fuck out of that honestly. Coat on babe.",
    "Sunny and cold as fuck but at least she showed up. That's more than your ex ever did. Layer up babe.",
    "Below freezing but the sun came through. She chose us today. Coat on and appreciate her girl.",
    "Cold as fuck but sunny. She didn't have to do that. The effort alone deserves a standing ovation. Coat on bitch.",
    "Freezing but sunny. At least the sky isn't gray and depressing. Silver linings literally. Bundle up babe.",
    "She's out here shining in below freezing like a goddamn warrior. Didn't quit on us. Coat on girl.",
    "Sunny and freezing. Cold as shit but at least she's making it pretty. Vitamin D is vitamin D. Coat on girl.",
    "Below freezing but she lit the whole sky up for us. Free serotonin in the cold. Take it. Coat on girl.",
    "She's giving gorgeous winter postcard energy. Cold as fuck but honestly breathtaking. Coat on babe.",
  ],
  TemperatureTier.jacketWeather: [
    "She walked in like she's been doing this perfectly forever. Ma'am you were unhinged last week. Jacket on girl.",
    "Sunny and cool and honestly she's the ex who finally got therapy. Good for her. Don't trust it though. Jacket on babe.",
    'Sun really said watch me do my fucking job today. And then she did it. Standing ovation girl.',
    'The kind of day you bitch about not having when it sucks. Shut up and go live in it babe.',
    // "She's giving I can change energy. She can't. But today she's perfect so who gives a shit.",
    "Oh so now she wants to act right. After everything she put us through. The nerve. Jacket on bitch.",
    "She showed up looking like she slept eight hours and drank water. Since fucking when. Jacket on go babe.",
    "Not her gaslighting us into trusting her again with one pretty day. It's working though. Jacket on girl.",
    "She's behaving and it's making me emotional. Who are you and what did you do with that psycho bitch. Jacket on girl.",
    "Sunny and cool and she finally fucking delivered. Get out there before she changes her mind babe.",
    "Oh she's in her sane era today. Didn't know she had this setting. Get out there before she changes her mind girl.",
    "Not her acting like she didn't try to kill us last week. Short memory cute face. Jacket on girl.",
    "The weather just handed me a coffee and asked how I slept. Who the fuck is this woman. Jacket on babe.",
    "She showed up cute and chill as fuck and didn't ask for a single compliment. So here's twelve girl.",
    "She's doing the thing where she pretends she's stable and I'm eating it up like a goddamn fool. Jacket on girl.",
    "Sunny and cool and she's out here making me wanna do shit. Get the fuck outside babe.",
  ],
  TemperatureTier.flannelWeather: [
    'She woke up and chose to be fucking perfect. No notes. Not one. Get outside immediately babe.',
    "It's so fucking nice out strangers are making eye contact and smiling. She drugged us all babe.",
    "This weather's so good I'm suspicious honestly. Get your ass out there before she changes her mind girl.",
    "She really looked at perfection and said hold my beer. Get outside babe.",
    "Okay it's nice as fuck outside. If you're inside I'm judging you babe. Go.",
    "Sunny and nice as fuck. Stop whatever you're doing. Stop it. Go outside right now babe.",
    "She's the kind of day that makes you forgive January. The whole fucking month. Just gone. Erased babe.",
    "Holy shit she's pretty today. Like offensively pretty. Get the fuck out there babe.",
    "It's so nice out the squirrels are showing off for her. Little backflips and shit. Get out there babe.",
    "It's giving Ferris Bueller. Like skip everything and go play today babe. You earned it.",
    'Sunny with perfect temps. She built today brick by brick for you bitch.',
    "Nice af out. If you're inside right now you're committing a crime. Like actually. Straight to jail girl.",
    'Weather equivalent of a glow up. Unrecognizable tbh. Light layers and go babe.',
    "Sunny and perfect temps. She really said fuck your plans I am the plan. She was right babe. Go.",
    'Flannel on boots on attitude off. She served a perfect day. Get out there babe.',
    'Sunny flannel weather. Throw on a hoodie and get the fuck outside. She earned this girl.',
  ],
  TemperatureTier.shortsWeather: [
    "Sun showed the fuck up and I'm emotional about it tbh. Shorts on go go go.",
    'Warm and sunny. She heard me talking shit all winter and took it personally. Good. Go play babe.',
    'Cancel everything. She popped tf off. Shorts. Sunnies. Outside. Now.',
    "She's giving '97 Shania. Warm sunny confident as fuck. That don't impress me much? This does babe.",
    'She woke up hot and sunny and I woke up grateful as fuck. Shorts on babe.',
    "Get outside she's so warm and sunny the trees are showing off. Leaves all perky and shit. Like okay girls.",
    "Sunny and warm and I'm fucking feral about it. Shorts on go girl.",
    'Sun came correct today. Sundress and go babe.',
    "It's giving serotonin on a silver platter. She's not even charging. Free drugs bitch.",
    'She served the kind of day that ruins every day after it. Shorts on babe.',
    "Sunny and warm and if you're not outside in five minutes what the fuck are you doing girl.",
    'Shorts on. Sunscreen on. Brain off. Get the fuck outside babe.',
    'She cooked today. Like actually fucking cooked. Shortest shorts you own. Go girl.',
    'Hot and sunny as fuck. Your legs have been in jail all winter. Free them bitch.',
    "SPF and shorts. That's the whole plan. Go babe.",
    'Booty shorts weather. Zero complaints. Get out there babe.',
  ],
  TemperatureTier.scorcher: [
    'Sun took every criticism personally and snapped. Like girl calm the fuck down.',
    "Not her cooking us like a fucking rotisserie chicken. She's unwell. Chug water babe.",
    "Sun said I'm going to make today everyone's problem. And she absolutely fucking did.",
    "She's running this bitch like a tanning bed with no off switch. SPF and hydrate babe.",
    "Hot as shit and sunny and I'm pretty sure my car is a pizza oven now girl.",
    "Nearest body of water immediately. A pool a river a fucking sprinkler I don't care girl.",
    "She's really fucking holding a magnifying glass over us right now. Girl we are not ants.",
    "Sun's having a psychotic break and she's fucking committed to the bit. SPF 50 babe.",
    "It's so fucking hot I'm googling how far is the ocean like I'll actually drive four hours. I will babe.",
    "She's cooking us alive and she's not even sorry. She's never fucking sorry. Hydrate babe.",
    "This bitch turned the planet into a panini press and we are the panini. Hydrate girl.",
    'I need a body of water or a body bag. Those are the options right now babe.',
    "So hot the birds are walking. She's out of her damn mind girl. SPF 50.",
  ],
};
