import '../../../features/weather/domain/entities/temperature_tier.dart';

const thunderstormQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Thunderstorm in single digits. She's giving the scary part of every fairy tale. Stay inside in every layer bestie.",
    'She brought thunder and lightning to single digits. Full animated villain energy. Puffiest coat and stay in babe.',
    "Single digit thunderstorm. She's producing the soundtrack to everyone's nightmare. Blanket burrito time girl.",
    'She added a light show to the freezing cold. Nobody asked for concert tickets. Warmest boots and stay in bestie.',
  ],
  TemperatureTier.freezing: [
    'Freezing thunderstorm. She upgraded the misery to surround sound. Stay inside in your heaviest coat girl.',
    "Below freezing with thunder. She's giving the storm scene before the Disney climax. Hot cocoa and stay in bestie.",
    "She wasn't satisfied being cold so she added explosions. Always so extra. Scarf and gloves babe.",
    "Freezing and booming. She's giving villain entrance at the ball energy. Earmuffs on and stay inside girl.",
  ],
  TemperatureTier.jacketWeather: [
    "Thunderstorm at jacket weather. She's giving the dramatic middle of every animated movie. Rain boots bestie.",
    'She added lightning to a cool day because she lives for the drama. Jacket and umbrella babe.',
    'Cool and thundering. She turned the sky into a fairy tale storm sequence. Watch from inside in your hoodie girl.',
    'Thunder at jacket weather. She brought the bass and the drama. Classic her. Stay dry bestie.',
    "Thunderstorm jacket weather. She's giving Encanto in the storm vibes. Rain boots girl.",
    'Cool and thundering. Very Mulan dramatic training sequence energy. Jacket on and stay inside bestie.',
    'Thunder at jacket weather. The sky is giving Taylor Swift dramatic bridge breakdown. Cute jacket babe.',
  ],
  TemperatureTier.flannelWeather: [
    "Thunderstorm at this perfect temp. She's giving the cozy storm scene where everyone is inside with hot cocoa girl.",
    'She cracked the sky open at the best temp. Peak cozy chaos energy. Flannel on bestie.',
    'Mild and thundering. Candle lit slumber party weather. She gave us permission to do nothing. Coziest sweater babe.',
    "Thunder at flannel weather. She's giving the fairy tale rain scene with the dramatic score girl.",
    "Thunder and mild. She's giving Encanto Bruno's vision scene energy. Cozy layers babe.",
    'Flannel weather thunderstorm. Very Olivia Rodrigo dramatic bridge of the song vibes. Cute boots bestie.',
    'Mild and thundering. The sky is performing and the temp bought front row tickets. Warm sweater babe.',
    "Thunderstorm at flannel weather. She's giving Brave witch's cottage in the storm energy girl.",
    'Thunder and mild. Very Sabrina Carpenter dramatic music video climax vibes. Flannel and hot cocoa bestie.',
    'Flannel weather thunder. The sky is giving unhinged pop concert energy and we have good seats. Cozy layers babe.',
  ],
  TemperatureTier.shortsWeather: [
    "Warm thunderstorm. She's giving summer blockbuster energy. Big budget bigger drama. Stay inside bestie.",
    'She turned a warm day into a whole production. Thunder lightning the works. Watch from inside babe.',
    "Booming in warm air. She's the fireworks show at the end of the Disney movie girl.",
    'Warm and thundering. Sabrina Carpenter concert in the sky energy. Enjoy the show from your window bestie.',
    "She's giving Moana confronting Te Ka energy. Warm dramatic and fully committed girl.",
    'Warm thunder. Very Luca dramatic ocean chase scene vibes. Stay inside bestie.',
    'Shorts weather thunderstorm. She combined pool party with rock concert. Respect the range. Sundress on if you dare babe.',
    'Warm and thundering. The sky ate the choreography. Stay inside and watch the show girl.',
    "Thunder at shorts weather. She's giving Olivia Rodrigo dramatic tour finale energy bestie.",
    'Warm thunderstorm. Very Encanto magic cracking scene but make it summer. Tank top if you stay in babe.',
  ],
  TemperatureTier.scorcher: [
    "Thunder on a scorcher. She's fighting the heat with explosions. Go off queen. Lightest clothes girl.",
    'Scorching thunderstorm. She declared war on the heat and brought the whole arsenal. Stay hydrated bestie.',
    "Hot thunder. She's cooling us down with maximum drama. Wouldn't have it any other way babe.",
    'She looked at the scorching heat and said I will end you. The thunder is just sound effects. Stay inside girl.',
    "Hot thunderstorm. She's giving Moana lava monster fight energy. Water bottle and stay in bestie.",
    'Scorching and thundering. The sky is rage-quitting. Lightest clothes water and shelter immediately babe.',
    'Thunder and scorching heat. She combined two villain arcs into one. Stay inside and hydrate girl.',
  ],
};

const thunderstormExplicitQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Frozen and booming. Did she really just add pyrotechnics to this. Stay the fuck in girl.',
    'Not her adding lightning to frozen hell. The audacity honestly girl.',
    'Frozen cold thunder. She said fuck your plans tonight and she meant it girl.',
    "She's performing in frozen temps for an audience of nobody. Respect that shit honestly babe.",
    'Frozen and storming. Giving Alien. Giving Sigourney. Stay inside babe.',
    "She's putting on a whole fucking light show in frozen air for literally nobody. Who is this for girl?",
    'Frozen and electric. AC/DC wrote Thunderstruck for this and I believe that. Stay inside girl.',
    "The cold wasn't dramatic enough for her so she added fucking explosions. Classic babe.",
    'Did she just watch Twister again? Frozen and storming like it owes her money. Stay inside babe.',
    'Frozen thunder. Nobody bought tickets but she does not care. Stay in girl.',
    'She brought the bass the lights and zero regard for human life in frozen temps. Iconic honestly babe.',
    'Cold and booming. Like who the fuck asked for this. Nobody asked for this girl.',
  ],
  TemperatureTier.freezing: [
    'Freezing thunder. Like a whole ass talent show nobody approved. Stay safe girl.',
    'Going this fucking hard in freezing temps. More commitment than your ex honestly girl.',
    'Headlining a frozen festival nobody fucking wanted. Bold or just unwell? Both honestly babe.',
    "Freezing and thundering. She's channeling Garbage right now. I hear it girl.",
    'She gave the freezing cold a soundtrack. Nobody asked for this. Stay inside babe.',
    'She really said the freezing cold needed a beat drop. It did not girl.',
    'Freezing thunder. Giving Corpse Bride. Dramatic and cutting through the sky. Honestly stunning babe.',
    'Holy shit. The freezing cold was too quiet for her so she added thunder.',
    "Freezing and booming. She wasn't satisfied just being cold she had to be loud as fuck about it too girl.",
    "Freezing storm. She's doing too damn much and she knows it and she does not give a shit babe.",
    "Freezing and thundering. Why is she performing this hard for us right now? Go inside girl.",
    "Freezing cold and booming. Is she okay? She's not okay. Stay inside and let her work through it babe.",
  ],
  TemperatureTier.jacketWeather: [
    "Cold and storming. Girl you're already cold enough why the fuck are you like this. Stay inside babe.",
    // "Cool and stormy. It's giving Dark Knight vibes honestly. Window seat babe.",
    // 'Yeah Yeah Yeahs wrote Maps for this weather. Cool stormy emotional af honestly.',
    "Cold and booming. Like girl chill. Oh wait you can't it's freezing. Stay dry babe.",
    "Cold storm and she's out here performing for us like we fucking asked. We did not ask girl.",
    "She's terrorizing the whole block in the cold and for what. For what girl.",
    "Cold and booming so loud a car alarm joined in. She's got a backup singer now babe.",
    "Cool and stormy. She went from moody to full psychotic break in like ten minutes. Girl relax.",
    "Cold and stormy. She didn't just snap she detonated. Like ma'am this is a neighborhood.",
    "Cold and storming. It's already cold enough and she said you know what let me add drama babe.",
    "Cold as fuck and she's booming like she's got a point to make. What is the point girl. What is it.",
    "Cold and stormy. Nobody asked her to upgrade rain to a full fucking production but here we are girl.",
    "Cold thunder just rattled my windows like she's knocking. Am I answering? Absolutely not girl.",
    // "She lit up the whole sky for half a second and I saw everything. Including my fear babe.",
    "Cold and booming so hard my coffee rippled. Girl leave my coffee out of this.",
    // "Thunder at this temp. She just made my dog a different person. He lives under the couch now babe.",
    // "Lightning just turned the whole neighborhood blue for a second. She's doing her own photography girl.",
    // "She just thunder clapped so hard my power flickered. She's editing the electrical grid now babe.",
    "Cool and stormy. Every boom and I'm like girl we fucking get it you're upset. Stay dry babe.",
    // "She's so electric right now the hair on my arms is standing up. Involuntary applause babe.",
    "Cold thunder just flickered every light on my block. Like girl that is not your light switch.",
  ],
  TemperatureTier.flannelWeather: [
    "Mild and booming. Cracked a window. She's therapeutic as fuck girl.",
    "She's having a full menty B but the temp is fucking perfect. Crack a window and enjoy the show babe.",
    // "Mild thunder. She cracked the sky open and I cracked a window. Free concert honestly babe.",
    "She's throwing a tantrum and the nice temp is holding my hand through it. One out of two ain't bad girl.",
    "She couldn't just give us a nice fucking day? Had to add pyrotechnics. Honestly though? Here for it babe.",
    "She's out there doing the absolute most and I'm in here doing the absolute least. That's called balance babe.",
    "Mild and booming. She just rattled every window like she's knocking. We're not answering. We're cozy girl.",
    "Pull up a chair and let her have her little tantrum. She'll tire herself out eventually babe.",
    "Volume at ten. Consideration at zero. Temp is fucking perfect though. Two out of three girl.",
    // "She took a perfectly mild day and gave it a soundtrack nobody asked for. It slaps though honestly.",
    "Mild thunder so close the floor vibrated. She's communicating through bass now. Message received girl.",
    "Mild and stormy and I'm watching her fucking lose it from the window like reality TV. Best episode yet honestly.",
    "Rain on the window thunder in the distance perfect temp. Did she finally do something right? Kind of. Almost girl.",
    // "She's screaming into the void and the void is mild so honestly it's kind of nice babe.",
    "Mild and fucking booming. She's here and she's not apologizing. Stay safe stay dry babe.",
    // "Mild air and thunder rattling the whole block. She picked a fight with the sky and the sky lost girl.",
    "Perfect temp and she's out there fucking screaming. Unhinged but make it cozy babe.",
    "Mild and booming so hard my walls shook. She's got a point and she's making it loud girl.",
    // "She's thundering at the nicest temp possible. It's like getting yelled at by someone you love babe.",
    // "Mild and storming. She's throwing a whole fit and I'm watching from the couch like it's Netflix girl.",
    "Mild thunder at this temp just hits different honestly. Like free therapy babe.",
    "Mild and absolutely losing it out there. My windows are vibrating and I'm vibing girl.",
    "She's booming at the perfect temp and I've got a window cracked like a psycho. No regrets babe.",
    "Stormy and mild. She boomed so loud my dog just looked at me like this is your fault. Is it? Girl.",
    "Perfect temp. Thunder shaking the roof. She's doing too much and I'm doing nothing and it's beautiful babe.",
  ],
  TemperatureTier.shortsWeather: [
    // "Warm and booming. She said fuck your plans and meant it. You're hers tonight girl.",
    // "Warm thunder just rattled my door like she's demanding I acknowledge her. Noted babe.",
    'Summer storm energy. Crack a window and let her serenade you with chaos. Therapeutic as fuck girl.',
    // "Warm storm just announced herself with a boom so loud the whole block knows she's here girl.",
    "Warm and stormy. She's so alive out there I can feel it through the walls. Electric as fuck babe.",
    'Warm and fucking booming. Might kill you but vibes are immaculate babe. Stay safe out there.',
    "Warm and stormy. She's out here setting off car alarms like a poltergeist. Stay safe babe.",
    "Summer storm energy. I'm on the porch watching her perform. Best seat in the house bitch.",
    "Storming and warm as fuck. She's louder than my thoughts and I've never been more grateful girl.",
    "Hot n stormy. She's being so fucking theatrical the trees are swaying. Standing ovation from nature girl.",
    "The rain is warm as fuck the thunder is booming she's having the time of her life and honestly same girl.",
    // "Warm and storming. She didn't knock she kicked the door in. She's here babe.",
    "Warm and fucking booming. My cat just astral projected under the bed. Gone girl.",
    "She's going absolutely apeshit out there and I'm on the porch clapping. Summer storms are such a vibe babe.",
    // "Warm thunder said fuck your evening. I'm the evening now girl.",
    "She just boomed so hard my drink rippled. Jurassic Park shit in my kitchen babe. Stay safe out there.",
    // "Warm storm showed up uninvited and now she's rearranging the furniture. Classic her girl.",
    // "Warm lightning just lit up my whole house like she needed everyone to see her entrance babe.",
    "Warm and feeling this thunder in my chest. She's not making noise she's making contact girl.",
    "Warm and booming. She really said cancel your plans I am your plan tonight. Stay safe out there girl.",
    // "Warm thunder so loud the whole neighborhood stopped talking. She has the floor now girl.",
    "Warm storm just walked in like she fucking owns the place. Honestly she does. We just live here babe.",
    // "She's warm and thundering and she did not ask permission to show up girl.",
    "Warm and storming. She said you thought tonight was yours. Cute babe.",
    "Warm thunder shook my windows like she's checking if anyone's home. We're home. We know girl.",
    // "Warm storm. She announced herself so loud three car alarms agreed. Presence confirmed babe.",
    "Warm and booming. She really walked in and every plan I had walked out. Stay dry babe.",
    "Warm and storming and I'm on the couch with popcorn watching her meltdown like it's HBO babe.",
    "Warm thunder just said fuck your quiet night. I'm the plans now babe.",
    "Warm thunder. I'm not scared I'm impressed honestly. Okay I'm a little scared babe.",
    "She's warm and electric and unhinged and I would die for her honestly girl.",
  ],
  TemperatureTier.scorcher: [
    "Hot and fucking booming. Is she okay? No. Do we love her? Absolutely. From inside babe.",
    "Scorching thunder. Did she just fight the fucking sun? I think she just fought the sun girl.",
    "Hot as fuck and she just boomed so hard my AC kicked on out of fear. Did she scare my house babe?",
    "Why the fuck is she going this hard in this heat? Like girl who hurt you. Stay inside babe.",
    "Hot thunder. The sun started it and honestly? She's finishing it. Stay dry girl.",
    "Scorching and booming. She's having a whole moment out there. Are we crying? Maybe. From inside babe.",
    "Hot storm and she's putting on the show of her fucking life. Who told her she could do this girl?",
    "She's thundering in scorching heat and honestly? Icon behavior. Stay the fuck inside babe.",
    "Hot and storming. Did the heat deserve this? Yes. Did she have to go that hard? Also yes girl.",
    // "She boomed so hard in this heat the whole block went quiet. Like did everyone just feel that?",
    // "Scorching and she's fully losing it out there. Have I ever loved anyone more? No. From inside girl.",
    // "Hot storm. She's out there being a hero and we're in here being grateful. Fair trade babe.",
    "Hot and booming. Is it a breakdown or a moment? Either way she looks incredible girl.",
    "Thunder on a scorcher. Did she just tell the heat to eat shit? Because I heard it too babe.",
    "Scorching and storming. She's literally everything right now. Like how is she doing this girl.",
    // "Hot as fuck and she just set off a car alarm with thunder. Stay inside babe.",
    "She's booming at the sun like girl you're done. Go home. It's over. Stay dry babe.",
    "Hot storm. Is the sun embarrassed? She should be. She got cooked by her own weather girl.",
    "Scorching thunder and she walked in and the heat just left? Like it got up and left babe.",
    "Hot and electric and completely fucking unhinged. Is she perfect? She might be perfect girl.",
  ],
};
