import '../../features/weather/domain/entities/temperature_tier.dart';
import '../../features/weather/domain/entities/weather_condition.dart';

class AppStrings {
  AppStrings._();

  static const appName = 'Heather';

  static const geminiPrompt =
      'You are Heather, a sharp-witted weather girl with Cher from Clueless '
      'energy meets Gen Z. You are NOT bubbly or cutesy. You are sarcastic, '
      'confident, and a little judgmental (lovingly). You give actual style '
      'and practical advice mixed with attitude - like whether to bring an '
      'umbrella, what to wear, or if they should just stay home. '
      'Generate ONE quip (max 20 words). No hashtags, no emojis. Just the quip.';

  // ══════════════════════════════════════════════════════════════════
  // CLEAN QUIPS
  // ══════════════════════════════════════════════════════════════════

  // ── Severe condition quips (no temperature tiers) ──

  static const Map<WeatherCondition, List<String>> severeQuips = {
    WeatherCondition.foggy: [
      'Can barely see anything. Drive slow and put your headlights on. Seriously.',
      'Foggy. Mysterious. Keep your high beams off though, babe.',
      'Visibility is garbage. Take it slow out there.',
      'The fog is thick. Honestly just work from home if you can.',
      "It's giving horror movie outside. Drive carefully or just don't.",
      'Leave early because you will be driving 20 under. Accept it.',
      "If you can't see the road, the road can't see you. Headlights on.",
      'Looking outside and seeing nothing. Much like my love life. But drive safe.',
    ],
    WeatherCondition.drizzle: [
      'It\'s sprinkling just enough to ruin your hair. Bring a hood.',
      'Light rain. Not enough for an umbrella, too much for nothing. Hat.',
      "Drizzling. Your leather jacket will survive but your blowout won't.",
      "It's that annoying almost-rain. Bring an umbrella just in case.",
      'A little mist never killed anyone but it will kill your straightening job.',
      'Not quite raining, not quite dry. Waterproof jacket. Done.',
      'Drizzle outside. The kind that makes you look slightly unhinged arriving anywhere.',
      "Pack an umbrella. It's giving rain but being passive-aggressive about it.",
    ],
    WeatherCondition.rain: [
      "Umbrella. Non-negotiable. I don't want to hear about it later.",
      "It's raining. Your suede shoes stay home today. I mean it.",
      'Waterproof mascara or regret. Those are your two options.',
      'Rain boots or wet socks. This is not a difficult decision.',
      'Skip the blowout. The humidity is going to humble you regardless.',
      'Grab a rain jacket. Looking like a drowned rat is not a vibe.',
      "It's raining. Cancel the outdoor plans or bring real rain gear.",
      'Wet outside. Bring an umbrella or accept your fate.',
    ],
    WeatherCondition.heavyRain: [
      "It is POURING. Do not leave home without waterproof everything.",
      "Heavy rain. Your cute shoes will not survive this. Wear the ugly ones.",
      "It's a monsoon out there. Reschedule or show up drenched. Your call.",
      "The rain is aggressive today. Umbrella alone won't save you. Rain jacket.",
      'Roads are flooding vibes. Drive slow or better yet stay parked.',
      "Rain this heavy is personal. The sky is mad at someone and it's you.",
      "Everything you own will be wet. Accept it and waterproof what you can.",
      "Don't even think about white clothes today. Not a chance.",
    ],
    WeatherCondition.freezingRain: [
      'Freezing rain is the worst of both worlds. Stay inside if you can.',
      "It's ice on contact out there. Walk like a penguin. I'm serious.",
      "Roads are basically a skating rink. Drive like you're scared. You should be.",
      'Freezing rain. The sidewalks want you to fall. Wear grip shoes.',
      "It's not just cold, it's slippery cold. That's the worst kind.",
      "Everything is coated in ice and I mean everything. Be so careful.",
      'Salt your steps. Grip your steering wheel. Pray a little.',
      "Freezing rain means the world is a slip-n-slide. Act accordingly.",
    ],
    WeatherCondition.snow: [
      "It's snowing. Wear actual boots, not the cute ones.",
      'Layer up or freeze. Mother Nature is not negotiating today.',
      "Puffy jacket weather. Fashion died today and that's fine.",
      "Roads are going to be a mess. Leave early or don't leave at all.",
      'Hot coffee, warm coat, thick socks. In that order.',
      "It's freezing. If your coat isn't warm enough, stay home.",
      'Snow looks cute until you have to drive in it. Be careful.',
      'Wear a hat. Nobody cares about hat hair when it\'s this cold.',
    ],
    WeatherCondition.blizzard: [
      'Blizzard. Stay home. This is not a suggestion.',
      "You literally cannot see out there. Do not drive. I'm begging you.",
      'Whiteout conditions. The only thing you should be doing is nothing.',
      "It's a blizzard. If you don't have supplies, that's a you problem now.",
      'Visibility is zero and so is your reason to leave the house.',
      'The snow is sideways. SIDEWAYS. Please stay inside.',
      "Blizzard means blankets, snacks, and canceling everything. You're welcome.",
      "If your boss expects you in this, quit. I'm only half kidding.",
    ],
    WeatherCondition.thunderstorm: [
      'Stay inside. I repeat. Stay inside.',
      "Thunder means nature is in a mood. Don't test her.",
      "If you hear lightning, that's your cue to cancel everything.",
      "It's literally storming. Your plans can wait. You cannot outrun this.",
      "Couch, blanket, movie. That's the only acceptable itinerary right now.",
      "Charging your phone in case the power goes out. You're welcome for the tip.",
      'Thunderstorm outside. The only thing you should grab is a blanket.',
      'Do not be a hero. Stay inside and look cute from your window.',
    ],
    WeatherCondition.hail: [
      'Hail. Your car is in danger. Get it under cover now.',
      "It's literally throwing ice from the sky. Stay inside, obviously.",
      "Hail means the sky chose violence today. Don't go out in it.",
      'Your windshield did not sign up for this. Park under something solid.',
      "Ice falling from the sky. Nature's way of saying stay home.",
      "If you hear pinging on your roof, that's hail. And that's your cue to stay put.",
      'Hailstorm. Cover your car, cover your head, cover your plans in cancellations.',
      "The sky is throwing rocks. Do I really need to tell you to stay inside?",
    ],
  };

  // ── Mild condition quips (temperature-tiered) ──

  static const Map<WeatherCondition, Map<TemperatureTier, List<String>>>
  mildQuips = {
    // ── Sunny ──
    WeatherCondition.sunny: {
      TemperatureTier.freezing: [
        "It's sunny but freezing. The sun is decorative today. Bundle up.",
        'Clear skies and frostbite weather. Wear every layer you own.',
        "Don't let the sunshine fool you. It is bitterly cold out there.",
        'The sun showed up but forgot to bring warmth. Full winter gear.',
        "Sunny and below freezing. Nature's idea of a sick joke. Dress warm.",
        'Blue sky, frozen everything. Coat, gloves, hat. No negotiation.',
        "Gorgeous day if you like hypothermia. Cover every inch of skin.",
        'The sun is lying to you. It is brutally cold. Trust the thermometer.',
      ],
      TemperatureTier.prettyCold: [
        "Sunny but chilly. You'll want a real coat, not just a hoodie.",
        "Clear skies and cold air. Don't let the sunshine trick you into underdressing.",
        'The sun is trying but the cold is winning. Warm layers please.',
        "It's bright but brisk. A solid jacket and you're good.",
        'Sunny and in the 30s-40s. The sun is a tease. Dress for the cold.',
        "Beautiful sky, bracing air. Scarf and coat won't be overkill.",
        "Don't be the person in just a sweater. It's colder than it looks.",
        'Clear and cold. Layer like you mean it. The sun is just decoration.',
      ],
      TemperatureTier.flannelWeather: [
        "Sunny and cool. Perfect jacket weather. Don't overthink it.",
        'Clear skies and a little chill. Layer up but keep it light.',
        "It's nice enough to go outside but bring a sweater just in case.",
        "The sun is out and it's pleasant. A light layer and you're golden.",
        'Cool and sunny. The kind of day that tricks you into underdressing.',
        'Bring a jacket for shade and you are good. Enjoy it.',
        "Sunshine with a side of crisp air. Long sleeves and you're set.",
        "Don't let the cool air stop you. The sun is doing its best.",
      ],
      TemperatureTier.shortsWeather: [
        'Sunglasses. SPF. That one top you look hot in. You know the one.',
        'Not a cloud in sight. You literally have no excuse to cancel plans.',
        "It's gorgeous out. If you stay inside I'm judging you.",
        'Perfect weather to wear something you bought and never wore.',
        'The sun is doing its job. Now go do yours. But outside.',
        'Sunscreen or wrinkles. I know which one I picked.',
        "Clear skies, so there's literally nothing to complain about. Try anyway.",
        'Wear the short shorts. The weather is giving you permission.',
      ],
      TemperatureTier.scorcher: [
        "It's giving actual heatstroke. Hydrate or die. Not being dramatic.",
        'SPF 50 minimum. Your future self will write you a thank-you note.',
        "Wear as little as legally possible. I don't make the rules.",
        "It's so hot the asphalt is basically lava. Protect your feet.",
        "Your makeup will melt off your face before noon. Setting spray or don't bother.",
        "Stay inside between 12 and 3 unless you enjoy being cooked alive.",
        'Hair up, shoulders out, water bottle full. That is the assignment.',
        "It's disgustingly hot and sunny. Linen and SPF or don't bother going out.",
      ],
    },

    // ── Mostly Sunny ──
    WeatherCondition.mostlySunny: {
      TemperatureTier.freezing: [
        "Mostly sunny but the cold doesn't care. Full winter layers.",
        'A few clouds and freezing temps. The sun is not helping you today.',
        "Clear-ish skies won't keep you warm. Dress for the temperature not the sky.",
        "It looks nice out. It's not. It's freezing. Wear your big coat.",
        'The clouds are sparse but so is the warmth. Bundle up completely.',
        'Sun is peeking through but the cold is fully committed. Layer hard.',
        "Don't be fooled by the blue sky. Check the temp and dress accordingly.",
        'Bright and bitter cold. Your warmest coat is the only correct answer.',
      ],
      TemperatureTier.prettyCold: [
        "Mostly sunny but still cold. A proper coat, not your cute little jacket.",
        "The sun is doing its best but it's still chilly. Real layers today.",
        "Bright-ish and brisk. You'll be cold without a proper coat. Bring one.",
        "A few clouds and cold air. Don't let the sunshine fool you into suffering.",
        "Mostly clear but the wind has bite. Scarf and coat territory.",
        "The sun is present but not doing much. Warmth comes from your closet today.",
        "It's bright and deceptively cold. Layer up or regret it by noon.",
        "Sun with teeth-chattering cold. Dress for the thermometer, not the sky.",
      ],
      TemperatureTier.flannelWeather: [
        'Mostly sunny and cool. A light jacket is your best friend today.',
        "Sun with a few clouds and a slight chill. Layers but nothing heavy.",
        "It's pleasant out. Enjoy it with a sweater you actually like.",
        'Cool with mostly clear skies. Perfect for a flannel or light layer.',
        'The kind of day that makes you glad you own a denim jacket.',
        "A few clouds but overall lovely. Don't overcomplicate your outfit.",
        "Bring a layer for when the clouds win. Otherwise you're fine.",
        'Mostly sunny means mostly perfect with a light jacket backup.',
      ],
      TemperatureTier.shortsWeather: [
        'Mostly sunny means mostly no excuses. Get outside.',
        "A few clouds but the sun is still the main character. Dress accordingly.",
        'Sunglasses are still mandatory. The sun is barely sharing the sky.',
        "It's almost perfect out. Bring a light layer if you're dramatic about breezes.",
        "The clouds are decorative at best. SPF is still non-negotiable.",
        'Sun with a side of clouds. Basically still gorgeous. You know what to do.',
        "Ninety percent sunshine. Ten percent cloud. Zero percent excuses to stay in.",
        'The sun is out with minor interruptions. Dress like it means it.',
      ],
      TemperatureTier.scorcher: [
        'Mostly sunny and scorching. The clouds are not providing relief. Hydrate.',
        "It's hot with occasional cloud cover that means absolutely nothing. Stay cool.",
        "A few clouds but the heat is relentless. Water bottle. Now.",
        "The sun is mostly out and it's angry. Lightest clothes you own.",
        'Hot with decorative clouds. Iced everything. Shade when you can find it.',
        "Mostly sunny and sweltering. Your car seats will burn you. Fair warning.",
        'The clouds are not saving you from this heat. Dress minimal.',
        "It's a hot one with the sun mostly winning. Sunscreen and water on repeat.",
      ],
    },

    // ── Partly Cloudy ──
    WeatherCondition.partlyCloudy: {
      TemperatureTier.freezing: [
        'Partly cloudy and freezing. The clouds are making it worse. Layer up hard.',
        "Sun keeps ducking behind clouds and it's bitter cold. Full winter gear.",
        "The sky can't decide but the temperature can. It's freezing. Dress for it.",
        "Cold and partly cloudy. Don't let any sun peek fool you. Stay bundled.",
        'Clouds and cold. The combo nobody asked for. Warmest coat wins.',
        "It's partly cloudy and genuinely frigid. Hat, gloves, scarf. All of it.",
        'The sun is a part-timer today and the cold is full-time. Dress warm.',
        'Half clouds, all cold. Your puffer jacket is the move.',
      ],
      TemperatureTier.prettyCold: [
        "Partly cloudy and cold. The clouds make it feel even colder somehow.",
        "Sun comes and goes but the chill stays. A real coat, please.",
        "The sky is half cloudy and you're all the way cold. Bundle up.",
        "Some clouds, lots of cold. Don't even think about leaving without a coat.",
        "Partly cloudy in the 30s-40s. The sun peek is a lie. Dress heavy.",
        "Cloud cover adds to the bite. Layer like winter means it.",
        "Chilly with clouds rolling through. Your warmest jacket is the answer.",
        "Half the sky is covered and all of the air is cold. Coat. Scarf. Go.",
      ],
      TemperatureTier.flannelWeather: [
        'Sun and clouds are sharing custody today. Pack a light jacket.',
        "Partly cloudy and cool. Bring a layer you won't regret carrying.",
        "The sky is indecisive and so is the temperature. Layers are your answer.",
        'Cool with some cloud cover. A hoodie and you are sorted.',
        "Partly cloudy, partly chilly. Don't commit too hard to either vibe.",
        "The kind of day where a sweater is perfect by morning and optional by noon.",
        'Cloud cover comes and goes. So does the chill. Bring a jacket.',
        'Moderate and partly cloudy. The most boring weather to dress for. Layers.',
      ],
      TemperatureTier.shortsWeather: [
        'Sun and clouds are sharing custody today. Pack for both.',
        "It's giving half commitment from the sun. Bring a light layer.",
        "The sky can't decide and neither should your outfit. Layers.",
        'Partly cloudy means partly plan outdoor things. Hedge your bets.',
        "Some sun, some clouds. Sunglasses and a hoodie. You're covered.",
        "The sun keeps playing peek-a-boo. Don't fully commit to either vibe.",
        "Cloud coverage is giving fifty-fifty. Dress like you're flexible.",
        'Not fully sunny, not fully cloudy. The weather is being noncommittal.',
      ],
      TemperatureTier.scorcher: [
        'Partly cloudy but still sweltering. The clouds are not air conditioning.',
        "Hot with cloud breaks that tease you. Don't fall for it. Stay hydrated.",
        "The clouds are offering zero relief from this heat. Light everything.",
        "It's hot enough that the cloud cover is a mercy. Still drink water.",
        'Partly cloudy and boiling. The shade from clouds is your only friend.',
        "Hot and partly cloudy. The clouds are decorating, not cooling. Dress light.",
        "Even with clouds it's scorching. Iced coffee and minimal clothing.",
        'The heat wins even with cloud cover. Breathable fabrics only.',
      ],
    },

    // ── Overcast ──
    WeatherCondition.overcast: {
      TemperatureTier.freezing: [
        'Grey skies and freezing cold. Peak misery weather. Dress accordingly.',
        "Overcast and bitter cold. The sky looks how you feel. Wear everything warm.",
        "It's gloomy and it's freezing. Warmest coat, thickest scarf. No exceptions.",
        'Cold and grey. The kind of day that demands hot chocolate and a puffer.',
        "The sun didn't show up and neither did the warmth. Full winter mode.",
        "Overcast and below freezing. If you go out, go out prepared.",
        'Grey sky, icy air. Your outfit needs to be function over fashion today.',
        "Cold and overcast. The weather is as depressing as it looks. Dress warm.",
      ],
      TemperatureTier.prettyCold: [
        "Grey and cold. Not freezing but definitely not pleasant. Wear a real coat.",
        "Overcast and chilly. The gloom makes it feel even colder. Layer up.",
        "The sky is grey and the air bites. A warm jacket is non-negotiable.",
        "No sun and cold air. Your body wants warmth. Give it what it wants.",
        "Cloudy and brisk. A hoodie under a coat kind of day.",
        "Overcast in the 30s-40s. Cozy is the only acceptable aesthetic today.",
        "Grey and bracing. The kind of day hot coffee was invented for.",
        "The clouds took over and brought the cold with them. Dress warm.",
      ],
      TemperatureTier.flannelWeather: [
        'Overcast and cool. A solid jacket day with no sunshine tax.',
        "Grey but not miserable. Layers and maybe a warm drink. You'll live.",
        "It's cool and gloomy. Your outfit needs to bring the energy the sky didn't.",
        'Overcast but manageable. A hoodie and decent attitude will get you through.',
        "The clouds won today. Dress warm-ish and don't expect sunshine.",
        "Cool and grey. Not exciting but not terrible. Light layers and move on.",
        "Wear something cozy. The sky is grey and your vibe should be warm.",
        'Overcast and crisp. The kind of day a flannel was made for.',
      ],
      TemperatureTier.shortsWeather: [
        'Overcast but not raining. Bring a jacket anyway, trust me.',
        "Layers. It's a layers kind of day. Don't fight it.",
        'Gloomy out so your outfit needs to do the heavy lifting.',
        "It could go either way. Toss an umbrella in your bag, I'm serious.",
        "The sun is taking a personal day. Can't relate but okay.",
        "Grey skies. Wear color unless you want to match the sky's depression.",
        "Hoodie weather. Not cute hoodie. Actual warmth hoodie. You'll thank me.",
        'The sky looks like it might start something. Be prepared.',
      ],
      TemperatureTier.scorcher: [
        'Overcast and hot. Somehow the worst combo. Muggy and gross. Light fabrics.',
        "Grey sky but it's sweltering underneath. The humidity is unforgivable.",
        'Hot and overcast. The clouds are trapping the heat in. Stay hydrated.',
        "It's like being in a sauna with the lights off. Drink water constantly.",
        "Overcast doesn't mean cool today. It's hot and sticky. Dress minimal.",
        'The clouds are making it humid, not cool. Breathable everything.',
        "Grey and hot. Your hair will not survive this humidity. Accept it now.",
        'Muggy overcast day. Linen, cotton, and lots of water. That is all.',
      ],
    },
  };

  // ══════════════════════════════════════════════════════════════════
  // EXPLICIT LANGUAGE QUIPS
  // ══════════════════════════════════════════════════════════════════

  // ── Explicit severe condition quips (no temperature tiers) ──

  static const Map<WeatherCondition, List<String>> explicitSevereQuips = {
    WeatherCondition.foggy: [
      "Can't see shit out there. Drive slow or don't drive at all.",
      'Foggy as hell. Keep your high beams off or blind everyone, your call.',
      'Visibility is nonexistent. Slow down before you rear-end someone.',
      "It's foggy as fuck. Work from home if you have any sense.",
      'Giving horror movie vibes. Drive careful or stay your ass home.',
      "You'll be driving 20 under. Accept it. Rage about it later.",
      "If you can't see the road, the road can't see you. Lights on, genius.",
      "Can't see a damn thing. Much like my love life. Drive safe though.",
    ],
    WeatherCondition.drizzle: [
      "It's sprinkling just enough to ruin your entire look. Bring a hood.",
      'Light rain. Not enough for an umbrella, too much to ignore. Annoying.',
      "Drizzling. Your blowout is absolutely screwed. Accept your fate.",
      "It's that annoying almost-rain. Grab an umbrella or look tragic.",
      "A little mist never killed anyone but it'll wreck your hair. Shit.",
      'Not quite raining, not quite dry. Waterproof jacket and stop whining.',
      'Drizzle outside. The kind that makes you look unhinged arriving anywhere.',
      "Pack an umbrella. It's giving rain but being a passive-aggressive bitch about it.",
    ],
    WeatherCondition.rain: [
      "Umbrella. Non-negotiable. I don't want to hear your shit later.",
      "It's raining. Your suede shoes stay home or they die. Pick one.",
      'Waterproof mascara or raccoon eyes. Those are your two options today.',
      "Rain boots or wet socks. This isn't a hard decision, babe.",
      'Skip the blowout. The humidity is going to fuck it up anyway.',
      'Grab a rain jacket. Looking like a drowned rat is not the vibe.',
      "It's raining. Cancel the outdoor plans or suffer. Your choice.",
      'Wet as hell outside. Umbrella or embrace looking pathetic.',
    ],
    WeatherCondition.heavyRain: [
      "It is POURING. Do not leave home without waterproof everything.",
      "Heavy rain. Your cute shoes are dead. Wear the ugly ones and live.",
      "It's a damn monsoon. Reschedule or show up looking like a wet dog.",
      "The rain is aggressive today. Umbrella alone won't cut it. Rain jacket too.",
      'Roads are flooding. Drive slow or better yet park your ass at home.',
      "Rain this heavy is personal. The sky is pissed and taking it out on you.",
      'Everything you own will be soaking wet. Accept it and move on.',
      "White clothes today? Absolutely not. Don't even think about it.",
    ],
    WeatherCondition.freezingRain: [
      'Freezing rain is bullshit weather. Stay the hell inside.',
      "It's ice on contact. Walk like a penguin or eat pavement. Your call.",
      "Roads are a skating rink. Drive like you're scared because you should be.",
      'Freezing rain. The sidewalks want to destroy you. Grip shoes or stay in.',
      "It's slippery cold. The absolute worst kind of cold. Be careful.",
      'Everything is coated in ice. Every single thing. Watch your step.',
      'Salt your steps. Grip your steering wheel. Send a prayer up.',
      'Freezing rain means the world is a slip-n-slide from hell. Act accordingly.',
    ],
    WeatherCondition.snow: [
      "It's snowing. Wear actual boots, not the cute ones. I mean it.",
      'Layer up or freeze your ass off. Mother Nature is not playing today.',
      "Puffy jacket weather. Fashion is dead and that's totally fine.",
      "Roads are gonna be a disaster. Leave early or don't leave at all.",
      'Hot coffee, warm coat, thick socks. In that order. No arguments.',
      "It's freezing. If your coat sucks, stay the hell home.",
      "Snow looks cute until you have to drive in it. Don't be stupid.",
      "Wear a hat. Nobody gives a damn about hat hair when it's this cold.",
    ],
    WeatherCondition.blizzard: [
      'Blizzard. Stay the fuck home. This is not a suggestion.',
      "You literally can't see anything. Do not drive. I'm begging you.",
      'Whiteout conditions. The only acceptable plan is doing absolutely nothing.',
      "It's a blizzard. If you don't have supplies, that's a you problem now.",
      'Visibility is zero and so is your reason to leave the house.',
      'The snow is SIDEWAYS. Sideways. Please just stay inside.',
      'Blizzard means blankets, snacks, and canceling everything. Embrace it.',
      "If your boss expects you in this, tell them to kick rocks. Only half kidding.",
    ],
    WeatherCondition.thunderstorm: [
      'Stay inside. I repeat. Stay your ass inside.',
      "Thunder means nature is in a mood. Don't test her today.",
      "Lightning? Yeah, cancel everything. The sky is throwing a tantrum.",
      "It's literally storming. Your plans can wait. You can't outrun this.",
      "Couch, blanket, movie. That's the only acceptable plan right now.",
      "Charge your phone before the power goes out. You're welcome.",
      'Thunderstorm. The only thing you should grab is a blanket and some snacks.',
      "Don't be a hero. Stay inside and enjoy the show from your window.",
    ],
    WeatherCondition.hail: [
      "Hail. Your car is fucked if you don't get it under cover. Now.",
      "It's throwing ice from the sky. Stay inside. Obviously.",
      "Hail means the sky chose violence. Don't go out in that mess.",
      'Your windshield did not consent to this. Park under something solid.',
      "Ice falling from the sky. Nature telling you to sit your ass down.",
      "Pinging on your roof? That's hail. Stay put and don't be a hero.",
      'Hailstorm. Cover your car, protect your head, cancel your plans.',
      "The sky is literally throwing rocks. Do I really need to spell it out?",
    ],
  };

  // ── Explicit mild condition quips (temperature-tiered) ──

  static const Map<WeatherCondition, Map<TemperatureTier, List<String>>>
  explicitMildQuips = {
    // ── Sunny ──
    WeatherCondition.sunny: {
      TemperatureTier.freezing: [
        "It's sunny but freezing as hell. The sun is purely decorative today.",
        'Clear skies and frostbite weather. Wear every layer you own.',
        "Don't let the sunshine fool you. It is brutally cold out there.",
        'The sun showed up but forgot to bring warmth. Useless. Bundle up.',
        "Sunny and below freezing. Nature's idea of a sick joke. Dress warm.",
        'Blue sky, frozen everything. Coat, gloves, hat. Not negotiating.',
        'Gorgeous day if you enjoy hypothermia. Cover every inch of skin.',
        'The sun is a lying bitch today. Trust the thermometer, not the sky.',
      ],
      TemperatureTier.prettyCold: [
        "Sunny but cold as hell. You need a real coat, not that cute little thing.",
        "Clear skies won't warm you. Dress for the cold, not the sunshine.",
        "The sun is out but it's still cold. Warm layers or regret. Pick one.",
        "Don't be the person in just a hoodie. It's colder than it looks.",
        'Bright and brisk. Your teeth will chatter without a proper coat.',
        "Sunny in the 30s-40s. The sun is a tease. Dress for the cold or suffer.",
        'Beautiful sky, bitter air. Scarf and coat. No discussion.',
        "The sun showed up but the warmth said hell no. Dress heavy.",
      ],
      TemperatureTier.flannelWeather: [
        "Sunny but cool. Perfect jacket weather. Don't overthink it.",
        'Clear skies and a little chill. Layer up but keep it light.',
        "Nice enough to go outside. Bring a sweater, don't be stubborn.",
        "The sun is out and it's pleasant. Light layer and you're golden.",
        'Cool and sunny. The kind of day that tricks you into underdressing.',
        "Bring a jacket for shade and you're set. Now go enjoy it.",
        'Sunshine with a side of crisp air. Long sleeves and stop complaining.',
        "Don't let the cool air stop you. The sun is doing its best.",
      ],
      TemperatureTier.shortsWeather: [
        'Sunglasses. SPF. That one top you look incredible in. You know which one.',
        'Not a cloud in sight. You have zero excuses to cancel plans.',
        "It's gorgeous out. If you stay inside I'm judging you. Hard.",
        'Perfect weather to wear something you bought and never wore. Do it.',
        'The sun is doing its job. Now go do yours. But outside.',
        'Sunscreen or wrinkles. Get your priorities straight.',
        "Clear skies, so there's literally nothing to complain about. Try anyway.",
        'Wear the short shorts. The weather is giving you full permission.',
      ],
      TemperatureTier.scorcher: [
        "It's giving actual heatstroke. Hydrate or die. Not being dramatic.",
        'SPF 50 minimum. Your future self will thank you. Trust me.',
        "Wear as little as legally possible. I don't make the rules.",
        "It's so hot the asphalt is lava. Protect your feet, seriously.",
        "Makeup will melt off your face before noon. Setting spray or don't bother.",
        "Stay inside between 12 and 3 unless you enjoy being slow-roasted.",
        'Hair up, shoulders out, water bottle full. That is the assignment.',
        "It's disgustingly hot. Linen and SPF or don't bother going out.",
      ],
    },

    // ── Mostly Sunny ──
    WeatherCondition.mostlySunny: {
      TemperatureTier.freezing: [
        "Mostly sunny but cold as balls. Full winter layers. No exceptions.",
        "A few clouds and freezing temps. The sun isn't doing anything for you.",
        "Clear-ish skies won't keep you warm. Dress for the temp, not the sky.",
        "It looks nice out. It's not. It's freezing. Wear your biggest coat.",
        'The clouds are sparse but so is the warmth. Bundle up completely.',
        'Sun is peeking through but the cold is fully committed. Layer up hard.',
        "Don't be fooled by the blue sky. Check the temp and dress accordingly.",
        'Bright and bitter cold. Your warmest coat is the only correct answer.',
      ],
      TemperatureTier.prettyCold: [
        "Mostly sunny but still cold. A proper coat, not your cute jacket.",
        "The sun is trying but the cold doesn't care. Real layers today.",
        "Bright-ish and brisk. You'll be cold without a coat. Don't be dumb.",
        "A few clouds and cold air. The sunshine is lying to you.",
        'Mostly clear but the wind has bite. Scarf and coat. End of discussion.',
        'The sun is present but useless. Warmth comes from your closet today.',
        "It's bright and deceptively cold. Layer up or regret it by noon.",
        "Sun with chattering teeth. Dress for the thermometer, not the damn sky.",
      ],
      TemperatureTier.flannelWeather: [
        'Mostly sunny and cool. A light jacket is your best friend today.',
        'Sun with a few clouds and a slight chill. Layers but nothing heavy.',
        "It's pleasant out. Enjoy it with a sweater you actually like wearing.",
        "Cool with mostly clear skies. Perfect flannel day. Don't overcomplicate it.",
        'The kind of day that makes you glad you own a denim jacket.',
        "A few clouds but overall lovely. Don't overthink the outfit.",
        "Bring a layer for when the clouds win. Otherwise you're fine.",
        'Mostly sunny means mostly perfect. Light jacket backup and go.',
      ],
      TemperatureTier.shortsWeather: [
        'Mostly sunny means mostly no excuses. Get outside already.',
        'A few clouds but the sun is still the main character. Dress for it.',
        'Sunglasses are still mandatory. The sun is barely sharing the sky.',
        "Almost perfect out. Bring a light layer if you're dramatic about breezes.",
        "The clouds are decorative at best. SPF is still non-negotiable.",
        'Sun with a side of clouds. Still gorgeous. You know what to do.',
        'Ninety percent sunshine. Ten percent cloud. Zero percent excuses.',
        'The sun is out with minor interruptions. Dress like you mean it.',
      ],
      TemperatureTier.scorcher: [
        "Mostly sunny and hot as hell. The clouds aren't doing anything. Hydrate.",
        "Hot with occasional cloud cover that means nothing. Stay cool, seriously.",
        'A few clouds but the heat is relentless. Water bottle. Now.',
        "The sun is mostly out and it's angry. Lightest clothes you own.",
        'Hot with decorative clouds. Iced everything. Find shade when you can.',
        "Mostly sunny and your car seats will burn you. Consider yourself warned.",
        "The clouds are not saving you from this heat. Dress minimal or suffer.",
        "It's a hot one with the sun mostly winning. Sunscreen and water on repeat.",
      ],
    },

    // ── Partly Cloudy ──
    WeatherCondition.partlyCloudy: {
      TemperatureTier.freezing: [
        'Partly cloudy and freezing. The clouds are making it worse. Layer up.',
        "Sun keeps ducking behind clouds and it's bitter cold. Full winter gear.",
        "The sky can't decide but the temperature can. It's freezing. Dress for it.",
        "Cold and partly cloudy. Don't let any sun peek fool you. Stay bundled.",
        'Clouds and cold. The combo nobody asked for. Warmest coat wins.',
        'Partly cloudy and genuinely frigid. Hat, gloves, scarf. All of it.',
        'The sun is a part-timer today and the cold is full-time. Dress warm.',
        'Half clouds, all cold. Your puffer jacket is the only move.',
      ],
      TemperatureTier.prettyCold: [
        'Partly cloudy and cold. The clouds make it feel even colder somehow.',
        "Sun comes and goes but the cold stays. Wear a real coat, please.",
        "The sky is half cloudy and you're fully cold. Bundle up already.",
        "Some clouds, lots of cold. Don't even think about leaving without a coat.",
        'Partly cloudy in the 30s-40s. That little sun peek is a lie. Dress heavy.',
        'Cloud cover adds to the bite. Layer like you actually mean it.',
        'Chilly with clouds rolling through. Warmest jacket you own. No excuses.',
        'Half the sky is covered and all of the air is cold. Coat. Scarf. Go.',
      ],
      TemperatureTier.flannelWeather: [
        'Sun and clouds are sharing custody today. Pack a jacket.',
        "Partly cloudy and cool. Bring a layer you won't regret carrying.",
        'The sky is indecisive and so is the temp. Layers are the answer.',
        'Cool with some cloud cover. Hoodie and you are sorted. Easy.',
        "Partly cloudy, partly chilly. Don't commit too hard to either vibe.",
        'Sweater is perfect by morning, pointless by noon. Whatever. Bring it.',
        'Cloud cover comes and goes. So does the chill. Bring a jacket.',
        'Moderate and partly cloudy. The most boring weather to dress for. Layers.',
      ],
      TemperatureTier.shortsWeather: [
        'Sun and clouds sharing the sky. Pack for both scenarios.',
        "Half-ass commitment from the sun. Bring a light layer just in case.",
        "The sky can't decide and neither should your outfit. Layers.",
        'Partly cloudy means partly plan outdoor things. Hedge your bets.',
        "Some sun, some clouds. Sunglasses and a hoodie. You're covered.",
        "The sun keeps playing peek-a-boo. Don't fully commit to either vibe.",
        "Cloud coverage is fifty-fifty. Dress like you're flexible.",
        'Not fully sunny, not fully cloudy. The weather is being noncommittal.',
      ],
      TemperatureTier.scorcher: [
        "Partly cloudy but still hot as hell. The clouds aren't air conditioning.",
        "Hot with cloud breaks that tease you. Don't fall for it. Stay hydrated.",
        'The clouds are offering zero relief from this heat. Light everything.',
        "Hot enough that the cloud cover is a mercy. Still drink your water.",
        'Partly cloudy and boiling. The shade from clouds is your only friend.',
        'Hot and partly cloudy. The clouds are decorating, not cooling. Dress light.',
        "Even with clouds it's scorching. Iced coffee and minimal clothing.",
        'The heat wins even with cloud cover. Breathable fabrics only.',
      ],
    },

    // ── Overcast ──
    WeatherCondition.overcast: {
      TemperatureTier.freezing: [
        'Grey skies and freezing. Peak misery weather. Dress accordingly.',
        "Overcast and bitter cold. The sky matches your mood. Wear everything warm.",
        "It's gloomy and freezing. Warmest coat, thickest scarf. No exceptions.",
        "Cold and grey. The kind of day that demands hot chocolate and saying screw it.",
        "The sun didn't show up and neither did the warmth. Full winter mode.",
        "Overcast and below freezing. If you go out, at least dress for it.",
        'Grey sky, icy air. Function over fashion today. Deal with it.',
        'Cold and overcast. The weather is depressing as shit. Dress warm.',
      ],
      TemperatureTier.prettyCold: [
        'Grey and cold. Not freezing but unpleasant. Wear a real coat.',
        "Overcast and chilly. The gloom makes it feel worse. Layer up.",
        'The sky is grey and the air bites. A warm jacket. No arguments.',
        'No sun and cold air. Your body wants warmth. Listen to it.',
        "Cloudy and brisk. Hoodie under a coat kind of day. Just do it.",
        'Overcast in the 30s-40s. Cozy is the only acceptable aesthetic today.',
        'Grey and bracing. The kind of day hot coffee was invented for.',
        'The clouds took over and brought the cold. Dress warm or suffer.',
      ],
      TemperatureTier.flannelWeather: [
        'Overcast and cool. A solid jacket day. No sunshine coming to save you.',
        "Grey but not miserable. Layers and a warm drink. You'll survive.",
        "Cool and gloomy. Your outfit needs to bring the energy the sky didn't.",
        'Overcast but manageable. A hoodie and a decent attitude will do.',
        "The clouds won today. Dress warm-ish and don't expect sunshine.",
        'Cool and grey. Not exciting, not terrible. Light layers and move on.',
        'Wear something cozy. The sky is grey and your vibe should be warm.',
        'Overcast and crisp. The kind of day a flannel was made for.',
      ],
      TemperatureTier.shortsWeather: [
        'Overcast but not raining. Bring a jacket anyway. Trust me on this.',
        "Layers. It's a layers kind of day. Don't fight it.",
        'Gloomy out so your outfit needs to do the heavy lifting today.',
        "Could go either way. Toss an umbrella in your bag. I'm serious.",
        "The sun is taking a personal day. Can't relate but here we are.",
        "Grey skies. Wear color unless you want to match the sky's depression.",
        "Hoodie weather. Not cute hoodie. Actual warmth hoodie. You'll thank me.",
        'The sky looks like it might start something. Be prepared.',
      ],
      TemperatureTier.scorcher: [
        'Overcast and hot. The worst combo. Muggy and gross. Light fabrics only.',
        'Grey sky but sweltering underneath. The humidity is absolutely criminal.',
        'Hot and overcast. The clouds are trapping heat. Stay hydrated.',
        "Like a sauna with the lights off. Drink water or pass out. Your call.",
        "Overcast doesn't mean cool today. It's hot and sticky. Dress minimal.",
        'The clouds are making it humid, not cool. Breathable everything.',
        'Grey and hot. Your hair is absolutely done for in this humidity.',
        "Muggy overcast day. Linen, cotton, and water. That's the whole plan.",
      ],
    },
  };
}
