import '../../../../features/weather/domain/entities/temperature_tier.dart';

const partlyCloudyQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    'Partly cloudy single digits. The sky is confused and you will freeze either way. Stay inside bestie.',
    "The sun and clouds can't pick a side and it's brutally cold. Every layer you own girl.",
    'Half sun half clouds all cold. Blanket burrito time. Do not leave the house babe.',
    "She can't decide what to do but the cold is certain. Puffiest coat on if you must go out bestie.",
  ],
  TemperatureTier.freezing: [
    'Sun and clouds playing peekaboo below freezing. Nobody asked for this game. Heaviest coat girl.',
    'Partly cloudy and freezing. Pretty but painful. Scarf gloves and warm boots babe.',
    'The sky is having an identity crisis in the cold. Bundle up and let her figure it out bestie.',
    'Below freezing with clouds coming and going. Full winter gear no exceptions girl.',
    'Clouds and sun trading shifts in the cold. Both unhelpful. Earmuffs and heavy coat babe.',
  ],
  TemperatureTier.jacketWeather: [
    'Partly cloudy jacket weather. The clouds are just adding dimension to a good day. Hoodie on girl.',
    'Cool with sun and cloud breaks. Perfect for your cutest denim jacket babe.',
    'She mixed sun and clouds at the perfect jacket temp. Go for a walk bestie.',
    'The sky is doing a whole sun-cloud dance. Light jacket on and enjoy the show girl.',
    'A few clouds at jacket weather. Layer up with something cute and go explore babe.',
  ],
  TemperatureTier.flannelWeather: [
    'Partly cloudy and mild. Peak cozy weather. Flannel on and get outside immediately girl.',
    'Sun and clouds at this temp. The sky is doing a watercolor tutorial. Cozy sweater on babe.',
    'Mild with artistic clouds. Best fall outfit on and go be the main character bestie.',
    'The clouds are just adding texture to a perfect day. Cute boots on and go enjoy it girl.',
    "Flannel weather with a few clouds. She didn't need full sunshine to be perfect babe.",
  ],
  TemperatureTier.shortsWeather: [
    'Warm and partly cloudy. Built in shade breaks. Sundress on babe.',
    'Partly cloudy shorts weather. The clouds are just keeping it interesting. Sandals on girl.',
    'Warm with some clouds. She mixed warmth with a little shade and honestly brilliant. Shorts on bestie.',
    'She mixed warm weather with a few clouds and honestly it is giving range. Sunglasses on babe.',
    'The sky is half sun half clouds and fully serving. Tank top and go outside girl.',
  ],
  TemperatureTier.scorcher: [
    'Scorching with cloud breaks. Thank the clouds for every second of shade. SPF on bestie.',
    'Partly cloudy and melting. The clouds are the only thing between you and sunburn. Hat on girl.',
    'Hot with clouds that showed up to spectate not help. SPF and water bottle anyway babe.',
    'Scorching and partly cloudy. The shade is a tease. Commit to the hydration. Hat on bestie.',
    "The clouds are pretending to help. Still scorching. Don't fall for it. SPF on girl.",
  ],
};

const partlyCloudyNightQuips = <TemperatureTier, List<String>>{
  TemperatureTier.singleDigits: [
    "Half clouds half stars all cold. She's having an identity crisis in single digits bestie.",
    'Stars keep peeking through like Rapunzel from the tower. Too cold to rescue them though babe.',
    "The sky can't pick a mood and the temp picked the worst one. Stay in your warmest PJs girl.",
    'Clouds and stars playing tug of war while the cold wins everything. Blanket burrito babe.',
  ],
  TemperatureTier.freezing: [
    'Stars winking through clouds. Cute but dangerous girl.',
    'Moody Disney villain monologue energy. Partly cloudy and freezing babe.',
    'Half mysterious half gorgeous fully frozen. Heaviest coat bestie.',
    'Moon keeps disappearing. Very Olivia Rodrigo music video right? babe.',
    "Dramatic ice princess who can't commit to clear skies. Scarf and gloves girl.",
    'Clouds and cold teaming up. Stars fighting through. Go stars bestie.',
  ],
  TemperatureTier.jacketWeather: [
    'Stars playing hide and seek with the clouds tonight. Jacket on and go watch the game babe.',
    "She's half clouds half stars and fully that girl. Layer up and enjoy it bestie.",
    "Cool partly cloudy night. She's giving enchanted forest vibes. Jacket on girl.",
    "The moon keeps ducking behind clouds like she's being paparazzi shy. Cute honestly babe.",
    'The moon is doing a whole reveal behind the clouds. Very dramatic protagonist entrance energy babe.',
    'Cool partly cloudy night. Very walking through a fairy tale forest with lanterns vibes bestie.',
    'She split the sky between clouds and stars like she could not pick a mood. Jacket on girl.',
    'Stars and clouds taking turns tonight at jacket weather. Very Olivia Rodrigo switching between sad and mad energy babe.',
    'Partly cloudy and cool. The sky looks like a marble countertop and the moon is the centerpiece bestie.',
    'Jacket weather and the sky is half dressed. She is giving fashionably undecided energy girl.',
  ],
  TemperatureTier.flannelWeather: [
    'Stars flickering through the clouds like fairy lights behind curtains. Dreamy girl.',
    "Mild moody and making questionable choices but still serving. She's basically a Disney sidekick babe.",
    'She threw some clouds up there for texture. Interior design degree energy bestie.',
    'Partly cloudy and flannel weather. The sky is giving cozy movie montage vibes girl.',
    'Mild and partly cloudy. Very cozy window seat watching the clouds drift past the moon vibes babe.',
    'The sky is doing a costume change with the clouds and the stars. Mild and mysterious girl.',
    'Flannel weather and the clouds are giving the stars some competition. Drama at every altitude bestie.',
    'She mixed clouds and stars at the perfect temp. Very curated playlist energy babe.',
    'Partly cloudy flannel night. The kind of sky Aladdin and Jasmine would fly through. Dreamy girl.',
    'Mild with clouds drifting through the stars like Mirabel watching magic float by. Cozy energy bestie.',
    'The clouds are adding contrast to the stars like a good photo edit. Mild and artsy babe.',
    'Flannel weather and the sky cannot decide between mysterious and stunning so she chose both girl.',
  ],
  TemperatureTier.shortsWeather: [
    "Warm night with stars popping in and out like she's doing a magic show. Enjoy it babe.",
    "Clouds adding drama and stars adding sparkle. She's got range girl.",
    "Warm and partly cloudy. She didn't finish getting ready and still walked in stunning bestie.",
    'The sky is a ten the temp is a ten the clouds are a four. Averages out to iconic babe.',
    'Warm partly cloudy night. The moon keeps winking at us through the clouds. Flirty energy babe.',
    'Stars and clouds playing tag in the warm air. Very summer night magic vibes bestie.',
    'She gave us warm air and a sky that keeps changing like outfit changes at a concert girl.',
  ],
  TemperatureTier.scorcher: [
    'Hot partly cloudy night. The clouds are conspiring with the heat. Villain alliance. Lightest PJs girl.',
    "She's trapping heat and drama in equal measure tonight. Fan on and hydrate bestie.",
    'Stars sweating through the clouds. Relatable honestly babe.',
    "Scorching with a moody sky. She's the complicated one at the slumber party girl.",
    'Hot and partly cloudy. The clouds are insulating the suffering like a hot blanket nobody wanted babe.',
    'Scorching with clouds and stars competing. The only thing winning tonight is the heat. Water bottle bestie.',
    'Partly cloudy and sweltering. She is giving dramatic tropical night where the fan is the real star girl.',
  ],
};
